### ISSUE TITLE
Call function.currentVersion to work around CDK issue

### ISSUE THREAD

**Issue by thdxr** [sst/sst#1001]
See this issue:  https://github.com/aws/aws-cdk/issues/13731#issuecomment-814801449

We should automatically call `function.currentVersion` if `function.currentVersionOptions` exists

### Requests
- https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1636130220420300

**Comment by junaway** [comment]
- [x] Research: How to test for provisioned concurrency
- [x] Reaserch: Where to apply fix from [aws/aws-cdk#13731 (comment)](https://github.com/aws/aws-cdk/issues/13731#issuecomment-814801449) in sst.Function
- [x] Implement: Fix from above.
- [x] Test: Lambda with provisioned concurrency.

**Comment by pabacham** [comment]
any updates here?

**Comment by SamStephens** [comment]
I've created https://github.com/aws/aws-cdk/issues/23002 to fix the root issue in the CDK (note I'm not a user of your project, I just saw this during my searches and thought you'd appreciate being able to track if the root cause is fixed and you can remove your workaround).

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
