### ISSUE TITLE
AppSyncApi: support lambda authorizer

### ISSUE THREAD

**Issue by MauriceWebb** [sst/sst#1012]
Currently, there is no way to set the `defaultAuthorization` or `additionalAuthorizationModes` prop on SST's `AppSyncApi` construct's `AppSyncApiProps` to a LAMBDA `authorizationType` and supply it's config. I've been trying to use the `cdk` constructs and even tried creating the graphApi and importing it into the `AppSyncApi` construct but to no working avail. 

Would be nice to be able to do something to this effect:
```javascript

// Add to and create Appsync Api:
    const appsyncApi = new sst.AppSyncApi(this, 'graph-authz-api', {
      graphqlApi: {
        schema: "graphql/schema.graphql",
        authorizationConfig: {
          defaultAuthorization: {
            authorizationType: appsync.AuthorizationType.API_KEY,
            apiKeyConfig: {
              expires: cdk.Expiration.after(cdk.Duration.days(365)),
            },
          },
          additionalAuthorizationModes: [
            {
              authorizationType: appsync.AuthorizationType.LAMBDA,
              lambdaAuthorizerConfig: {
                handler: iAuthZFn
              } 
            }
          ]
        },
      },
      ...
   }

```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
