### ISSUE TITLE
NextjsSite: api routes not working for Next.js 12 apps

### ISSUE THREAD

**Issue by fwang** [sst/sst#1013]
Requests:
- Dillon https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1636292259476900
- Justin Philpott https://serverless-stack.slack.com/archives/C01JG3B20RY/p1636231473311300

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
