### ISSUE TITLE
Multiple instances of a function by different names, incorrectly share env vars

### ISSUE THREAD

**Issue by rcoundon** [sst/sst#1017]
I have a single function definition that can be included in a stack multiple times with different names.

```ts
  someIds.forEach((someId) => {
     const populatorFunction = new sst.Function(this, `someFunction-${someId}`, {
        handler: 'src/main/handler/populator.someHandler',
        environment: {
          MY_VAR: someId,
        },
      });

      new sst.Cron(this, `MyCron-${someId}`, {
        schedule: process.env.POPULATOR_CRON,
        job: {
          function: populatorFunction,
        },
      });
  })
```
So you can see that the MY_VAR env var is set according to the value from a string array defined earlier.
When running this using sst start I'm seeing some odd behaviour regarding the env var MY_VAR.
On the first kick off of each lambda via the cron, sometimes the value of the env var is correct. However, after that, both lambdas have the same value for that env var. Sometimes they're the same on first start too.
Is there something about the local execution environment that would env vars end up getting shared between invocations of shared code?

@thdxr mentioned this could be do with the approach to hashing so maybe comparing the has and the function name might the way forward

**Comment by rcoundon** [comment]
Hi guys - any thoughts on this? It's causing us a fair bit of extra work as have to change our deployment for running locally to only use one instance of a function

**Comment by thdxr** [comment]
I'm going to be releasing something at the end of this week that will fix this issue

**Comment by rcoundon** [comment]
Great news, thank you

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
