### ISSUE TITLE
Support Cognito sts:TagSession in Identity Pool Role

### ISSUE THREAD

**Issue by simonireilly** [sst/sst#1034]
## Issue

I want to be able to extend the identity pool role of the Auth construct like the attached:

https://github.com/simonireilly/serverless-stack/pull/2

## Why?

I want to secure client and server-side with multi-tenant IAM policies as shown in the following code snippet:

code: https://github.com/simonireilly/saas-stack/blob/828ffe5839d80f53df3445cb38dac5e19e44cf2d/lib/DataStack.ts#L6-L64

When the trust relationship has `sts:TagSession` claims in the cognito JWT can be forwarded to the identity pool role, and used as pseudo params in the IAM policy.

```
{aws:PrincipalTag/<cognito_custom_claim>}
```

Example: 

| Description | Example |
| --- | --- |
| Talk direct to API Gateway and DynamoDB multi-tenant safe from the browser | ![secure-iam-client-side](https://user-images.githubusercontent.com/30017294/141737841-ced5f1de-ae8f-4190-9c6c-c2bc6216c715.gif) |

Demonstration site: https://d1mmk10lcvudwp.cloudfront.net/

Currently the underlying CDK implementation is also incorrect, but will be supported soon: https://github.com/aws/aws-cdk/issues/15908

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
