### ISSUE TITLE
Support Permission Boundaries

### ISSUE THREAD

**Issue by jcwrightson** [sst/sst#1056]
I may be wrong, but I've yet to find a way to attach a permission boundary to my stack rendering this tool useless to me.

**Comment by fwang** [comment]
Hey @jcwrightson, you can set permission boundaries on a stack like this:
```js
import * as iam from '@aws-cdk/aws-iam';

const boundary = new iam.ManagedPolicy(this, 'Boundary', {
  statements: [
    new iam.PolicyStatement({
      effect: iam.Effect.DENY,
      actions: ['iam:*'],
      resources: ['*'],
    }),
  ],
});

iam.PermissionsBoundary.of(this).apply(boundary);
```

Thanks for bringing this up! It just made me realize if we should add a helper function to help add permission boundaries on all stacks within an app. Something like:
```js
app.setDefaultPermissionBoundary(boundary);
```

Either way, we need to do a better job at documenting this.

**Comment by fwang** [comment]
Added an example to the doc https://docs.serverless-stack.com/constructs/Stack#setting-permission-boundary

**Comment by jcwrightson** [comment]
Cheers @fwang I tried that method initially but it did not work... I've also tried the `cdk.Aspects.of(this).add....` to no avail. Is there a way to do the `cdk synth` so that I can see the CloudFormation?

**Comment by fwang** [comment]
Hey @jcwrightson, yeah, after running `npm run build`, you can find the templates in `.build/cdk.out`.

So my stack looks like this (ie. contains 1 API with permission boundary set)
```ts
import * as iam from '@aws-cdk/aws-iam';
import * as sst from "@serverless-stack/resources";

export class MainStack extends sst.Stack {
  constructor(scope: sst.App, id: string, props?: sst.StackProps) {
    super(scope, id, props);

    // Create Api
    const api = new sst.Api(this, "Api", {
      routes: {
        "GET /": "src/lambda.main",
      },
    });

    // Create Permission Boundary
    const boundary = new iam.ManagedPolicy(this, "Boundary", {
      statements: [
        new iam.PolicyStatement({
          effect: iam.Effect.DENY,
          actions: ["iam:*"],
          resources: ["*"],
        }),
      ],
    });
    iam.PermissionsBoundary.of(this).apply(boundary);

    this.addOutputs({
      Endpoint: api.url || "no-url",
      CustomEndpoint: api.customDomainUrl || "no-custom-url",
    });
  }
}
```

And if I inspect the CFN template, I see this block:
```json
    "BoundaryEA298153": {
      "Type": "AWS::IAM::ManagedPolicy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": "iam:*",
              "Effect": "Deny",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        },
        "Description": "",
        "Path": "/"
      },
      "Metadata": {
        "aws:cdk:path": "dev-playground-api/Boundary/Resource"
      }
    }
```
And it's applied to all IAM Roles in the stack like this:
```json
    "ApiLambdaGETServiceRole210B6205": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
              ]
            ]
          }
        ],
        "PermissionsBoundary": {
          "Ref": "BoundaryEA298153"
        }
      },
      "Metadata": {
        "aws:cdk:path": "dev-playground-api/Api/Lambda_GET_--/ServiceRole/Resource"
      }
    },
```

Let me know if no luck on ur end. I can share a simple repo.

**Comment by jcwrightson** [comment]
Yep thanks! That's all good but when configuring an S3 bucket's retention
property and choosing DELETE as the SST stack does, an IAM policy is
created without the boundary. I had the same issue with serverless
framework. My organisation forces all IAM entities to have an attached
permission boundary 🤷‍♂️

**Comment by fwang** [comment]
Came across this thread https://github.com/aws/aws-cdk/issues/5925

Ppl seems to be setting the permission boundary manually on the IAM policy in this case, until CDK adds a proper fix.

**Comment by js-timbirkett** [comment]
I'm confused @jcwrightson - maybe you can help clarify - you set on IAM Permissions Boundaries on IAM Roles. With the above code examples, there are permissions boundaries set on all roles created (Aspects are used under the hood to ensure that). IAM policies, however, don't and can't have a permissions boundary set: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html

Maybe you can post an error that you're getting?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
