### ISSUE TITLE
sst update: use npm to update if yarn.lock is found outside of the SST repo

### ISSUE THREAD

**Issue by fwang** [sst/sst#1057]
Imaging this structure:
```
yarn.lock  
my-sst-app/                <-- repo root
  sst.json
  package.json
  package-lock.json
```
Running `npx sst update` will create a `yarn.lock` file inside the repo root. This should not happen.

---
Requests
- Ross https://serverless-stack.slack.com/archives/C01JVDJQU2C/p1637233703317200

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
