### ISSUE TITLE
`jest.mock()` calls not getting hoisted to the top by `esbuild-runner/jest`

### ISSUE THREAD

**Issue by joquijada** [sst/sst#1065]
This is more of a question than an issue. But, am I missing something? I'm using the OOTB configs and commands to run Jest tests written in TypeScript (I.e. the tests themselves are written in TypScript, examplke `my-module.test.ts`). I understand that under the hood, the Jest TypeScript tests are getting transpiled to JavaScript via configured Jest transformer `esbuild-runner/jest` (See [here](https://github.com/serverless-stack/serverless-stack/blob/master/packages/cli/scripts/util/createJestConfig.js), search for `"\\.ts$": "esbuild-runner/jest"`). But the generated JavaScript tests do not `jest.mock()` calls hoisted to the top. Example below is snippet of a test file, notice `jest.mock()` calls appear near the middle, nowhere near the top,

```
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const lambda = __importStar(require("../src/acme-lambda"));
jest.mock('ioredis');
jest.mock('@acme/common-util');
...
```

This is problematic because the code being tested will then see the actual modules instead of the mocked ones. 

The transpiling transformer that Jest uses OOTB, namely `babel-jest`, does honor hoisting, as per [this snippet of the Jest docs](https://jestjs.io/docs/code-transformation),

> Jest ships with one transformer out of the box - babel-jest. It will automatically load your project's Babel configuration and transform any file matching the following RegEx: /\.[jt]sx?$/ meaning any .js, .jsx, .ts and .tsx file. In addition, babel-jest will inject the Babel plugin necessary for mock hoisting talked about in ES Module mocking.

One way around this for me is to use dynamic `import()`'s in my tests, with the caveat that the dynamic `import()` appears _after_ the `jest.mock()` call for the given module. Is this the way to go? Should this question be posted in the [esbuild-runner/jest](https://github.com/folke/esbuild-runner/) project? I would think SST would handle `jest.mock()` hoisting correctly OOTB. I saw the SST unit test example [here](https://serverless-stack.com/chapters/unit-tests-in-serverless.html), but it's pretty basic and it does not use `jest.mock()`. I would like to make sure I'm following best practices to deal with this. Any advice is appreciated. Thanks.

**Comment by fwang** [comment]
Hey @joquijada, lemme loop in @thdxr. He's more familiar with the TypeScript and Jest setup.

**Comment by joquijada** [comment]
Thanks @fwang . @thdxr I've found a nice way to overcome this, namely by adding the below in my `package.json`,

`package.json`:
```
  "jest": {
    "setupFilesAfterEnv": ["./jest-test-setup.js"]
  },
```

And then creating my mocks in that file. This ensures the `jest.mock()` calls are all done earlier before the first `import...` happens,

`jest-test-setup.js`:
```
jest.mock('ioredis')
jest.mock('@acme/common-util')

const actualAcmeCommonUtil = jest.requireActual('@acme/common-util')
const redisGetMock = jest.fn()
const redisSetMock = jest.fn()

jest.mock('@acme/common-util', () => {
  actualAcmeCommonUtil.redisClient = {
    get: redisGetMock,
    set: redisSetMock
  }
  return actualAcmeCommonUtil
})
```

```

**Comment by OndeVai** [comment]
+1

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
