### ISSUE TITLE
Passing a JS/TS lambda handler by reference instead of src path

### ISSUE THREAD

**Issue by maciejgoscinski** [sst/sst#1068]
Hello!

At the moment, the only way to connect a lambda handler function to an APIGw route (or Function construct) is to pass it as a string path:
`src/blabla/certainLambdasFile.handlerFunction`. This is consistent with how CloudFormation refers to the handler method, but otherwise pretty gimmicky as something to be written "by hand".

When working in an all-typescript project, possibly a monorepo, it would be super handy to pass the handler by reference:

```
import { handlerFunction} from 'src/blabla/certainLambdasFile';

// ...
'GET /myLambda' : handlerFunction
// ..
```

There's been a [discussion on Slack](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1634222371143300) explaining it's rather difficult from the architecture standpoint.

Perhaps it would be possible to bypass the architectural problems, by "cheating" at build-time, swapping the references with their paths?

Also, is a "freely dangling" exported function the only way to export a handler? Would a class method, or the following syntax be possible anyhow?
```
export function MyLambdas() {
   function handler() { }

   return { handler }
}
```

**Comment by CorentinDoue** [comment]
With the serverless framework and CDK, we declare the configuration of the function in the same folder as the handler and use `__dirname` to resolve the path:

src
L_ functions
     L_ myFunction
         L_ config.ts
         L_ handler.ts
L_ stack.ts

```ts
// config.ts

export const myFunction = new NodejsFunction(this, 'Lambda', {
      entry: getCdkHandlerPath(__dirname),
      handler: 'main',
      runtime: Runtime.NODEJS_18_X,
      architecture: Architecture.ARM_64,
});
```

But as SST compiles all the stack in a single `.sst.config.1695484916830.mjs` before executing it, the dirname is not the right one. 

It could probably be done with an esbuild plugin to resolve the path when SST build the `.sst.config.1695484916830.mjs`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
