### ISSUE TITLE
sst start: watcher does not pick up changes in imported code

### ISSUE THREAD

**Issue by fwang** [sst/sst#1069]
### Steps to reproduce
1. Add an import to `lambda.handler`
```js
import config from "./config";
...
```
2. `sst start` detects the change and rebuilds the function. Rebuild will fail because `config.js` is not found.
3. Add `config.js`
4. `sst start` does not detect the change because it was not watching `config.js`

Now, any changes in `config.js` are not being watched. Until a change is made to `lambda.handler`, esbuild will then recognize `config.js` as a output file and add it to the watcher.

**Comment by dangreaves** [comment]
@fwang confirming that I can reproduce this, except I think it's a little more generalised than your example.

1. Create a handler file
2. Start `sst start`
3. Create config.js (nothing happens in SST)
4. Add `import config from "./config"` to the handler (see SST rebuilds)
5. Make a change in config.js (nothing happens in SST)

This implies that even though esbuild now "knows" about config.js via the import, it's still not added to the watcher. The only way to get any changes to config.js included in the watcher is to restart `sst start`.

**Comment by fwang** [comment]
Oh I see.. just bumped up the priority on this. Let me take a look.

@dangreaves Thanks for hunting this down!

**Comment by andrewbateman** [comment]
I came up with a workaround for this. It appears that the file watcher for each Lambda is scoped to the "srcPath" set for the function ([see watcher.ts](https://github.com/serverless-stack/sst/blob/20187e3d03acb36352e053f32f9864525beab48a/packages/core/src/runtime/watcher.ts#L20)). By manipulating this and the handler string for the function, you can force SST to watch as much or as little of your codebase as you like. e.g. 

```
const api = new Api(stack, "api", {
    defaults: {
      function: {
        srcPath: "../../packages",//e.g. in a monorepo, this will now watch all of your packages. 
        bundle: {
          format: "esm",
          loader: {".csv": "text"},
        },
      },
    },
    routes: {
      $default: "path/to/the-package/src/api-handler.handler",
    },
  });

```
OR, if you want to be more granular.....


```
const api = new Api(stack, "api", {
    defaults: {
      function: {
        srcPath: "../../packages/path/to/the-package/src/",//e.g. this will now watch only "the-package"
        bundle: {
          format: "esm",
          loader: {".csv": "text"},
        },
      },
    },
    routes: {
      $default: "api-handler.handler",
    },
  });

```

It's a bit of a blunt instrument, but works for my use case.

@fwang the watcher excludes node_modules, which is not always ideal for monorepo users, as node_modules is where changes to imported workspace packages are realised (I am using PNPM, so the workspace packages are symlinked locally for each package). Could this be configurable so we could choose to watch node_modules?

**Comment by fwang** [comment]
Lemme loop in @thdxr as he's more familiar w/ the watcher.

**Comment by andrewbateman** [comment]
Or could you somehow use esbuild --watch instead, given that esbuild is already used to bundle the functions (at least for node)? This works really well for most cases, including monorepos. So rather than watcher -> trigger build -> update live lambda, it could be build + watch -> update live lambda.

**Comment by Newbie012** [comment]
It appears that even if I re-run `sst start`, the client won't detect any changes, leading to a stale code in runtime.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
