### ISSUE TITLE
sst deploy: support hotswap

### ISSUE THREAD

**Issue by fwang** [sst/sst#1073]
Enable CDK's `--hotswap` flag https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/README.md#hotswap-deployments-for-faster-development

---
Requests
- Mike McCall
- Andrew https://serverless-stack.slack.com/archives/C01UJ8MDHEH/p1646261689015789

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
