### ISSUE TITLE
add description for tear down of CDKToolkit stack to tutorial

### ISSUE THREAD

**Issue by AdrianLoer** [sst/sst#1088]
**Background:** I was going through the [tutorial](https://serverless-stack.com/chapters/create-a-hello-world-api.html) and at first ran `sst start` with node v17 active. A warning appeared that 17 is untested so I cancelled the process.

Repeated runs after downgrading to node v16 seemed stuck. I checked cloudformation and the ~~debug~~ CDKToolkit stack from before was apparently stuck in `REVIEW_IN_PROGRESS`. I then manually deleted it and everything seems to work as expected.

**Proposal:** Add a description of how to delete the cloudformation ~~debug~~ CDKToolkit stack and any other resources so that the AWS account is reset to before the initial ~~debug~~ CDKToolkit stack setup was interrupted.

If it already exists perhaps link to it from this tutorial step. I could not find it

Edit: I meant the CDKToolkit stack, not debug

**Comment by riyadshauk** [comment]
I'm in this boat too. @AdrianLoer how'd you go about fixing this problem? I'm already forgetting how to log into the AWS console to do stuff because SST is so awesome (except maybe when something like this happens).

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
