### ISSUE TITLE
 Example: assigning a static IP to a Function

### ISSUE THREAD

**Issue by peter-sharp** [sst/sst#1089]
Communicating with APIs that enforce security via IP whitelisting would be a lot easier if there was a SST guide or a Function setting for assigning a static IP to a Function. There are a few guides for how to do this in console but, for someone who's relatively new to SST/AWS-SDK converting those steps into SDK code is a little daunting.

**Comment by fwang** [comment]
Hi @peter-sharp, gotcha!

You'd have to create a VPC with a NAT Gateway. Assign a elastic IP to the NAT Gateway. And finally deploys the functions in the VPC.

Will put together an example for this. cc @Manitej66

**Comment by peter-sharp** [comment]
@fwang What's the status on this?

**Comment by pjvds** [comment]
Any news on this @fwang or @peter-sharp?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
