### ISSUE TITLE
[AppSyncApi] Creating a pipeline resolver fails if no `dataSource` was specified.

### ISSUE THREAD

**Issue by alichry** [sst/sst#1115]
Creating a pipeline resolver does not require specifying a `dataSource` value. `AppSyncApi.addResolver` performs several checks on the passed value to determine whether the resolver is a data source resolver or a Lambda function definition (1, 2).

If `dataSource` is `undefined`, a Lambda function creation error will be thrown: `Error: Invalid function definition for the "Lambda_${ypeName}_${fieldName}" Function`

Somewhere down the line, CDK will throw an error if a `pipelineConfig` was passed along with a `dataSource` (3). Passing `""` as a `dataSource` or any non-existing data source key would make both SST and CDK happy =)

Any thoughts? I would like to open a PR for this.

- [(1) SST: AppSyncApi.ts#L386](https://github.com/serverless-stack/serverless-stack/blob/09573c6f261e5fd16d5931e0f4f094e4fa272817/packages/resources/src/AppSyncApi.ts#L386)
- [(2) SST: AppSyncApi.ts#L433](https://github.com/serverless-stack/serverless-stack/blob/09573c6f261e5fd16d5931e0f4f094e4fa272817/packages/resources/src/AppSyncApi.ts#L433)
- [(3) CDK: resolver.ts#L85](https://github.com/aws/aws-cdk/blob/b606a2321769d5e8f15072a62848aaba35bb1d35/packages/%40aws-cdk/aws-appsync/lib/resolver.ts#L85)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
