### ISSUE TITLE
LAMBDA_TASK_ROOT environment variable is not set

### ISSUE THREAD

**Issue by geauser** [sst/sst#1118]
In the example project implementing [Sentry monitoring](https://serverless-stack.com/examples/how-to-use-sentry-to-monitor-your-serverless-app.html), I get the following error when running the wrapped lambda handler via the API HTTP endpoint:

```
Error: LAMBDA_TASK_ROOT environment variable is not set
```

This is triggered by `node_modules/@sentry/serverless/dist/awslambda-auto/awslambda-auto.js`:

```js
Object.defineProperty(exports, "__esModule", { value: true });
const Sentry = require("./index");
const lambdaTaskRoot = process.env.LAMBDA_TASK_ROOT;
if (lambdaTaskRoot) {
    const handlerString = process.env._HANDLER;
    if (!handlerString) {
        throw Error(`LAMBDA_TASK_ROOT is non-empty(${lambdaTaskRoot}) but _HANDLER is not set`);
    }
    Sentry.AWSLambda.init();
    Sentry.AWSLambda.tryPatchHandler(lambdaTaskRoot, handlerString);
}
else {
    throw Error('LAMBDA_TASK_ROOT environment variable is not set');
}
//# sourceMappingURL=awslambda-auto.js.map
```

Is it a problem with the tutorial not being up to date or something deeper?

**Comment by thdxr** [comment]
Hey @geauser is this in local development mode or when you deploy to production? We generally conditionally attach sentry so it only runs in real deployments

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by apetta** [comment]
I'm getting this in v3 as well, strange because it worked fine on `dev`/`staging` stages but crashing with this error on `production` stage - I'm sure some config is causing that.

Here's the error:
```
Run pnpm sst deploy --stage production
/home/runner/work/***-serverless/***-serverless/node_modules/.pnpm/@sentry+aws-serverless@9.13.0/node_modules/@sentry/aws-serverless/src/awslambda-auto.ts:30
  throw Error('LAMBDA_TASK_ROOT environment variable is not set');
        ^


Error: LAMBDA_TASK_ROOT environment variable is not set
    at <anonymous> (/home/runner/work/***-serverless/***-serverless/node_modules/.pnpm/@sentry+aws-serverless@9.13.0/node_modules/@sentry/aws-serverless/src/awslambda-auto.ts:30:9)
    at ModuleJob.run (node:internal/modules/esm/module_job:263:[25](https://github.com/Wyzr-uk/wyzr-serverless/actions/runs/14644607025/job/41095553605#step:11:26))
    at async ModuleLoader.import (node:internal/modules/esm/loader:540:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:112:9)
```

EDIT: This went away when I stopped trying to set `NODE_OPTIONS` via SST environment var config, and instead setting it in the AWS console post-deployment
