### ISSUE TITLE
Preserve cdk.out assets between builds

### ISSUE THREAD

**Issue by revmischa** [sst/sst#1121]
I have a lambda layer to provide prisma - it builds fine with SST however it takes some time to build. Each time I run sst deploy it deletes the cdk.out directory it uses to rebuild the app, which blows away my cached layer that took a while to build. 

When I use normal CDK without SST it preserves the built layer and doesn't need to rebuild it each deployment. Is it possible to not delete all the assets from cdk.out every deploy?

**Comment by fwang** [comment]
Hey @revmischa, I actually wasn't aware of this. So CDK doesn't rebuild an asset if it's already present inside `cdk.out`? I'm curious how do they know the asset doesn't need to be built 🤔

**Comment by revmischa** [comment]
@fwang CDK assets such as lambda layers and code have options to control the hashing of content to detect if it needs to be rebuilt etc. You can even use your own custom hashing method - see the AssetOptions docs: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3-assets.AssetOptions.html#assethash

My prisma layer uses this:
```ts

    const createBundleCommand = [
      // create asset bundle in docker
      "bash",
      "-c",
      [
        `mkdir -p ${layerDir}`,
        // install PRISMA_DEPS
        `cd ${layerDir} && HOME=/tmp npm install ${modulesToInstallArgs}`,
        // delete unneeded engines
        `rm -f ${engineDir}/introspection-engine* ${engineDir}/prisma-fmt*`,
        // sdk sux
        `rm -f ${sdkDir}/dist/libquery_engine*`,
        `rm -rf ${sdkDir}/dist/get-generators/*engine*`,
        // get rid of some junk
        `rm -rf ${nm}/prisma/build/public`,
        `rm -rf ${nm}/prisma/prisma-client/src/__tests__`,
        `rm -rf ${nm}/@types`,
      ].join(" && "),
    ]

    // hash our parameters so we know when we need to rebuild
    const bundleCommandHash = crypto.createHash("sha256")
    bundleCommandHash.update(JSON.stringify(createBundleCommand))
```

So it only rebuilds if the "dockerfile" changes

**Comment by edoardolincetto** [comment]
Same issue! 🤔 
Right now, I'm using `Code.fromAsset()` passing a zip to avoid a new rebuild during each deployment.

**Comment by Gr33nLight** [comment]
Hello,
I am facing the same issue.
If I change the code from a single lambda, the other lambdas get rebuilt on deploy too (taking a lot of extra time), even if I didn't change anything..

Thanks

**Comment by gduquesnay** [comment]
Same issue.  In our case the build has started to time out in Seed.  Not sure what to do now.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
