### ISSUE TITLE
Feature Request: Terraform CDK

### ISSUE THREAD

**Issue by justindra** [sst/sst#113]
This is more of a future integration, but it would be cool to also have an option to use the Terraform CDK on top of the AWS CDK. This will make it a lot more flexible in the future to switch to other providers or even just have resources in different providers.

**Comment by jayair** [comment]
Yeah, we've been watching https://github.com/hashicorp/terraform-cdk. It'll most likely be the route we take when we add support for other providers.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
