### ISSUE TITLE
Create runtime helpers to parse user pool id from Lambda event object

### ISSUE THREAD

**Issue by fwang** [sst/sst#1132]
Gabriel suggested this:
```js
import { cognitoUtils } from '@serverless-stack/runtime'

[...]

const userIds = cognitoUtil.extractUserPoolInfoFromIdentityContext(context)
const userRole = cognitoUtil.extractAssumedRoleNameFromIdentityContext(context)
```

---
Requests:
- Gabriel https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1638967652013700?thread_ts=1638964681.012100&cid=C01HQQVC8TH

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
