### ISSUE TITLE
Script: allow setting custom resource output from function's return value

### ISSUE THREAD

**Issue by fwang** [sst/sst#1133]
---
Requests:
- Bshr https://serverless-stack.slack.com/archives/C01JG3B20RY/p1638750727052400

**Comment by oscarthorn** [comment]
This would be really nice to have, I'm currently using cdk custom resource directly since I need output values.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
