### ISSUE TITLE
Dependabot complaining about dep-sec issues

### ISSUE THREAD

**Issue by iDVB** [sst/sst#1139]
![image](https://user-images.githubusercontent.com/189506/145621564-89eb9823-a378-4bc8-80f0-2dd80580dc6b.png)

All relating to cli and resournces

![image](https://user-images.githubusercontent.com/189506/145621657-d25a2849-7cbe-4ea2-a528-180cad00ffc8.png)

**Comment by iDVB** [comment]
@fwang @thdxr Are dep-sec issues a priority for SST?
Now that we are rolling many things out with SST at our company, these gaps are being picked up by our Trust team and its making for a bit of a bumpy SST onboarding-ride.

**Comment by fwang** [comment]
Hey @iDVB I will take a look at this today and have this updated!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
