### ISSUE TITLE
Support stacks with different AWS account

### ISSUE THREAD

**Issue by fwang** [sst/sst#1140]
Dan listed out two uses cases for this:
1. Stack Cleanup Webhook (Github => Lambda)
  - when feat branches are deleted in github, this lambda goes out and tears down the associated enviroment. This can be across two AWS accounts. Sandbox (DEV envs) and Prod (RC envs)
  - In order for that Lambda to have permissions, I need to have already created a Role in the Sandbox account it can assume in order to delete stacks in that account.
2. Cross-Account-Site Lambda@Edges
  - we have an Edge lambda that is used on all our sites both dev (AWS account 1) and prod (AWS account 2) this lambda needs access to that site’s bucket to access it’s routing file. This access is given via that site’s bucket policy.
  - I wasn’t sure if I could easily give a cross-account role access in a bucket policy so we create duplicate Lambda@Edge functions in both sandbox and production accounts as well as roles.
---
Ashish also shared some reasonings:
> 1. Deploy only apps that are affected, because Cfn will take decades to generate the changeset.
> 2. Ensure that an affected service / account / region doesn't impact another.
> 3. Separate free-tier and limits per account.
> 4. simpler dev onboarding, create account via sso, clone service repo, deploy.
> 5. separation of data from infra, i.e. separate xray, s3, dynamodb, rds accounts, helps a lot if looking into getting compliant.
> 6. most importantly, seed could deploy in parallel and probably figure out a deploy pattern in case of a monorepo.

> The separation of data from infra seems trivial but is an amazing point because it allows separation of data (can't access all data together to make sense of it). If designed well, this would inherently make any service idempotent i.e. the underlying data layer wouldn't matter. The single-table per app approach would move into a single table per service approach. Also, decoupled apps would help in decoupling teams, reducing blast-radius on failures, etc.
---
Requests:
- Dan https://serverless-stack.slack.com/archives/C01JG3B20RY/p1639060811159700?thread_ts=1638989201.132200&cid=C01JG3B20RY
- Austin & Edward https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1654100600194559
- Ashish https://discord.com/channels/983865673656705025/985224097342582865/1014310900464881766

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
