### ISSUE TITLE
create-serverless-stack failing with "CMake executable is not found"

### ISSUE THREAD

**Issue by aggiustino** [sst/sst#1145]
Hello, I'm trying to set up a new SST app but the process seems to be broken due to a dependency error.

How to reproduce it:

Command: `npx create-serverless-stack@latest test-app`.

Error:
```
npm ERR! code 1
npm ERR! path /Projects/test2/node_modules/aws-crt
npm ERR! command failed
npm ERR! command sh -c node ./scripts/install.js
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info TOOL Building only the install target, as specified from the command line.
npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! /Projects/test2/node_modules/cmake-js/lib/cMake.js:117
npm ERR!         throw new Error("CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.");
````

**Comment by fwang** [comment]
Hey @aggiustino, thanks for bring this up.

**Comment by aggiustino** [comment]
I'm on MacOS Monterey, a quasi pristine installation. Node 16.13.0.
It was my first time creating a SST app. Installing manually CMake via brew fixed the issue.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
