### ISSUE TITLE
ESLint, Jest, TSJest, Typescript should be devDependencies and (maybe) peerDependencies in cli and resources

### ISSUE THREAD

**Issue by dkershner6** [sst/sst#1151]
https://github.com/serverless-stack/serverless-stack/blob/3985a15a2f02b281fa4a9e8c41e3005444a3c62e/packages/resources/package.json#L70-L82

Example is for resources.

These dependencies cause downstream projects to install multiple versions of each of these (unless they exactly match) which causes conflicts.  There are some less concerning ones that could probably also be devDependencies like `chalk`, `graphql` and `@types`, but they are less likely to cause problems.

I don't know of any downside to this change.

**Comment by kamsar** [comment]
Ran into this just now trying to use a TypeScript 4.9 feature that works fine for my package.json version of TS, but since SST is pinned to 4.8 its build does not use my installed TypeScript version and instead uses its own.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
