### ISSUE TITLE
AppSyncApi: Add a resolver for external labmda data source

### ISSUE THREAD

**Issue by AntoniusGolly** [sst/sst#1155]
I want to define a schema like this

```
type Query {	
   getStatus: String
}
```

whereas the field `getStatus` should be **resolved by an external lambda data source**. I need to reference this lambda function by its functionArn. 

Q: _How can that be done?_

## Basic code
```
import * as sst from "@serverless-stack/resources";

export default class MyStack extends sst.Stack {
  constructor(scope: sst.App, id: string, props?: sst.StackProps) {
    super(scope, id, props);

    // Create the AppSync GraphQL API
    const api = new sst.AppSyncApi(this, "AppSyncApi", {
      graphqlApi: {
        name: "nextApi",        
        schema: "graphql/schema.graphql"
      },
      dataSources: {
        notes: "src/main.handler" // internal handler
      },
      resolvers: {
        "Query getNoteById"   : "notes",
        "Mutation createNote" : "notes",
        "Mutation updateNote" : "notes",
        "Mutation deleteNote" : "notes",
      },
    });

    // add Data Source
    //  ? 
    // add field
    //  ?

    api.addResolvers(this, {
      "Query getStatus": "XXXXX" // what to specify here?
    })
   
    // Show the AppSync API Id in the output
    this.addOutputs({
      ApiId: api.graphqlApi.apiId,
    });
  }
}

```
### Adding the data source
I [was given the advice](https://github.com/serverless-stack/serverless-stack/issues/998) to use `addLambdaDataSource`. However, when the value passed to `addResolver` is a string, [it is expected](https://github.com/serverless-stack/serverless-stack/blob/master/packages/resources/src/AppSyncApi.ts#L358) to be in `this.dataSourcesByDsKey`.

When using this code
```
const dataSource = api.graphqlApi.addLambdaDataSource("serviceManagerLambda", lambda)

api.addResolvers(this, {
  "Query getStatus": dataSource.name
})
```
that won't add the key to `dataSourcesByDsKey` :( and I'm getting expectadly `Failed to create resolver "Query getStatus". Data source "serviceManagerLambda" does not exist.`

So, I need to utilize `api.addDataSource()` and I tried
```
const lambda = sst.Function.fromFunctionArn(
    this,
    'external-lambda-from-arn',
    'arn:aws:lambda:eu-central-1:000000000000:function:service-manager-dev-graphql'
)
 api.addDataSources(this, {
  "serviceManagerLambda": lambda
})
```
resulting in `Invalid function definition for the "Lambda_serviceManagerLambda" Function`.

I also tried 
```
const lambda = sst.Function.fromFunctionArn(
  this,
  'external-lambda-from-arn',
  'arn:aws:lambda:eu-central-1:000000000000:function:service-manager-dev-graphql'
)

const mappingTemplate = appsync.MappingTemplate.fromString('$util.toJson($context.result.statusCode')
const dataSource = api.graphqlApi.addLambdaDataSource("serviceManagerLambda", lambda)

const field = new appsync.ResolvableField({
  returnType: appsync.GraphqlType.string(),
  dataSource: dataSource,
  responseMappingTemplate: mappingTemplate,
})

// add Query
api.graphqlApi.addQuery('getStatus', field)
```
resulting in `Unable to add query. Schema definition mode must be CODE. Received: FILE`
I can apparently have only either File definition for the schema OR code. 

Even when I remove the file definition having only that constructor
```
// Create the AppSync GraphQL API
const api = new sst.AppSyncApi(this, "AppSyncApi", {
  graphqlApi: {
    name: "nextApi"
  }  
});
```
it is compiling but not giving the correct resolver attached. 

Result in AppSync console:
![image](https://user-images.githubusercontent.com/3856505/146080761-c42f998a-1dbb-4c9f-a343-393f28e78537.png)

Now, I'm lost. 
Please point me into the right direction or can it not be done?

**Comment by davideicardi** [comment]
Hi @AntoniusGolly . I have the same requirements, creating a data source that point to an external defined lambda. Did you ever solved this problem?

**Comment by fwang** [comment]
Hey @davideicardi by externally defined Lambda, is the Lambda function created outside of the SST app, or is it created in another Stack within the same app?

**Comment by davideicardi** [comment]
My lambda is defined by another service, outside of the SST app.
I have managed to solve this using the following code:

```
    const api = new sst.AppSyncApi(this, "lab-AppSyncApi", {
      graphqlApi: {
        schema: "graphql/schema.graphql",
      },
    });

    const ds = api.graphqlApi.addLambdaDataSource(
      "patients",
      sst.Function.fromFunctionArn(
        this,
        'test-patients',
        'arn:aws:lambda:eu-west-1:XYZ:function:list-patients'
      )
    )

    ds.createResolver({
      typeName: "Query",
      fieldName: "listPatients",
    })
```

Not sure if there are better alternatives.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
