### ISSUE TITLE
Default test suite failed to run in serverless-stack graphql-appsync example template

### ISSUE THREAD

**Issue by vivekvt** [sst/sst#1157]
I created new graphql appsync project using this [command](https://github.com/serverless-stack/serverless-stack/tree/master/examples/graphql-appsync#getting-started)

```
yarn create serverless-stack --example graphql-appsync
```

Then I ran the test
```
npm run test
```

I got this error

```
Running type checker
 FAIL  test/MyStack.test.ts
  ● Test suite failed to run

    test/MyStack.test.ts:1:38 - error TS2307: Cannot find module '@aws-cdk/assert' or its corresponding type declarations.

    1 import { expect, haveResource } from "@aws-cdk/assert";
                                           ~~~~~~~~~~~~~~~~~
    test/MyStack.test.ts:3:21 - error TS2307: Cannot find module '../lib/MyStack' or its corresponding type declarations.

    3 import MyStack from "../lib/MyStack";
                          ~~~~~~~~~~~~~~~~

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.905 s
Ran all test suites.
```

serverless-stack graphql-appsync example template needs to updated
In `MyStack.test.ts`
- their is no  `'../lib/MyStack'` instead it should import it from `'../stacks/MyStack'`
- Add `@aws-cdk/assert` to dependencies in package.json

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
