### ISSUE TITLE
sst deploy based on sst build

### ISSUE THREAD

**Issue by jpmtrabbold** [sst/sst#1159]
[Link to discussion](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1639608724350000)

Would it be possible to develop an option on `sst deploy` so that it could deploy based on the outputs of a previous `sst build`?

**Comment by jpmtrabbold** [comment]
@thdxr based on our discussion on Slack

**Comment by louislatreille** [comment]
Hi @thdxr and @jpmtrabbold ! Are there any updates on this feature request? This would be really useful to build CI/CD pipelines for application using SST. Currently, if we want to deploy to multiple regions, for example, the application needs to go through the exact same build for each region, leading to a lot of wasted resources.

**Comment by thdxr** [comment]
This is going to be included in our next phase of work which will overhaul parts of our CLI.

I can't give an exact timeline but we won't be starting it for a month.

**Comment by louislatreille** [comment]
Awesome @thdxr ! Thanks for the quick reply! I've just started working with SST and absolutely love it!

Let me know if I can help with that feature at some point. I just took a look at the project board, I assume it's this issue: https://github.com/serverless-stack/sst/issues/1467? We could close one of the two, as they seem exactly the same.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
