### ISSUE TITLE
NextjsSite: Allow configuring nextjs-lambda build options 

### ISSUE THREAD

**Issue by 3stacks** [sst/sst#1165]
In the builder the default option defines the build command like this:

```
const defaultBuildOptions = {
    cwd: process.cwd(),
    cmd: "./node_modules/.bin/next",
}
```

This is problematic for me because I'm working in a Yarn monorepo, so the `next` binary is not in the working directory, but in the root of the monorepo. As far as I could tell in the NextjsSite construct the only place those `defaultBuildOptions` are actually overridden is on line 578 here:

`packages/resources/src/NextjsSite.ts`
```
const configBuffer = Buffer.from(
      JSON.stringify({
        cwd: path.resolve(sitePath),
        args: ["build"],
      })
    );
```

By passing in the path to my `next` binary there (see below. I determine the path to the binary using the command `yarn bin next`) my build instantly starts working as expected without having to change the hoisting strategy of my monorepo.

```
const configBuffer = Buffer.from(
      JSON.stringify({
        cwd: path.resolve(sitePath),
        cmd: '/<repositoryRoot>/node_modules/next/dist/bin/next',
        args: ["build"],
      })
    );
```

I'm more than happy to implement this and submit a PR, but I'd just like to run it past the maintainers to see how those props should be passed down into the construct. 

Thanks!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
