### ISSUE TITLE
TypeScript project generation doesn't work when using npm init

### ISSUE THREAD

**Issue by moshe-shaham-dt** [sst/sst#1168]
This creates a JS project, rather than TypeScript, as stated in the docs:

`npm init serverless-stack@latest my-sst-app -- --language typescript`

https://docs.serverless-stack.com/installation

Using `npx create-serverless-stack` works correctly

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
