### ISSUE TITLE
Function: log groups do not respect removal policy

### ISSUE THREAD

**Issue by fwang** [sst/sst#1175]
## The issue
Log groups for Lambda functions are not created as a part of CloudFormation template. They are not being removed even if removal policy is set to DESTROY for the function.

## Solution 1
Manually create the log group and set removal policy to DESTROY. This can only work for named functions.

## Solution 2
Create a custom resource that removes the log group. But a log group will be created for the custom resource, which won't get deleted.

## Solution 3
SST collects a list of functions before `sst remove`, and calls AWS SDK API to remove the log groups manually. How to handle SST failing when removing the log groups?

---
Requests:
- Matt Morgan https://serverless-stack.slack.com/archives/C01JVDJQU2C/p1640043494022700?thread_ts=1640038363.011600&cid=C01JVDJQU2C

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
