### ISSUE TITLE
Console: Playbook feature

### ISSUE THREAD

**Issue by fwang** [sst/sst#1177]
Gabriel suggested a Playbook feature. It works like this:

For more complex cases.. I use a playbook page.. where we define "plays" for each scenario that the develop may want.. for example:
- users ready to onboard
- users with no friends
- users with 1k friends
- etc..

Make this available only for non-prod envs and the "play" button call a lambda that does the magic..

And scripts for basic after deploy data..

inside each play you can store information/access etc.. but this would force a dynamo table to store "play data".. not that simple but make sense for large application.. and lots scenarios..

```js
const playbook = new sst.Playbook(app, {
"Scenario Name": "lambda/path"
})
```

each play (lambda) would return data.. and we could store that data in dynamo and get this data for the lifetime of the environment or until we reset playbook data..
e.g.:
imagine a place that generates users for testings.. each user in a different context. You turn up you environment and open sst console to check the playbook section to generate or get an user... Imagine we run: admin user.. the lambda function would run, generate the user and return data login info. We could store this as a play result and make this available in the console.. next time you don't need to run  the data is already there..

store the "output of that lambda" if is a link to a page or a user or other data..

what sometimes I use is the AWS console itself.. run a test for a lambda and log the output of this seeder lambda with console.log... so I can get in aws console..
I would imagine sst console with a better ux/ui for this kind of seeder lambdas..

sst script works for that... but my point is for more complex use cases and better development experience... imagine a QA running your app and need to test the system in a give context for a given user.. open the sst console and run play x.. off you go.. you can now test it..

---
Requests:
- Gabriel Araújo https://serverless-stack.slack.com/archives/C01JG3B20RY/p1640123827048800?thread_ts=1640033855.457100&cid=C01JG3B20RY

**Comment by RichiCoder1** [comment]
So would the basic design of this be something like: (inspired by CDK custom resource design)
<img width="456" alt="image" src="https://user-images.githubusercontent.com/2391878/147599482-9cf16aee-462b-44ed-9435-898141e38527.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
