### ISSUE TITLE
CLI: Unable to find function undefined

### ISSUE THREAD

**Issue by jayair** [sst/sst#1181]
I think this is an edge case but I see these log messages most likely because I'm commenting out certain stacks. They probably had a cron resource and now that the function isn't deployed it's giving this error.

```
Unable to find function undefined
```

It would be helpful if the error message told me which resource had the problem?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
