### ISSUE TITLE
Example: GraphQL Apollo Example Cannot Enable Playground

### ISSUE THREAD

**Issue by ngoctranfire** [sst/sst#1182]
Hi there, I have tried out the Serverless Stack Apollo GraphQL example. For some reason, no matter what I do, the graphql Playground does not seem to ever work. There is no link to access the GraphQl Playground. I was wondering if anyone was able to get it to work. I would love some guidance on this!

This is the only thing I see even when I set the following settings:
```
const server = new ApolloServer(<Config<LambdaContextFunctionParams>>{
  typeDefs,
  resolvers,
  playground: {
    endpoint: "/dev/graphql"
  },
  introspection: true,
});

export const handler = server.createHandler(<CreateHandlerOptions>{
  cors: {
    origin: '*',
    credentials: true,
  }
});

```
![Screen Shot 2021-12-24 at 10 55 25 PM](https://user-images.githubusercontent.com/3119704/147379405-4409a478-1fae-4482-b942-2ea7f02dca78.png)

**Comment by fwang** [comment]
Hey @ngoctranfire, which playground r u referring to? If you go to the deployed URL, do you see a similar playground in the attached screenshot?
<img width="1296" alt="apollo-graphql-playground" src="https://user-images.githubusercontent.com/83515/147380943-a1a2db33-29e9-41a7-a265-b0831187ddca.png">

**Comment by ZimaBlue6** [comment]
You have the wrong e-mail address, Frank.

**Comment by ngoctranfire** [comment]
Hey Frank, when I go to the deployed address (referring to the one I deployed), I don't see that address. I see the screenshot I have attached above.

**Comment by ngoctranfire** [comment]
@fwang I figured out what the issue is. It actually has to do with the version I'm using:
In your example, the version you are using is:
"apollo-server-lambda": "^2.21.1".

In my version, I am using: 
```
    "apollo-server-lambda": "^3.5.0"
 ```
Barring this difference, nothing else is different. It seems I need to file an issue with apollo-server-lambda's repository.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
