### ISSUE TITLE
Adding ESBuild Plugins

### ISSUE THREAD

**Issue by ngoctranfire** [sst/sst#1183]
I wanted to add the ESBuild GraphQL Loader plugin. I read up on Serverless Stack and I saw that it is using ESBuild. Can we add Plugins to support importing .graphql files? I wanted to see if there was a way for us to just add in configurable ESBuild plugins.

**Comment by rcoundon** [comment]
You can do it like this:
https://docs.serverless-stack.com/constructs/Function#configure-esbuild-plugins

**Comment by ngoctranfire** [comment]
Awesome! Didn't see this. Amazing!

**Comment by ngoctranfire** [comment]
Actually, I followed the docs, but I am running into this issue:
```
 No loader is configured for ".graphql" files:
 ```

Here is what I'm doing right now as in my settings:

```
const api = new sst.ApolloApi(this, "ApolloApi", <ApolloApiProps>{
      defaultFunctionProps: <sst.FunctionProps>{
        loader: {
          ".graphql": "graphql-loader-plugin",
        },
        bundle: {
          plugins: "src/esBuildConfig.js",
        }
      },
      server: "src/graphql.handler",
      rootPath: "/",
    });
    ```

**Comment by rcoundon** [comment]
I think you may need something like this:
https://github.com/luckycatfactory/esbuild-graphql-loader
However, I'm not sure how (or if?) it's possible to specify a loader in the esbuildConfig. I can see that `define` and `keepNames` options are there but not `loader` 

I know others are using GQL in various ways so there must be some way to achieve this. I'm sure one of the authors will respond.

**Comment by ngoctranfire** [comment]
Yes, I did download that graphql loader and do use it as well too. That file looks like this:
// esBuildConfig.js (can this be written in Typescript).
```
import graphqlLoaderPlugin from '@luckycatfactory/esbuild-graphql-loader';

module.exports = [
  graphqlLoaderPlugin(),
];

```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
