### ISSUE TITLE
Console: Leave the function request body after an invocation

### ISSUE THREAD

**Issue by jayair** [sst/sst#1194]
This lets users invoke it again with the same payload or a slightly different one. Ideally we should remember this for all the functions so as you switch screens it'll hang on to the last payload.

Originally brought up here: https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1640734631177900

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
