### ISSUE TITLE
Console: add a new route with non-exist handler path > deploy stack > crash

### ISSUE THREAD

**Issue by fwang** [sst/sst#1195]
Steps to reproduce:
1. Run `sst start`
2. Add a new route with `handler` pointing to a non-exist file
3. Select redeploy in console
4. `sst start` crashes after redeploy succeeds

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
