### ISSUE TITLE
Console: new resources do not show up after redeploying stacks 

### ISSUE THREAD

**Issue by fwang** [sst/sst#1199]
Step to reproduce:
- Run `sst start`
- Add a new `Bucket` to a stack
- Go to the Console and `Deploy` the stack changes

After deploy succeeds, the new Bucket does not show up in the Console automatically. The Bucket shows after refreshing the page.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
