### ISSUE TITLE
Console: Error fetching metadata when sst start boots up

### ISSUE THREAD

**Issue by fwang** [sst/sst#1201]
Steps to reproduce:
- Open up SST Console, you should see `waiting for CLI...`
- Run `sst start`
- SST Console show error `Error fetching metadata`
<img width="462" alt="Screen Shot 2021-12-31 at 2 57 06 AM" src="https://user-images.githubusercontent.com/83515/147811049-e73aa0f1-0b73-4f72-b486-349668ca29ec.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
