### ISSUE TITLE
Show stack function is in

### ISSUE THREAD

**Issue by thdxr** [sst/sst#1229]
> Just been looking at the new console and I like it - nice work guys!  A couple of related suggestions though...
> 
> On the local tab it would be useful to see the stack the invoked function was from.  For example, we have a *Lambda_GET_--* entry and in order to work out which stack it's from you have to click on the item to navigate to the function entry.  We have ~22 stacks so it's not always obvious which one it's from and it'd be nice to not have to keep navigating backwards and forwards.
> 
> The related issue is that it might be useful to see the stack name in the function detail pane too.  At the moment, you have to scroll up the navbar to see which stack it's from, which can be a bit of a pain if your stack has lots of functions.
> 
> Hopefully both easy UI only tweaks to change (if you agree!) :slightly_smiling_face:

---
Request: https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1641318808253600

**Comment by carlosdnba** [comment]
Hey I think I can help with that

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
