### ISSUE TITLE
Upgrade the @serverless-stack/nextjs-lambda dependency

### ISSUE THREAD

**Issue by lalau** [sst/sst#1234]
My company has an open source license scanner and block packages that include certain licenses. Although the package @serverless-stack/nextjs-lambda has MIT license, it bundles other code that uses other licenses that are blocked, such as [detect-libc](https://www.npmjs.com/package/detect-libc) which is Apache-2.0. The installation of @serverless-stack/nextjs-lambda is blocked and I am unable to install @serverless-stack packages because it is a [dependency](https://github.com/serverless-stack/serverless-stack/blob/fbd7dfcf9991443ad00ff73dd9a66547369d2d6e/packages/resources/package.json#L69).

After some digging, looks like @serverless-stack/nextjs-lambda has been renamed to [@sls-next/lambda-at-edge](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/libs/lambda-at-edge) and is several major versions ahead. It also no longer bundle these packages. Can we please upgrade to use the new package?

**Comment by fwang** [comment]
Hi @lalau, sorry for the delayed response. I'm going to update the package this week, and also move it out of the @serverless-stack/resources to its own package. So if you are not using the `sst.NextjsSite` construct, you won't have it as a dependency.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
