### ISSUE TITLE
Python REST API example has runtime error when deployed

### ISSUE THREAD

**Issue by SethThomas** [sst/sst#1239]
Checking out the [python REST API example](https://github.com/serverless-stack/serverless-stack/tree/master/examples/rest-api-python) and executing `sst start` works as expected.

Deploying with `sst deploy` successfully deploys the API without error.  However, when accessing the API endpoint `GET /notes`, I am faced with a runtime exception.

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'list': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/var/lang/bin/python3.8"
  * The NumPy version is: "1.21.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

Traceback (most recent call last):
```

It appears that numpy is not properly packaged when deployed.  I was able to get this particular example working by importing numpy as a lambda layer instead of importing/packaging it in the project directly.

  However, I thought it was useful to raise this issue since there is a difference between local and deployed python projects that can be confusing.

**Comment by SethThomas** [comment]
Here's the [same example using lambda layers to include Numpy](https://github.com/SethThomas/sst-rest-api-python)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
