### ISSUE TITLE
Execution of aws-lambda-ric unreliable on node 14 with yarn workspaces

### ISSUE THREAD

**Issue by ttarhan** [sst/sst#1253]
Hello,

On node 14 when using yarn workspaces, the following line which executes `aws-lambda-ric` can cause unexpected behavior:

https://github.com/serverless-stack/serverless-stack/blob/4ec613a6d8b1325115ff7f8ae32dcc340751b1f4/packages/core/src/runtime/handler/node.ts#L225

The core issue is that yarn will hoist `aws-lambda-ric` to the workspace root, however the `npx` that ships with node 14 does not search parent `node_modules` (or so, it seems from empirical testing). As such, `npx` will not find `aws-lambda-ric` as being "locally installed", and instead it will download `aws-lambda-ric`, install it in a temporary location, and execute from there. The problem is, when it finds and installs `aws-lambda-ric`, it will find the upstream version, rather than `@serverless-stack/aws-lambda-ric`, and the upstream version doesn't work (fails trying to load nativeClient).

This does not happen in node 16+, as `npx` now seems to find the locally installed copy of `aws-lambda-ric` in the parent `node_modules` directory.

I'm not sure what the best solution is. Using `--package` with `npx` will force the right package to be selected for `aws-lambda-ric`, but it will also cause `npx` to install the package every time (it will not cache it between runs, and it will not use the locally installed version in `node_modules`). The best solution might be to rename `aws-lambda-ric` to a new name and then name the package appropriately so that it's the default found/used by `npx`.

Workaround: upgrade `npm` (and therefore `npx`).

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
