### ISSUE TITLE
Provisioned Concurrency Example

### ISSUE THREAD

**Issue by pabacham** [sst/sst#1269]
Is there any example of how to set up Provisioned Concurrency for all the functions in the API? Because seems like this ex does not work https://docs.serverless-stack.com/constructs/Function#configuring-provisioned-concurrency

When I create a Function and pass it to the API, I get this error 
Error: The "defaultFunctionProps" cannot be applied if an instance of a Function construct is passed in. Make sure to define all the routes using FunctionProps, so the API construct can apply the "defaultFunctionProps" to them.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
