### ISSUE TITLE
Consider supporting provided.al2 runtime + ARM processor for Go

### ISSUE THREAD

**Issue by NickBlow** [sst/sst#1271]
Since Amazon Linux is now EOL, AWS is recommending people use provided.al2 runtime for Go Lambdas - this also has the benefit of supporting the new ARM graviton processors. Potentially even do this as default as the cost / performance is better.

The [CDK Go Lambda ](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-lambda-go-readme.html) passes GOARCH as well, which allows ARM support.

Thanks.

**Comment by fwang** [comment]
Tracking a list of people requested for this:
- PeterSSTLover https://discord.com/channels/983865673656705025/999779383571132507
