### ISSUE TITLE
Next.js 12 - `target` config deprecated

### ISSUE THREAD

**Issue by mmkal** [sst/sst#1290]
Getting a warning when building with next.js 12:

```
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
```

Those docs suggest refactoring to use output file tracing (don't know much about it but sounds cool!): https://nextjs.org/docs/advanced-features/output-file-tracing

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
