### ISSUE TITLE
Construct for Vite SSR

### ISSUE THREAD

**Issue by fwang** [sst/sst#1330]
Ross suggested that:
> Another suggestion for a new context, ViteSSRSite. This would expect an app using one the vite SSR libraries (https://github.com/vitejs/awesome-vite#libraries) to spit out a single lambda file for the app. With this you could skip the s3 bucket all together and go with just an APIGateway or maybe this could get really fancy and just use cloudfront and run the Lambda @ Edge. Likely could just wrap up what is being done here https://github.com/jamesladd/aws-vite-ssr. An interesting side effect here, since it is a lambda, is it may be able to work via live dev like other lambdas do...

---

Requests:
- Ross Gerbasi https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1643909541328319

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
