### ISSUE TITLE
Script: display Lambda logs in deploy output

### ISSUE THREAD

**Issue by fwang** [sst/sst#1338]
Requested by Brinsley:
> Hey guys, been playing with the `Script` construct as a way of running migrations in a post-deploy process. Anyone know how to get logs from my functions to output in the console?

---
Request:
- Brinsley https://serverless-stack.slack.com/archives/C01JG3B20RY/p1643713209182869

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
