### ISSUE TITLE
Example: Nestjs

### ISSUE THREAD

**Issue by fwang** [sst/sst#1360]
Kujtim Hoxha shared his configuration for setting up Nextjs with SST:

I had to do this to make nestjs work:
1. Add this to these compiler options:
```
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
  }
```
2. Add a new file to the root esbuild.js  also install 
```
@anatine/esbuild-decorators
const { esbuildDecorators } = require("@anatine/esbuild-decorators");

module.exports = [esbuildDecorators()]; 
```
3. Add these function configs
```
 bundle:{
      externalModules:["@nestjs/websockets","@nestjs/microservices", "cache-manager"],
      esbuildConfig: {
        plugins: "esbuild.js",
      },
    }
```
If you use the modules that are marked as external here install them and remove them from the list.

---
Requests:
- Kujtim https://serverless-stack.slack.com/archives/C01JG3B20RY/p1644782537364839
- Karolis https://serverless-stack.slack.com/archives/C01JG3B20RY/p1650962851588789
- Ravi https://serverless-stack.slack.com/archives/C01JG3B20RY/p1652117777329449

**Comment by masterbater** [comment]
I was thinking of using sst to deploy nestjs
Does this support this feature?
- Websockets
- Queue using bullmq
- prisma
- bcrypt binaries

**Comment by jayair** [comment]
Oops @masterbater this is really old. Honestly Nest.js doesn't work great in Lambdas.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
