### ISSUE TITLE
Gracefully handle CloudFormation stack stuck in the UPDATE_ROLLBACK_FAILED state

### ISSUE THREAD

**Issue by fwang** [sst/sst#137]
### How to reproduce
1. create an `sst.Auth` object with a valid auth0 domain, ie. "https://hello.us.auth0.com", and deploy
2. remove "https://" from it, ie. "hello.us.auth0.com", and deploy again
3. deployment should fail
4. change domain back, and deploy again
5. deployment should fail saying the stack is stuck in the UPDATE_ROLLBACK_FAILED state

### What can users do
According to AWS Support, https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-update-rollback-failed/
> If your stack is stuck in the UPDATE_ROLLBACK_FAILED state after a failed update, then the only actions that you can perform on the stack are the ContinueUpdateRollback or DeleteStack operations.

### How to fix
Idealy, SST should try to automatically continue to rollback. And if cannot be rolled back, display a helper saying contact AWS Support or delete the stack.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
