### ISSUE TITLE
Add an example of debugging Python functions in VS Code

### ISSUE THREAD

**Issue by fwang** [sst/sst#1377]
Nicklas https://serverless-stack.slack.com/archives/C01JG3B20RY/p1644504125778219

**Comment by DubKF** [comment]
It's not fully fledged out (e.g. missing command line support to switch debugging on / off without modifying the function), but this could serve as a base for later improvement https://serverless-stack.slack.com/archives/C01JG3B20RY/p1653290821502669?thread_ts=1653277309.443279&cid=C01JG3B20RY

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
