### ISSUE TITLE
GraphQL console: add support for signing requests with AWS_IAM authorization

### ISSUE THREAD

**Issue by Rohithgilla12** [sst/sst#1378]
Thanks for such an amazing framework, it is great.

When using `ApolloApi` along with `defaultAuthorizationType: sst.ApiAuthorizationType.AWS_IAM,` is giving Forbidden error when opening the preview URL

Is there any way to use the console, it would help during the development process.

I could do something like checking the environment and flip it accordingly but wanted to know if it is the right way or do we have any cleaner way.

**Comment by fwang** [comment]
Hi @Rohithgilla12, you'd need to sign the request with the IAM credentials. I'm not aware of a simple way to do that in Apollo Studio.

Btw, are you using the `sst.Auth` construct for the `AWS_IAM` authorization?

^^The reason I'm asking is b/c we added a GraphQL playground to the SST Console. And we are planning to add support for signing in as a user from the User Pool, and auto-signing the API requests with its IAM credentials. (cc @thdxr)

**Comment by Rohithgilla12** [comment]
@fwang Oh yes I am using the `sst.Auth` 
I discovered sst recently and I am in awe with what is accomplishes, loved it.

I did check the GraphQL playground in the sst console, but apollo playground has a bit more features so was inclined towards that.


Thanks for the reply waiting for the support for signing in as a user from User pool.

**Comment by fwang** [comment]
Yup, added this to our roadmap. I will keep you posted when we have something.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
