### ISSUE TITLE
Update copy for no resources found

### ISSUE THREAD

**Issue by fwang** [sst/sst#1379]
Cognito tab: `No Auth constructs found with User Pool enabled in this app`
Buckets tab: `No Buckets constructs found in this app`
RDS tab: `No RDS constructs found in this app`
GraphQL tab: `No GraphQLApi or AppSyncApi constructs found in this app`

And link the construct names to the doc.

---
Dan: https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645134874517199?thread_ts=1644521017.718079&cid=C01JG3B20RY

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
