### ISSUE TITLE
Topic: allow the same Function subscribe to multiple Topics

### ISSUE THREAD

**Issue by fwang** [sst/sst#1380]
Submitted a PR to CDK https://github.com/aws/aws-cdk/pull/19028

---
Requests:
- Hubert https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645106814842379?thread_ts=1643732326.046299&cid=C01JG3B20RY

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
