### ISSUE TITLE
Invalid S3 bucket name in DebugStack

### ISSUE THREAD

**Issue by teyckmans** [sst/sst#1383]
I'm running into an "Invalid S3 bucket name" error.

Tracked down that it is introduced since 0.60.9, 0.60.8 does not give this error.

![image](https://user-images.githubusercontent.com/44382/154686810-e2bc1e66-2ddb-4967-8cd1-27a3388c27fe.png)

I'm guessing it is caused by the trailing `-` in the generated name.

**Comment by teyckmans** [comment]
If we revert this locally it works again: https://github.com/serverless-stack/serverless-stack/commit/52982ff43d0c968d9abd5a4840e94641653f0ef3 

I don't really get what it does but this is the place to look.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
