### ISSUE TITLE
Api: add option to set access log group name

### ISSUE THREAD

**Issue by fwang** [sst/sst#1386]
Current workaround: Create a log group and pass in to access log
```js
const logGroup = new logs.LogGroup(this, "LogGroup", {
  logGroupName: "/custom/log/group",
});

new Api(this, "Api", {
  accessLog: {
    destinationArn: logGroup. logGroupArn,
  },
  routes: {
    ...
  },
});
```

---
Requests:
- Kujtim https://serverless-stack.slack.com/archives/C01JG3B20RY/p1644438060724169

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
