### ISSUE TITLE
Waiter InvalidationCompleted failed: Max attempts exceeded

### ISSUE THREAD

**Issue by fwang** [sst/sst#1397]
Deploying `StaticSite` fails on cache invalidation:
```
Received response status [FAILED] from custom resource. Message returned: Waiter InvalidationCompleted failed: Max attempts exceeded
```
![image (12)](https://user-images.githubusercontent.com/83515/155040806-393821a2-e301-42e8-a459-7368e8505171.png)

We should gracefully handle this error.

---
Dan https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645060768947149

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
