### ISSUE TITLE
Auto-generate VTLs

### ISSUE THREAD

**Issue by fwang** [sst/sst#1404]
Amplify is generating all default VTL's and basically overwrites the once that is modified.

Reference: https://docs.amplify.aws/cli/graphql/custom-business-logic/#extend-amplify-generated-resolvers

Requests:
- Mr.9715 + Nir Weiner https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645450719825309

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
