### ISSUE TITLE
Add support for parameter mapping

### ISSUE THREAD

**Issue by fwang** [sst/sst#1405]
Requests
- Jonathan https://serverless-stack.slack.com/archives/C01JG3B20RY/p1643737535260019
- Jan + Aman https://serverless-stack.slack.com/archives/C01JG3B20RY/p1646268771126119

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
