### ISSUE TITLE
SSM Parameters Reset

### ISSUE THREAD

**Issue by robosung** [sst/sst#1416]
When we recently updated from version **0.49.2** to **0.54.4** all our SSM parameters were reset to their original values.
It is okay in most cases, but some parameters were updated "out of band" and needed to be manually reset afterward.

Is this expected behavior? I don't believe we experienced this before so we would like to understand what caused it and how we can guard against it in the future.

Thank you

**Comment by fwang** [comment]
Hi @robosung, thanks for bringing this up. Can I see how the SSM parameters are created in ur app? And how are the values updated usually, through AWS Console?

**Comment by robosung** [comment]
Hi @fwang, I apologize for the delayed response.

The SSM parameter is created like so:

```
    new ssm.StringParameter(this, "this-is-my-parameter", {
      stringValue: "CHANGEME",
      parameterName: "this-is-my-parameter",
    });
```

**Comment by fwang** [comment]
Thanks @robosung. And are they updated manually through the AWS SSM Console?

**Comment by thdxr** [comment]
Hey @robosung typically with IaC tools all changes should be done through code.  If you make changes in the console there is "drift" and things maybe be set back to the IaC determined value at any time

**Comment by robosung** [comment]
@fwang Yes, it's done manually, usually via console.

@thdxr Yes, that's what we try to do most of the time, but because it's CDK, it doesn't work for things provisioned outside of AWS, like webhook URLs, API keys, etc.  It would be great if there is a recommendation for a better approach?

Thank you

**Comment by fwang** [comment]
I see. Is there any specific reason why you are not creating the SSM parameter in the console to begin with?

**Comment by robosung** [comment]
The main reason is that if they were solely created through ClickOps, it's not clear that it's required with provisioning the application. It also allows us to establish references and linkage to the parameters/secrets in code, as part of IaC.
I know it's a little arbitrary since we decided to document the **need to update the parameters** instead of documenting the **need to create the parameters**.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
