### ISSUE TITLE
Sometimes Functions get updated on redeploy when nothing has changed

### ISSUE THREAD

**Issue by fwang** [sst/sst#1417]
Requests:
- Patrick https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645660108808139?thread_ts=1641851553.159900&cid=C01JG3B20RY

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
