### ISSUE TITLE
Stuck on "syncing metadata" in brave browser

### ISSUE THREAD

**Issue by fwang** [sst/sst#1424]
Michael reported that:
> it ended up being because I was using the brave browser and it was blocking certain scripts.. I had to turn off shields up for that site

---
Requests:
- Ernie & Michael https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645667543916359
- Uday https://serverless-stack.slack.com/archives/C01JG3B20RY/p1648911297987219

**Comment by Manitej66** [comment]
HTTP requests are blocked my brave from HTTPS enabled websites.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
