### ISSUE TITLE
Clear all invocations in local tab

### ISSUE THREAD

**Issue by fwang** [sst/sst#1425]
Requests:
- Dan https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1642699280052700
- Daniel https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1645716854634269

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
