### ISSUE TITLE
RDS Schema Migrations - Error: Could not resolve "pg-native"

### ISSUE THREAD

**Issue by bbeckrest** [sst/sst#1427]
Hello,

I'm attempting to use the new RDS construct w/ Kysely to run migrations for Aurora Serverless. 

I'm seeing the following error when I click the "Migrations" button in the SST console (while running locally w/ `sst start`):

```
7dfa4346-d7a0-44a8-9c34-744bbf50573c REQUEST aurora-api-db-dbrdsauroraMigrationFunction97E-vOGZsozm21aw [index.handler] invoked
✘ [ERROR] Could not resolve "pg-native"

    node_modules/pg/lib/native/client.js:4:21:
      4 │ var Native = require('pg-native')
        ╵                      ~~~~~~~~~~~

  You can mark the path "pg-native" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

7dfa4346-d7a0-44a8-9c34-744bbf50573c ERROR build_failure: The function index.handler failed to build
```

Any idea what could be happening here? Thanks.

**Comment by fwang** [comment]
Hey @bbeckrest, are you using Prisma or any ORM client?

**Comment by fwang** [comment]
Yeah, I was confused too. The migrator does not import `pg`. Btw, are you configuring any function props using `app.setDefaultFunctionProps()`?

**Comment by bbeckrest** [comment]
I am, but just this though:

```
app.setDefaultFunctionProps({
  runtime: 'nodejs14.x',
});
```

Idk how this is related, but here's my API construct that references `pg-native`. I think this is the only place I reference it.
```
   this.api = new sst.Api(this, 'Api', {
      // ...
      defaultFunctionProps: {
        environment: {
          DB_NAME: process.env.DB_NAME,
          DB_CLUSTER_ARN: dbCluster.clusterArn,
          DB_SECRET_ARN: dbCluster.secretArn,
        },
        permissions: [dbCluster],
        bundle: {
          esbuildConfig: {
            keepNames: true,
          },
          externalModules: ['pg-native', 'pg-query-stream'],
          nodeModules: ['oso'],
          copyFiles: [{ from: 'src/oso/main.polar', to: 'src/oso/main.polar' }],
        },
        // ...
      });
```

**Comment by bbeckrest** [comment]
So once I deleted & uninstalled `knex` and `pg` from my `package.json`, the error disappeared and I can apply migrations successfully.

Not sure why that was affecting the migrator though.

**Comment by fwang** [comment]
Hmm.. that's weird.

Are you ready to remove `knex` and `pg` from your app and switch to `myself`? If you have to put them back, would it be possible for u to setup a sample repo that can reproduce the issue? I can give it a try on my end.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
