### ISSUE TITLE
Allow filter by string partial match

### ISSUE THREAD

**Issue by fwang** [sst/sst#1432]
Currently string operators are not shown.

<img width="266" alt="Screen Shot 2022-02-25 at 1 06 17 PM" src="https://user-images.githubusercontent.com/83515/155765390-5c9176ef-3a64-466f-a6cd-dccbee52c2bb.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
