### ISSUE TITLE
Could not unzip uploaded file. Please check your file, then try to upload again.

### ISSUE THREAD

**Issue by fwang** [sst/sst#1436]
Artem reported:
> I was stuck with this error CREATE_FAILED | AWS::Lambda::LayerVersion | PrismaLayer958161C6 | Could not unzip uploaded file. Please check your file, then try to upload again. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4fa5aa5e-24be-4cfa-83d5-ef466628c847; Proxy: null) and could not understand what was happening. But it turned out that the reason is that the S3 bucket where SST uploads lambdas and layers zip files is full. So I manually deleted all objects from the bucket and now the deployment works. Is there a way to remove files from SST service bucket (cdk-hnb659fds-assets-660857977215-us-east-1) automatically?

This seems related to this CDK issue https://github.com/aws/aws-cdk/issues/5636#issuecomment-719901174

Remove all files in the bucket seems to get around the issue.

---
Requests:
- Artem + Bshr https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645626522994999

**Comment by heikkis** [comment]
CDK 1.150.0 had we experienced similar problem multiple times:

```
8:37:51 AM | UPDATE_FAILED        | AWS::Lambda::Function | AWS679f53fac002430cb0da5b7982bd2287 (AWS679f53fac002430cb0da5b7982bd22872D164C4C) Resource handler returned message: "Could not unzip uploaded file. Please check your file, then try to upload again. (Service: Lambda, Status Code: 400, Request ID: ad060fe5-bdf7-444c-abaf-e493873d9d68)" (RequestToken: f56d4602-2862-9310-61f6-93982febc727, HandlerErrorCode: InvalidRequest)
```

**Comment by adminCitify** [comment]
I JUST had this same issue, and removing the files did the trick. I trusted this thread but I'm not sure what I removed. New to SST here.

**Comment by nicoroy2561** [comment]
Having the same issue.
I've tried manually deleting the files from the bucket, but still got the same exact issue.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
