### ISSUE TITLE
CLI commands with \ line breaks fail on Windows

### ISSUE THREAD

**Issue by fwang** [sst/sst#1453]
It works if the command is typed in the same line.

![cli](https://user-images.githubusercontent.com/83515/156506203-e4e6617e-7985-4f9b-b445-f79ad85567f6.png)

---
Requests:
- Sulaiman https://serverless-stack.slack.com/archives/C01JG3B20RY/p1646236433678599

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
