### ISSUE TITLE
Selectively live debug Lambda functions

### ISSUE THREAD

**Issue by fwang** [sst/sst#1456]
Ross suggested:
> Have you guys considered providing the ability to run a subset of functions locally?
For example, maybe I’ve got some heavy lifting cron based functions that chug away and move data around from APIs into databases. I’m happy with those and I’m happy for them to carry on running in AWS.
However, I’m developing a lambda attached to an API route that uses that data which I want to debug locally?
I guess it could also be useful in a situation where there is a last resort emergency production issue that could be quickly identified by updating the stack to run that single function locally but have all the others carry on as they were.

ie.
```bash
sst start --enable-for some-lambda-func-name,some-other-lambda-func-name
```

---
Requests:
- Ross https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1646154372429339

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
