### ISSUE TITLE
Access cloud infrastructure through typed package inside lambda runtimes

### ISSUE THREAD

**Issue by cmaycumber** [sst/sst#1466]
I think it would be cool if you could access your cloud infrastructure  and easily use it inside of your different lambda runtimes for example something like this:

```js
import stack from '@serverless-stack/stack'

...
// Access queue from my lambda
stack.queue('myQueue').publish(params)
...

```

Right now we currently handle this by passing down env variables and calling the AWS SDK directly. 

So basically auto-generate an SDK for your cloud infra. I think [`arc.codes`](https://arc.codes/) has something similar. Thoughts?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
