### ISSUE TITLE
Custom path for dotenv files

### ISSUE THREAD

**Issue by fwang** [sst/sst#1468]
Seth suggested:
> Is there a convenient way to configure dotenv to look for .env files in a place _other_ than the root directory?  This isn't a big deal, but my root directory looks like a junk drawer, and I'd like to clean it up a bit.  For example, an `environment` folder at the project root would be nice.  Or having them alongside my stack definitions within the `/stacks` directory also makes sense since they aren't used elsewhere in my app

---
Request:
- Seth https://serverless-stack.slack.com/archives/C01JG3B20RY/p1646408992796689

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
