### ISSUE TITLE
Support other cloud providers like `Auth0` and `GitHub`

### ISSUE THREAD

**Issue by fwang** [sst/sst#1469]
Justin asked:
> yea mainly ask as we do use some services outside of AWS like Auth0 and Github that would be nice if it was all in one place rather than separate.

---
Request:
- Justin https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1646494187033559
- Discussion https://serverless-stack.slack.com/archives/C01JVDJQU2C/p1647297634296739
- Discussion https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1646494187033559
- Te

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
