### ISSUE TITLE
Passwordless login using Cognito

### ISSUE THREAD

**Issue by fwang** [sst/sst#1472]
Based on this guide https://schof.co/cognito-magic-links/

After creating the post, mention https://twitter.com/tschoffelen and Thomas Ankcorn
https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645179164839979

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
