### ISSUE TITLE
Example: SolidJS

### ISSUE THREAD

**Issue by Manitej66** [sst/sst#1474]
Requests:
- xinhash https://discord.com/channels/983865673656705025/983866416832864350/1037000851471995000

**Comment by Errol-Hassall** [comment]
Hey @Manitej66 
Given you raised this ticket a while back I was wondering how far you got and if I could take over if you hadn't gotten very far.

**Comment by fwang** [comment]
Hey @Errol-Hassall, are you using SolidJS as a static site, or are you looking to use Solid Start with SSR support?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
