### ISSUE TITLE
Run NextjsSite using fargate

### ISSUE THREAD

**Issue by fwang** [sst/sst#1475]
Robert mentioned that:

I am more and more leaning towards switching to lb + fargate. I have been hosting some sites this way and I get more freedom and also the latest features

I am running server.js  with node , generated by setting outputStandalone:true  in next experimental config. I am serving a version of vercel's platforms example in github for this other use case, but I am strongly leaning towards switching to this as well for my main site.

### Steps:
- Build an image using a version of vercel's example Dockerfile https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
- Use `NetworkLoadBalancedFargateService/ApplicationLoadBalancedFargateService` from `aws-cdk-lib/aws-ecs-pattern`
- Viewing logs from CloudWatch

---
Requests:
- Robert https://serverless-stack.slack.com/archives/C01JG3B20RY/p1646512244976869?thread_ts=1641330960.446700&cid=C01JG3B20RY
- heldl https://discordapp.com/channels/983865673656705025/1017225857326129203

**Comment by sladg** [comment]
Stumbled upon this repo: https://github.com/rajyan/low-cost-ecs when trying to tackle situations, when Lambda cannot be used, might be useful for inspiration.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
