### ISSUE TITLE
Accept multiple HTTP method for a given route

### ISSUE THREAD

**Issue by fwang** [sst/sst#1478]
Jan mentioned:

Is there a way to have 2 routes (GET + POST) using the same function and using defaultFunctionProps on Api.?

For example: "GET,POST /path": {}`

---
Request:
- Jan https://serverless-stack.slack.com/archives/C01JG3B20RY/p1646679363817119?thread_ts=1646677333.674539

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
