### ISSUE TITLE
Function: esbuild fails with no error output

### ISSUE THREAD

**Issue by fwang** [sst/sst#1486]
Ross reported that:
> I’m running into a problem when the endpoint is called which just says
> ```
> ERROR build_failure: The function src/handlers/lambdaHandlers.bookAppointmentHandler failed to build
> ```
> I can’t find any more information anywhere on what it was that caused the build to fail, where should I be looking?

Ross suspected the cause being:
> I changed a bunch of things as I went through the code, it’s possible it was down to changing a require to an import there and a missing reference to a function.

Dax mentioned that:
> there is a rare case I haven't been able to track down where ebsuild exits without printing an error

---
Requests:
- Ross https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1646654261723989

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
