### ISSUE TITLE
StaticSite: update cacheControl to enable CloudFront caching

### ISSUE THREAD

**Issue by fwang** [sst/sst#1503]
Current setting for `ReactStaticSite` and `ViteStaticSite`:
```js
{
  exclude: "*",
  include: "*.html",
  cacheControl: "max-age=0,no-cache,no-store,must-revalidate",
},
```
change to:
```js
{
  exclude: "*",
  include: "static-pages/*",
  cacheControl: "public,max-age=0,s-maxage=2678400,must-revalidate",
},
```

---
Requests:
- Derek https://serverless-stack.slack.com/archives/D02JU7000QP/p1646855329785929

**Comment by dkershner6** [comment]
Any reason why the `include` changed?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
