### ISSUE TITLE
Cleanup old files in CDK bootstrap bucket

### ISSUE THREAD

**Issue by fwang** [sst/sst#1504]
Dan asked:
> I noticed the S3 bucket that I assume SST uses to deploy, called something like `cdk-xx-assets-1234567-us-west-2` is not deleting old objects ... is there a reason why this bucket shouldn't have a lifecycle rule to remove old objects? Is there a recommendation on how to manage this bucket?

The bucket is mainly used to store Lambda function zip files. It is not safe to remove the files without knowing which ones are still in-use and which are orphaned. See a lengthy discussion here - https://github.com/aws/aws-cdk-rfcs/issues/64

I haven’t tried this toolkit-cleaner but it seems it will work if you dropped this right into ur SST app
```js
new ToolkitCleaner(this, 'ToolkitCleaner');
```

---
Request:
- Dan https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1646864401942289
- MageD https://discord.com/channels/983865673656705025/1000925767741485106

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
