### ISSUE TITLE
how to import  import /billing from the billing-api 

### ISSUE THREAD

**Issue by NoWillToBreak** [sst/sst#1506]
In https://serverless-stack.com/chapters/share-an-api-endpoint-between-services.html#Limitations.
how to import exist path in new service?
Project a: '/a'
How to use '/a/b' in Project b?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
