### ISSUE TITLE
StaticSite (all types) - Deleted files do not get deleted (and are therefore still available on S3/urls)

### ISSUE THREAD

**Issue by dkershner6** [sst/sst#1513]
Potential to create an option for the FileList to retain or delete file patterns?

cc: @iDVB 

https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1646235250400579

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
