### ISSUE TITLE
Waiter InvalidationCompleted failed: Max attempts exceeded

### ISSUE THREAD

**Issue by fwang** [sst/sst#1516]
When CloudFront takes long to invalidate the cache, the build can fail with error
```
Received response status [FAILED] from custom resource. Message returned: Waiter InvalidationCompleted failed: Max attempts exceeded
```

We should gracefully handle this error and not fail the build.

---
Request:
- Carlos https://serverless-stack.slack.com/archives/C01JG3B20RY/p1647013294342529

**Comment by aisflat439** [comment]
I'm having this problem today. Just as another data point.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
