### ISSUE TITLE
Add support for transpiling migrations

### ISSUE THREAD

**Issue by fwang** [sst/sst#1525]
Currently migrations are not transpiled. It comes with two limitations:
1. Cannot `import` kysely or other modules
2. Cannot write migrations in TS

---
Requests
- Brinsley https://serverless-stack.slack.com/archives/C01JG3B20RY/p1647257964678019
- Justin https://serverless-stack.slack.com/archives/C01JG3B20RY/p1645406980747339
- jamlen https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1646904078695309

**Comment by mendellerner** [comment]
Is there a way to compile the set of migrations into the lambda (such as by creating on object of all the files) rather than importing at runtime? This would allow users to use TypeScript.

My current setup is to have a `tsc watch` that processes the individual migrations and outputs the .js to a folder that I point to from the CDK.

**Comment by fwang** [comment]
Hey @mendellerner, I looked at the migrator function's package again, and it seems `kysely` is there at runtime. So no need for the layer. I think the issue is that you have to `require` instead of `import` because the code isn't transpiled.

I agree we should transpile the migrations so u can use TS.

Let me update this issue to "Add support for transpiling migrations".

**Comment by mendellerner** [comment]
Thanks.

Out of scope of the ticket, I had also wanted to import the AWS SDK Secret Client (v3) in order to create a read-only user in the migrations. I know I could have used the v2 library. I was able to solve it using a lambda layer.

**Comment by elkevinwolf** [comment]
@fwang is this in progress or planed? If not, I could collaborate with a PR!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
