### ISSUE TITLE
RDS Console: Screen becomes blank when there are no migrations

### ISSUE THREAD

**Issue by Manitej66** [sst/sst#1530]
When there are no migrations in the stack and when we click the migrations button in RDS console the screen becomes blank.
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/61357713/158559623-5aae1f37-0807-4d4f-acca-b940cc434f88.png">

**Comment by JohnMarsden24** [comment]
I've just experienced this randomly, did you check your browser console for any more error information?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
