### ISSUE TITLE
"sst build" naively assumes it was invoked interactively with AWS credentials

### ISSUE THREAD

**Issue by octogonz** [sst/sst#1537]
We are trying to add SST-based projects to a large corporate monorepo, however the SST toolchain assumes it will always be invoked by a person with AWS credentials, and who can respond to STDIN prompts.

## Repro steps

1. `npx create-serverless-stack@latest my-sst-app -- --language typescript`
2. `cd my-sst-app`
3. `npm run build`

## Actual behavior (problem)

1. The CLI prompts to read interactive input from STDIN:

```
Look like you’re running sst for the first time in this directory. Please enter a stage 
name you’d like to use locally. Or hit enter to use the one based on your AWS 
credentials (Owner):
```

2. Then the CLI refuses to proceed without AWS credentials: 
```
EnvironmentCredentialsProviderFailure: Variable AMAZON_ACCESS_KEY_ID not set.
```

## Expected behavior

It's fine to require  AWS credentials for operations that do deployments or communicate with Amazon's cloud.  However a developer should be able to **_compile_** source files and **_run Jest tests_** without AWS credentials.  

Also the `npm run build` action must not prompt for STDIN input, because it is invoked by monorepo commands that build many projects in parallel.

## Background
 
At our company, the SST projects exist in a monorepo that is used by many other developers, many of whom don't have AWS credentials at all, because they work on other project types such as client apps.  Those developers need to **_compile_** SST projects and **_run unit tests_** for validation, but they do not need to  **_run services_** or **_deploy service projects_**.  (In fact, today I am able to build/test all the projects in our monorepo in "airplane mode" without any internet at all.)

If we add SST projects to this workspace, the SST toolchain needs to distinguish compiling/testing (`sst build` and `sst test` let's say) from running/deploying (`sst start`, `sst deploy`).  The toolchain should assume that every user is a Serverless Stack developer with AWS credentials set up.

CC @frekje-wm @elliot-nelson @mickeyphoenix

**Comment by fwang** [comment]
Hi @octogonz, appreciate the details.

> 1. The CLI prompts to read interactive input from STDIN:
Building the SST app requires knowing the stage as resource names by default are generated based on the stage. The first time u run an SST command, it prompts for a default stage name. And that stage name is stored inside `.sst`. You can actually bypass this prompt by explicitly specifying the stage, ie. `sst build --stage dev`. Does that work for you?

> 2. Then the CLI refuses to proceed without AWS credentials:
The `sst build` process sometimes needs to perform one-off lookups using AWS SDK. For example, when you configure the Api domain like this:
```js
new Api(this, "Api", {
  customDomain: "api.domain.com",
  routes: {
    "GET /notes": "src/list.main",
    ...
  },
});
```
SST (CDK behind the scene) makes a call to your Route53 account to verify the `domain.com` Hosted Zone exists. Another example is, when you create a VPC, SST looks up how many subnets there are in the region. These lookups are done once, and cached in a file `cdk.context.json`. There might be something we can do here such that if no lookups are required, we skip the AWS credentials check.

Before settling on a solution, just to clarify:
1. Do developers have a default profile in `.aws/credentials` file, or do they have their own playground AWS account?
2. Do they need to `sst build` to run jest tests?

Happy to jump on zoom if that'd be easier to dive into some of the details.

**Comment by octogonz** [comment]
> Happy to jump on zoom if that'd be easier to dive into some of the details.

I'm free tomorrow (Thu) morning Pacific Time if that works. We can DM on Twitter or Zulip to arrange it.

**Comment by fwang** [comment]
Reached out on Twitter.

Also wanted to share a link to the Slack workspace if anyone on the team got any questions - https://serverless-stack.com/slack.

**Comment by olizilla** [comment]
It would be great if there was a command to get SST to only generate the types. We verify our jsdoc type comments with tsc in CI, but this now fails for the PR where we adopt the `Config` construct, as the magic types aren't available. We use seed.run to deploy, so we'd rather not be forced to provide aws credentials to CI as well.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
