### ISSUE TITLE
Display better error message when uploader fails due to S3 permission

### ISSUE THREAD

**Issue by fwang** [sst/sst#1538]
Hans mentioned that:

exceptions raised by subprocess calls in the site upload lambda is not handled gracefully, (i.e. Custom::SSTBucketDeployment here)
this results in pretty vague messages, e.g.
```
Custom::SSTBucketDeployment | .../ReactSite/S3Deployment/Default (ReactSiteS3Deployment...) Received response status [FAILED] from custom resource. Message returned: invalid request. Missing key 'Status'
```

i had to dig through the cloudwatch logs to find this
```
CalledProcessError: Command '['/opt/awscli/aws', 's3', 'cp', 's3:...', '/tmp/...']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/var/task/s3-upload.py", line 29, in handler
    s3_deploy(s3_source_zip, s3_dest, file_options, replace_values)
    ...
```

i had to modify the lambda a bit to log the exception to figure out what went wrong (permissions in this case)

---
Requests
- Hans https://serverless-stack.slack.com/archives/C01JG3B20RY/p1647431563850889

**Comment by mixman** [comment]
Such a random error. Happened to me and a co-worker at different times.

**Comment by jayair** [comment]
@mixman which version of SST is this?

**Comment by mixman** [comment]
Solved by adding build information to StaticSite, in our case:
```
    buildOutput: "build",
    buildCommand: "yarn build",
```

SST version 1.18.4. Backend runs on npm, if that makes any difference.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
