### ISSUE TITLE
Function concurrency not working locally and overloading the machine

### ISSUE THREAD

**Issue by unlimitechcloud** [sst/sst#1546]
Hello,

I've been using SST lately and I noted a problem in my use case.
I am developing an infrastructure for thousands of records processing. My test needs to upload thousands of records on queues to be proccessed by lambdas. The problem is that my dev machine is getting overloaded by too much parallel executions. I have configured concurrency to 1 on every function, but still the same function is spawned multiple times in parallel. 
Is there a way to limit local executions to 1 or to a preset number?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
