### ISSUE TITLE
Add a doc on how to resolve circular dependency

### ISSUE THREAD

**Issue by fwang** [sst/sst#1549]
A common use case being the `Api` needs to know `StaticSite`'s URL, and `StaticSite` needs to know the `Api`'s URL in environment.

**Comment by adambiggs** [comment]
Just ran into this exact issue! Do you have any tips before the doc is ready?

**Comment by rocketana** [comment]
Following as I have the same problem with circular dependencies of 3 stacks. For now I had to combine them into one big stack.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
