### ISSUE TITLE
Allow creating Function constructs through npm modules

### ISSUE THREAD

**Issue by fwang** [sst/sst#1550]
Currently it is tricky to create a 3rd party npm custom constructs that uses `sst.Function`. Reasons detailed in this Slack thread https://serverless-stack.slack.com/archives/C01JG3B20RY/p1647454228283289.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
