### ISSUE TITLE
Error: CloudWatch Logs role ARN must be set in account settings to enable logging

### ISSUE THREAD

**Issue by fwang** [sst/sst#1556]
### Error

```
ApiEndpoint: https://5hnofpe0i5.execute-api.us-east-1.amazonaws.com/

Stack gabiras-coffee-menu-websocket
  Status: failed
  Error: CloudWatch Logs role ARN must be set in account settings to enable logging (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: cacfd1a9-235b-41e8-a17c-3dc8eeaf7845; Proxy: null)
  Helper: This is a common error when configuring Access Log for WebSocket APIs. The AWS API Gateway service in your AWS account does not have permissions to the CloudWatch logs service. Follow this article to create an IAM role for logging to CloudWatch - https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/
```

### Solution

Create a Custom Resource to create the role

Matt wrote a blog post on this topic - https://blog.100daysofcloud.com/building-real-time-serverless-web-applications-with-aws-api-gateway-websocket-apis-cks7wumow046c22s14s3o9scg#cloudwatch-role

---
Request:
- Theo https://serverless-stack.slack.com/archives/C01JG3B20RY/p1647820546187119
- Gabriel https://serverless-stack.slack.com/archives/C01JG3B20RY/p1639782415403600
- Danielgato https://discord.com/channels/983865673656705025/991751731824308344/1030046428942303233

**Comment by bblanke** [comment]
This should be included in documentation; it's not a niche issue - it seems like this is a standard barrier to overcome when setting up a websocket API. Thanks for posting the solution @fwang

**Comment by myfreax** [comment]
@fwang @bblanke hello，can you tell me fix this issue. according to[ this blog ](https://blog.100daysofcloud.com/building-real-time-serverless-web-applications-with-aws-api-gateway-websocket-apis-cks7wumow046c22s14s3o9scg#cloudwatch-role) created the following code
```ts
import {
  WebSocketApi as WS,
  App,
  Stack,
  StackProps,
} from "@serverless-stack/resources";

import { ManagedPolicy, Role, ServicePrincipal } from "@aws-cdk/aws-iam";
import { CfnAccount, CfnStage } from "@aws-cdk/aws-apigateway";
import { WebSocketStage, WebSocketApi } from "@aws-cdk/aws-apigatewayv2";
import { LogGroup, RetentionDays } from "@aws-cdk/aws-logs";
import { RemovalPolicy } from "@aws-cdk/core";

export default class MyStack extends Stack {
  constructor(scope: App, id: string, props?: StackProps) {
    super(scope, id, props);


    const webSocketApi = new WebSocketApi(scope, "WebSocketApi")
    const cwRole = new Role(scope, 'CWRole', {
      assumedBy: new ServicePrincipal('apigateway.amazonaws.com'),
      managedPolicies: [ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonAPIGatewayPushToCloudWatchLogs')],
    });

    new CfnAccount(scope, 'Account', {
      cloudWatchRoleArn: cwRole.roleArn,
    });

    const stage = new WebSocketStage(scope, 'WebSocketStage', {
      autoDeploy: true,
      stageName: scope.stage,
      webSocketApi,
    });

    const log = new LogGroup(scope, 'AccessLogs', {
      removalPolicy: RemovalPolicy.DESTROY,
      retention: RetentionDays.ONE_WEEK,
    });

    const cfnStage = stage.node.defaultChild as CfnStage;
    cfnStage.accessLogSetting = {
      destinationArn: log.logGroupArn,
      format: `$context.identity.sourceIp - - [$context.requestTime] "$context.httpMethod $context.routeKey $context.protocol" $context.status $context.responseLength $context.requestId`,
    };



    const ws = new WS(this, "WS", {
      webSocketStage: stage,
      accessLog: true,
      routes: {
        $connect: "src/webSocket/connect.main",
        $default: "src/webSocket/default.main",
        $disconnect: "src/webSocket/disconnect.main",
        sendMessage: "src/webSocket/sendMessage.main",
      },
    });

  }
}
  
```
But i get this error
```
Error: WebSocketApi2 at 'WebSocketApi' should be created in the scope of a Stack, but no Stack found
    at _lookup (/home/myfreax/work/typescript/crownfish/node_modules/@aws-cdk/core/lib/stack.ts:93:15)
    at _lookup (/home/myfreax/work/typescript/crownfish/node_modules/@aws-cdk/core/lib/stack.ts:96:14)
    at Function.of (/home/myfreax/work/typescript/crownfish/node_modules/@aws-cdk/core/lib/stack.ts:76:21)
    at new Resource (/home/myfreax/work/typescript/crownfish/node_modules/@aws-cdk/core/lib/resource.ts:76:24)
    at new ApiBase (/home/myfreax/work/typescript/crownfish/.build/lib/index.js:4474:7)
    at new WebSocketApi2 (/home/myfreax/work/typescript/crownfish/node_modules/@aws-cdk/aws-apigatewayv2/lib/websocket/api.ts:47:5)
    at new MyStack (/home/myfreax/work/typescript/crownfish/lib/MyStack.ts:780:26)
    at Object.main (/home/myfreax/work/typescript/crownfish/lib/index.ts:10:3)
    at Object.<anonymous> (/home/myfreax/work/typescript/crownfish/.build/run.js:85:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
```

**Comment by bblanke** [comment]
Only a guess, but it looks like when you create the websocket stage, you're passing "scope" instead of a stack (this):

```
    const webSocketApi = new WebSocketApi(this /* instead of scope */, "WebSocketApi")
    const cwRole = new Role(scope, 'CWRole', {
      assumedBy: new ServicePrincipal('apigateway.amazonaws.com'),
      managedPolicies: [ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonAPIGatewayPushToCloudWatchLogs')],
    });
```

**Comment by chrisxue815** [comment]
Looks like this is what we need to do to solve this issue ([source](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html#set-up-access-logging-permissions)):
1. Create an IAM role with `AmazonAPIGatewayPushToCloudWatchLogs` policy.
2. Set the IAM role ARN on the CloudWatch `cloudWatchRoleArn` property at the account level for each region in which we want to use APIGateway + CloudWatch.

To do it manually, we can follow https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/

To do it programmatically:
* In CloudFormation: [Associate account with IAM role](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-account.html#aws-resource-apigateway-account--examples)
* In Serverless Framework: [api-gateway-cloud-watch-role](https://github.com/serverless/serverless/blob/b7d6af6b1309a5b4fbfac54265e7900196416976/lib/plugins/aws/custom-resources/resources/api-gateway-cloud-watch-role/handler.js)
* In CDK, using APIGateway V1 `RestApi`: [`cloudWatchRole`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.RestApi.html#cloudwatchrole)

The CDK `cloudWatchRole` attribute above leverages [`configureCloudWatchRole`](https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L522) to create the required CDK constructs. Unfortunately, this function will be made internal and no replacement will be provided ([source](https://github.com/aws/aws-cdk/blob/10b6b96f35ac32a60aa2bf4ea1856158392ae8ad/DEPRECATED_APIs.md)). I believe SST could provide a similar function to solve this issue.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
