### ISSUE TITLE
sst start: Return console.log content to Lambda and print them out to CloudWatch

### ISSUE THREAD

**Issue by fwang** [sst/sst#1557]
Use case: CloudWatch subscriptions

---
Request:
- Matt https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1647823771830139?thread_ts=1647816315.477409

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
