### ISSUE TITLE
Doc: best practice on splitting resources to different stacks

### ISSUE THREAD

**Issue by fwang** [sst/sst#1558]
Ted asked that:
> I’m interested in refactoring some existing resources to a separate stack, notably a `Distribution`. Are there any examples/guides on how to do this with SST?

---
Request
- Ted https://serverless-stack.slack.com/archives/C01JG3B20RY/p1647843178171689

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
