### ISSUE TITLE
How to escape from a `UPDATE_IN_PROGRESS` state?

### ISSUE THREAD

**Issue by michaelrambeau** [sst/sst#1564]
Hello and thank you for your hard work to develop and maintain this awesome project!

I'm running the version `0.69.0` to build a REST API using Lambdas.

After having setup a custom domain, I tried to deploy my stack and the process was stuck in the `Checking deploy status...` state for a long time.
I stopped the process after more than 30 minutes (maybe I should have waited more!).
My problem is that now I cannot either `deploy` again or `remove` my stage:

```
 ❌  test-xxx-yyy-stack failed: 
Error: Stack test-xxx-yyy-stack is in the UPDATE_IN_PROGRESS state. It cannot be deployed.
```

What is the appropriate way to reset/clean the state? Should I delete the whole `.sst` folder?
Thank you in advance for your help!

**Comment by fwang** [comment]
Hey @michaelrambeau, thanks for the kind words.

What's in ur app? are you creating an Api or StaticSite with custom domain by any chance?

**Comment by michaelrambeau** [comment]
Thank you Frank for your quick reply!

Yes, it was an API, a single Lambda with a single `POST` route and the problem happened when I tried to set up a custom domain, after having created a specific hosted zone in AWS Route 53.

Everything was fine until this point, I was able to run locally and build without any trouble.

**Comment by fwang** [comment]
It is likely AWS is trying to repeatedly verify that you own the domain, but isn't able to.

Is your domain purchased on Route53 or another registrar? You can do a quick [DNS lookup](https://mxtoolbox.com/DNSLookup.aspx) on the domain and see if the DNS servers are pointing to Route 53.

**Comment by michaelrambeau** [comment]
Everything is on AWS Route 53 (`Your DNS hosting provider is "Amazon Route 53"` as the tool you mentioned said).

I'm sorry if my question was confusing, it was was not about the endless checking process that happened (that was maybe an unfortunate timing issue), it was  about what to do when you shut down the process, leaving the application in the `UPDATE_IN_PROGRESS ` state,  because now I cannot `remove` or `deploy` this stage.

I guess deleting the `.sst` folder would "nuke" everything but then how would you clean all the infrastructure stuff created on AWS?

Thank you for your advice!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
