### ISSUE TITLE
GastbyStaticSite

### ISSUE THREAD

**Issue by fwang** [sst/sst#1568]
Roger mentioned that:
- [ ] Ability to create cloudfront/lambda@edge functions to handle url rewrite rules
- [ ] Support for all rendering methods such server side rendering,  and deferred static site generation
- [x] ~The current static site construct, doesn't really work that well as cloudfront can't handle loading the default document object (index.html) for sub directories, so support for that via an option on the construct would be awesome~
  — implemented in #2564 

---
Requests:
- Roger https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1647945567631779?thread_ts=1647649275.673509&cid=C01HQQVC8TH

**Comment by aphex** [comment]
Quick solution for this seems to a Cloudfront edge Function. (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-javascript-runtime-features.html)

I have to say this is a bit crazy we have to add an edge function just to get default `index.html` working in subfolders. This really seems like an Amazon issue and should be configurable from Cloudfront itself without the need to run more JS. 

They are a bit limited but certainly get the job done for this. I would think `staticSite` might want to have this on by default and provide a config option to turn it off. To get this working an example looks like this

```ts
import type { App, StackContext } from '@serverless-stack/resources'
import { ViteStaticSite } from '@serverless-stack/resources'
import {
  Function,
  FunctionCode,
  FunctionEventType,
} from 'aws-cdk-lib/aws-cloudfront'


export default function (app: App) {
  app.stack(({ stack }: StackContext) => {
    const indexFn = new Function(stack, 'indexFn', {
      code: FunctionCode.fromInline(`
      function handler(event) {
        var request = event.request;
        var uri = request.uri;
        
        if (uri.endsWith('/')) {
            request.uri += 'index.html';
        } else if (!uri.includes('.')) {
            request.uri += '/index.html';
        }
    
        return request;
      }
      `),
    })

    const site = new ViteStaticSite(stack, 'Vite', {
      path: 'frontend',
      buildOutput: '.vitepress/dist',
      cdk: {
        distribution: {
          defaultBehavior: {
            functionAssociations: [
              {
                function: indexFn,
                eventType: FunctionEventType.VIEWER_REQUEST,
              },
            ],
          },
        },
      },
    })

    stack.addOutputs({
      URL: site.url,
    })
  })
}
```

I would think if a user provided their own `functionAssociations` it would be all on them to do this, but if it is not provided by the user it seems like this would be a fair default for static sites. Either way an option to toggle this on/off would be ideal.

Can we get this added to StaticSite as an option so we do not need to keep duplicating this for multiple static site within a deploy?

**Comment by fwang** [comment]
@aphex Just implemented ur solution with a bit of tweak.

1. `https://mydomain.com/profile/` => `https://mydomain.com/profile/index.html`
2. `https://mydomain.com/profile` => `https://mydomain.com/profile.html`
The behaviour for case 2 differs from ur implementation.

I tried out `python -m` and `npx http-server`, the behaviour is:
- if `profile.html` exists => `https://mydomain.com/profile.html`
- if `profile.html` doesn't exists, but `profile/index.html` exists => `https://mydomain.com/profile/index.html`

There doesn't seem to be a perfect solution 🤷‍♂️

Let me know if that makes sense.

**Comment by aphex** [comment]
@fwang That makes sense, I guess we just need to make a choice and go with it. Should this be configurable at the StaticSite level? Something line `requireTrailingSlash`, with that should this whole inline function have a way to opt out? Maybe something like `defaultRoot: 'index.html'` which would be the default value, but then someone would do `defaultRoot: false` to turn this off? Maybe there is a cost savings here to not have a edge function for your static site if you don't need it?

**Comment by fwang** [comment]
Yeah.. I think most ppl probably need this. This being the default behaviour makes sense. I'm thinking adding the opt-out option when ppl ask for it? 🤔

**Comment by aphex** [comment]
Definitely agree with this as the default, and adding when asked if probably a good use of time/resources :) Happy to see this in though, still seems crazy amazon doesn't have a easy way to do this.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
