### ISSUE TITLE
Show init error stack trace in aws-lambda-ric

### ISSUE THREAD

**Issue by fwang** [sst/sst#1569]
I’m triaging a couple of issues where the printed out error have stack traces from aws-lambda-ric which aren’t very useful
<img width="1252" alt="Screen Shot 2022-03-23 at 11 20 15 AM copy" src="https://user-images.githubusercontent.com/83515/159738888-abf96b14-de6f-4f28-a5dd-019bdead186c.png">

If i console.log(reason) i see the proper stack trace
<img width="1252" alt="Screen Shot 2022-03-23 at 11 20 15 AM" src="https://user-images.githubusercontent.com/83515/159738927-7707e27f-0505-44de-a8b9-2d5482094553.png">

We should show proper stack trace.

---
Request: https://serverless-stack.slack.com/archives/C0286U10CSJ/p1648048942104469

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
