### ISSUE TITLE
Bundled functions live in absolute path

### ISSUE THREAD

**Issue by revmischa** [sst/sst#1575]
Easier to describe this with a screenshot...

<img width="557" alt="Screen Shot 2022-03-24 at 16 26 46" src="https://user-images.githubusercontent.com/245131/159963909-c000e41d-14ae-4072-9ca6-2269e7d37eb3.png">

I'm using a monorepo with an absolute path to `srcPath`. Maybe that's causing the issue?

If I set `srcPath: "../../"` I get this output:
<img width="1037" alt="Screen Shot 2022-03-24 at 16 37 20" src="https://user-images.githubusercontent.com/245131/159965931-f90e7c05-a43d-4e2a-88b2-828258c4692a.png">

<img width="1042" alt="Screen Shot 2022-03-24 at 16 37 36" src="https://user-images.githubusercontent.com/245131/159965981-8ea1cc77-bfe9-4dcd-9767-6ce98cd9c763.png">

<img width="536" alt="Screen Shot 2022-03-24 at 16 37 47" src="https://user-images.githubusercontent.com/245131/159966018-fb7b1edd-5223-4091-b53e-4bf3a4c81713.png">

Which isn't ideal either

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
