### ISSUE TITLE
Support esbuild options

### ISSUE THREAD

**Issue by revmischa** [sst/sst#1576]
I was using the options:
* [sourcesContent](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#sourcescontent) - smaller sourcemaps
* [metafile](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#metafile) - for analyzing my bundles and making them smaller

Ideally all the options [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#properties) would be supported but I would be happy with those two for now

I still think SST should be leveraging NodejsFunction. I'd be potentially happy to work on that if you agree and want to point me in the right direction.

**Comment by tim-helloquickly** [comment]
I want to add to this -- the metafile option takes a boolean, not a string, and it doesn't seem to actually get generated. Seems like this was maybe half implemented?

**Comment by jayair** [comment]
We have the esbuild option now https://docs.sst.dev/constructs/Function#esbuild

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
