### ISSUE TITLE
Live Lambda Dev Console: Multiple Live environments - Port for second environment doesn't carry to links in console

### ISSUE THREAD

**Issue by mendellerner** [sst/sst#1581]
Hi,

When I run multiple Lambda dev environments, SST adds a port number to the console URL:
`https://console.serverless-stack.com/{service}/{stage}/local?_port=13558`, which is awesome.

However, when clicking a link to on of the tabs, the port is not carried over and the Console displays an error:
`No stacks found for app {service} and stage {stage}`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
