### ISSUE TITLE
Unexpected token * Following example from serverless-stack guide

### ISSUE THREAD

**Issue by Mexassi** [sst/sst#1587]
Hi, I am following the Serverless-stack guide to create a hello world api. All I have don so far is following the guide and running the following commands:

- `npx create-serverless-stack@latest notes`
- `npx sst start`

The first command generates a project I haven't touched the generated code. When I try to execute the second command to start a local debug stack I can see the stack been provisioned successfully, however when I hit the endpoint I get an `Internal Server Error`. The console shows an `Unexpected Token *` error see pics
<img width="337" alt="image" src="https://user-images.githubusercontent.com/9665331/160936670-a752ca08-647b-4eaf-a94f-5d78f4d7698c.png">

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/9665331/160936515-2eaaafe1-4ec6-4c4d-aa85-8a6d5c72083a.png">

It would be great if this could work out of the box. The versions I am using are:
```
SST:   0.69.3
CDK:  2.15.0
```

I will try a different version and see how that goes.

**Comment by Mexassi** [comment]
I had the same issue over with other versions. I have also tried running the `rest-api-ts` example locally https://github.com/serverless-stack/serverless-stack/tree/master/examples/rest-api-ts and got the same `Unexpected token *` error.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
