### ISSUE TITLE
Re-deployment not handling updated/modified API routes correctly

### ISSUE THREAD

**Issue by shaunhurley** [sst/sst#1589]
After making changes to the target lambda path for API routes, although sst detects the requirement to rebuild the environment, and you are prompted to hit enter to deploy, it does not handle the changes to route targets correctly and results in an `ReferenceError: require is not defined` error such as below.

```
Stacks: Deploying completed.
ee9295da-22ea-44da-b27b-c44cf72e69da REQUEST dev-beltway-api-apiLambdaGETsuppliers7FE14F86-WyTqEjERxZBf [src/suppliers/list.main] invoked by API GET /suppliers
Unhandled Promise Rejection     {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"ReferenceError: require is not defined","reason":"ReferenceError: require is not defined","promise":{},"stack":["Runtime.UnhandledPromiseRejection: ReferenceError: require is not defined","    at process.<anonymous> (file:///C:/Users/Shaun/SST/beltway/node_modules/@serverless-stack/aws-lambda-ric/lib/index.js:34:23)","    at process.emit (node:events:390:28)","    at emit (node:internal/process/promises:136:22)","    at processPromiseRejections (node:internal/process/promises:242:25)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
```

Stopping the test environment and reissuing the `npx sst start` command causes the updated route targets to be handled correctly.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
