### ISSUE TITLE
Feature request: containers (Dockerfile -> ECR)

### ISSUE THREAD

**Issue by lefnire** [sst/sst#1590]
I freaking love this project, so easy with its removal of CDK boilerplate with its opinionated handling of resources, permissions, etc. I want to use containers (ECR) for certain Lambdas, as well as Batch. AFAIK there's no container support in SST? So I'll drop down to CDK and string some stuff up myself, but dropping a feature request here since I think it'd fit well in this project's ethos.

How it might look
1. A folder `containers/` with various `Dockerfile`s. 
2. `const image = sst.ECR({registry: {name, ...}, dockerfile, environment, ...})` that will setup an ECR registry; push said Dockerfile to registry, triggering a build (or just running build/push on localhost if that's too much). `environment` maybe doesn't make sense here, since it'd likely be handled at Lambda/Fargate level...
3. `api.attachPermissions(image)` if necessary. Can't recall the IAM stuff around ECR<->Lambda. 
4. The last part would be Live Lambda against the container, but I imagine this would be quite some leg work so I'd recommend leaving it out initially ("use at your own risk"). Localhost using Docker Desktop and whatnot.

Ostensibly this request is for Lambda images. Doesn't seem like much value, given how much distance one can go with the non-container Lambda tooling provided here. I will mention that for Python projects, there are popular pip packages which don't play well with Lambda and require either a container or forked-pip Lambda Layers (psycopg2, numpy, etc). The real value of this feature I think would be bleeding SST out into the rest of a project's stack for non-serverless resources, like Batch, SageMaker, ECS, Fargate. Eg, a project would likely start as a basic CRUD web/mobile app, where SST shines. Then the project might add some data science / ML services. Currently they'd do so manually via CDK, that's fine. But easing them outward via turnkey support for containers, and *just* containers (leaving them to handle ECS, Batch, etc) would add that grey-zone transition to help their growth; while also fitting the actual use-case of SST as it's intended (`sst.ECR` only documented for use with Lambda).

**Comment by aaka3207** [comment]
bump, this is probably the one thing stopping me from fully using this framework.

**Comment by lefnire** [comment]
@aaka3207 it's been a while since this post, I'm using CDK docker functions pretty easily. Here's my sample code https://github.com/ocdevel/gnothi/blob/main/sst/stacks/Ml.ts#L80 . You lose some niceties:
1. Live lambda - biggest loss. You'll have test your Docker code locally and stack-free before you deploy. But your local lambdas can still call these functions, so it's not too big.
2. `bind`. You'll have to manually setup invoke permissions, and pass environment variables to your calling function

Other than losing the niceties that SST offers, it's just raw CDK - so you're not actually losing anything CDK would have offered. Point being: doing let it stop you from using SST, because even without this feature provided via SST, you wouldn't gain anything elsewhere.

**Comment by aaka3207** [comment]
@lefnire Thanks for the reply! what's your workflow for testing your docker containers with your lambdas locally? are you using docker-compose?

**Comment by lefnire** [comment]
@aaka3207 I think the best approach is to run it with `docker run`. A one-off run, where you pass it the data somehow which is expected to be consumed as `event` (the first parameter of the Lambda function). So your tests should pass info into the Docker container, and get data back. I'm being vague here because I know it's what I *should* do, but haven't set things up properly myself yet. 

What this allows you to do is detach the container from needing resources in the stack, like RDS, and instead your SST stuff (sst.Api, ss.Function) will have those resources, and they'll just make direct calls to these Docker lambdas. Basically, treat your Docker Lambdas as if stuff goes in, and stuff comes out - immutable, functional programming. The reason for all this is because you can't get into this Docker Lambda on localhost: live debug, console.sst, etc. So when you run `npx sst dev`, it will actually deploy these containers, and they should have been tested in advance in order to make life easy.

**Comment by aaka3207** [comment]
@aaka3207 makes sense. I have a service that runs continuously along with my lambdas, but i'm currently using the serverless framework. I put my serverless project into a docker container, running serverless offline, together with my continuous-running container so they're always running together. Might take a similar approach with this.

**Comment by jayair** [comment]
@lefnire Thanks for sharing this. I might add this to the docs.

**Comment by angelhodar** [comment]
Hi everyone, I would like to up this issue because I wanted to migrate from Pulumi to SST but I am blocked because I csnt use docker containers in the Function construct. I dont know exactly how to replicate this code I had using Pulumi to deploy a blender based docker image to AWS Lambda:

```ts
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const bucket = new aws.s3.Bucket("3d-model-optimizer");

const image = awsx.ecr.buildAndPushImage("model-optimizer", {
  context: "..",
});

const role = new aws.iam.Role("modelOptimizerRole", {
  assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal({
    Service: "lambda.amazonaws.com",
  }),
});

const attachment = new aws.iam.RolePolicyAttachment("lambdaFullAccess", {
  role: role.name,
  policyArn: aws.iam.ManagedPolicy.AWSLambdaExecute,
});

const optimizer = new aws.lambda.Function("optimizer", {
  packageType: "Image",
  imageUri: image.imageValue,
  role: role.arn,
  timeout: 300,
  memorySize: 1536,
}, { dependsOn: [ attachment ]});

bucket.onObjectCreated("onNewModel", optimizer, { filterSuffix: ".zip" });
```

**Comment by lefnire** [comment]
```typescript
import * as aws_lambda from "aws-cdk-lib/aws-lambda";
export function Optimizer({stack, app}: sst.StackContext) {
  const optimizer = new aws_lambda.DockerImageFunction(stack, "Optimizer", {
    code: lambda.DockerImageCode.fromImageAsset("myFolder", {
      file: "optimizer.dockerfile"
    }),
  })
```

is the basics. I'm trying to figure out... are you deploying an optimizer as a trigger-response to an upload of a zip file to s3? I'll have to sit with it more if so. But if you just want to deploy a local dockerfile as a Lambda, all you need is my code above. It handles the ECR, IAM, Lambda, etc for you.

**Comment by jayair** [comment]
We have Docker function support coming real soon!

**Comment by angelhodar** [comment]
@lefnire Thank you so much for your answer!!! And yes, you have described exactly what I needed with the code I shared. I think I could try with the DockerImageCode construct and check how it works, but if @jayair says support in sst is coming soon then I will wait a bit!

**Comment by sladg** [comment]
Bumping this one. Docker function support is in place, however, in case I have 5 functions, running on exactly same image, I cannot easily build single image and specify 5 different CMD paths unfortunately. Any plans to allow for passing ECR image instead of forcing local build?

**Comment by jayair** [comment]
https://docs.sst.dev/constructs/Service

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
