### ISSUE TITLE
Console: web UI crashing when clicking a function in Functions view

### ISSUE THREAD

**Issue by hans-m-song** [sst/sst#1591]
When clicking on a specific function from within the functions view, the console web ui crashes with the following error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'data')
```

which points to

```
function jo() {
    const t = _()
      , n = G("Function", t.stack, t.function)
      , a = be(r=>r.functions[n.data.localId] != null, [t.function]);
                                ^
```

which seems to point to [here](https://github.com/hans-m-song/serverless-stack/blob/master/packages/console/src/App/Stage/Functions/Detail.tsx#L55)

This seems to be due to using `stack` from the call to `useParams` which is the stack id not the name. In my use case, the stack name does not match the stack id, meaning the result of `useConstruct` is undefined

Related to https://github.com/serverless-stack/serverless-stack/issues/1565

**Comment by hans-m-song** [comment]
Upon further investigation, the root cause seems to be due to using the `route` property [here](https://github.com/hans-m-song/serverless-stack/blob/master/packages/console/src/App/Stage/Functions/index.tsx#L191) which specifies the stack id instead of the stack name, this means when clicking a function in the list, it navigates to 
`/{app}/{stage}/functions/{stack_id}/{function_addr}` instead of `/{app}/{stage}/functions/{stack_name}/{function_addr}`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
