### ISSUE TITLE
Add --outputs-format for --outputs-file (eg, "env" for .env)

### ISSUE THREAD

**Issue by lefnire** [sst/sst#1595]
Doing some integration tests via localhost, I add `--outputs-file env.json` and then manually convert it to the `.env.local` or `.env.test` file. I'm probably going about this process wrong, seems this project has thought through guard-rails for a proper e2e setup. If so, LMK and I'll shut up. But just in case, would be nice to have a `--outputs-format=env`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
