### ISSUE TITLE
How to remove serverless-stack from my aws account

### ISSUE THREAD

**Issue by x2197** [sst/sst#1600]
How to remove serverless-stack from my aws account. I have ran `npx sst remove` but there is some iam roles & policy still present

![image](https://user-images.githubusercontent.com/91653768/162024811-81e7c0b3-dc8a-469e-87d0-0e3682db90fc.png)

![image](https://user-images.githubusercontent.com/91653768/162024820-483fbe89-27e1-4f61-a0b6-2934f63ff559.png)

how can I remove all serverless-stack related aws resource

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
