### ISSUE TITLE
Cli: display update CLI npm/yarn alert

### ISSUE THREAD

**Issue by fwang** [sst/sst#1602]
David suggested that:
> just a thought: if i start expo with an out of date package, it tells me that in the cli. i suppose i also see that with yarn too. maybe SST should also say that? i didn’t check, i just assumed i was on the latest version.

---
Request:
- David https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1649283924135349?thread_ts=1649281392.297179

**Comment by iamdavidmartin** [comment]
expo-cli will show warnings if:
- the cli is an old version
- other package versions don't match what the cli is expecting.

here's an example:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/373633/162316246-da44e4d9-e429-448f-af97-bfda1d38c5fc.png">

i'm currently up-to-date with the latest version of the cli, so i don't have a screenshot of that warning to share, but you can image it looks quite similar.

here's the line of code in the expo-cli where they validate dependencies: https://github.com/expo/expo-cli/blob/7ce126ec50f8b2a6b3efb1e00b903152c6bde151/packages/expo-cli/src/commands/start/startAsync.ts#L71

**Comment by iamdavidmartin** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/373633/162330838-25a42b89-a943-458d-a5d0-5ed34dc2bed5.png">

**Comment by iamdavidmartin** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/373633/162858417-75d23dd1-2895-4c1c-a807-1a3a19158b25.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
