### ISSUE TITLE
Console: Feature request: provide example payloads in function invocation screen

### ISSUE THREAD

**Issue by hans-m-song** [sst/sst#1611]
It would be good to mimic the behaviour of the lambda test screen on the AWS console in which templates are available to send as payloads.

Example: an apigateway proxy payload

![image](https://user-images.githubusercontent.com/21118015/162380592-42e8a6f1-3c65-4a88-a5a6-9a8a32ec47d3.png)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
