### ISSUE TITLE
Unable to run `sst test` when using Python for functions

### ISSUE THREAD

**Issue by estyrke** [sst/sst#1613]
I get mysterious errors when trying to run tests on my stack. It seems there are errors when trying to build the Python lambda code.

I am running on OS X. I also use [Colima](https://github.com/abiosoft/colima) instead of Docker Desktop, which might be the cause of these problems. However, I don't have enough knowledge of SST/CDK to get any further. Is rsync run inside the docker container? Is `/asset-output/` a (bind-mounted?) volume ?

```
[...]
 => CACHED [6/9] COPY Pipfile* pyproject* poetry* requirements.tx[t] ./                                                                                                     0.0s
 => CACHED [7/9] RUN if [ -f 'Pipfile' ]; then pipenv lock -r > requirements.txt; else echo "Pipfile not found"; fi                                                         0.0s
 => CACHED [8/9] RUN if [ -f 'poetry.lock' ]; then poetry export --with-credentials --format requirements.txt --output requirements.txt; else echo "poetry.lock not found"  0.0s
 => CACHED [9/9] RUN if [ -f 'requirements.txt' ]; then pip install -r requirements.txt -t .; else echo "requirements.txt not found"; fi                                    0.0s
 => exporting to image                                                                                                                                                      0.1s
 => => exporting layers                                                                                                                                                     0.0s
Bundling asset dev-my-app-test-stack/derivedGroupUpdater/Code/Stage...30983f4f4b7f914ee4d86c                                                                                0.0s

 RUNS  test/MyStack.test.js
rsync: mkstemp "/asset-output/.poetry.lock.btXim6" failed: Permission denied (13)
rsync: recv_generator: mkdir "/asset-output/PyJWT-2.3.0.dist-info" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
[... many more of the same for other paths ...]
```

**Comment by fwang** [comment]
Hey @estyrke, the `sst test` command has been removed in SST v1. The command really just ran the `jest` command behind the scene without adding much value.

In v1, you have more flexibility configuring `jest` based on ur setup or even using other testing frameworks (ie. [vitest](https://vitest.dev)). Here are more details on setting up tests in v1 - https://docs.serverless-stack.com/advanced/testing#stacks-tests.

Let me know if you still get this error with v1.

**Comment by adumeye** [comment]
Thank you for your response

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
