### ISSUE TITLE
Function: no reliable way to set log retention for all functions

### ISSUE THREAD

**Issue by fwang** [sst/sst#1627]
There isn’t a good way to set log retentions for all Lambda functions. The reason is, to set log retention, behind the scene CDK creates a custom resource to set it. But that custom resource will in turn create a new Lambda function. And the new function has `Never expire` retention.

Similarly, there isn't a way to reliably remove all Lambda function log groups.

---
Request:
- Tim https://serverless-stack.slack.com/archives/C01JG3B20RY/p1649906461187949?thread_ts=1649096611.790069
- Seth https://github.com/serverless-stack/sst/issues/1627
- Peter Hase https://discord.com/channels/983865673656705025/1037786319084077146

**Comment by fwang** [comment]
Related to #953

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
