### ISSUE TITLE
Can you use the "schedule" field on EventBus rules? 

### ISSUE THREAD

**Issue by cmaycumber** [sst/sst#1629]
I'm currently trying to define my crons inside of our EventBus and an running into the error when using the "schedule" field on a rule:

```
Error: Cannot associate rule with 'eventBus' when using 'schedule'
```

Am I doing something wrong or is this currently not supported?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
