### ISSUE TITLE
Console: give an option to copy the API endpoint

### ISSUE THREAD

**Issue by Manitej66** [sst/sst#1636]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/61357713/163721915-60e7f4bf-9b9a-480f-91ae-8a818eb17dcd.png">
An option to copy the API url with the query params would help to quickly test the endpoint in browser or something like postman/insomnia

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
