### ISSUE TITLE
Community contributed examples

### ISSUE THREAD

**Issue by fwang** [sst/sst#1637]
Keeping track examples put together by the community. This list will be moved to and featured on the SST Examples page. Submissions welcome!

| Author | Title | Link | Slack Conversation |
| - | - | - | - |
| Mischa | SST + Prisma ORM Template with DB migrations | https://github.com/jetbridge/sst-prisma | [Slack](https://serverless-stack.slack.com/archives/C01JVDJQU2C/p1650208060720919) |

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
