### ISSUE TITLE
Live development reload feature not working for f#

### ISSUE THREAD

**Issue by MaxHill** [sst/sst#1639]
Hello, thanks for this awesome tool!

I'm trying to get started with the f# template but have run into a bug it seems.
The live development reload feature does not get triggered when changing Handler.fs.

### Reproduction
`npx create-serverless-stack@latest bigfoot --language fsharp`
`yarn start` / `npm run start`
Open API endpoint in browser and see response
Change response.Body to another text
Open API endpoint in browser and text **is not** changed

### Expected behavior 
`npx create-serverless-stack@latest bigfoot --language fsharp`
`yarn start` / `npm run start`
Open API endpoint in browser and see response
Change response.Body to another text
Open API endpoint in browser and text **is** changed

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
