### ISSUE TITLE
ProvisionedConcurency not working as expected.

### ISSUE THREAD

**Issue by emouragym** [sst/sst#1642]
It seems I can`t get ProvisionedConcurency to work as its state in the docs:

This is what I am currently doing 
```
 this.api = new sst.ApiGatewayV1Api(this,"api",{ 
 
 (...)
 
routes: {
  [route]: {
            function: "---handler",
            currentVersionOptions: {
              provisionedConcurrentExecutions: 5,
            },
          }
       }
    }
    (...)
   const fn = this.api.getFunction(route);
   const version = fn.currentVersion;

  ```
}

When checking on the AWS console, I see that new version is created correctly, but the concurrency is not provisioned.

I then tried creating a alias via:

```
 version.addAlias("AUTO_GENERATE_ALIAS", {
          provisionedConcurrentExecutions: 1,
        });
 ```
 
 And my alias does get auto generate, with the correct values, but whenever I hit my api endpoint, it does not go through the provisioned alias, it cold starts a new request.
 
 If I go to the console , manually change the endpoint on API_GATEWAY to point to the lambda and REDEPLOY the api from the console, then it does hit the new alias as expected.
 
 In essence I want to remove the need for us to do any manual setup on AWS console, is this possible? Can I set my api gateway to point to the alias in the code? 
 
 Quick questions:
 Do I even need a alias in the first place for the provisionedConcurrentExecutions?
 Am I missing a better way of setting this up?
 
 Any pointers would be appreciated.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
