### ISSUE TITLE
Console: S3 explorer shows "No files" at the end of the list

### ISSUE THREAD

**Issue by jayair** [sst/sst#1644]
A directory with files, still shows "No files" at the end of the list.

<img width="1297" alt="Screen Shot 2022-04-20 at 5 10 12 PM" src="https://user-images.githubusercontent.com/53023/164323831-f7ed1416-a95a-47c0-b577-eecc206899a5.png">

**Comment by jayair** [comment]
Btw, this is when connecting to prod.

**Comment by Manitej66** [comment]
Working fine for me
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/61357713/164626127-58230f4c-9895-488a-a178-1e2993418eca.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
