### ISSUE TITLE
Auth: add error helper for CFN error "Invalid AttributeDataType input"

### ISSUE THREAD

**Issue by fwang** [sst/sst#1645]
The happens when changing the standard user pool attributes after the user pool is created.

Error:
```
Invalid AttributeDataType input, consider using the provided AttributeDataType enum. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException;)
```

---
Request:
- Edoardo https://serverless-stack.slack.com/archives/C01JG3B20RY/p1650472615472379?thread_ts=1650469453.932009

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
