### ISSUE TITLE
Doc: SST vs Amplify

### ISSUE THREAD

**Issue by fwang** [sst/sst#1663]
A very good discussion here https://serverless-stack.slack.com/archives/C01JG3B20RY/p1651089173442799

---
Requests:
- Karolis https://serverless-stack.slack.com/archives/C01JG3B20RY/p1651089173442799

**Comment by espetro** [comment]
Hi, how can I join the SST's slack channel?

**Comment by jayair** [comment]
We moved to Discord recently: https://discord.gg/sst

**Comment by gty3** [comment]
I made a blog post on this: https://gtyusa.com/38875d865f584dd399565c7947cf03e1
I'd be happy to make changes and provide the markdown.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
