### ISSUE TITLE
Sharing values between Terraform CDK and SST

### ISSUE THREAD

**Issue by paambaati** [sst/sst#1665]
Our teams use both Terraform CDK and SST to manage our resources – the backend teams primarily use SST (so Lambdas & AppSync) while the devops/SRE teams use Terraform CDK to maintain more global resources (API gateway, DynamoDB tables, CloudFront distributions, ACM, etc.)

There are often cross-dependencies (for example, API gateway requires knowledge of Lambdas), which require ways of passing data between TF CDK and SST.

What is the recommended approach?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
