### ISSUE TITLE
How to access RDS using external tools?

### ISSUE THREAD

**Issue by marcelltoth** [sst/sst#1669]
Hi, thanks for taking your time.

I'm a recent SST adopter, and everything is going great so far, except for one think I can't seem to solve:

I create my RDS resource using SST, after which I can access it through the console. The console is fine for basic usage, however it is very bare-bones compared to any real DB client (pgAdmin, DataGrip, etc). Even so, the console is only an option using local development, I can't access it for production deployments. 

How do I connect DataGrip to the DB created by SST?

There are two main problems:
1. **Credentials**: I tried to specify an admin user but I couldn't figure out how.
2. **Access**: I then managed to add an admin user by using the console and running SQL manually. I still couldn't access the DB as it is not visible from the outside from a networking PoV. I understand this is a security feature but I still need a way to access it, how do I do so?

Thanks

**Comment by fwang** [comment]
@marcelltoth There are a couple options:
1. You can you the query editor in the AWS RDS console.
2. You can actually use the SST console for production stages by running `sst console`. More details here https://docs.serverless-stack.com/console#connecting-to-deployed-environments
3. To use DB clients, you'd need to launch the RDS cluster in a VPC with public subnets and an internet gateway. More details here https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_CommonTasks.Connect.html

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
