### ISSUE TITLE
[improvements] Setting AWS Profiles based on stage

### ISSUE THREAD

**Issue by justindra** [sst/sst#167]
Currently to set an AWS PROFILE to use, we need to run the following:
```
AWS_PROFILE=profile-dev sst deploy --stage dev
AWS_PROFILE=profile-prod sst deploy --stage prod
```

Most of the time the profile would be dependent on the stages. It would be useful to have some sort of configuration on this, maybe in `sst.json`. And then that's one less thing to set, especially since SST already has knowledge of the stage.

```json
{
    ...
    "profiles": {
       "default": "profile-dev",
       "qa": "profile-qa",
       "prod": "profile-prod"
    }
}
```

**Comment by fwang** [comment]
Agreed. We need to figure out what to do in the CI environment when profiles are not available.

**Comment by justindra** [comment]
Yep, we generally just use the AWS CLI in our CI like so:
```
aws configure --profile profile-prod set aws_access_key_id ${AWS_ACCESS_KEY_ID}
aws configure --profile profile-prod set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
```

So you can set as many of those profiles up as necesssary via ENV Variables on the CI machines.

**Comment by fwang** [comment]
Gave this some more thoughts, 2 issues with keeping the `stage-to-profile` mapping in `sst.json`:
1. the sst.json file can get bloated for teams with many stages (ie. 1 stage for each developer)
2. for PR workflow, each PR is deployed to a new stage and the stage name is often auto-generated (ie. pr233) It is tricky to define the stage names up front

**Comment by justindra** [comment]
What if its done similarly via `.env` files? you can have as many as required and can generate one on the fly for each PR too.
* .env
* .pr233.env
* .development.env
* .other-profile.env

**Comment by TonnyORG** [comment]
I just found a need for this as well, I was thinking more on doing it in the way that SST handles the "stage", so maybe another variable or setting within the `.sst/stage` file; I mean technically I don't need this on production or any other "external" place (I have `seed.run` or any other CI/CD tool to handle specifics), but I need it to play around different projects (multiple projects and multiple AWS accounts make this so "annoying to remember to either prefix `AWS_PROFILE=whatever` in any command.

Maybe the SST can do a `export AWS_PROFILE=whatever` internally AFTER reading the content of the `.sst/stage` file?

Just throwing ideas here don't get me wrong.

**Comment by justindra** [comment]
@TonnyORG that sounds pretty good to me and would work for my use case too. Although as a workaround in the meantime, I have just added the export in from of an npm script and that works pretty well for now.

**Comment by TonnyORG** [comment]
@justindra yeah, and also the problem with your temporal workaround is that you're overriding the `package.json` not just for you but also for anyone in your team.

**Comment by TonnyORG** [comment]
@thdxr what do you think ^

**Comment by justindra** [comment]
@TonnyORG Yep, completely agree. Fortunately our team is small enough at the moment that it's not a huge issue, but its definitely not the best way.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
