### ISSUE TITLE
RDS migration deployment succeed without error but actually doesn't take effect when using a invalid schema

### ISSUE THREAD

**Issue by suqi** [sst/sst#1673]
Reproduce:
1. Build a RDS using SST
2. Write a migration schema, but invalid, such as duplicate column added
3. Deploy
4. You will see:  deployment succeed without error, but actually migration failed and doesn't take effect.

Suggestion: Output the migration error explicitly

<img width="971" alt="image" src="https://user-images.githubusercontent.com/1326887/167057619-7f08a1d8-2ad3-4732-8141-ced7ac4860bd.png">

**Comment by fwang** [comment]
@thdxr I've run into this issue as well. Seems like either pothos or the migrator function depressed the error.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
