### ISSUE TITLE
Construct for running delayed job

### ISSUE THREAD

**Issue by fwang** [sst/sst#1691]
Requests:
- Cam https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1652120496755589

**Comment by camsloanftc** [comment]
The news of [AWS eventrbridge scheduler](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/) may either eliminate the need for this request, or maybe it enables an easy high-level construct to be made here. Figured I would share though if it helps the discussion.

**Comment by jayair** [comment]
Oh I saw that, we add this recently: https://docs.sst.dev/long-running-jobs but we haven't hooked it up to cron yet.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
