### ISSUE TITLE
Step Function construct

### ISSUE THREAD

**Issue by fwang** [sst/sst#1703]
Tracking a list of things the SST construct need to on top of the CDK construct:
- use SST Function
- accepting the "asl" file? https://serverless-stack.slack.com/archives/C01JVDJQU2C/p1652815003049849

There isn't enough reason to build an SST construct.

Let us know what you'd like the SST Step Function construct to do.

**Comment by accexs** [comment]
Hi,

Maybe a construct is not really that necessary (still i think i would be cool to have it) but maybe to have a good example or mention in the docs would be nice (how to create the asl template, deploy, integrate lambdas and specific resources like dynamo, etc), recently i've seen step functions being used a lot and being integrated with EventBridge and i think it will be a quality of life thing to have even if is just a tutorial, i think i saw someone on discord help channel asking about how to bring the two together (step functions and SST) so maybe he can be reached to scaffold some of the work

**Comment by geekyayush** [comment]
Any update on this?

**Comment by jayair** [comment]
Sadly no, the CDK constructs aren't too bad here tbh.

**Comment by geekyayush** [comment]
Got it. Thanks for the update @jayair ^ _ ^
Sticking with CDK.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
