### ISSUE TITLE
Example: Integration tests

### ISSUE THREAD

**Issue by fwang** [sst/sst#1704]
Update [Testing doc](https://docs.sst.dev/advanced/testing) to use Resource Binding instead of Config
---
Requests:
- Alex: https://serverless-stack.slack.com/archives/C01JG3B20RY/p1652729028424149?thread_ts=1652604977.028099&cid=C01JG3B20RY

**Comment by obrienbcg** [comment]
Have there been any developments on this? Thanks :)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
