### ISSUE TITLE
Type 'string' is not assignable to type '"none" | "iam" | ...' for js projects

### ISSUE THREAD

**Issue by fwang** [sst/sst#1707]
outaTiME shared in Slack

![Image](https://user-images.githubusercontent.com/83515/169194753-73cb41cc-67d8-401a-98ab-096b77e58474.png)

![Image](https://user-images.githubusercontent.com/83515/169194764-4129ae6a-c683-4624-bbf0-9a9e02d0a988.png)

![Image](https://user-images.githubusercontent.com/83515/169194770-0856b896-1b2e-4b46-a0b5-25e88bcb57af.png)

---
Requests:
- outaTiME https://serverless-stack.slack.com/archives/C01JG3B20RY/p1652900144002089?thread_ts=1652899514.827329&cid=C01JG3B20RY

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
