### ISSUE TITLE
API’s customDomain does not update Route53 on subsequent changes

### ISSUE THREAD

**Issue by tobyspark** [sst/sst#1714]
Steps to reproduce –
- Set desired custom domain to a non-final stage, e.g. a PR stage to establish it’s working. Deploy, it works.
- Change stage custom domain applies to final stage, e.g. production. Deploy, the Route53 record is unchanged, pointing to the PR stage endpoint.

Expected behaviour –
- Route 53 record to update

Using SST 0.59.4

**Comment by tobyspark** [comment]
For anyone who encounters this –
- Deploy an earlier commit without any customDomain property
- Then re-deploy your latest

**Comment by fwang** [comment]
Hi @tobyspark, if the PR stage and the production stage are in the same AWS account, the Route 53 record should not change. This is because the Route 53 record points to the same API Gateway custom domain resource.

Let me know if that makes sense.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
