### ISSUE TITLE
Optimization/Bug: Script params nests object under the hood

### ISSUE THREAD

**Issue by mendellerner** [sst/sst#1720]
The Script construct takes the event parameters like so:
```TypeScript
new Script(scope, `myScript`, {
    params: {
        myParam: 'myValue',
    },
    onCreate: 'src/handler.main',
})
```
and calls the function with the parameters nested inside another object:
```TypeScript
// @serverless-stack/resources/dist/Script/index.js
...
if (cfnRequest.RequestType === "Create" && fnCreate) {
    yield invokeUserFunction(fnCreate, { params: fnParams });
}
...
```
which means that the parameters are sent differently to the Function construct (helpful for testing a function before loading into a Script) and the Script construct, but you'd only know this by investigating the "under-the-hood" construct.

I think it would be clearer if the parameters were passed directly:
```TypeScript
// @serverless-stack/resources/dist/Script/index.js
...
if (cfnRequest.RequestType === "Create" && fnCreate) {
    yield invokeUserFunction(fnCreate, fnParams );
}
...
```

Is there a reason for this design?

Thanks

**Comment by fwang** [comment]
Hi @mendellerner, there might be a need down the road to pass additional stuff to the function. ie. parameters from the previous invocation:
```js
await invokeUserFunction(fnCreate, {
  params: fnParams,
  oldParams: ..., // we can get this from cfnRequest
});
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
