### ISSUE TITLE
Remove `jest` from docs

### ISSUE THREAD

**Issue by fwang** [sst/sst#1722]
Remove `jest` from:
- docs ie. https://docs.serverless-stack.com/packages/cli#test
- repo README:
  <img width="646" alt="image (6)" src="https://user-images.githubusercontent.com/83515/169914940-0a2d5178-0a23-4d0a-8752-bfd7b7c17b59.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
