### ISSUE TITLE
Check build time check for handler length

### ISSUE THREAD

**Issue by fwang** [sst/sst#1732]
From Stan:
> there are some AWS limits on max lambda path length of 128 characters and 64 characters limit on lambda name. Would it be possible that you add some checks for this limits exceeded in sst before deployment? Some time ago we run into some problems with too long paths to the lambda handler and it fail during deployment but without any decent error from aws

---
Requests:
- Stan https://serverless-stack.slack.com/archives/C01HYQRUGG6/p1653036998640369

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
