### ISSUE TITLE
Restrict the account and region a stage can be deployed to

### ISSUE THREAD

**Issue by fwang** [sst/sst#1737]
Derek mentioned:
> if I accidentally run the sst deploy command without setting profile a stack may deploy to another account.
> With the CDK itself, there is an option to set the account so an error would be thrown in this case, but not so with SST.

---
Requests:
- Andrea & Derek https://serverless-stack.slack.com/archives/C01JG3B20RY/p1653498690718539?thread_ts=1653194958.801369&cid=C01JG3B20RY

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
