### ISSUE TITLE
Async building for Functions and Sites

### ISSUE THREAD

**Issue by fwang** [sst/sst#1755]
Two benefit:
- build in parallel
- `sst deploy StackA` only needs to build Functions and Sites in StackA

---
Requests:
- Aleksandr https://serverless-stack.slack.com/archives/C01JG3B20RY/p1653736611074769
- Taufik https://github.com/serverless-stack/serverless-stack/issues/1674

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
