### ISSUE TITLE
Possible to add Alexa skill as a trigger for a lambda?

### ISSUE THREAD

**Issue by mostthingsweb** [sst/sst#1768]
In normal Serverless it's one line of YAML to add an Alexa trigger: https://www.serverless.com/framework/docs/providers/aws/events/alexa-skill

Is it possible to do this with sst?

**Comment by fwang** [comment]
Hey @mostthingsweb, I shared a snippet in Slack. Let me repost it here:

I found this [helper construct](https://github.com/aws-samples/cdk-alexa-skill/blob/main/src/skill.ts) from AWS. Save it to ur local and use it like this:
```js
import { Skill } from "./Skill";

const fn = new sst.Function(this, 'SkillFn', { ... });

const skill = new Skill(this, 'Skill', {
  endpointLambdaFunction: fn,
  skillPackagePath: 'src/skill-package',
  alexaVendorId,
  lwaClientId,
  lwaClientSecret,
  lwaRefreshToken,
});
```

Here’s the [full example from AWS blog](https://aws.amazon.com/blogs/devops/deploying-alexa-skills-with-aws-cdk/). It’s similar to the above code. Instead of the PythonFunction, we are using `sst.Function` to use Live Lambda Dev.

**Comment by mostthingsweb** [comment]
As @fwang and I discussed on Slack, what I was really looking for was just the ability to add an Alexa skill as the trigger for a lambda, not actually create the skill itself with SST. This snippet you gave me works:

```
import * as iam from "aws-cdk-lib/aws-iam";

const fn = new sst.Function(stack, "SkillFn", { ... });

fn.addPermission('Skill Invocation', {
  principal: new iam.ServicePrincipal('alexa-appkit.amazon.com'),
  eventSourceToken: "amzn1.ask.skill.xx-xx-xx-xx-xx",
});
```

![image](https://user-images.githubusercontent.com/337962/171320400-07d92574-c7a0-41e4-8aaf-568f6aa38249.png)

**Comment by mostthingsweb** [comment]
Would also be useful to support / document Alexa smart home integration as well. Here's how Serverless Framework does it: https://github.com/serverless/serverless/blob/main/lib/plugins/aws/package/compile/events/alexa-smart-home.js. Basically the same as above, just with different principal and eventSourceToken.

**Comment by fwang** [comment]
@mostthingsweb thanks for updating it here.

Btw, the above code allows the skill to invoke the Lambda, but how are you telling the skill which Lambda to invoke? I'm not too familiar with skill, are you setting that manually in the AWS Console?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
