### ISSUE TITLE
sst start: warn if local Node version does not match runtime version

### ISSUE THREAD

**Issue by fwang** [sst/sst#1797]
Tim mentioned:
> we debugged an issue today where the same lambda code was behaving differently when using sst start or sst deploy, which turned out to be because the local environment was running node 16 and the deployed lambda was using node 14. would it be possible to have sst warn/error when sst start is running with the wrong runtime version?

Requests:
- Tim https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1654811494750139

**Comment by preshetin** [comment]
Hi there, I'd like to take this one.

The solution I see is to loop through stack functions. In case we have at least one function with Node.js runtime then we check it's version against `process.version` or `process.versions.node`.

This version check can be added somewhere in  [packages/cli/scripts/start.mjs](https://github.com/serverless-stack/sst/blob/master/packages/cli/scripts/start.mjs) and can look look like this:

```js
const checkNodejsVersion = () => {
  const funcs = State.Function.read(paths.appPath);

  const NODE_MAJOR_VERSION = process.versions.node.split(".")[0];

  for (const func of funcs) {
    if (
      func.runtime &&
      func.runtime.includes("nodejs") &&
      func.runtime.match(/^nodejs(\d+)/)[1] !== NODE_MAJOR_VERSION
    ) {
      logger.warn(
        [
          "⚠️  Node js versions do not match!",
          `Your function '${func.handler}' has runtime ${func.runtime}`,
          `while this Node.js process has version ${process.versions.node}`,
        ].join(" ")
      );
    }
  }
};
```

Would love some feedback on this

**Comment by DCzajkowski** [comment]
@preshetin In https://github.com/sst/sst/blob/master/packages/sst/src/runtime/handlers/node.ts#L55 the lambda's `process.env` is injected. It contains `AWS_EXECUTION_ENV` which is defined [as specified here](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime). You can compare it to `process.version` in the local runtime (`packages/sst/support/nodejs-runtime/index.ts`) to see if they match and throw/warn if they don't.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
