### ISSUE TITLE
Node.js and Python runtimes combined in one serverless-stack project

### ISSUE THREAD

**Issue by junnu87** [sst/sst#1798]
Is it possible to combine Node and python runtimes in a single project? I have tried with Node.js backend to add a Python runtime (that only uses certain Python lambdas while nodejs runtime uses the all the other lambdas). I am using sst version 0.69.7 and cdk version 2.15.0.

**Comment by sampov2** [comment]
I'm really interested in hearing back about this. Combining python and nodejs backends in a single SST project would be very valuable for us!

**Comment by bros4president** [comment]
Hi guys, my team is currently using a setup like this. Most of the code is in node and some specific tasks written in python. What we do is to invoke the python lambdas directly from node code with the AWS client. Good for background tasks that are not required to have super fast responses.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
