### ISSUE TITLE
[Vulnerabilities] `@serverless-stack/resources` depends on `zip-local`

### ISSUE THREAD

**Issue by brifiction** [sst/sst#1804]
Hello SST Community,

Please see reported vulnerabilities below for `@serverless-stack/resources` - about `zip-local` peer dependencies with `jszip`. This was found with `npm i`, `npm audit fix`.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/9148451/173270577-d651925b-71ec-4b2f-b788-ec400b082a56.png">

Below is a snippet of my `package.json` file:
```
  "devDependencies": {
    "@serverless-stack/cli": "^1.2.20",
    "@serverless-stack/resources": "^1.2.20",
    "@tsconfig/node16": "^1.0.3",
    "aws-cdk-lib": "2.24.0",
    "c8": "^7.11.3",
    "typescript": "^4.7.3",
    "vitest": "^0.14.2"
  },
```

**Comment by ashleyfrieze** [comment]
I think `zip-local` is a strange, small-time, package to be using here. It's bound to jszip2, whose latest version still has vulnerabilities. It's not been updated in a couple of years, and it's only used in one line of code:

https://github.com/serverless-stack/sst/blob/master/packages/sst/src/runtime/handlers/java.ts#L92

That's using a `sync` version of unzipping, but we have `async`/`await` in the surrounding context, and the JSZip library can probably be used more directly with its promises API to avoid this dependency.

**Comment by jayair** [comment]
Ah thanks for digging in, let me share it with the team.

**Comment by jayair** [comment]
Actually, I see your other comment too. Do you want to take a stab at removing this? @ashleyfrieze

**Comment by ashleyfrieze** [comment]
Hey @jayair - I might be interested in having a look. However, my first attempt to follow the build instructions for the project didn't end well. Are you sure the build guide in CONTRIBUTORS.md is correct - it doesn't refer to the directory I was expecting, and my `yarn` crashed when I tried it.

If you can give me some clues on getting a build working, and also an idea of where to look to ensure there's suitable unit or integration testing around the zipping behaviour, so I can trust those tests, I could have a look.

As far as I can tell the line of code in question is scanning a directory for `.zip` files, unzipping them and then rezipping them into a single zip...

**Comment by jayair** [comment]
Do you mind opening a thread in #help on Discord and I'll ask the team to help you get started.

**Comment by ashleyfrieze** [comment]
I've created issue #2823 in respect of the inability to even build SST according to the instructions. I believe the team switched to `pnpm` but didn't update the docs.

**Comment by julbrs** [comment]
> I've created issue #2823 in respect of the inability to even build SST according to the instructions. I believe the team switched to `pnpm` but didn't update the docs.

CONTRIBUTING.md is now updated!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
