### ISSUE TITLE
Error while starting project

### ISSUE THREAD

**Issue by oskhar1099** [sst/sst#1810]
Hi, I'm just starting to use serverless-stack but I cannot even start. When I type npm start it crashes in here:

```
current credentials could not be used to assume 'arn:aws:iam::XXXXXXX:role/cdk-hnb659fds-deploy-role-XXXXXX-us-east-1', but are for the right account. Proceeding anyway.

Socket timed out without establishing a connection

```
I have looked all over the internet but couldn't found the solution. Hope you can help me :)

Im working with: Mac OS Monterey 14.2. Node v14

**Comment by oskhar1099** [comment]
It was the node version, sorry

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
