### ISSUE TITLE
Timeout invoking lambda trigger for cognito

### ISSUE THREAD

**Issue by technology-cerberus-labs** [sst/sst#1815]
Hey, 

All my lambda triggers have been added as such: 

    this.auth = new sst.Auth(this, "Auth", {
      cognito: {
        userPool: {
          // Users can login with their email or username and password 
          signInAliases: { email: true, username : true, preferredUsername: true },
        },
        triggers: {
          preSignUp: "src/preSignUp.main",
          createAuthChallenge: "src/createAuthChallenge.main",
          verifyAuthChallengeResponse: "src/verifyAuthChallengeResponse.main",
          defineAuthChallenge: "src/defineAuthChallenge.main",
        },
      },
    });

However when in use they're timing out with:

Client.js:145 Uncaught (in promise) UnexpectedLambdaException: PreSignUp invocation failed due to error Socket timeout while invoking Lambda function.

I believe this is due to the permissions required for the userpool to invoke the function as per: 

https://stackoverflow.com/questions/42934361/creating-a-cognito-userpool-with-lambdas-configured-as-triggers

and in sst i'd need to use the construct something like this:

    this.auth.attachPermissionsForTriggers(["lambda::InvokeFunction"]);

But im struggling to do so as the docs are unclear in terms of what exactly you can put into that function. Any help would be much appreciated

Thanks :)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
