### ISSUE TITLE
Properly support ESbuild config. 

### ISSUE THREAD

**Issue by AshHeskes** [sst/sst#1818]
I ran into an issue today where I had my lambda runtime set to `nodejs.16.x` with a top level `async/await` which is supported by node 16. Even though I had my `app.setDefaultProps()` set to use node 16 runtime. This didn't translate down to the esbuild config. So I constantly got an error `Top level await is not supported in the environment node14`. I was thinking this was something wrong with Lambda runtime in AWS not respecting the node 16 runtime prop.

Turns out it is just because of esbuild. Because it's hardcoded in serverless stack if the format isn't `format: 'esm'` it is set to build for target `node14` and `CJS`. Irrespective of `runtime` or `package.json.type=''module"`.

So the only solution is to rely on the `Function` config option of `format` as `ESM`. When format and target are quite different. It's quite possible to have a target of `node16` and format of `cjs`

Can you please allow for straight passthrough of all ESbuild options or allow people to generate their own builds and point serverless stack to the`/dist`? You support this kind of setup for StaticSite in the form of passing a build command and output dir. Is there anything preventing this being the same for functions?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
