### ISSUE TITLE
Error using sst start with custom stackName

### ISSUE THREAD

**Issue by ArranJacques** [sst/sst#1820]
Using custom stack names has started erroring when trying to run `sst start`.

Given the example app below, if I run `sst start --stage local`

```
// stacks/MyStack.ts

export function MyStack({ stack }: StackContext) {
  // ...
}

// stacks/index.ts

export default function (app: App) {

  // ...

  app.stack(MyStack, { stackName: `custom-stack-name-${app.stage}` });
}
```

Then I'll get the error

```
ValidationError: Stack 'local-my-sst-app-MyStack' does not exist
```

The stack deploys to AWS okay and has the correct status, so I can see a stack in CloudFormation with the name `custom-stack-name-local`, and a status of `CREATE_COMPLETE`.

It appears that when checking if the stack has finished deploying, it's not using the custom name so is failing to find any stack and thinking the deployment has failed.

This appears to be an issue in version `1.2.12` and up. If I downgrade to `1.2.11`, then I'm able to run `sst start` with a custom stack name, but if I upgrade to any version from `1.2.12` onwards it stops working.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
