### ISSUE TITLE
Support VSCode remote extensions

### ISSUE THREAD

**Issue by pharindoko** [sst/sst#1821]
**issue:**
I cannot use  the sst web console out of the box when working with vscode remote extensions.

**reason:**
When using vscode remote ssh extension the remote extensions doesn`t detect that ports for the websockets need to be forwarded.

Specifically we talk about the websocket tcp connection on port:
- 12557
- 13557

**enhancement:**

add file .vscode/settings.json with following settings

```
{
  "remote.SSH.defaultForwardedPorts": [
    { "name": "sst-websocket-1", "localPort": 12557, "remotePort": 12557 },
    { "name": "sst-websocket-2", "localPort": 13557, "remotePort": 13557 }
  ], 
}
```

and describe issue in documentation

**Comment by jordangarrison** [comment]
I hit this same issue, the workaround also worked for me, however, only on chromium browsers. Safari would not allow insecure content to load.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
