### ISSUE TITLE
Be able to specify on installation starter project and install directory using command flags

### ISSUE THREAD

**Issue by omenking** [sst/sst#1824]
When you first install SST it attempts to create a project and you get prompted with inputs

```
npm install sst
```

This is what I would perfer:

I install sst globally
```
npm install sst -g
```

Then I create a project with command flags:

```
sst create my-project --directory . --starter typescript
```

## Why no creating on first install?

I don't think this is a normal behaviour of most frameworks, you normally install a tool, and that tool then is used to generate project. 

The input prompts also limit the ability of programmatic workflows, so there needs to be ways to enter command flags.

## Why globally install?

Most other tools do this approach?

## Why command flags?

Its less error prone during instructional (tutorials, workshops) to give folks a single command with flags than hope they enter the right things into a prompt.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
