### ISSUE TITLE
When I generate a new app I would like to use the current directory

### ISSUE THREAD

**Issue by omenking** [sst/sst#1825]
When installing sst and choosing the current directory it does not choose appropriate names and I have to manually rename them:

The following name properties:
- package.json
  - `@@app` to `bar-raiser-partipcant`
- sst.json
  - `@@app` to `bar-raiser-partipcant`
- api/package.json
  - `@@@app/api` to `bar-raiser-partipcant-api`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
