### ISSUE TITLE
When I start npm and need to create the debug stack, improve the wording so its more clear

### ISSUE THREAD

**Issue by omenking** [sst/sst#1827]
When you first do `npm start` you get prompted to create a `stage name` you'd like to use `locally`.

- `stage name` makes me thing staging enviroment
- `locally` makes me thing nothing is being deployed to AWS
- naming the environment is a confusing, should be `dev` or left alone to default?

```
Look like you're running sst for the first time in this directory. Please enter a stage name you'd like to use locally. Or hit enter to use the one based on your AWS credentials (BarRaiserParticpant): dev
Using stage: dev
Preparing your SST app

=======================
 Deploying debug stack
=======================
```

These are the two CloudFormation stacks that get created

- dev-bar-raiser-particpant-debug-stack
- dev-bar-raiser-particpant-MyStack

I'm going generate with the default name and see what comes out.

[edit] @thdxr informed me that this stack in the developer's stack and its to default to the name of the username of the IAM user so you get `andrew-bar-raiser-particpant-debug-stack`

**Comment by omenking** [comment]
@thdxr best I could think up:
```
Look like you're running sst for the first time in this directory. 
A debug stack for your developer environment needs to be genreated. 
Please enter a name you'd like to use, we recommend your IAM username.
Or hit enter to use the one based on your AWS credentials (BarRaiserParticpant): andrew
Using stage: andrew
Preparing your SST app
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
