### ISSUE TITLE
Error: The specified permissions are not supported

### ISSUE THREAD

**Issue by romanpod** [sst/sst#1832]
Issue: adding multiple permission tuples to a function using `grantX` method results an error:
 "**_Error: The specified permissions are not supported_**".

Steps to recreate the issue:
1. Create a stack with a Table and a Bucket (sst Constructs)
2. Create a stack with a Function (sst Construct); `use` Table and Bucket stacks as `table1` and `bucket1` vars.
3. Use `permissions` prop or `fun.attachPermissions()` (which are the same, according to docs) and pass in an **array of tuples** of construct and a grant permission function.
For example:
`fun.attachPermissions( [ [ table1, 'grantReadData' ] , [ bucket1, 'grantReadWrite' ] ] );`
5. Deploy and witness the error: **_"Error: The specified permissions are not supported."_**
6. As a workaround, use fun.attachPermissions() with a single tuple for each permission, e.g.:
```
fun.attachPermissions( [ table1, 'grantReadData' ] );
fun.attachPermissions( [ bucket1, 'grantReadWrite' ] );
```

**Comment by suamai** [comment]
I had the same problem, and after some investigation found what was wrong: 

Try something like this:
```
fun.attachPermissions( [ [ table1.cdk.table, 'grantReadData' ] , [ table2.cdk.table, 'grantReadWrite' ] ] );
```

The documentation is a bit misleading here, but the permission attribute seems to expect a CDK construct and not an SST one.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
