### ISSUE TITLE
Error: When migration handler throws it does not stop deployment

### ISSUE THREAD

**Issue by JohnMarsden24** [sst/sst#1838]
Recently updated SST from 1.0.11 and there seems to have been a changed in the migration functionality. Previously my migration files had a `.js` file extensions as per the examples at the time. After upgrading and trying to deploy the migration handler was taking a very long time and eventually errored out:

<img width="1076" alt="Screenshot 2022-06-22 at 09 49 13" src="https://user-images.githubusercontent.com/55828757/175000435-7c054ce5-2eb6-4947-9328-f9586ae0b104.png">

<img width="1369" alt="Screenshot 2022-06-22 at 11 19 15" src="https://user-images.githubusercontent.com/55828757/175006064-0eb007f0-bee5-49ad-86a2-6e91b0c75044.png">

Taking a look at the logs attached to this handler Lambda I saw this error:

```
module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

I renamed the migration file and viola it worked, however the initial handler that threw the error didn't stop deployment as expected. Instead deployment only stopped after an hour when no response was found, which I imagine was caused by hitting the time limit.

Side note - taking a look at [more recent examples](https://github.com/serverless-stack/serverless-stack/blob/master/examples/rest-api-postgresql/api/migrations/first.mjs) I can see the migration files now use `.mjs` file extension and supports ES6 module exports, however the [SST docs still show using Common JS](https://docs.serverless-stack.com/constructs/RDS#migrations).

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
