### ISSUE TITLE
Default now() timestamp in migration script example causes fixed date

### ISSUE THREAD

**Issue by steviec** [sst/sst#1842]
The migration script example in the ideal stack has the following line: `col.defaultTo("now()")`.  It should be:

```
col.defaultTo(sql`now()`)
```

Otherwise the default date is hardcoded when the table is created and then all new records will use that same date. I was going to submit a simple PR for this, but `yarn test` was failing for me on the repo, and I didn't want to start poking around on how to fix the build.

To confirm that the date was hardcoded I ran this in the SST console:
```
select col.table_schema,
       col.table_name,
       col.column_name,
       col.column_default
from information_schema.columns col
where col.column_default is not null
      and col.table_schema not in('information_schema', 'pg_catalog')
order by col.column_name;
```

Columns that used `defaultTo("now()")` had a hardcoded date associated with `column_default`, whereas columns that used the `sql` template literal helper correctly showed `now()` in `column_default`.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
