### ISSUE TITLE
Bug: Renaming a stack causes SST console to crash when trying to migrate with RDS

### ISSUE THREAD

**Issue by JohnMarsden24** [sst/sst#1846]
### What's the problem?

SST console crashes if you rename a stack using `stackName` and try to apply a migration via the console.

### How to reproduce?

- Install [PostgreSQL example](https://github.com/serverless-stack/serverless-stack/tree/master/examples/rest-api-postgresql)
- Run locally using `npm start`
- Go to SST console -> RDS -> migrations
- All should work fine
- Add a `stackName` to `MyStack`:
```javascript
  app.stack(MyStack, {
    stackName: `${app.stage}-sst-test`,
  });
```
- Redeploy stack
- Go to SST console -> RDS -> migrations
- Console will crash with a `TypeError: Cannot read properties of undefined (reading 'data')` error caused by this line:
```javascript
const migrations = useListMigrations(func.data.arn, params.database!);
```

From what I figure when you rename a stack the FE isn't able to retrieve the newly named stack so `func` isn't defined.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
