### ISSUE TITLE
sst start: allow using layers

### ISSUE THREAD

**Issue by fwang** [sst/sst#1850]
Sam mentioned:
> is there any way to test in live dev mode & use layers instead of local packages?

### Possible Solution
On sst start, download the layers to (ie. `.sst/myLayer:5`), and set the node modules path to it when spawning processes.

Need to account for layers in a different OS arc as local.

---
Requests:
- Sam: https://discord.com/channels/983865673656705025/983866416832864350/991053145033543750

**Comment by Edwin-Luijten** [comment]
This would be a very welcome feature.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
