### ISSUE TITLE
Console: pressing tab in Lambda function focuses text box

### ISSUE THREAD

**Issue by fwang** [sst/sst#1852]
David mentioned:
> Would be nice if pressing tab in lambda function invoke text box in sst console didn't jump to 'invoke' button.
> I can see the benefit of being able to quickly jump to the button but there's already a hotkey for that
> makes formatting the payload kind of cumbersome

---
Requests:
- David https://discord.com/channels/983865673656705025/983865673656705028/990974829316435988

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
