### ISSUE TITLE
Telemetry: ignore error on failure

### ISSUE THREAD

**Issue by fwang** [sst/sst#1857]
Mayowa got this error on internet interruption:

![Image](https://user-images.githubusercontent.com/83515/176586288-51fceb6f-fe2f-4152-b9b4-649beb920e39.jpeg)

Telemetry errors should always be ignored.

---
Requests
- mayowa https://discord.com/channels/983865673656705025/991632223885348924

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
