### ISSUE TITLE
Console usage on Windows / WLS2

### ISSUE THREAD

**Issue by stefanullinger** [sst/sst#1861]
Hey guys, I was trying to use the console on Windows 11 and have some issues with it. I hope you can provide some guidance as I have no clue, why it behaves like it does.

1. I was testing it on Windows directly: I started my stack using `npm start`. It was giving me some URL to the console.
`https://console.sst.dev/sst-test/dev/local?_port=13558`.
Using Firefox, loading the Console in the browser works, but when navigating the console, e.g. clicking the Cognito link, the URL param _port=13558 is getting lost, because the app is doing a full page refresh. In the dev tools' console, I can see it is having issues connecting to "ws://localhost:13557/". Using Google Chrome, the apps does not do any full page refreshes and therefore continues to work as expected.

2. I was trying the same within WSL (Ubuntu), but neither in Chrome nor in Firefox I was able to access the Console. Both browsers log the same error: `WebSocket connection to 'ws://localhost:13557/' failed:`.
I guess I am missing some port forwarding from Windows to WSL2 (Ubuntu). But trying to add this using `netsh interface portproxy add v4tov4 listenport=13557 listenaddress=0.0.0.0 connectport=13557 connectaddress=172.26.181.138;` did not work. I have also added an incoming rule for port 13557 in Windows Defender Firewall, but until now, I was not able to get the Console working.

Is there some way to set a different port for the Console?
Can somebody provide some guidance on how to use this within WSL2?
Or maybe share some ideas on how I can track down, why it is not working?

Thanks in advance!
Stefan

**Comment by TGlide** [comment]
Bump, Console isn't working on Windows 10 with WSL either

**Comment by wengkhing** [comment]
@stefanullinger Would you be able to share how you get it working here? As we do not have access to the discord channel.

![image](https://github.com/serverless-stack/sst/assets/8358060/5d2907a4-1b56-461a-a4d5-ce272f686ed0)

**Comment by stefanullinger** [comment]
For everyone not having access to discord:

To get the SST console running, I followed the mkcert instructions here: https://github.com/microsoft/WSL/issues/3161#issuecomment-888992389 ... and then removed the two pem files from the .sst directory as Dan mentioned here: https://discordapp.com/channels/983865673656705025/990989982799900792/996023493491687424

> dax — 11.07.2022 14:01
> Can you ~~uninstal mkcert and~~ delete the two cert files in the .SST folder

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
