### ISSUE TITLE
create-sst: Overwrites non-empty folder & errors

### ISSUE THREAD

**Issue by garretcharp** [sst/sst#1865]
Just noticed that I accidentally overwrote a folder when I was trying to create a new SST project.
I also notice at the end of any `npx create-sst` I get the following: `Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\PC\AppData\Roaming\npm-cache\_npx\27552\node_modules\create-sst'`

Was just a random test thing that I don't even fully remember what I was testing at that specific time all I know is I wanted to test something with appsync and I already had a project called appsync test and whatever I was testing before is overwritten.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
