### ISSUE TITLE
Polling time is not configurable

### ISSUE THREAD

**Issue by emressener** [sst/sst#1870]
We are facing throttling on describeStacks api. Is it possible to add a configuration to configure the polling interval?
Following code looks hardcoded 5000 ms:
https://github.com/serverless-stack/sst/blob/a8f56ae888d3860e126ed88ea539389985b5da9e/packages/cli/scripts/remove.mjs#L109
https://github.com/serverless-stack/sst/blob/a8f56ae888d3860e126ed88ea539389985b5da9e/packages/cli/scripts/util/cdkHelpers.mjs#L365

**Comment by kostiantyn-korniienko-aurea** [comment]
created PR here - https://github.com/serverless-stack/sst/pull/1872 for v0

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
