### ISSUE TITLE
VSCode shows "unbound breakpoint" when used through WSL2

### ISSUE THREAD

**Issue by fwang** [sst/sst#1879]
Steve asked:
> Are there any extra steps to using the debugger when in VSCode through WSL2? I've been getting "unbound breakpoint" in both python and typescript lambdas

---
Requests
- Steve https://discord.com/channels/983865673656705025/996476879332716554

**Comment by Bhavikpatel576** [comment]
Want to bump this to see if there has been any development?

**Comment by Bhavikpatel576** [comment]
I was able to resolve the "unbound breakpoint" by setting a breakpoint and then hitting an endpoint.

**Comment by rob3c** [comment]
While working through the tutorial, I was able to finally get a red dot to replace the empty circle on the breakpoint line in the lambda source. However, execution still didn't stop there. The React client was still able to see the value, so the loop through the local function seemed to be working even though the breakpoint wasn't.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
