### ISSUE TITLE
GraphQL needed when following the new Learn setup

### ISSUE THREAD

**Issue by aisflat439** [sst/sst#1881]
I'm happy to update this but I'm not exactly sure how. This chapter talks about initialize the database, but if we're using GraphQL this doesn't make sense because the page renders 

![image](https://user-images.githubusercontent.com/3719502/179076154-9b210aad-e4d9-4a22-b2ea-8cebd6d18f42.png)

https://github.com/serverless-stack/sst/blob/master/www/docs/learn/initialize-the-database.md

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
