### ISSUE TITLE
cdk-nag lints - StaticSite bucket block public access

### ISSUE THREAD

**Issue by scottgerring** [sst/sst#1883]
Hi all,

I am using [cdk-nag](https://github.com/cdklabs/cdk-nag) on an SST project. There is a bunch of noise that would be nice to clean up so that it is practical to use the tool in SST-derived projects, but one particular one jumped out - the default behaviour for a `StaticSite` creates an S3 bucket without public access blocking turned on. This should be an easy fix - just provide a default value for `blockPublicAccess` on the underlying CDK construct used by StaticSite:
```
      bucket: {
        //blockPublicAccess: BlockPublicAccess.BLOCK_ALL
      }
```
The OAI policy that is attached will still provide Cloudfront access to the bucket.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
