### ISSUE TITLE
Load table/database name from .env by default

### ISSUE THREAD

**Issue by tonnyorg** [sst/sst#1884]
It would be nice if by default (through `create-sst`) the table and database names are dynamic, loaded through a `.env` variable; that way you can easily switch your table names through the .env file without actually have to code it yourself.

Something like:
```
  const tableName: string = process.env.TABLE_NAME || 'table';

  const table = new Table(stack, tableName, {
```

Instead of `const table = new Table(stack, "table", {`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
