### ISSUE TITLE
Export 'getExports' function from FunctionalStack

### ISSUE THREAD

**Issue by mdcrivello-adi** [sst/sst#1895]
If `getExports()` was exported from FunctionalStack, it would make it possible to do something like `sst.getExports(app)` within a stack. You could then pull in the exports of a previously deployed stack without importing the stack code.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
