### ISSUE TITLE
View logs from the debug stack and stub

### ISSUE THREAD

**Issue by jayair** [sst/sst#19]
Show the logs from the `stub Lambda` and `websocket connection handler` that is deployed in the Debug Stack.

### Use cases
Mike had an issue where the DynamoDB table was manually removed from the debug stack. And when `sst start` tries to send a websocket call to register itself, the websocket call returned "Internal Server Error".

Noah also ran into a [similar issue](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1633244522124900).

### Solution
- Whenever the stub function or the websocket function fails, send an error message to local. And display the message in the terminal.
- On `sst start`, auto-detect missing resources in the debug stack. And auto-recreate them.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
