### ISSUE TITLE
Is it possible to reference deploy time values from one stack as part of the build steps for another?

### ISSUE THREAD

**Issue by liam-jones-lucout** [sst/sst#1903]
This is an issue I've bumped up against a couple of times now and it would be great to get a definitive answer.

Lets say I have a GraphQL stack and a React app stack. I want the React app to be able to make requests to the GQL stack. However, for the React app to build properly I need to pull in the GQL types from the GQL stack. This of course needs to happen before the React app is deployed. Is there a way to resolve the tokenized values from one stack before beginning the build/deployment of another?

I guess what I'm asking is: Does SST allow for part of an app to be *completely* deployed and it's exports resolved before continuing with the next step in the app?

This is a pseudo-ish code of the kind of thing I've tried before, just in case what I'm trying to do is possible, but I've been doing it completely wrong:

```typescript
function GQL({stack}) {
  const gqlAPI = new GraphQLApi(stack, "Api", {
    //stuff
  });
  
  return gqlAPI;
}

function ReactSite({stack}) {
  const gqlApi = use(GQL);
  //also tried putting a dependsOn in here

  getGQLTypes(gqlApi.url); //This is where I have the issue

  return new ReactStaticSite(stack, "ReactSite", {
    path: "./packages/web/overlay",
  });
}
```

If it's not possible to do this dynamically, what's the best way to do it statically? What I'm really looking to avoid is having to go look up the gql api url manually before I can build/deploy the react app.

To be clear, this is a simplified example. I know I could reference the gql schema locally to generate the types. One example where that's not possible is with apollo federation, where you need to run a cli command before building in order to generate the federated schema. That CLI requires a yml filled with the URLs you want to federate.

**Comment by fwang** [comment]
Hey @liam-jones-lucout, I like the pattern you suggested. Essentially, instead of building all stacks up front, build each stack right before deploying, so it has access to stack outputs from deployed stacks.

This works for ur use case, but wouldn't work if `GraphQLApi` and `ReactStaticSite` were created in the same stack. I'd prefer a solution that handles both cases consistently.

--- 

That said, you can use SSM to work around this. Pseudo code looks like:
```ts
import * as ssm from '@aws-cdk/aws-ssm';
import aws from 'aws-sdk';

function GQL({app, stack}) {
  cons SSM_NAME = `${app.name}/${app.stage}/GQL_API_URL`;

  const gqlApi = new GraphQLApi(stack, "Api", {
    //stuff
  });
  
  const ssm = new ssm.StringParameter(stack, 'StringParameter', {
    name: SSM_NAME,
    stringValue: gqlApi.url,
  });

  return SSM_NAME;
}

function ReactSite({stack}) {
  const SSM_NAME = use(GQL);
  //also tried putting a dependsOn in here

  const ssm = new aws.SSM();
  const url = await ssm.getParameter({
    name: SSM_NAME
  });

  getGQLTypes(url); //This is where I have the issue

  return new ReactStaticSite(stack, "ReactSite", {
    path: "./packages/web/overlay",
  });
}
```

Let me know if that makes sense.

**Comment by liam-jones-lucout** [comment]
@fwang thanks for getting back to me! In your example (which I will try this evening) can you confirm that the SSM parameter will be fully resolved by the time ReactSite is called like so:
```
export default async function (app: App) {
   app.stack(GQL).stack(ReactSite)
}
```
I'm guessing from your example that SSM has a role in delaying build steps in time for the value to be resolved fully. I wasn't aware of that at all, so that if that's the case then it may be exactly what I need. Many thanks again

**Comment by fwang** [comment]
Yeah it will. Note that ssm.getParameter() is just a normal AWS SDK call.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
