### ISSUE TITLE
Support for .mts files for RDS migrations

### ISSUE THREAD

**Issue by ByronHawksmith** [sst/sst#1920]
Just out of curiosity is there a reason for not supporting `.mts` files for migrations?

https://github.com/serverless-stack/sst/blob/f2f887bbdec1e45e618da5a53ca526d95012285f/packages/resources/assets/RDS/migrator/index.js#L74

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
