### ISSUE TITLE
Accessing Function Build Output Dirs 

### ISSUE THREAD

**Issue by AshHeskes** [sst/sst#1928]
Is it possible to get a reference to the build output dir of a function construct (or any other construct) to pass as the input to another?

I appreciate this might sound odd on the surface so heres the context. I'm building a small stack for handling transactional email sending. The stack consists of the following...

1. An SQS queue will hold the type of email and parameters to be sent.
2. A lambda handler for the above queue that will send the requested email.
3. A StaticSite that contains static assets such as logos etc for said emails.

The lambda function that pulls items from the queue is responsible for selecting which email template should be sent and rendering any template params, that are then are sent via SES (templates are defined in the lambda fn code not stored in SES).

Imagine the lambda FN code structure similar to a react app...

```
- src/
    - templates/
        - example-template/
            - assets/
                - logo.png
            - template.html
            - template.js
```

inside template.js we have something like...

```js
import render from "render"
import template_html from "./template.html";
import logo_url from "./assets/logo.png"

export default function ( template_params ) {

    return render ( template_html, { logo_url, ...template_params  }  )

}
```

The difference being an email template obviously needs to reference static assets like images that cannot (read: should not) be sent with the email and cannot be "bundled" as data URIs. They need to be hosted somewhere and cannot change without breaking all previously sent emails.

The ESBuild file loader can handle importing them and can be configured to copy these files into a different dir in the build output e.g. `/public`. Whilst also hashing the content, adding the content hash to filename and allows me to prepend these filenames with a URL.

So in the above code case the value of `logo_url` is not `"logo.png"`.

instead it's...

```js
import logo_url from "./assets/logo.png"

console.log(logo_url);

// > "https://email-assets.example.com/logo-aB1cDf.png"
```

So in theory I could then use the `<build output path of the lambda fn>/public` as the `src` input to `StaticSite` and use the URL of the `StaticSite` to tell the lambda ESBuild config what to prepend these loaded files with (given the site URL is known in advance, which outside local is nearly always true). 

This would be great because not only do assets get to live alongside their template and code. As file contents are hashed, when deployed to a StaticSite I can preserve older versions of assets so recipient emails always render correctly no matter how old and we can change templates and assets without worry. 

The problem here is that I can't seem to figure out how I would be able to tell the `StaticSite` that its source input is the `/public` folder output from the Lambda function build.

There's obviously many ways to skin this cat and achieve the same result. It's just the above is by far the "cleanest" and DRY. If it can't currently be done, could it be a feature for consideration to add the build output path of any construct as a property?

Or allow us to do our own builds?

I can see many cases where this type of setup is ideal including in react apps, native react apps and vanilla JS apps.

**Comment by thdxr** [comment]
Interesting situation.

An alternative - can you use `bundle.commandHooks.afterBundling` to copy the files somwhere else? I believe you get the `inputDir` as an argument to your callback.

I imagine you might have several of these template functions and you probably only want one staticsite to host all of the assets.  So you'd probably need to collect them all in a single place anyway right?

**Comment by AshHeskes** [comment]
Correct there are multiple templates in the same code. As said though the ESbuild config can take care of collecting them all and moving them to a specific dir in the lambda build output.

Interesting that I may be able to get access to the build output via a build hook. Do you know how long build files stick around for? As in let's say the lambda build runs. I get the output dir and just use that path to pass to the static site which then builds. 

Would the original lambda build files still be around or do they get destroyed/moved after the build finished?

**Comment by thdxr** [comment]
Yep they should still be there, they stick around till the next build

**Comment by AshHeskes** [comment]
@thdxr So accessing the build output from the command hooks works. Although I noticed a few oddities while attempting this.

1. Specifying 1 command hook requires all to be specified or the build errors with `<unused command hook> is not a function`. 

2. The build output folder contains the full filesystem path to the code rather than being relative to the Lambda `srcPath` e.g. say the source code is in `<project root>/modules/email/src` the build output recreates the entire tree e.g. `<project root>/.stt/<stage>-<app>-<stack>-<handler>/modules/email/src`. Rather than simply `<project root>/.sst/<stage>-<app>-<stack>-<handler>/src`. Specifying an esbuild option of `outbase` does not change this (I will come on to how I did this later) so it seems to be done by SST somewhere. Which means when passing to my static site I have to specify `<build output dir from hook>/path/from/root/to/src/public` as the the input path to static site.

3. Paths specified for constructs i.e. `srcPath` and `handler` are relative to the project root rather than relative to the stack file itself. In my case I have put the stack code for a module in the folder next to the module src (there's multiple modules that are themselves stacks with one root App construct importing and composing them). So it seems odd to be writing paths relative to the project root instead of relative to the stack file.   

On to the next points of actually building.

The options I need for ESbuild to do what I want are not able to be passed down through the lambda function config. Namely the `assetNames` and `publicPath` options.  Which I use to specify to outdir folder to move images to and prepend the url of the static site to the imported image path string.

To get around this I wrote an esbuild plugin which literally just adds the esbuild config I actually want. This came with a few annoyances.

```js
// This is all the plugin file does.

const { IS_LOCAL, EMAIL_ASSETS_DOMAIN } = process.env;

const config_plugin = {
  name: "config-plugin",
  setup({ initialOptions: options = {} } = {}) {
    options.assetNames = "public/[name]-[hash]";
    options.publicPath = IS_LOCAL ? "" : EMAIL_ASSETS_DOMAIN;
  },
};

module.exports = [config_plugin]
```

1. Again the path to the esbuild plugin in the lambda construct is relative to the root of the project not the stack file.

2. The esbuild plugin file has to be in commonjs  format with `module.exports = [plugin]` using es modules doesn't work ie. `export default [plugin]`. You only get a `Could not transpile lambda code` error so it can be tricky to realise what's wrong.

3. Since I have to use a plugin to configure the ESbuild props I want. It means that in my stack code I cannot specify the `publicPath` option to prepend the URL of the staticsite which will host the assets. Fortunately I can get around this by pulling in an env var from my plugin file which SST preserves from the .env that gets loaded, or I can assign it to `process.env`. But it's still hacky and obfuscates how this is being handled from the actual stack code.

I've brought up this issue of SST not just proxying all bundle props to esbuild even when there's already a special subprop for `esbuildConfig`. Is there some limitation that prevents this? Given I can override and specify all options via a simple plugin it doesn't seem likely while not supporting it does make things messy.

**Comment by AshHeskes** [comment]
So it seems I was a little hasty in thinking command hooks work to get the output dir due to me just using `sst diff` to test my code rather than actually deploying it. So it works when using `sst diff` cause that helper seems to run the bundling synchronously.

Where as `sst start` or `sst deploy` runs the bundling async (or at least after your stack code finishes). Thus you cannot capture the output dir from a command hook to pass to another construct.

Unless theirs some way to force bundling to happen synchronously in `sst start` or figure out the `.sst/artifacts/<resource>` path ahead of time. The artifacts path could be hardcoded but since you can change the identifier for the stack at the app level and you guys could change your output structure. Hardcoding it doesn't seem like the best solution long term.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
