### ISSUE TITLE
logicalPrefixedName() seems useless.

### ISSUE THREAD

**Issue by AshHeskes** [sst/sst#1943]
I tried using this in a stack where the [documentation says](https://docs.sst.dev/constructs/Stack#prefixing-resource-names) `scope.logicalPrefixedName( "name" )` to change the name of a stack from the stack `fn.name` and thus the assumption being that `scope` is `this` inside the stack in which it's called.

However `this.logicalPrefixedName()` is not a function nor is the passed in `stack.logicalPrefixedName()`. The only thing that works is the passed in `app.logicalPrefixedName()`. But when I do this and pass a name string. The actual build output omits the stack name entirely when without it the build output is the stack `<stage>-<app>-<stackFn.name>-<resource>` and with it the build output is just the the `<stage>-<app>-<resource>`.

What am I missing? The docs certainly seem wrong and by extension the only thing that does work seems to have the inverse effect by omitting a prefix name for the stack entirely?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
