### ISSUE TITLE
Dynamo expressions should support special characters

### ISSUE THREAD

**Issue by mikestopcontinues** [sst/sst#1944]
My hash and sort keys are `$hash` and `$sort`. I get the following error when I try to run the query in the local dev env:

```
ExpressionAttributeNames contains invalid key: Syntax error; key: "#$hash"
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
