### ISSUE TITLE
Stack traces should use source maps

### ISSUE THREAD

**Issue by mikestopcontinues** [sst/sst#1946]
It would be wonderful if the console stack traces used the sourcemaps to correctly locate issues...

<img width="870" alt="Screen Shot 2022-08-11 at 9 08 02 AM" src="https://user-images.githubusercontent.com/150434/184152605-d1c56596-e253-4f71-8a00-6f1cf53b2680.png">

**Comment by Newbie012** [comment]
@mikestopcontinues did you find a workaround for this?

**Comment by mikestopcontinues** [comment]
@Newbie012 Nope. :(

**Comment by jayair** [comment]
We should prioritize this. @thdxr @fwang?

**Comment by oscarthorn** [comment]
Is there a solution for this? The lack of source maps support makes debugging needlessly hard.

**Comment by jayair** [comment]
Yeah I think we are fixing this in v2.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
