### ISSUE TITLE
Function srcPath referencing adjacent folder not working

### ISSUE THREAD

**Issue by jsaundersonc** [sst/sst#1948]
Hey,
I'm trying to setup a monorepo in which the SST code is located in a folder adjacent to the application code.

The examples achieve this by running SST at the root level, but in this case I'm trying to run SST within a subfolder.

I've set the `srcPath` for functions to `../services` which almost works but when esbuild builds the function then the `../` get resolved for the output path and handler. This results in the JS bundle being created outside of the function artifact folder.

![image](https://user-images.githubusercontent.com/97411624/184270503-e556376d-1ec6-40c2-bcd3-9a9135865a54.png)

![image](https://user-images.githubusercontent.com/97411624/184270549-eb27285a-49c8-4c62-b22a-ef1736a6d29f.png)

Would it be possible to filter out the `../` when generating the target and handler to support this?
https://github.com/serverless-stack/sst/blob/master/packages/core/src/runtime/handler/node.ts#L53
https://github.com/serverless-stack/sst/blob/master/packages/core/src/runtime/handler/node.ts#L217

Example setup:
https://github.com/jsaundersonc/sst-bug

We are trying to run SST from within the `stacks` folder, in our actual scenario we are attempting to tie SST into a Turbo monorepo.

Cheers.

**Comment by shaunchong** [comment]
I've run into the same issue as well, where I'm trying to move SST away from the root folder, and into its own dedicated "infrastructure" folder. I then tried to reference my functions by setting the `srcPath` to `../services` but it doesn't seem to be bundling properly.

Were you able to find any workarounds?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
