### ISSUE TITLE
RemixSite: support Live Lambda dev in non-Edge mode

### ISSUE THREAD

**Issue by fwang** [sst/sst#1949]
Matt mentioned:
> Is it possible to run Remix during sst start within a local dev live lambda?  Or are there some challenges there that make running it like that not possible?
> The reason is to fully simulate the cognito protected api gateway and, hopefully, pull cognito attributes (like the user's sub id) from the request.

---
Requests:
- Matt https://discord.com/channels/983865673656705025/1006300210349211749

**Comment by dangreaves** [comment]
Would love to be able to do this!

One of the benefits of SST and the Live Lambda is that backend logic has access to AWS resources (like DynamoDB) through the normal IAM role on the Lambda. When running the Remix dev server directly, any loader or action logic will be connecting to AWS resources from your local machine, which comes with problems.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
