### ISSUE TITLE
Attempting to run SST with vitest in GitLab pipeline fails during bundle of functions

### ISSUE THREAD

**Issue by sjakos** [sst/sst#1950]
I ran into an issue where SST and vitest were able to run locally, but when I set up a GitLab pipeline it would consistently fail while bundling the NodeJS functions for testing the Stacks. 

```
TypeError: Cannot read properties of null (reading 'toString')
 ❯ Object.bundle node_modules/@serverless-stack/core/dist/runtime/handler/node.js:166:44
 ❯ Module.bundle node_modules/@serverless-stack/core/dist/runtime/handler/index.js:16:16
 ❯ new Function node_modules/@serverless-stack/resources/dist/Function.js:223:45
```

I was overriding process.env during the stack tests so I could have a consistent snapshot of the templates. This was causing the childProcess that was trying to spawn "node" by name for the bundling script to fail because "node" wasn't in the path. I'm not entirely sure why it was working locally and not in the container in the pipeline.

My solution for now is to use a spread operator to keep the rest of process.env intact in my tests and just override the variables needed. However it might be better to use `process.execPath` in the spawn calls for the bundling process, rather than calling "node"

https://github.com/serverless-stack/sst/blob/c19a9b30ab65508e5e1bb43ad5651f293c1c6786/packages/core/src/runtime/handler/node.ts#L197

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
