### ISSUE TITLE
[Feature Request][Security] The Api construct, when using a custom domain, should setup a CAA record

### ISSUE THREAD

**Issue by ari-becker** [sst/sst#1973]
When using a [custom domain on the API construct](https://docs.sst.dev/constructs/Api#customdomain), the Api construct simplifies the process of adding alias records to Route 53 and issuing an ACM certificate.

When doing so, the Api construct should additionally add a [CAA record](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#CAAFormat) for the custom domain authorizing ACM to issue the cert. CDK makes this simple with a batteries-included [resource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_route53.CaaAmazonRecord.html) that sets up the CAA record correctly.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
