### ISSUE TITLE
Lambda live development / debugging does not work for python

### ISSUE THREAD

**Issue by pharindoko** [sst/sst#1974]
you cannot debug python at the moment.
Debugpy would be the best option to do this (at least for vs-code)

**Comment by yellowtailfan** [comment]
I found [this recipe ](https://www.linen.dev/s/serverless-stack/t/445893/Hey-U01J5Q8HV5Z-U01JVDKASAC-I-ve-successfully-followed-the-G) linked from the [SST docs](https://docs.sst.dev/live-lambda-development#languages). They involve manually patching your local copy of the SST code, which would need to be redone for every SST update. As far as I can tell, the proposed changes haven't been implemented in the SST code itself yet.

**Comment by pharindoko** [comment]
Hey @yellowtailfan  - thanks for your reply.
I checked the recipe link - I was the last one to reply to this thread. :)

Each time to change something directly in the code in node_modules is not a stable solution in my eyes.
As many lambdas are written in python as well, for me this is a requirement for sst.

**Comment by jayair** [comment]
I think somebody in the community had a write up on how to get Python debugging working. Might have to search for it on Discord.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
