### ISSUE TITLE
Reference values of Secrets in CDK constructs

### ISSUE THREAD

**Issue by revmischa** [sst/sst#1984]
Problem: I need developers to configure oauth secrets (clientId/clientSecret for external auth providers. I need to pass these values both [to Cognito](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.UserPoolIdentityProviderOidc.html#clientid) and also to be used at runtime. 

Currently I handle this using Secrets Manager - I create a secret using
```ts
  const secret = new Secret(stack, 'Secret', {
    description: app.logicalPrefixedName('app'),
    generateSecretString: {
      secretStringTemplate: JSON.stringify({
        // optional
        ['LINKEDIN_CLIENT_ID']: 'changeme',
        ['LINKEDIN_CLIENT_SECRET']: 'changeme',
      }),
      generateStringKey: 'RANDOM', // unused
    },
  });

  app.addDefaultFunctionEnv({
    ['APP_SECRET_ARN']: secret.secretArn,
  });
  app.addDefaultFunctionPermissions([[secret, 'grantRead']]);
```
Source: https://github.com/jetbridge/sst-prisma/blob/master/stacks/secrets.ts#L15

The secrets are loaded at runtime using the SDK but in CDK I am able to reference the values in the secrets.
```ts
    const clientSecret = secrets.secretValueFromJson('LINKEDIN_CLIENT_SECRET').toString();
    const clientId = secrets.secretValueFromJson('LINKEDIN_CLIENT_ID').toString();
```

If I try to replace this with the sst.Secret construct it does not resolve the secret value.

Also, if I try to create a sst.Secret using secretValueFromJson I get the following error:
```
Error: Resolution error: Resolution error: Resolution error: "SST_SECRET_${Token[TOKEN.826]}" is used as the key in a map so must resolve to a string, but it resolves to: {"Fn::Join":["",["SST_SECRET_{{resolve:secretsmanager:",{"Fn::ImportValue":"mish-myapp-Secrets:ExportsOutputRefSecretA720EF052D953DED"},":SecretString:LINKEDIN_CLIENT_ID::}}"]]}. Consider using "CfnJson" to delay resolution to deployment-time.
```

---

Ideally in my stack I could say "if LINKEDIN_CLIENT_ID/SECRET is set then enable this OIDC provider", but I'd settle for making it required for now. I need to share the secrets with people setting up their dev environments and tell them how to set the oauth secrets.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
