### ISSUE TITLE
Secrets for nextJS backend?

### ISSUE THREAD

**Issue by revmischa** [sst/sst#1986]
I'd like to be able to use a secret in my NextjsSite. I want the SSR code to have [NEXTAUTH_SECRET](https://next-auth.js.org/configuration/options#nextauth_secret) set

e.g.
```ts
  const frontendSite = new NextjsSite(stack, 'Web', {
    path: 'web',
    environment: {
      NEXTAUTH_SECRET: Config.JWT_SECRET,   // probably not on Config but you get the idea
```

I was trying to do this with Secrets Manager; you can tell it to automatically generate a random string for you in CDK and then reference that value. But the reference isn't getting resolved by NextjsSite - it just gets passed to the Nextjs app as:
```
    NEXTAUTH_SECRET: {{resolve:secretsmanager:arn:aws:secretsmanager:us-west-2:92658999003:secret:SecretA720EF05-abR85M3Xpzlu-v1pq7D:SecretString:APP::}}
```

So I'm not clear on how to provide a secret to my Nextjs app.

**Comment by revmischa** [comment]
This is solved by using https://www.npmjs.com/package/cdk-nextjs-standalone

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
