### ISSUE TITLE
REQUEST: Add api/graphql to vpc with latest constructs

### ISSUE THREAD

**Issue by sf0rman** [sst/sst#1991]
Due to company policy, internal APIs (in which we'll be using GraphQL) needs to sit inside a VPC. Currently, I cannot find a way to do this with the latest constructs, and am relying on the apiv1 construct.

If possible, it would be very useful to be able to add the 'new" api and graphql constructs to a (non default) vpc.

**Comment by fwang** [comment]
Hey @sF0rman, SST uses the AWS API Gateway service to create the APIs. AWS API Gateway does not have the concept of deploying into a VPC.

Does ur company have existing internal APIs made using API Gateway? If so, we can look at how they are deployed and follow the same setup.

**Comment by sF0rman** [comment]
So I'm obviously inaccurate on the terminology, but with the RESTApi (v1) it was possible to create a private api gateway that was only accessible from within the VPCs using VPC endpoints, and with the new construct we have HTTP api's which cannot be made private.

So what I'm looking for is a quick way of making a private graphql endpoint really. Not accessible from the outside internet.

```
    cdk: {
      restApi: {
        endpointConfiguration: {
          types: [EndpointType.PRIVATE],
          vpcEndpoints: ["vpce-xxxxxxxxxx"]
        },
        policy: apiResourcePolicy
      }
    }
```

**Comment by sF0rman** [comment]
Just adding an update here:

I've managed to create a private API using the `ApiGatewayV1Api` construct, but this doesn't work with sst console. Works elsewhere and can stick to this.

Request could be marked a nice to have. (preferably I'd like Amazon to allow private HTTP gateway or private appsync constructs, which is out of your control)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
