### ISSUE TITLE
Stripe Test, Token tok_visa not valid

### ISSUE THREAD

**Issue by AndreaNocciolini** [sst/sst#1993]
Hello!
I just finish the "Add an API to Handle Billing" chapter from your guide. Everything seems working fine so far, but at the end of this chapter I ran into a problem with `aws-api-gateway-cli-test`. </br>Putting the command line that you provide,  I receive this response: </br> 
![immagine](https://user-images.githubusercontent.com/80393968/186263205-3eb8d9a8-ca2f-493e-9a3a-8e2ff8d65761.png)

I have read the Stripe documentation regarding the tests and I tried with other tokens provided by them, but the answer is always the same ( _status 500_ ).

Can you tell me if this problem is due to Stripe or SST? Or if you know a method to solve it?

P.S.
I'm working from Windows10, so I had to use this command line:
`npx aws-api-gateway-cli-test --username ${username} --password ${user password}  --user-pool-id ${user_pool_id}  --app-client-id ${app_client_id} --cognito-region ${region}  --identity-pool-id ${identity_pool_id} --invoke-url ${url} --api-gateway-region ${region} --path-template /billing --method POST --body "{\"source\":\"tok_visa\",\"storage\":21}"`.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
