### ISSUE TITLE
StaticSite local dev `placeholder: false` re-deploy

### ISSUE THREAD

**Issue by AshHeskes** [sst/sst#1996]
When using the staticsite construct and the option for `placeholder: false` and running locally. The staticSite does not get re-deployed to S3 when the src changes.

I think this has to do with the staticsite construct never actually "watching" for changes itself. As when using `placeholder: true` the site is typically ran independently with an `npm start` command.

I'm not really sure what a good solution is here as even using a `buildCommand` prop on the static site that watches for changes to at least compile the src into the build dir on change. Causes the entire `sst start` command to halt as it is waiting for the build command to finish executing (which as it is watching, obviously never does). While at the same time the build command does not get recalled by SST on src changes either it seems. 

Just out of interest in this case, why is it required to pass the `path` when `buildCommand` with `buildOutput` is set? It seems logical that `path` could just be set to the output of the `buildCommand`. Which also negates the need to check the existence of the `path` before the `buildCommand` is ran. 

It would appear that either `buildOutput` or `path` is redundant if `buildCommand` is set. This is one thing that led me to assume that the need to set `path` along with `buildOutput` and `buildCommand` was for SST to watch for changes on `path`, which it doesn't.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
