### ISSUE TITLE
AWS is asking customers to upgrade Serverless Aurora to postgres11.13 by Jan 31.

### ISSUE THREAD

**Issue by shechter** [sst/sst#2011]
https://github.com/serverless-stack/sst/blob/35751e415b92e274a30156209c28e79e5e5b4bee/packages/resources/src/RDS.ts#L139

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
