### ISSUE TITLE
StaticSite: build sites in parallel

### ISSUE THREAD

**Issue by fwang** [sst/sst#2037]
Similar to how functions are now built in parallel starting v1.11.1, do the same for Sites.

### Benchmark from Sean:

❯ time yarn build:serial
✨  Done in 43.65s.

❯ time yarn build:parallel
✨  Done in 29.71s.
approx an extra 14s. I suppose this will vary. I have one very slow build, so it always ends up as slow as that one.
But if all builds took 10s it would be close to 10s compared to 30s.

---
Requests
- Sean https://discordapp.com/channels/983865673656705025/983865673656705028/1016954597442601000

**Comment by jayair** [comment]
I think the latest release actually does this now. https://github.com/serverless-stack/sst/commit/a734123f718ef12b95834928c14d29e564933bcc

**Comment by ceilfors** [comment]
Unfortunately, a734123 is regressed by https://github.com/sst/sst/pull/3340/files#diff-386b83955f40fc2447c4c0ad9cde6d448b2dec1d4e1458864821647ab50f587cL451.

**Comment by jayair** [comment]
Oh, hmm I haven't looked into this yet but happy to review a PR.

**Comment by ceilfors** [comment]
No worries! We have decided to build it in parallel outside of `sst deploy`.

For anyone else who came here, we essentially removed the responsibility of building next from SST by:
- Overridding NextJsSite buildCommand, so it does nothing in CI.
- Before `sst deploy` is called, calling `npx --yes open-next@2.3.1 build` in parallel(which is the command used inside NextJsSite).

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
