### ISSUE TITLE
Function: support dockerImage option

### ISSUE THREAD

**Issue by fwang** [sst/sst#2040]
Ryan mentioned:
> For DockerImage functions I just want them to deploy as DockerImages, when running locally it would be great if they just ran like normal Functions with the live debug.
---
Requests
- Ryan https://discordapp.com/channels/@me/997591665315430430/1017162943571439688

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
