### ISSUE TITLE
is there any examples to unit test APIs with authentication?

### ISSUE THREAD

**Issue by muhammadnasr** [sst/sst#2043]

**Comment by fwang** [comment]
Are you testing by calling the API endpoint?

**Comment by muhammadnasr** [comment]
Yes

**Comment by muhammadnasr** [comment]
I am using the example in sst guide
https://sst.dev/chapters/add-an-api-to-create-a-note.html

**Comment by fwang** [comment]
You'd need to programmatically login as a user, and make a signed API
request as if the request was made from the frontend.

Let me know if that works for you.

Frank

--
<https://seed.run/>
Founder at SST <https://sst.dev>

SST <https://github.com/serverless-stack/serverless-stack> - OS framework
for building serverless apps
SEED <https://seed.run/> - Deploy, manage, and monitor serverless apps

**Comment by muhammadnasr** [comment]
Is there any examples to login programmatically using SST?



> You'd need to programmatically login as a user, and make a signed API
> request as if the request was made from the frontend.
>
> Let me know if that works for you.
>
> Frank
>
> --
> <https://seed.run/>
> Founder at SST <https://sst.dev>
>
> SST <https://github.com/serverless-stack/serverless-stack> - OS framework
> for building serverless apps
> SEED <https://seed.run/> - Deploy, manage, and monitor serverless apps
>
>
> On Fri, Sep 9, 2022 at 9:47 AM Muhammad Hassan Nasr <

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
