### ISSUE TITLE
NextjsSite: Allow individual configuration for lambdas

### ISSUE THREAD

**Issue by dkershner6** [sst/sst#2045]
Currently, all 3 edges lambdas and the regeneration (normal) lambda have to have the same configuration, controlled by `defaults.function` prop.

This is less than ideal, since the use cases vary massively between the lambdas (even the defaults are not the same memory size).  Also, the regeneration lambda could support ARM64, while the edge cannot.

These restrictions require all lambdas to use the highest requirements of any of the lambdas, which is expensive at scale.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
