### ISSUE TITLE
RDS: running migrations in Console is flaky

### ISSUE THREAD

**Issue by fwang** [sst/sst#2054]
Samster:
> running the migrations is basically a wild goose chase. The migrations might run/hang/stall/die on a whim, seemingly. Console logs following errors
![Image](https://user-images.githubusercontent.com/83515/189553797-16ade4f0-b5b5-4d01-9c0e-830af0705d02.png)

Bruno De Paula:
> I am and can confirm about that error appearing periodically with the query select from pg_database. I tried switching to Postgres as well but it seems the behaviour is still unstable, sometimes it works but only after a couple of refreshes of the panel. I can see from the console the quest to migrate is in "pending" state

---
Requests
- Samster https://discordapp.com/channels/983865673656705025/1011551088983412747

**Comment by hehooleehoo** [comment]
We're also seeing problems when running migrations. Clicking on a migration usually just hangs. I have noticed that we can often get it working when refreshing and trying each migration one-by-one - however after a few attempts, all requests (migrations, graphql requests, etc) return a "rate exceeded" error, and retrying `yarn start` errors with:

```
WebSocket connection error Error: Unexpected server response: 500
    at ClientRequest.<anonymous> (/<<path-to-my-app>>/node_modules/@serverless-stack/core/node_modules/ws/lib/websocket.js:886:7)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

Then we have to wait around 15 minutes before retrying, assuming for lambda to time out the hanging requests?

**Comment by thdxr** [comment]
Hey @hehooleehoo can you try the latest version?

**Comment by hehooleehoo** [comment]
Thanks @thdxr that seems to have done the trick!

**Comment by LewisAlderman** [comment]
I'm still getting this, on v1.13.0

**Comment by xinha-sh** [comment]
Yup. Still facing the issue. Rollbacks are not working at all

**Comment by cesaraugustogarcia** [comment]
Same for me, rollbacks sometimes work, sometimes don't, and is very difficult to find out what could be happening under the hood.

**Comment by jayair** [comment]
@cesaraugustogarcia @xinha-sh which SST version are you using?

**Comment by xinha-sh** [comment]
@jayair The issue was fixed by Dax. Had to clear all node_modules.

**Comment by steviec** [comment]
One additional note: when the query select from pg_database fails, it renders the SST console's RDS UI useless. I can't switch between databases using the database dropdown in the header, I can't load/run migrations, etc. If I remove the Mysql db from the stack, everything starts working again.

**Comment by cody-hoffman** [comment]
Some of my teammates are experiencing a similar issue when running migrations through the console - migrations will hang for ~30min. We're on `v1.15.16`.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
