### ISSUE TITLE
`sst-env`: robust way to detect `sst start` is running

### ISSUE THREAD

**Issue by fwang** [sst/sst#2068]
Currently if `sst start` and `sst-env` are kicked off simultaneously, `sst-env` sees the `.build/static-site-environment-output-values.json` file from the previous deployment. We need a more robust way to detect `sst start` is running.

---
Requests
- MageD https://discordapp.com/channels/983865673656705025/1018899426493857862/1019630050242474054

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
