### ISSUE TITLE
Feature request: Support qualifier prefix for resource names

### ISSUE THREAD

**Issue by hans-m-song** [sst/sst#2086]
Currently, the behaviour of SST is to append `${appStage}-${appName}` to resource names. This becomes problematic when deploying into an account with restrictive lambda boundary policies that require resources to be named in a certain way, e.g. `"arn:aws:s3:::qualifier-*/*"`, `"arn:aws:lambda:::function:qualifier-*"`, etc. This is also problematic with the Config construct as the SSM parameter path is hardcoded.

My suggestion: allow specifying a qualifier via `cdk.json` (`"@aws-cdk/core:bootstrapQualifier"`) or as a part of the app or stack parameters, i.e. `${qualifier}-${appStage}-${appName}` or Config parameter paths `/sst/${qualifier}/${appName}/${stageName}/...`

I wouldn't mind having a go at implementing such functionality If the SST team is open to this.

**Comment by hans-m-song** [comment]
[Semi-related discussion](https://discord.com/channels/983865673656705025/1020116506912227389)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
