### ISSUE TITLE
RemixSite: support config

### ISSUE THREAD

**Issue by fwang** [sst/sst#2093]
Requests
- joshyork https://discordapp.com/channels/983865673656705025/983866416832864350/1023275478620049430
- m4tty_d https://discordapp.com/channels/983865673656705025/983866416832864350/1026947775868440637

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
