### ISSUE TITLE
Auth `onSuccess` handler to be supplied with `queryString` parameters from `authroize` endpoint.

### ISSUE THREAD

**Issue by brinsleylogic** [sst/sst#2094]
# Feature Request

## Problem

It would be useful if we could call our `auth/{adapter}/authorize` endpoints with some additional parameters in the query string, for things like dynamic redirects, etc... With the help of @thdxr shortly after Auth's launch I managed to work around this limitation but I've since a new scenario where this feature would make things a little easier/cleaner to design and handle.

## Potential Solution

When I initially came up against this I was looking at how we could get access to the query string in the `callback` handler and came up with [this](https://discord.com/channels/983865673656705025/985224097342582865/1015554382386966568) but there's probably a cleaner way of doing this.

## Notes

My original message/stream-of-consciousness [in Discord](https://discord.com/channels/983865673656705025/985224097342582865/1015519595630702673)

User [tlmander's message](https://discord.com/channels/983865673656705025/991751731824308344/1023343173520597002) that prompted me opening this feature request.

**Comment by JannikWempe** [comment]
This is what I did:

```typescript
let redirectUri: string | null = null;

export const handler = (request: APIGatewayProxyEventV2, context: Context) => {
  if (request?.queryStringParameters?.redirect_uri) {
    redirectUri = request.queryStringParameters.redirect_uri;
  }
  
  return AuthHandler({
    providers: {
      github: GithubAdapter({
        clientID: Config.GITHUB_CLIENT_ID,
        clientSecret: Config.GITHUB_CLIENT_SECRET,
        scope: "user",
        onSuccess: async (tokenset) => {
          //...
          if (!redirectUri) {
            throw new Error("No redirect URI found");
          }

          return Session.cookie({
            redirect: redirectUri,
            // ...
          });
        },
      })
    },
  })(request, context)
};
```

That way you can pass a query param like `/auth/github/authorize?redirect_uri=http://localhost:3000/my-path`.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
