### ISSUE TITLE
Feature request: Pass static site url to it's own environment variable

### ISSUE THREAD

**Issue by patricknazar** [sst/sst#2099]
I'm using `ViteStaticSite` construct and I'd like to pass the resultant `site.url` to the site itself as an env var. I am using the `cdk` property to add an extra origin that resolves to a bucket of images. The frontend needs to access the images at `{CDN_URL}/images/{someImageFilename}`.

I've found a hacky solution using `sst start --outputs-file outputs.json` and modifying the `vite.config.ts` to read that and create a proxy but it's not pretty or robust. It also makes testing harder as fetch in node doesn't support relative URLs. As of this moment the only way I can think of achieving this without that hacky stuff is by using the `customDomain` property but it's still fairly manual and not great when using lots of different environments.

Perhaps someone has a cleaner solution to my problem or can suggest a better way of doing it.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
