### ISSUE TITLE
API custom domain and Hosted Zone deployment dependency

### ISSUE THREAD

**Issue by felipevyg** [sst/sst#2107]
I noticed that you cannot create a hosted zone and use it as a custom domain in an API in the same deployment run.

I have an API stack and a Domain stack. The API stack creates an Api construct and has customDomain set.
The Domain stack creates that hosted zone used by the API stack.

When I run the deployment, it makes a look up for the domain in Route53, and obviously can't find it, so it fails the deployment. Even though the Domain stack would create the zone.

The solution was to first deploy the Domain stack, then add a customDomain in the API. It's understandable but breaks CI/CD since it makes sense to create a single change set that adds a hosted zone and use it in the same PR, for example.

Notes:
The Domain stack is created before the API stack during deployment.

**Comment by fwang** [comment]
Hey @felipevyg, can u try pass the created hosted zone into NextjsSite's `customDomain.cdk.hostedZone`?

**Comment by felipevyg** [comment]
@fwang Thanks for the reply. I'm not using NextjsSite.

The HostedZone is created like this:

```javascript
export const DomainStack = ({ stack }: StackContext) => {
  const API_DOMAIN = process.env.API_DOMAIN
  if (!API_DOMAIN) throw new Error('API_DOMAIN must be provided')

  const hostedZone = new HostedZone(stack, 'api-hosted-zone', {
    zoneName: API_DOMAIN,
  })

  return {
    hostedZone,
    API_DOMAIN,
  }
}
```

In the main app, `app.stack(DomainStack)` is called before `app.stack(APIStack)`.
Then in the APIStack I run:

```javascript
// inside the stack:
const { API_DOMAIN } = use(DomainStack)

new Api(stack, 'api', {
    customDomain: {
      domainName: `api.${API_DOMAIN}`,
      hostedZone: API_DOMAIN,
    },
})
```

**Comment by fwang** [comment]
Ah, sorry. Try this:
```ts
// inside the stack:
const { hostedZone, API_DOMAIN } = use(DomainStack)

new Api(stack, 'api', {
    customDomain: {
      domainName: `api.${API_DOMAIN}`,
      cdk: {
        hostedZone,
      },
    },
})
```

**Comment by felipevyg** [comment]
That's interesting, thank you for your help. 
Can't test right now, but does that mean that I don't need to create the HostedZone manually (via `new HostedZone(...)`)?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
