### ISSUE TITLE
Allow use of Config in cjs lambda

### ISSUE THREAD

**Issue by camsloanftc** [sst/sst#2119]
It would be great to have the option to use Config.Secret within my lambdas that are stuck in cjs without the option to switch them over to esm (due to downstream modules not being compatible). The top-level await seems to be the main blocker.

I tried a few workarounds, and ended up needing to just put the env variables into my CI/CD platform and using them that way (by passing them into the function environment directly).

Another option that would be helpful:
I thought I could maybe just go fetch them from SSM in the construct like below:

```typescript
const DATABASE_URL_VALUE = StringParameter.valueFromLookup(
  stack,
  `/sst/${SST_APP}/${SST_STAGE}/secrets/${DATABASE_URL.name}`
);
```

and it _almost_ works, except the value is encrypted. So if there was some utility to decrypt this, I could just pass the values directly into the lambda function, but then keep them within the config setup so other esm lambdas could still use Config as intended.

**Comment by art049** [comment]
Totally need this as well!
The Config handling looks amazing but I can't use it as I'm also stuck in CJS for now.

@fwang Would you be ok to add the feature if I find some time to implement it?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
