### ISSUE TITLE
Python Function: help dealing with Lambda size limitations

### ISSUE THREAD

**Issue by fwang** [sst/sst#2120]
Patrick:
> I found in a serverless package that may be useful as bundling props in SST: https://www.npmjs.com/package/serverless-python-requirements#dealing-with-lambdas-size-limitations
> custom removal patterns and package omission settings
> This is something that I think can be done in bundle command, but would be nice if it was baked in

---
Requests
- Patrick https://discordapp.com/channels/983865673656705025/1015442812751327353/1025182138053705758

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
