### ISSUE TITLE
.env.local is used when deploying to other stages

### ISSUE THREAD

**Issue by dmueller39** [sst/sst#2122]
Adding an .env.local file and setting environment variables works as expected when using the local development tools. Running `yarn start` uses this file correctly. However what was unexpected was that if you run an `npx sst deploy --stage staging` locally, then it uses .env.local for the environment variables as well.

I am not certain what the best solution is here, but if the above is expected behavior, it might make sense to warn/log/announce that a local .env file is being used instead of the one that is committed. It probably would have saved me a few hours of debugging.

```
~/myapp $ npx sst deploy --stage staging
Using stage: staging
Using environment file: .env.local
```

**Comment by dmueller39** [comment]
Re-reading the docs, I realize that it was explained pretty well there. NVM!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
