### ISSUE TITLE
CLI: allow hooking into SST deployment cycle

### ISSUE THREAD

**Issue by fwang** [sst/sst#2123]
### Use cases
- Run scripts after `sst start` is started up

---
Requests
- rubythulhu https://discordapp.com/channels/983865673656705025/1024842578778132520
- @cmaycumber https://github.com/serverless-stack/sst/issues/527

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
