### ISSUE TITLE
Function: support .NET 6.0 minimal APIs

### ISSUE THREAD

**Issue by fwang** [sst/sst#2124]
Reference:
- https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/

---
Requests
- vegardb https://discordapp.com/channels/983865673656705025/1026826873805746236

**Comment by dex2dot0** [comment]
@fwang I have been looking at adding support and moving towards submitting a PR. There is currently a bootstrap project that is used https://github.com/serverless-stack/sst/tree/master/packages/sst/support/dotnet6-bootstrap. I can bypass that locally and get everything to work as expected but didn't know if the bootstrap was important to something SST was doing?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
