### ISSUE TITLE
Can't run tests against stacks using Jest with tests transformed to CJS 

### ISSUE THREAD

**Issue by AshHeskes** [sst/sst#2130]
When trying to setup jest to run tests against SST stack code with the code being transformed to CJS fails with:

```
node_modules/@serverless-stack/core/dist/util/paths.js:38
    const __dirname = import_url.default.fileURLToPath(new URL(".", import_meta.url));
          ^

    SyntaxError: Identifier '__dirname' has already been declared

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/@serverless-stack/core/dist/util/index.js:2:24)
```

The crux is that you try to hack the lack of `__dirname` in ESM by creating your own. However in a CJS environment `__dirname` is already declared and thus the code breaks. A simple fix would be to use a different var name.

So this breaks testing using Jest with CJS modules and due to https://github.com/serverless-stack/sst/issues/1735 using Jest with experimental ESM modules also fails.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
