### ISSUE TITLE
sst start: support AppConfig extension

### ISSUE THREAD

**Issue by fwang** [sst/sst#2136]
AppConfig extension is a Lambda layer. To support it, `sst start` needs to:
- download & unzip the layer
- set the `NODE_PATH` to the layer folder
- hook it up with local Runtime API

---
Requests
- Harish https://discord.com/channels/983865673656705025/983865673656705028/1029669599236599818

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
