### ISSUE TITLE
[Graphql] Post creation SST native graphql implementation guide

### ISSUE THREAD

**Issue by piccinnigius** [sst/sst#2137]
Hi all,
the project is awesome, thanks so much for your work.
I'm new to the GRAPHQL World, there is any tutorial on how to setup the starter graphql template on an existing project?
 (not the apollo or appsync ones)

Thanks in advance
Giuseppe

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
