### ISSUE TITLE
ApiGatewayV1Api: cannot Importing an existing API Gateway custom domain

### ISSUE THREAD

**Issue by juiwenchen** [sst/sst#2139]
Dear SST team, 
First of all, thanks to make this amazing project open source.

I would like to create `RestApi` with the `custom domain` which already exists in ApiGateway by using the construct `ApiGatewayV1Api`. 

I took the following example, but SST reported the error` [AWS::ApiGateway::BasePathMapping] is missing required property: domainName.`

[importing-an-existing-api-gateway-custom-domain](https://docs.sst.dev/constructs/ApiGatewayV1Api#importing-an-existing-api-gateway-custom-domain)

It seems  `domainName` in `ApiGatewayV1ApiCustomDomainProps` is optional in the source code, but it complains somehow if it's not given. 

I would expect to be like the given example in the SST docs. What do you think? 

sst --version
SST: 1.15.13
CDK: 2.39.1

Thank you

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
