### ISSUE TITLE
Set `IS_LOCAL` env var when running `sst remove`

### ISSUE THREAD

**Issue by AshHeskes** [sst/sst#2145]
When running the CLI command `sst remove` the `IS_LOCAL` env var is not set when remove is using local as the stage. This causes errors removing some resources that depend on the presence of `IS_LOCAL` to manage resource configuration.

In my case I have a static site with

```js
'cdk' : {
    'bucket' : { 'removalPolicy' : IS_LOCAL ? RemovalPolicy.DESTROY : RemovalPolicy.SNAPSHOT },
},
```

When trying to remove local SST errors with `Error: Cannot use 'autoDeleteObjects' property on a bucket without setting removal policy to 'DESTROY'.` as `IS_LOCAL` is `undefined`.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
