### ISSUE TITLE
Question: Is it possible to use cloudflare WAF with a nextjs site deployed with sst?

### ISSUE THREAD

**Issue by dgokcin** [sst/sst#2148]
Hello

We have been looking for a way to deploy a next.js app and came across to this project after experimenting with vercel, terraform-aws-nextjs, amplify and serverless-nextjs. For various reasons, none of them was a good fit for our use in production. I was wondering if it is possible to benefit from cloudflare's CDN while using sst for a SSR nextjs app.

Thanks!

**Comment by fwang** [comment]
Hey @dgokcin, apart from SSR, are there other Nextjs features u need? ie. ISG, image optimization, middleware

**Comment by truecolintracy** [comment]
Yes, we actually have this setup. There's a few things to setup with Cloudfront and Cloudflare, but I have this setup to allow Cloudflare to handle the WAF and security for our nextjs application.

**Comment by tabuchid** [comment]
@truecolintracy Could you provide some of the details? I'm having issues currently with a sst api I'm trying to setup behind cloudflare and I'm getting 403s

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by nileshtrivedi** [comment]
@thdxr I'm confused. Why does this repo has the latest release marked as [v3.17.14](https://github.com/sst/sst/releases) but the v2 repo has it an older version as [v2.49.4](https://github.com/sst/v2/releases/tag/v2.49.4)?

Is this repo not being transitioned to v2 repo anymore as you wrote above?

**Comment by jayair** [comment]
It already has been. v2 used to be in this repo and has been moved away.
