### ISSUE TITLE
Merge default function props

### ISSUE THREAD

**Issue by art049** [sst/sst#2154]
Currently, when using `app.setDefaultFunctionProps` the docs mentions:
> These default values will be overridden if a Function sets its own props. This needs to be called before a stack with any functions have been added to the app.

I think it would be very helpful to have an option allowing merging the defaultFunctionProps with the function-specific props. Using something with the same behavior as [lodash.merge](https://lodash.com/docs/4.17.15#merge)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
