### ISSUE TITLE
 Improve environment variables doc quickstart example

### ISSUE THREAD

**Issue by tlcheah2** [sst/sst#2158]
## Problem

![Screenshot 2022-10-23 at 2 12 32 PM](https://user-images.githubusercontent.com/7456033/197377054-85084023-8e9c-49b1-bd52-c435f01725f3.png)

The quickstart guide step 2 will mislead beginners. Adding the `api` code to finish the whole example would provide more clarify and better understand. For e.g,

```
  const myFunction = new Function(stack, "MyFunction", {
    handler: "lambda.handler",
    config: [STRIPE_KEY, GITHUB_TOKEN],
  });

  const api = new Api(stack, "api", {
   routes: {
     "GET /notes": myFunction,
   },
  });
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
