### ISSUE TITLE
Twitch OIDC provider returns HTTP 500 in /callback 

### ISSUE THREAD

**Issue by adarah** [sst/sst#2162]
Hi, first time SST user here. I'm trying to setup Twitch as a OIDC provider following the [Auth guide](https://docs.sst.dev/auth), and `/callback` seems to be returning status code 500 due to "Missing body".
The [Twitch docs](https://dev.twitch.tv/docs/authentication/getting-tokens-oidc) say this about the callback response:
> If the user authorized your app by clicking Authorize, the server sends the access token and ID token to your redirect URI in the fragment portion of the URI (see the access_token and id_token parameters)

And that's also what I observed, after granting the authorization, I was redirected to: `mydomain.com/auth/twitch/callback#id_token=eyJ...` (there's no access_token since `/authorize` seems to use the `response_type=id_token` param)

So the id_token is present as expected, but it seems to not be handled correctly.

**Comment by tobyspark** [comment]
I hit the same. `TwitchAdapter` should be fixed or removed.

Notwithstanding that, the `OauthAdapter` can be used. Getting that working took some investigation, but I now have `onSuccess` returning access tokens. Here’s the hard-won comment from my code –
```
// The following is the result of `await Issuer.discover('https://id.twitch.tv/oauth2')` with one crucial difference: `userinfo_endpoint` is ommited.
// Currently, SST's OauthAdapter choses between the OpenID client's `callback` and `oauthCallback` based on the presence of `userinfo_endpoint`.
// Understanding why would take some investigation, but the upshot is we want `oauthCallback`, which requires some level of completeness beyond options having the three fields as per SST docs, hence `discover`. But to get `oauthCallback` we need `userinfo_endpoint` to be falsy.
```

**Comment by fwang** [comment]
Thanks for sharing Toby!

Will prioritize this.

The Twitch adapter and the other social adapters are thin wrappers around
the OauthAdapter. You can use the Oauth adapter in the meantime.

Frank

--
<https://seed.run/>
Founder at SST <https://sst.dev>

SST <https://github.com/serverless-stack/serverless-stack> - OS framework
for building serverless apps
SEED <https://seed.run/> - Deploy, manage, and monitor serverless apps

**Comment by angie** [comment]
@tobyspark's comment helped me start to debug. I finally settled on the below to get a Twitch auth provider set up.

```typescript
import { Issuer } from "openid-client";
import { AuthHandler, OauthAdapter } from "sst/node/auth";
import { Config } from "sst/node/config";

export const handler = AuthHandler({
  providers: {
    twitch: OauthAdapter({
      clientID: Config.TWITCH_CLIENT_ID,
      clientSecret: Config.TWITCH_CLIENT_SECRET,
      issuer: await Issuer.discover("https://id.twitch.tv/oauth2"),
      scope: "some scopes here",
      onSuccess: async (tokenset) => {
        return {
          statusCode: 200,
          body: JSON.stringify(tokenset.claims()),
        };
      },
    }),
  },
});
```

Dropping here in case anyone else gets stuck 😸

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
