### ISSUE TITLE
Upgrade Apollo Server example to use Apollo Server 4 and new AWS integration package. 

### ISSUE THREAD

**Issue by mauricedmarx** [sst/sst#2163]
SST has an Apollo Server example using Apollo Server 3 with the apollo-server-lambda package. It would be nice to upgrade the example to use [Apollo Server 4](https://www.apollographql.com/docs/apollo-server/) and the new [AWS integration package](https://www.npmjs.com/package/@as-integrations/aws-lambda).

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
