### ISSUE TITLE
Error "Please install pg package manually"

### ISSUE THREAD

**Issue by czarnndz** [sst/sst#2169]
I'm getting below error in CLoudWatch when I did deploy my aplication to staging stage.

![image](https://user-images.githubusercontent.com/7936586/199316057-c86e5987-c376-4733-a879-9439bf7437be.png)

I'm using sequelize as ORM, but in local dev it works normally, I tried to add pg as nodeModule option in the index 
![image](https://user-images.githubusercontent.com/7936586/199316929-85fd5778-0bba-45a9-acee-9b0bbce0a1ed.png)

but when I tried to build it never finish.
![image](https://user-images.githubusercontent.com/7936586/199317209-117321ec-7a0a-4d20-8b6e-80e2518560f9.png)

Hope someone can help me with this issue.

Thanks and regards

**Comment by jayair** [comment]
Hmm I don't know if I've seen this issue before. Is this an edge function btw?

**Comment by czarnndz** [comment]
> Hmm I don't know if I've seen this issue before. Is this an edge function btw?

No is not, it's a normal lambda function.

This is the code of the function:
![image](https://user-images.githubusercontent.com/7936586/199646240-e0aa361d-a90f-4aa5-8d2c-99a4415842fc.png)

**Comment by thdxr** [comment]
This is likely fixed in v2 but need you to give it a try

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
