### ISSUE TITLE
setDefaultRemovalPolicy overrides policy configured at resource level

### ISSUE THREAD

**Issue by fwang** [sst/sst#2190]
### What's the issue?
Currently, the removal policy for the table is set to `DESTROY`, despite it is specifically set to `RETAIN` at the resource level.

```ts
  app.setDefaultRemovalPolicy("destroy");
  new Table(stack, "table", {
    cdk: {
      table: {
        removalPolicy: RemovalPolicy.RETAIN,
      }
    }
  });
```

### Fix
CDK automatically sets the removal policy for `dynamodb.Table` to `RETAIN`. We need to figure out a way to disguise those that set by CDK by default vs those set by user manually.

---
Requests:
- Mayowa https://discord.com/channels/983865673656705025/1029452029174747327/1038439662051659809

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
