### ISSUE TITLE
Build of minimal-java example with DEBUG=1 produces hex output

### ISSUE THREAD

**Issue by mgranell** [sst/sst#2192]
When DEBUG=1 is set, trying to build minimal-java example, output is:

SST: 1.15.11
CDK: 2.39.1
Determining if we're on an EC2 instance.
Does not look like an EC2 instance.
Using stage: martin
Preparing your SST app
Synthesizing CDK
synth {
  app: 'node .build/run.mjs',
  output: '.build/cdk.out',
  rollback: undefined,
  roleArn: undefined,
  verbose: 0,
  noColor: false
}
[dotenv][DEBUG] did not match key and value when parsing line 1: # These variables are only available in your SST code.
[dotenv][DEBUG] did not match key and value when parsing line 2: # To apply them to your Lambda functions, checkout this doc - https://docs.serverless-stack.com/environment-variables#environment-variables-in-lambda-functions
[dotenv][DEBUG] did not match key and value when parsing line 3: 
[dotenv][DEBUG] did not match key and value when parsing line 5: 
CPU cores 8
buildAsync spawning: gradle build -Dorg.gradle.project.buildDir=/Users/martin/github/sst/examples/minimal-java/.sst/artifacts/martin-minimal-java-MyStack-api-Lambda_GET_-/services/api.Handler-handleRequest -Dorg.gradle.logging.level=debug
<Buffer 32 30 32 32 2d 31 31 2d 31 32 54 31 32 3a 33 38 3a 31 32 2e 37 37 31 2b 31 31 30 30 20 5b 49 4e 46 4f>
<Buffer 5d 20 5b 6f 72 67 2e 67 72 61 64 6c 65 2e 69 6e 74 65 72 6e 61 6c 2e 6e 61 74 69 76 65 69 6e 74 65 67 72 61 74 69 6f 6e 2e 73 65 72 76 69 63 65 73 2e ... 77 more bytes>
<Buffer 32 30 32 32 2d 31 31 2d 31 32 54 31 32 3a 33 38 3a 31 32 2e 38 31 31 2b 31 31 30 30 20 5b 49 4e 46 4f 5d 20 5b 6f 72 67 2e 67 72 61 64 6c 65 2e 69 6e ... 48 more bytes>
<Buffer 5d 20 49 6e 69 74 69 61 6c 69 7a 65 64 20 6a 61 6e 73 69 20 73 65 72 76 69 63 65 73 20 69 6e 3a 20 2f 55 73 65 72 73 2f 6d 61 72 74 69 6e 2f 2e 67 72 ... 12 more bytes>
<Buffer 32 30 32 32 2d 31 31 2d 31 32 54 31 32 3a 33 38 3a 31 32 2e 38 34 36 2b 31 31 30 30>
<Buffer 20 5b 4c 49 46 45 43 59 43 4c 45 5d 20 5b 6f 72 67 2e 67 72 61 64 6c 65 2e 6c 61 75 6e 63 68 65 72 2e 63 6c 69 2e 44 65 62 75 67 4c 6f 67 67 65 72 57 ... 389 more bytes>
<Buffer 32 30 32 32 2d 31 31 2d 31 32 54 31 32 3a 33 38 3a 31 33 2e 31 34 39 2b 31 31 30 30 20 5b 44 45 42 55 47>
...

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
