### ISSUE TITLE
SST Console / API - Failed to fetch due to incorrect URL.

### ISSUE THREAD

**Issue by Newbie012** [sst/sst#2207]
Given the following URL:

```
api.addRoutes(context.stack, {
  "POST /chats/{id}/message": { type: "function", function: "..." }
});
```

I'm getting "Failed to fetch" in the console:

![image](https://user-images.githubusercontent.com/10504365/202904243-8dc22d70-a9be-42e2-ba17-8e885cad2bfa.png)

It turns out that the URL that is being generated has a double slash between the API URL and the endpoint:

```
https://x.execute-api.eu-central-1.amazonaws.com//chats/123/message
                                                 ^
```

I believe the logic behind is here:

https://github.com/serverless-stack/sst/blob/0de07efcd12fb5ea0f0c87ffd6f6220a2b66f968/packages/console/src/App/Stage/Api/index.tsx#L214-L233

I'm not sure how (or if) it works for everyone else. If needed, I can push a PR to fix it.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
