### ISSUE TITLE
Layer at function level does not attach to lambda automatically

### ISSUE THREAD

**Issue by bardzh** [sst/sst#2208]
After adding a layer to the API route function, I can see that the layer is being created and built but isn't attached to lambda on `sst start` . this is the setup.

```js
const api = new Api(stack, "api", {
    routes: {
      "GET /{path+}": {
        function: {
          handler: "functions/lambda.handler",
          bundle: {
            externalModules: ["sharp"],
          },
          layers: [
            new lambda.LayerVersion(stack, "SharpLayer", {
              code: lambda.Code.fromAsset("layers/sharp"),
            }),
          ],
        }
      },
    },
  });
```
The layer is available in the layers tab. i tried adding `Arn` still doesn't work

<img width="1323" alt="Screenshot 2022-11-20 at 4 52 34 PM" src="https://user-images.githubusercontent.com/3595255/202928152-b6cd9d97-045f-4db3-b3c6-96c3dcfd77f5.png">

Not sure if I'm doing something wrong

**Comment by fwang** [comment]
Hey @bardzh, layers aren't loaded on `sst start`. Is `sharp` in ur local `node_modules`? You don't need to load it from the layer right?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
