### ISSUE TITLE
Resource binding: allow customizing IAM permissions

### ISSUE THREAD

**Issue by fwang** [sst/sst#2210]
Akos suggested:
> maybe like how permissions are done, i.e. you can pass one of the CDK methods of 'grantReadWrite' or 'grantRead'?

---
Requests:
- Akos https://discord.com/channels/983865673656705025/983866416832864350/1042492439295971348

**Comment by fezproof** [comment]
Would love to see this, as resource binding is super cool but currently is a bit too permissive.
An API like this would be pretty nice and not that different from permissions.
```typescript
    bind: [[dataTable, 'grantRead'],  [storageBucket, 'grantReadWrite']],
```

**Comment by jayair** [comment]
@fwang bringing this up.

**Comment by fwang** [comment]
In v2.40.4, instead of
```ts
site.bind([bucket]);
```
Permissions can be customized like this:
```ts
site.bind([
  { resource: bucket, permissions: [{ actions: ["s3:GetObject"], resources: [`${bucket.arn}/*`] }] }
]);
```
