### ISSUE TITLE
Feature Request: Support typePaths for Config

### ISSUE THREAD

**Issue by bestickley** [sst/sst#2218]
## What?
Similar to how ViteStaticSite supports [typePaths](https://docs.sst.dev/constructs/v0/ViteStaticSite#typespath) where you can customize where the types of your env vars are written, I'm requesting the same feature for [Config](https://docs.sst.dev/config#overview).

## How?
It would be nice to be able to specify this at both the individual parameter or secret level and at the stack level. So maybe add property `typePath` for [Config.Parameter](https://docs.sst.dev/constructs/Parameter) and [Config.Secret](https://docs.sst.dev/constructs/Secret) and then `configTypePath` for stack?

## Why?
I use a PNPM monorepo for developing full-stack serverless web apps with SST. I typically have a core, ui, and infra package for each app or domain I'm building which is all within the same monorepo. Each package has it's own node_modules and not all node_modules are hoisted to the top level like npm. Currently, SST depends on a hoisted node_modules directory because the types are written to the same node_modules directory of the package where the infrastructure is defined which for PNPM monorepo setup isn't the same node_modules folder as my core business logic where I want intellisense on my configuration environment variables.

**Comment by fwang** [comment]
Hey @bestickley, yeah writing the types to `node_modules` has caused a lot of problems. In SST v2, the types will be generated within the repo by default, in the `.sst` folder I think.

@thdxr can u confirm? Also will u be able to override the default path?

**Comment by thdxr** [comment]
In sst 2.0 it will generate to .sst/types

we can provide a way to override this path but let me know if that doesn't work for you

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
