### ISSUE TITLE
SST Console doesn't update

### ISSUE THREAD

**Issue by davidrhoderick** [sst/sst#2227]
**Current behavior**

When I change my stacks, for example, if I change my DDB table structure and name and API routes, the SST Console shows the original structure and name.

**Expected behavior**

When I change my stack's DDB table name and structure and API routes, I expect to see them changed in the SST Console.  The SST Console makes it easy to test and debug and because it doesn't update, I'm forced to manually test using `curl` etc. in terminal.

**Steps to reproduce**

1. Create a stack with a DynamoDB and API routes.
2. Deploy it.
3. Then change the DynamoDB table name and structure.  Change the API routes.
4. Re-deploy it.
5. Notice how the Console has the old table name, structure, and API routes.

**Stack code**

```
import { StackContext, Api, use } from '@serverless-stack/resources';

import { StorageStack } from './storage-stack';

export function ApiStack({ stack }: StackContext) {
  const { table } = use(StorageStack);

  const api = new Api(stack, 'Api', {
    defaults: {
      function: {
        permissions: [table],
        environment: {
          TABLE_NAME: table.tableName,
        },
      },
    },
    routes: {
      'POST /user': 'functions/updateUser.main',
      'GET /user/{userId}': 'functions/getUser.main',
      'DELETE /user/{userId}': 'functions/deleteUser.main',
    },
  });

  stack.addOutputs({
    ApiEndpoint: api.url,
  });

  return { api };
}
```
**SST Console**
![image](https://user-images.githubusercontent.com/2300366/204316082-edcf7160-c39a-45bf-962b-1f4e379dc8e1.png)
**AWS Functions**
![image](https://user-images.githubusercontent.com/2300366/204316222-ff477ebe-4f70-4b7a-844d-1fe9c424714d.png)

**Here's what I already tried**
1. `npx sst remove` (all and any stages deployed).
2. Deleting all resources in AWS; CloudFormation, DynamoDB, and S3.
3. `npm start`
4. Resetting AWS credentials file.

**Comment by alistairstead** [comment]
Is your console connected to the same stage?

You use the word 'deploy', which suggests you are running a complete deployment rather than starting the local development stage. The console, by default, connects to the local stage. 

## My workflow:

1. `yarn start` (the initial output includes a URL to open the console for this stage)
2. open the console URL from step 1, wait for the console to sync, and show all the resources and outputs from this stage.
3. make changes to stacks
4. the shell where I ran `yarn start` will notice the stack changes and prompt "Stacks: There are new infrastructure changes. Press ENTER to redeploy." this rebuilds the stacks that have been modified. Once this has been completed, the console will reflect the changes. 

If you want to connect the console to a specific stage, you need to specify that in the  command e.g. `yarn sst console --stage production`

Hope this helps.

**Comment by davidrhoderick** [comment]
Thanks @alistairstead for the help (and on Discord).  As per our debugging, just wanted to post an update here:

Today, I tried to updating SST to 1.18 and that required a couple code changes as per the migration guide but didn't help otherwise (although `bind` is going to be _very_ useful in the future).

What _did_ help was changing the local stage.  I was able to successfully see the latest version of my application in the SST Console on a different stage by using `npx sst console --stage development`.  That made me wonder about changing the local `stage` file in the `.sst` directory.  I added `-2` to the stage name and was able to get the latest version of my application.  However, when I made a change to that version and ran `npm start` again, the change was not present.

To my eyes, it looks like the stage is just "snapshotting" whatever state the app is when it is initiated and not updating the stacks after changes, even after synthesizing the changes and triggering the rebuild via the CLI (or even completely tearing everything down manually before rebuilding).

**Comment by davidrhoderick** [comment]
Latest update is that I was able to append `-1` to my stage name after updating 1.18 and for some reason, now the Console is working as expected.  I'm not exactly sure what is working; perhaps I had errors before when I'd redeploy but didn't notice them.  I guess I'll close this for now and come back to it if it persists.

**Comment by davidrhoderick** [comment]
Looks like this has happened again although I think I might have stumbled across the trigger.

I moved from one computer to another computer and I'm using the same stage `david-vrio-com-1`.  My code shows the new update to add a route:

```
routes: {
  'PUT /user/{userId}': 'functions/updateUser.main',
  'GET /user/{userId}': 'functions/getUser.main',
  'DELETE /user/{userId}': 'functions/deleteUser.main',
  'GET /campaigns': 'functions/listCampaigns.main',
},
```
And I can see in CloudFormation that the route is there:
![image](https://user-images.githubusercontent.com/2300366/205444795-990a29cc-946b-4f51-bca4-17e0ed4a41ce.png)
And I even see an error in the SST CLI from hitting the API endpoint:
```
1bc939d6-5231-4cf1-b9b3-d1054cb98d6e ERROR TypeError: Invalid URL 
 TypeError [ERR_INVALID_URL]: Invalid URL
```
However, that endpoint doesn't show in the SST Console.  I will create a new stage and see if I can fix the issue that way but perhaps using the same stage name on multiple computers is the issue.

**Comment by davidrhoderick** [comment]
Looks like this has happened again although I think I might have stumbled across the trigger.

I moved from one computer to another computer and I'm using the same stage `david-vrio-com-1`.  My code shows the new update to add a route:

```
routes: {
  'PUT /user/{userId}': 'functions/updateUser.main',
  'GET /user/{userId}': 'functions/getUser.main',
  'DELETE /user/{userId}': 'functions/deleteUser.main',
  'GET /campaigns': 'functions/listCampaigns.main',
},
```
And I can see in CloudFormation that the route is there:
![image](https://user-images.githubusercontent.com/2300366/205444795-990a29cc-946b-4f51-bca4-17e0ed4a41ce.png)
And I even see an error in the SST CLI from hitting the API endpoint:
```
1bc939d6-5231-4cf1-b9b3-d1054cb98d6e ERROR TypeError: Invalid URL 
 TypeError [ERR_INVALID_URL]: Invalid URL
```
However, that endpoint doesn't show in the SST Console.  I will create a new stage and see if I can fix the issue that way but perhaps using the same stage name on multiple computers is the issue.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
