### ISSUE TITLE
API request returns 503 while script is still running

### ISSUE THREAD

**Issue by ankitmishra88** [sst/sst#2232]
Sometime api call return early with a status 503 code, but when I see the console, I find lambda function is still running, but it's just API that has returned early with a status code 503 and message "Service Unavailable".

Is there a way to fix it or if it is a known issue?

**Comment by joshstrange** [comment]
I'm seeing this as well. It appears that if I kick of like 4+ requests at the same time to my API that 1-2+ of them will timeout and throw the Service Unavailable message.

I think is the same issue seen here: https://github.com/serverless-stack/sst/issues/341

**Comment by disbelief** [comment]
I believe this "503 Service Unavailable" error is originating from API Gateway itself. From what I've read, API Gateway has a hard limit of 30 seconds for any lambda function (this is not configurable).

So your lambda could still be happily chugging along but the API Gateway has already given up and shown an error to your user.

**Comment by ankitmishra88** [comment]
@disbelief yes that's correct.
@joshstrange same goes for 4+ requests case at same time, when our local server gets parallel 4+ requests, same machine handles it which makes it slower , but when it's for deployed, different lambda instance handles it.

**Comment by disbelief** [comment]
Is there a proposed solution/workaround for this? Ideally SST would fork multiple processes to handle concurrent requests/events

**Comment by jayair** [comment]
I mean it handles concurrent requests fine. Is the issue that these requests are timing out?

**Comment by ankitmishra88** [comment]
> Is there a proposed solution/workaround for this? Ideally SST would fork multiple processes to handle concurrent requests/events

@disbelief as this is issue with API gateway, SST doesn't do anything as of now. One workaround what I implemented which helps app in production too is,

I send a `request_id` let's say uuidV4 along with api, and save the response before returning from lambda along with that `request_id` for a short time in db as Transient. And if request has returned a 503, I retry to get the value of that pending response using that `request_id` . Let's say `GET /pending-response/<request_id>`

**Comment by ankitmishra88** [comment]
> I mean it handles concurrent requests fine. Is the issue that these requests are timing out?

yes, the lambda is taking more than 30sec

**Comment by disbelief** [comment]
> I mean it handles concurrent requests fine. Is the issue that these requests are timing out?

They're timing out _because of_ the way SST handles concurrent operations (ie. other requests or EventBus handlers) in development.

An app with any amount of concurrency (multiple requests, Event Bus triggers, etc) is likely to encounter this, as things tend to run a bit slower in development than in production and everything is executed by a single process.

**Comment by disbelief** [comment]
@ankitmishra88 

> > Ideally SST would fork multiple processes to handle concurrent requests/events
> 
> I don't think, this would also work. What in case if single lambda is taking more than 30sec to complete? That would anyway fail and return 503

There isn't much that can be done about a single request taking longer than 30 seconds, and in situations where that is the case, your solution (storing result in db and refetching) is a pretty cool workaround.

The problem is handling concurrent requests (or event bus triggers) with a single process slows down _all_ of the requests, making the 30 second timeout far more likely. Multiple processes would resolve this.

**Comment by jayair** [comment]
That's really strange that it does that. @disbelief can you put together a repo that we can reproduce it with?

**Comment by disbelief** [comment]
I can try to find some time to do that.

Here's a very high-level overview of my project in the meantime:

1. Receive API request from user
2. Query database ~0.5s
3. Perform business logic ~5-10s
4. Write to database ~1-2s
5. Emit EventBus events (eg. "message.created") ~0.1s
6. Prepare API response ~0.2-0.5s
7. Respond to user ~0.1s

At step 5, some EventBus handlers execute and slow down the remaining steps. There are typically 1-3 EventBus handlers, depending on scenario, and they tend to execute in ~5s
