### ISSUE TITLE
Request: Add example authenticated tests using Session.create

### ISSUE THREAD

**Issue by patricknazar** [sst/sst#2234]
As per [the auth docs](https://docs.sst.dev/auth#create-a-token) you can create a token directly without using a redirect. I noticed that there is no real-world example of this, and I would like there to be one. In particular I want to understand:

* How to use Auth in tests, with actual test examples that actually run.
* The recommended way to keep prod from getting accidental auth backdoor if tests create one?
* How this plays together with `Session.cookie`
* Make this all automated. No creating users or hardcoding passwords. Does that even make sense?

**Comment by jayair** [comment]
Yeah we should. @fwang I think we need to add to the examples with this.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
