### ISSUE TITLE
Default region to .aws/config

### ISSUE THREAD

**Issue by EddyDavies** [sst/sst#2237]
Every time I run `npx create-sst` the AWS region is `sst.json` gets set to `us-east-1`. Would it be possible to make this pull the default region from the` .aws/config` file that sets the defaults for the AWS CLI?

```
[default]
region = eu-west-2
output = json
```

Thanks

**Comment by fwang** [comment]
Thanks @EddyDavies.

Lemme pull in @thdxr. Dax, in SST v2, u can set the AWS profile to use in sst config. Should the region in profile override the region in sst config?

**Comment by ruchernchong** [comment]
> Thanks @EddyDavies.
> 
> Lemme pull in @thdxr. Dax, in SST v2, u can set the AWS profile to use in sst config. Should the region in profile override the region in sst config?

We get this. But it would be good if we could do a global config for it.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
