### ISSUE TITLE
[Unit Test] How to test Attaching permissions

### ISSUE THREAD

**Issue by duyquan238** [sst/sst#2238]
I have Nextjs Site stack and give it attached permission to access the S3 bucket and DynamoDB. How can I write the unit test to test this permission? I am also following the SST testing document but I don't know which [CloudFormation resource definitions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html) which has properties will stand for this permission. Does anyone have any ideas? Please help me solve this.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
