### ISSUE TITLE
Issue with using AWS resources from Live Lambda when behind corporate proxy

### ISSUE THREAD

**Issue by miman** [sst/sst#2244]
Hi, We have an issue when accessing a DynamoDb from a Live Lambda when behind a corporate proxy.
fyi: Our company inserts it's own certificate in the communication chain.
We have set http_proxy & https_proxy in our OS, but the Lambda doesn't seem to use that.
When running the code on another computer outside the corporate network everything works fine.

The local lambda is called ok, but the error occurs when it tries to access other AWS cloud resources, like the DynamoDb.
We get the following error:
*Error: self signed certificate in certificate chain    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)    at TLSSocket.emit (node:events:390:28)    at TLSSocket._finishInit (node:_tls_wrap:944:8)    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {code: 'SELF_SIGNED_CERT_IN_CHAIN', $metadata: {…}, stack: 'Error: self signed certificate in certificate…Trampoline (node:internal/async_hooks:130:17)', message: 'self signed certificate in certificate chain'}
*
Any hints on how to force the Live lambda code to use the proxy settings

**Comment by miman** [comment]
A typical example on how we access a DynamoDb for example would be with this code:

`private async findByPartiQlSql(sqlStatement: string): Promise<T[]> {
    try {
      const params = {
        Statement: sqlStatement,
      }
      const results: ExecuteStatementOutput = await ddbDocumentClient.send(new ExecuteStatementCommand(params));

      let entities: T[] = [];

      if (results.Items) {
        results.Items.forEach((value) => {
          // Remove DynamoDb specific members
          const { pk, sk, gsi1sk, gsi1pk, gsi2sk, gsi2pk, ...tmp } = value;
          entities.push(<T>unmarshall(tmp));
        });

        return entities;
      } else {
        logger.warn(`findByPartiQlSql did not find any entity with the given statement: ${sqlStatement}`);
        return [];
      }
    } catch (err) {
      logger.warn(`Failed to execute findByPartiQlSql with the given statment: ${sqlStatement}, Error: ${err}`);
      throw new DatabaseException(`Failed to execute findByPartiQlSql with the given statment: ${sqlStatement}, Error: ${err}`);
    }
  }`

Example statement:
`const statement = `SELECT * FROM "${this.tableName}" WHERE "pk" = '${pk}' and "sk" = '${sk}'``

**Comment by fwang** [comment]
Hey @miman, which's ur SST version?

Proxy support was added in v1.15.9.

Here's the doc on configuring proxy — https://docs.sst.dev/advanced/connecting-via-proxy

**Comment by miman** [comment]
Hi, we have the following dependencies:
`  "devDependencies": {
    "@serverless-stack/cli": "^1.18.4",
    "@serverless-stack/resources": "^1.18.4",
    "@tsconfig/node16": "^1.0.3",
    "aws-cdk-lib": "2.39.1",
    "global-agent": "^3.0.0",
    "typescript": "^4.9.4",
    "vitest": "^0.25.7"
  },
  "dependencies": {
    "@serverless-stack/node": "^1.18.4",
    "winston": "^3.8.2"
  }
`

We have set http_proxy, https_proxy & no_proxy & imported global-agent as above.

**Comment by miman** [comment]
FYI I found a way to resolve this when using Visual Studio Code:

I added the to the environment variable
NODE_TLS_REJECT_UNAUTHORIZED = 0
To the **.vscode/launch.json** file

This way the code running in VS code ignores any invalid certificate in development mode.

_**Example:**_
`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug SST Start",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/sst",
      "runtimeArgs": ["start", "--increase-timeout"],
      "console": "integratedTerminal",
      "skipFiles": ["<node_internals>/**"],
      "env": {
        "NODE_TLS_REJECT_UNAUTHORIZED": "0"
      }
    }
  ]
}
`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
