### ISSUE TITLE
Use reduced permissions with `bind`-ed constructs

### ISSUE THREAD

**Issue by cromo** [sst/sst#2247]
I read the documentation on [resource binding](https://docs.sst.dev/resource-binding) and would love to use it, but it grants full permissions on the bound resource. I prefer to ratchet my permissions as tight as they can go, especially for handlers that don't need write access to resources. Is there a way to specify the permissions when `bind`ing a construct? If there's not, could it be added, perhaps in a similar way to how `attachPermissions` works - e.g. `api.bind([[bucket, "s3:GetObject"]])`?

#2186 mentions `bind` granting all permissions on a resource, and uses `attachPermissions` as a workaround. This grants fewer permissions but does not gain all the benefits of `bind`, such as type safe access to construct properties in lambdas.

**Comment by fwang** [comment]
Got it! Adding to the roadmap!

**Comment by connorgiles** [comment]
Would also like to see this +1

**Comment by fwang** [comment]
In v2.40.4, instead of
```ts
site.bind([bucket]);
```
Permissions can be customized like this:
```ts
site.bind([
  { resource: bucket, permissions: [{ actions: ["s3:GetObject"], resources: [`${bucket.arn}/*`] }] }
]);
```
