### ISSUE TITLE
SST Console caches stack load requests and fails to add new endpoints

### ISSUE THREAD

**Issue by jannylund** [sst/sst#2248]
There seems to be a caching issue in the SST Console.

**To reproduce:**
1. Setup an sst app with an api and at least one endpoint.
2. Start the console
3. Add another endpoint. Wait for the infrastructure redeploy.

**Expected result**
- SST Console should show two endpoints.

**Actual result**
- Only the first endpoint is visible.
- Looking at the network traffic in browser developer tools, we can see that the stack is not re-fetched but loaded from cache.

**Workaround**
Either:
- Opening an private/incognito browser will show both endpoints.
- In chrome, find the stack in developer tools network view, right click and select "Clear browser cache"

The bug was discussed in SST Discord: https://discord.com/channels/983865673656705025/990989982799900792/1049656509644152842

NOTE! It is possibly the same refresh bug causing problems in https://github.com/serverless-stack/sst/issues/2227

**Comment by i-bajrai** [comment]
I am also experiencing this issue, I'm not sure what the fix is though, I've stopping and restarting then closing everything down and reopening.

Seems to clear after some time.

I will deploying to a different stage and see if that clears it.

**Comment by happyfloat** [comment]
Same issue, just added my second endpoint and running into this problem. I thought it was related to my custom function config and authorizer first... but opening the chrome console and disabling the cache it works just fine 👍 .

**Comment by XtremeAI** [comment]
+1 Still the same... requires fixing

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
