### ISSUE TITLE
Ability to configure the resource name prefix

### ISSUE THREAD

**Issue by ryands17** [sst/sst#2253]
Currently SST adds a naming convention of `${stage-name}-${app-name} ` to each resource. Is it possible to configure this or can support be added for this in the future?

**Comment by fwang** [comment]
Hey @ryands17, got it. Lemme add it to the roadmap.

Btw, do you want to configure just the stack name, or each resource (ie. function name, queue name, etc)?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
