### ISSUE TITLE
Function construct reporting wrong Runtime

### ISSUE THREAD

**Issue by CodyDunlap** [sst/sst#2254]
Our app has mostly NodeJS Lambda functions using NodeJS16.X but we also have a couple of Python3.9 functions. We've recently discovered that no matter what runtime is configured on the SST function construct, all functions report the runtime as being NodeJS16.X. 

I've tested changing the default function runtime to NodeJS14.X but all functions still report that the runtime is NodeJS16.X. The only way that I can get the other runtimes to report correctly is by circumventing the SST Function construct altogether and using the AWS CDK Function construct. 

This can be reproduced by simply creating a new SST app from the `examples/rest-api-python` template and printing the runtime of the functions in the API using the following snippet: 

```typescript
const sstStack = stack as Stack;
sstStack.getAllFunctions().forEach((f) => {
  console.log(`Runtime: ${f.runtime}`);
});
```

**Comment by fwang** [comment]
Hey @CodyDunlap, functions is first created with placeholder runtime (ie. Nodejs 16) and placeholder handler. And at the end of the build process, all `Functions` are built together in parallel and gets replaced with the real runtime+handler.

I think we can make it use the real runtime. Let me prioritize this.

Btw, can you share why you need to check the runtime?

**Comment by CodyDunlap** [comment]
Sure! We are trying to instrument our functions with monitoring tools. We've been exploring a few different tools but they all use Lambda layers to some degree to provide metrics for the function invocations. To do this well, they provide different layers for each Lambda runtime, so we need to know the runtime of each function in our SST code so that we know which Lambda Layer to attach to the function.

**Comment by tobz1000** [comment]
I believe I'm running into this issue via `getStack`. I use this in unit tests to check that template output is as expected (similar to the [example in the docs](https://sst.dev/chapters/unit-tests-in-serverless.html#testing-cdk-infrastructure)).

I'd like to check that every Function is using `nodejs18.x`, but this isn't reflected in test output.

Minimal test repro:

```ts
import { App, Function, type StackContext, getStack } from 'sst/constructs';
import { initProject } from 'sst/project';
import { Template } from 'aws-cdk-lib/assertions';
import { it } from 'vitest';

function TestStack({ stack }: StackContext): void {
  new Function(stack, 'example-function', {
    functionName: 'example-function',
    handler: './x',
    runtime: 'nodejs18.x',
  });
}

it('function runtime should be nodejs18.x', async () => {
  await initProject({});
  const app = new App({ mode: 'deploy' });
  app.stack(TestStack);
  const template = Template.fromStack(getStack(TestStack));

  template.hasResourceProperties('AWS::Lambda::Function', {
    Runtime: 'nodejs18.x',
  });
});
```

**Comment by jayair** [comment]
Are you running this against your local stage?

**Comment by tobz1000** [comment]
> Are you running this against your local stage?

@jayair In the test, the stage name `test-user` is used, i.e.:

```ts
const name = 'app-name';
const stage = 'test-user';
await initProject({ stage });
const app = new App({ mode: 'deploy', stage, name });

app.stack(...);
```

This stage name doesn't correspond to any real stack in my AWS account. I'm not sure what the implications of this are.

**Comment by jayair** [comment]
Hmm interesting. But when deployed does this set the right runtimes?

**Comment by jayair** [comment]
Interesting. We might need to dig in to see why that's happening.

**Comment by jayair** [comment]
Interesting. I'll ask the team to take a look.

**Comment by thdxr** [comment]
Did you make sure to do `await app.finish()` in your test?

**Comment by tobz1000** [comment]
> Did you make sure to do `await app.finish()` in your test?

@thdxr Thanks for the tip, this isn't mentioned in the docs.

Adding `await app.finish()` causes the error: "nodejs18.x runtime is unsupported" - so it is acknowledging the runtime setting at this point, but seems to be unsuitable for unit tests.

I also tried without specifying a non-default runtime, and still get the error "nodejs16.x runtime is unsupported"

**Comment by fwang** [comment]
@tobz1000 just updated the doc — https://docs.sst.dev/testing#testing-infrastructure

> Note that app performs several tasks asynchronously, including building the function code and container images. It then modifies the template. To ensure you are testing against the finalized resources, call await app.finish() before running any tests.

Can you share a screenshot of the error w/ more context?

**Comment by tobz1000** [comment]
@fwang Sorry to say I was testing on an old version... With sst updated to 2.29, adding `await app.finish()` fixes the test. Thanks for the help/docs.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
