### ISSUE TITLE
Support bind for Cognito

### ISSUE THREAD

**Issue by jayair** [sst/sst#2257]
- Bind Cognito to a function
- Use the `sst/node` package to access Cognito info

https://discord.com/channels/983865673656705025/1047186631498678383/1051951959646675094

**Comment by tobz1000** [comment]
This would be a really nice quality of life improvement, is it still planned?

**Comment by jayair** [comment]
We haven't gotten a ton of requests for it but I'll bring it up.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
