### ISSUE TITLE
Function Permissions Validation (Security Gap)

### ISSUE THREAD

**Issue by blytheaw** [sst/sst#2258]
Summary: It is somewhat easy to accidentally provide overly permissive permissions to a function. Ideally there would be better validation on the types of inputs supported by Permissions

Referencing [these docs](https://docs.sst.dev/constructs/Permissions) on Permissions.

We frequently use this pattern for granting permissions to constructs in our stacks:

```
permissions: [[constructA, "grantRead"], [constructB, "grantReadWrite"]]
```

However, in the case where there is only one construct, the below mistake is ignored by SST and results in overly permissive access to the resource
```
permissions: [constructA, "grantRead"]
```

Expected result: Validation error stating the "grantXYZ" is not a valid input to the Permissions array

Actual result: Access is granted for ALL IAM actions on `constructA`. The second element in the above array seems to be ignored by SST.

I realize it is incorrect per the docs, but since it is such a simple mistake to make, and can result in a decrease in expected security, it makes sense to catch this and warn/error as a result. This will further help developers maintain a least privilege security model.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
