### ISSUE TITLE
Deploy DockerImageFunction with Api not works with Seed

### ISSUE THREAD

**Issue by Rajivhost** [sst/sst#2260]
Hi @thdxr @fwang,

I have a strange issue trying to deploy a DockerImageFunction  associated to a Api route using seed.
Please found below some details:

DockerImageFunction :

![image](https://user-images.githubusercontent.com/3539984/208095364-0a923297-406b-4395-8e43-a76519135a9e.png)

The API:

![image](https://user-images.githubusercontent.com/3539984/208095798-d281ccdb-5111-4003-be6d-57e6d13d0dc7.png)

![image](https://user-images.githubusercontent.com/3539984/208095854-84836eb3-a0f2-44c0-8ec0-8981db3e7c65.png)

Here the error I got on See :

![image](https://user-images.githubusercontent.com/3539984/208096003-00480693-7799-4355-8f9e-ab461deb0226.png)

I'm stuck on this since few days, so far, I cannot figure out the problem.
Kindly help please!

Br,
Rajiv.

**Comment by jayair** [comment]
Does this deploy locally for you?

**Comment by Rajivhost** [comment]
Hi @jayair,

I have the same error locally

![image](https://user-images.githubusercontent.com/3539984/208178150-05eac092-5c7a-4fb5-a15d-479d495463d7.png)

**Comment by jayair** [comment]
Can you post this over on Discord with the what yours stacks code looks like?

**Comment by Rajivhost** [comment]
Hi @jayair,

Sorry for the delay.

I'm putting this on discord `general` channel

**Comment by Rajivhost** [comment]
It's done

**Comment by Rajivhost** [comment]
Hi all,

Merry Christmas and Happy new year.

@jayair, can I expect any update on this point please?

**Comment by Rajivhost** [comment]
![image](https://user-images.githubusercontent.com/3539984/209444730-84f34981-baed-4b95-baff-6234c74caeb7.png)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
