### ISSUE TITLE
Incorrect Path name in stack:  api/graphql/schema.graphql -> services/graphql/schema.graphql

### ISSUE THREAD

**Issue by SalhiYassine** [sst/sst#2261]
Hi all,

With the template, it seems that the folder is expected to be /api when in reality it is /services. This is within the MyStack.ts file.

![image](https://user-images.githubusercontent.com/44145823/208423126-82b45f98-6ee5-45e3-8a2b-31b9e10b8f6e.png)

Not the biggest issue in the world but for a beginner could be potentially harmful.

Thanks

**Comment by jayair** [comment]
@SalhiYassine good catch. Which template is this?

**Comment by SalhiYassine** [comment]
Hey, its this one: https://github.com/serverless-stack/sst/tree/master/examples/graphql-appsync

Thanks

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
