### ISSUE TITLE
Function: packages fail to import for Python runtime

### ISSUE THREAD

**Issue by fwang** [sst/sst#2263]
Requests
- eddywd https://discord.com/channels/983865673656705025/1049359834568470570/1051941499438370936

**Comment by jalexanderII** [comment]
Does this mean the python rest-api examples doesn't work yet? @fwang

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
