### ISSUE TITLE
SST Live Lambda for vanilla cdk lambdas?

### ISSUE THREAD

**Issue by dev-samples** [sst/sst#2269]
I am using `aws-cdk-lib/aws-lambda` with typescript for my lambdas e.g.:

```
import * as lambda from 'aws-cdk-lib/aws-lambda';
...
    const myLambda = new lambda.Function(this, `my-lambda`, {
      functionName: `my-lambda`,
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'my-lambda.default',
      code: lambda.Code.fromAsset('../../dist/functions/my-lambda'),
    });
```
but based on:
https://docs.sst.dev/migrating/cdk

it seems that to use SST I need to migrate my current apps/lambdas to SST. Basically I just want to use this very cool feature: 
https://docs.sst.dev/live-lambda-development

to develop my lambdas locally and hoped it was possible without having to migrate my project to SST. 

Or am I missing something?

**Comment by dangreaves** [comment]
The SST [Function](https://docs.sst.dev/constructs/Function) construct is what powers the Live Lambda functionality, which itself relies on the SST [App](https://docs.sst.dev/constructs/App) and [Stack](https://docs.sst.dev/constructs/Stack) constructs, so yes, you would need to migrate your app to SST to use that feature.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
