### ISSUE TITLE
Advice on integrating hasura

### ISSUE THREAD

**Issue by ericwooley** [sst/sst#2273]
This project is awesome, and I'm digging it so far. As a newb though, I'm struggling to find a good way to usehasura. 

For the unfamiliar: Hasura essentially translates a postgres DB to a graphql endpoint, with row level security, and some other cool features. Hasura runs locally as a container, and connects to postgres, with volumes mapped to your local disk.

The hasura container provides a GUI for interacting with your postgres schema, and automatically creates migration sql files for you, which you can commit.

I could use custom CDK code to create an ec2 or something to run hasura for development, but the migrations would not map over to my local file system.

I'm not really sure how to approach this in a way that isn't hacky AF. 🤷‍♂️

**Comment by jayair** [comment]
@ericwooley I'm not really familiar with Hasura but have you tried asking over on our Discord to see if anybody has tried to do this?

**Comment by ericwooley** [comment]
I have not tried discord, I could give it a shot there, but I'm sure I'm not the only one to have this question, feels like having the answer in a searchable place would be a good idea

**Comment by ezebc182** [comment]
> I have not tried discord, I could give it a shot there, but I'm sure I'm not the only one to have this question, feels like having the answer in a searchable place would be a good idea

Hey man, did you figured it out?
If so, could you share some refs/docs? Thanks

**Comment by ericwooley** [comment]
> > I have not tried discord, I could give it a shot there, but I'm sure I'm not the only one to have this question, feels like having the answer in a searchable place would be a good idea
> 
> Hey man, did you figured it out? If so, could you share some refs/docs? Thanks

@ezebc182 

I did not. Just moved on :(

Upon reflection, I kinda just prefer to develop services, and deploy them however. 🤷‍♂️

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
