### ISSUE TITLE
Docs Typo - learn/index.md

### ISSUE THREAD

**Issue by goofygoobers** [sst/sst#2274]
In the learn preface section, there is a typo. 

As seen in the file sst/www/docs/learn/index.md on line 29

`The source for the app we are builing is on GitHub for reference`

<img width="573" alt="image" src="https://user-images.githubusercontent.com/63584829/209892869-595751cc-5adc-4e9b-a487-62f6d918b89b.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
