### ISSUE TITLE
[Feature request] CLI Hooks

### ISSUE THREAD

**Issue by jakenvac** [sst/sst#2278]
Hi, firstly thanks for a great project.

Apologies if this has been asked for already or exists, I have searched issues/prs/docs but couldn't find anything.

It would be great if there was a way to execute code locally (On the machine deploying) at certain stages when using the CLI.

The use case that comes to mind for me is executing code before and after an app and/or stack has been deployed. Similar to how the `commands` section behaves on the [GraphQL Api construct](https://docs.sst.dev/constructs/Api#graphql) for generating schemas, it would be really useful for all sorts of code gen and tidy up.

My initial idea would be to have event handlers along the lines `preDeploy`, `postDeploy`, `preStackDeploy`, `postStackDeploy` etc. where the postDeploy handlers could have args that indicate any errors that may have occurred.

I haven't given much thought to the actual implementation, but if I can get time I would be happy to have a go at implementing this feature. Don't let me stop you if someone else gets to it first, though.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by abarone-btf** [comment]
Is there a way to achieve this (postStackDeploy for example), on sst v3?

**Comment by jayair** [comment]
Are you trying to run something after a resource has been deployed? You can script most things in the `sst.config.ts` directly.
