### ISSUE TITLE
Working with API Models Documentation Mistake

### ISSUE THREAD

**Issue by aihaddad** [sst/sst#2283]
There's an error in the example [under this section](https://github.com/serverless-stack/sst/blob/master/www/docs/constructs/ApiGatewayV1Api.about.md#working-with-models). the `"application/json"` template should be defined within the `cdk.requestTemplates` prop, not the `cdk.requestParameters`. The validation section after it is related more to the `cdk.requestParameters`, so it feels like it's _missing_ something

A good, extended example on how to model and how to validate is going to be a great help

I'm assuming something similar cannot be done for the `Api` construct?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
