### ISSUE TITLE
Zip._tmp File Not Found During Deploy

### ISSUE THREAD

**Issue by cdalton713** [sst/sst#2289]
I'm suddenly getting this error rather randomly during deploys.  Doing a second deploy seems to fix it, however.

```
fail: ENOENT: no such file or directory, rename '<PATH_TO_PROJECT>/.build/cdk.out/.cache/d81bf7c85b8f1e4fd9aac65a2e0af8b84190f6ddf1ed0e40fa256d6e87b306a3.zip._tmp' -> '<PATH_TO_PROJECT>/.build/cdk.out/.cache/d81bf7c85b8f1e4fd9aac65a2e0af8b84190f6ddf1ed0e40fa256d6e87b306a3.zip'
```

Bundle Config:

```
    runtime: "nodejs16.x",
    bundle: {
      minify: false,
      sourcemap: true,
      externalModules: ["pg-native", "aws-sdk"],
    },
```

**CLI & Resources Version**: 1.18.4
**Package Manager**: Yarn Berry

**Comment by 0xAlwaysDumpling** [comment]
Also running into this same issue all of a sudden.

**Comment by blytheaw** [comment]
We're also experiencing this issue

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
