### ISSUE TITLE
Allow multiple CNAMEs on resource/NextjsSite

### ISSUE THREAD

**Issue by shroomist** [sst/sst#2295]
cloudfront Distribution [allows](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.Distribution.html#domainnames) for multiple CNAMEs, but `resource/NextjsSite` resolves to having only one that is [specified](https://github.com/serverless-stack/sst/blob/master/packages/resources/src/NextjsSite.ts#L1017) with `domainName`

We should be able to attach multiple domains to distribution when using `resource/NextjsSite`

**Comment by shroomist** [comment]
It looks like this should be resolved in `v2`

**Comment by fwang** [comment]
Hey Andrey, it will? I don't think we intentionally made this available yet
lol.

Frank

--
<https://seed.run/>
Founder at SST <https://sst.dev>

SST <https://github.com/serverless-stack/serverless-stack> - OS framework
for building serverless apps
SEED <https://seed.run/> - Deploy, manage, and monitor serverless apps

**Comment by shroomist** [comment]
@fwang 
I'm on `"@serverless-stack/resources": "^1.18.4"`
and
this is what I have in `node_modules/@serverless-stack/resources/dist/NextjsSite.js`
```js
        // Build domainNames
        const domainNames = [];
        if (!customDomain) {
            // no domain
        }
        else if (typeof customDomain === "string") {
            domainNames.push(customDomain);
        }
        else {
            domainNames.push(customDomain.domainName);
        }
```

this is master
```ts
// Build domainNames
    const domainNames = [];
    if (!customDomain) {
      // no domain
    } else if (typeof customDomain === "string") {
      domainNames.push(customDomain);
    } else {
      domainNames.push(customDomain.domainName);
      if (customDomain.alternateNames) {
        if (!customDomain.cdk?.certificate)
          throw new Error(
            "Certificates for alternate domains cannot be automatically created. Please specify certificate to use"
          );
        domainNames.push(...customDomain.alternateNames);
      }
    }
```

I'm looking for that `alternateNames` spread.

**Comment by podbasico** [comment]
@shroomist were you able to have multiple domains?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
