### ISSUE TITLE
CLI: sst secrets: support multi-line secret value

### ISSUE THREAD

**Issue by fwang** [sst/sst#2306]
Current workaround, Stevie

## From CLI - backticks around base64 command required for CLI to actually run the command
npx sst secrets set MY_SECRET `base64 <cert dir location>`

## Example
npx sst secrets set MY_SECRET `base64 ./certs/cert.pem`

## setup secret in my Stack
const mySecret = new Config.Secret(stack, 'MY_SECRET');

## Obtain in code & Decode
import { Config } from '@serverless-stack/node/config';

const mySecret = Buffer.from(Config.MY_SECRET, 'base64').toString('utf-8')

---
Requests:
- https://discord.com/channels/983865673656705025/1029135511459221666/1060506366936092674

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
