### ISSUE TITLE
example to implement CustomAttributes under Cognito User Pool

### ISSUE THREAD

**Issue by PJCAfonso** [sst/sst#2308]
Hi all

Any ideia how to add some custom attributes to a particular auth.userPoolId / auth.cognitoIdentityPoolId?

example customType, customCLass, customXField

I look around [aws cognito](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#addCustomAttributes-property) but I could understand how to be implemented under sst.dev.

thanks for your sharing

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
