### ISSUE TITLE
StaticSite (NextJs) builds at start and not waiting for dependent Stacks => Build EnvVars are not resolved correctly. 

### ISSUE THREAD

**Issue by ggallotti** [sst/sst#2336]
Hi Team,

I'm using SSTv2 (RC). 

I have a Frontend Stack as follows:

```
export function FrontendStack({ stack }: StackContext) {
  const { auth } = use(CognitoAuthStack);
  const { api } = use(ApiStack);

  const nextSite = new NextjsSite(stack, "frontend", {
    path: "nextjsapp",
    waitForInvalidation: false,
    environment: {
     API_URL: api.endpointUrl,
     COGNITO_USER_POOL_ID: auth.userPoolId
    }
  });
```

FrontendStack depends on CognitoAuthStack. CognitoAuthStack creates the CognitoPool and all the Settings.
COGNITO_USER_POOL_ID is passed as an ENVVar for the NextJsSite build.

(It also depends on the API Gateway URL 'api.endpointUrl')

The App is bootstrapped like this:

```
 app
      .stack(VpcStack)
      .stack(DbStack)
      .stack(CognitoAuthStack)
      .stack(ApiStack)
      .stack(FrontendStack)
```

When Deploy is run, NextJS App is built at startup. (before any dependent stack)
Then all the ENV Vars that are passed to the NextJS site are not resolved. 

The problem seems to be that the NextJSSite should be built after deploying all the Dependency stacks (CognitoAuthStack, ApiStack) in order to have all the vars resolved correctly.  

```
yarn sst deploy --stage staging --profile app
yarn run v1.22.19
$ /Users/user/workspace/git/app/node_modules/.bin/sst deploy --stage staging --profile app
Using v0.5.2

┌─────────────────────────────────┐
│ OpenNext — Building Next.js app │
└─────────────────────────────────┘

```

Any workaround for this Issue? 
Thanks in advance.

**Comment by mochetts** [comment]
+1 on this one. We're facing the same issue and this is preventing us from being able to use seed.run.

**Comment by ggallotti** [comment]
Seems to be related: https://github.com/serverless-stack/sst/issues/888

**Comment by khuezy** [comment]
Might be relevant: https://github.com/serverless-stack/sst/pull/2340

**Comment by mike623** [comment]
for my workaround. separate two step.
1. `FOR_TYPE=true npx sst build ...`  <- generated types folder in .sst
2.  `npx sst deploy ...` <- actually deploy with types generated
![image](https://user-images.githubusercontent.com/14008281/222846752-3828058d-5b05-421f-b361-b983fede4570.png)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
