### ISSUE TITLE
Can't remove function because they are still attached to the api gateway

### ISSUE THREAD

**Issue by 0ptional** [sst/sst#2358]
Hey everyone!

I have two Stacks. One for the Service with functions and one for the api gateway. See the following:

```ts
export function API({ stack }: StackContext) {
  const api = new ApiGatewayV1Api(stack, "api");
  return { api }
}

export function Service({ stack }: StackContext) {
  const { api } = use(API);

  api.addRoutes(stack, {
    "GET /auth/install": {
      function: {
        handler: "services/service1/src/functions/some.handler",
      },
    },
  })
}
```

This works, but when removing an endpoint from my service stack, the endpoint + function stay. SST is not giving me any error and tells me everything is deployed (Bug?). But looking in CloudFormation, I get the error that the function can not be deleted, as the api stack is still using it.

This is also when I realized that the endpoints are not created in the service stack, but in my API stack. Which I don't understand. Because as a scope, I provide the stack from Service. 

Is my setup wrong, or how can I remove an endpoint + function? Is it possible to create the endpoint resources within the service stack, so that the stack manages the endpoints and the function together?

I use SST Version 2.0.0-rc.40

**Comment by thdxr** [comment]
hey! what version of sst is this?

**Comment by 0ptional** [comment]
Sorry, forgot to mention. I use sst 2.0.0-rc.40.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
