### ISSUE TITLE
SST not deploying stack to AWS. 

### ISSUE THREAD

**Issue by fddayan** [sst/sst#2371]
Hi I've been running into a problem deploying a stack to aws with `npx sst start` so I can try it in my local env.

This is the code for the repo https://github.com/fddayan/react-trpc-api

and this is the error I have been getting

<img width="863" alt="image" src="https://user-images.githubusercontent.com/188936/214345686-b5d4e09d-ec0a-45aa-beef-848287c7f835.png">

The debug stacks gets deployed correctly and I can see in my aws console. 

Any idea what `[100%] fail: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.` might be ?

Thanks!

**Comment by jayair** [comment]
Just to double check, are you running `sst start` or `sst deploy`?

**Comment by jayair** [comment]
Cos it sorta sounds like the upload to AWS failed. Could it be because of your internet connection?

**Comment by fddayan** [comment]
I'm running `sst start`.... yes, it could be because of my connection. However, it was able to deploy the debug stack and I tried it multiple times and different days. I thought at some point it had to work. I'm not sure how much data is transferring to deploy the stack

**Comment by fddayan** [comment]
This is the stack https://github.com/fddayan/react-trpc-api/blob/master/stacks/MyStack.ts

**Comment by jayair** [comment]
Thanks, let me ask @fwang to take a look.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
