### ISSUE TITLE
SST CLI: add option to pass custom sst.json as parameter

### ISSUE THREAD

**Issue by SchmellaKaa** [sst/sst#2381]
I am currently trying to deploy the same project multiple times automatically using a workflow with different parameters.
These deployments would need to be under different names but the cli does not allow to change the name used.

My approach was to run a script before executing `sst build` to swap out the sst.json file, however, it would be much cleaner to just pass a custom sst.json when running `sst build` and `sst deploy`.

**Comment by jayair** [comment]
Can you explain the use case a bit more? Typically people deploy to multiple stages and that handles this.

**Comment by SchmellaKaa** [comment]
In my case I deploy multiple staging and production environments whith different application names. 
The proposed solution to add the project name to the stage would work obviously but it does seem a bit strange to me to combine these two together. 
The catch with this approach is if i want to access the application name, for examle, to define domains, etc in a stack I would always have to access the stage instead of the name. 

There would be multiple approaches to solve this. 

Either allow a --name parameter.
Eg:
```
sst deploy --stage staging --name projectA
sst deploy --stage production --name projectA

sst deploy --stage staging --name projectB
sst deploy --stage production --name projectB
```

Or allow to specify a custom sst.json in which name, region, etc... can be specified. 
Eg: `sst deploy --json custom-sst.json`

Currently i solved the problem by simply swapping out the sst.json file on deployments using `mv custom-sst.json sst.json` before building and deploying, but it would be nice if sst could simply handle passing a custom sst.json out of the box.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
