### ISSUE TITLE
SST NextJS Deploy - Target is not longer supported

### ISSUE THREAD

**Issue by CervarlCG** [sst/sst#2386]
Hello everyone, when i try to deploy a NextJS 13 stack i received the next message

> Build error occurred
Error: The "target" property is no longer supported in next.config.js.

isn't NextJS 13 supported yet?

**Comment by jayair** [comment]
Join us on the #nextjs channel on Discord. Next 13 is supported for SST v2, that's in RC.

**Comment by CervarlCG** [comment]
Thanks @jayair i'll do it

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
