### ISSUE TITLE
[SST 2] When adding to Astro project, .gitignore is not updated

### ISSUE THREAD

**Issue by ffxsam** [sst/sst#2390]
When adding SST 2 to an Astro project, `.gitignore` should be updated to ignore `.sst` as well as any other outputs that shouldn't be part of the repo.

<img width="284" alt="CleanShot 2023-01-29 at 12 02 10@2x" src="https://user-images.githubusercontent.com/12532733/215346252-84b38bb7-ebaa-434f-be8f-d0dd073caa92.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
