### ISSUE TITLE
sst start fails if there's an AWS Profile called main

### ISSUE THREAD

**Issue by bahrmichael** [sst/sst#2398]
I followed the tutorial https://sst.dev/examples/how-to-use-dynamodb-in-your-serverless-app.html and when running npm start it failed with

```
npm start

> rest-api-dynamodb@0.0.0 start
> sst start

Look like you’re running sst for the first time in this directory. Please enter a stage name you’d like to use locally. Or hit enter to use the one based on your AWS credentials (Admin): dev

TypeError: Cannot redefine property: main
    at Function.defineProperty (<anonymous>)
```

I had a profile called `main` in my `~/.aws/config`, and once I removed that the npm start command succeeded.

```
[profile main]
region = us-east-1

[main]
region = us-east-1
```

**Comment by fwang** [comment]
Hey @bahrmichael, just to clarify, were u specifying `AWS_PROFILE` when running sst start, ie. `AWS_PROFILE=main npm start`?

**Comment by bahrmichael** [comment]
> Hey @bahrmichael, just to clarify, were u specifying `AWS_PROFILE` when running sst start, ie. `AWS_PROFILE=main npm start`?

No. I think I had `export AWS_PROFILE=something` or just the default before.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
