### ISSUE TITLE
NextjsSite - Default props make s3 bucket publicly accessible

### ISSUE THREAD

**Issue by jbhammon** [sst/sst#2427]
I noticed a bit of an anti-pattern in some default props of the `NextjsSite` and `RemixSite` constructs.

I ran into some issues deploying a `NextjsSite` or `RemixSite` at my current organization due to some permissions errors. Specifically, we have an SCP in place that doesn't allow s3 buckets to be publicly accessible, which is generally the suggested pattern to follow. However, it seems like the default behavior for the `NextjsSite` and `RemixSite` constructs is to make the s3 bucket publicly accessible.

```js
// packages/resources/src/NextjsSite.ts

private createS3Bucket(): s3.Bucket {
  const { cdk } = this.props;

  // cdk.bucket is an imported construct
  if (cdk?.bucket && isCDKConstruct(cdk?.bucket)) {
    return cdk.bucket as s3.Bucket;
  }
  // cdk.bucket is a prop
  else {
    const bucketProps = cdk?.bucket as s3.BucketProps;
    return new s3.Bucket(this, "S3Bucket", {
      publicReadAccess: true, // <--- HERE
      autoDeleteObjects: true,
      removalPolicy: RemovalPolicy.DESTROY,
      ...bucketProps,
    });
  }
}
```

We were able to get around this issue using the `cdk` prop like this:

```js
const frontend = new NextjsSite(stack, "Frontend", {
    ...
    cdk: {
      bucket: {
        publicReadAccess: false,
      }
    }
    ...
  });
```

Even with the ability to drop down to the `cdk` level and adjust that setting, I'm wondering if there is any reason these s3 buckets have to be publicly accessible **by default**. If there isn't a specific reason, I propose changing the default to `publicReadAccess: false` so this project has more "production ready" defaults.

If maintainers are open to this change I'm happy to contribute it with a PR.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
