### ISSUE TITLE
StaticSite: support files larger than 200MB

### ISSUE THREAD

**Issue by fwang** [sst/sst#2440]
Currently StaticSite and SsrSites do not allow upload files larger than 200MB.

The solution would be to detect the largest file in the bundle, if larger than 200MB, adjust the uploader function's disk size accordingly.

---
Requests:
- truecolin https://discord.com/channels/983865673656705025/1065472974184009759/1072693180018991134

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
