### ISSUE TITLE
experimentalUseProvidedRuntime support for golang

### ISSUE THREAD

**Issue by dgocoder** [sst/sst#2461]
I found this flag for java however I do not see a way to add it for golang. https://docs.sst.dev/constructs/Function#experimentaluseprovidedruntime

There are things that require this for example a datadog layer extension. Seems odd to limit it just to java in the current construct.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
