### ISSUE TITLE
[SST-100] CLI: add option to turn off auto-deploy on stack changes

### ISSUE THREAD

**Issue by fwang** [sst/sst#2486]
Requests:
- McLean25 https://discord.com/channels/983865673656705025/1007139657324187729/1073747065517113395
  > use case: when switching branch, there are large number of changes

<sub>[SST-100](https://linear.app/sst-dev/issue/SST-100/cli-add-option-to-turn-off-auto-deploy-on-stack-changes)</sub>

**Comment by khuezy** [comment]
+1 on this feature, it would be helpful for a lot of people who make sweeping/frequent changes on their code bases.

**Comment by michaellyons** [comment]
+1, I auto-save so often, it thrashes my infra! Epic feature but it's just not the easiest for me to use

**Comment by mvanleest** [comment]
Is it an option to set something in the sst.config.ts?
maybe something like:
```
export default {
  config(input) {
    return {
      name: "myapp",
      region: "eu-central-1",
      autodeploy: false,
    }
  },
....
```
And in the console maybe show a question if autodeploy is set to false,
"Stack code has changed. Do you want to deploy? (Y/N)"

**Comment by robdobtob** [comment]
+1 would also like this. When rebasing/handling merge issues this completely cooks stacks while auto deploy is running
