### ISSUE TITLE
Question: How can I do cross region resources?

### ISSUE THREAD

**Issue by lukeshay** [sst/sst#2493]
I am trying to create a Web ACL for Cloudfront which has to be in us-east-1 but I am deploying other resources to us-west-2. Is there a way to create the Web ACL in us-east-1 but keep the other stacks in us-west-2?

```ts
import type { SSTConfig } from "sst";
import { Tags } from "aws-cdk-lib";
import { Api, Database, Auth, Site, WAF } from "./stacks";

export default {
	config: (input) => ({
		name: "Backend",
		region: "us-west-2",
		...input,
	}),
	stacks: (app) => {
		app.setDefaultFunctionProps({
			runtime: "nodejs18.x",
		});
		app.setDefaultRemovalPolicy(app.local ? "destroy" : "retain");

                // This stack needs to be in us-east-1
		app.stack(WAF, {
			crossRegionReferences: true,
		});
		app.stack(Database);
		app.stack(Auth);
		app.stack(Api);
		app.stack(Site);

		Tags.of(app).add("Project", "FriendFetcher");
		Tags.of(app).add("Environment", app.stage);
	},
} satisfies SSTConfig;
```

**Comment by fwang** [comment]
Hey @lukeshay, the current recommendation is to create the Web ACL in a different SST app.

It is something on our radar, and we have an open issue for it here — https://github.com/serverless-stack/sst/issues/1299

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
