### ISSUE TITLE
GraphQLApi in 2.0.23

### ISSUE THREAD

**Issue by maxbaluev** [sst/sst#2502]
Hi! @thdxr It is possible to use GraphQLApi(not AppSyncApi) with sst 2.0.23? It is exist on examples, but doesn't work, look like no exports for GraphqlApi since 2 version. What I can do, I need to increase timeouts to more than 30 secs and it is not possible on appsync...

**Comment by maxbaluev** [comment]
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/9191176/219349342-dbda1c8a-cf72-4ca3-b56d-defd5759f977.png">

**Comment by maxbaluev** [comment]
Example here couldn't started https://github.com/serverless-stack/sst/tree/master/examples/graphql-apollo

**Comment by jayair** [comment]
@maxbaluev does this doc help? https://docs.sst.dev/upgrade-guide#constructs

**Comment by lschierer** [comment]
It would be nice to have an updated example since trying to follow an upgrade guide at the same time as trying to follow an example as I'm trying to learn the platform is less than ideal. Thanks!

**Comment by jayair** [comment]
@lschierer which example are you following btw?

**Comment by jayair** [comment]
Good point. I'll make a note to have that updated. Thanks!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
