### ISSUE TITLE
Always get `deploying bootstrap stack` message

### ISSUE THREAD

**Issue by ryands17** [sst/sst#2504]
I recently upgraded to SST 2.0 and deploying via CI always gives this message:
![image](https://user-images.githubusercontent.com/19697099/219413899-d7141d79-2377-4da3-8c57-f5c60d77ca0e.png)

I also checked CloudFormation and the bootstrap stack does exist. Is this just a message or does it create/update this stack every deployment?

**Comment by fwang** [comment]
Hey @ryands17, one way this could happen is if CI is using a different version of SST than ur local.

Can you run `yarn sst version` prior to `yarn deploy` in your CI to double check the version.

Also, what's the bootstrap version? You can see in the CFN outputs tab. It should be version 7 if you are using the latest SST version.
<img width="815" alt="Screen Shot 2023-02-20 at 4 29 45 PM" src="https://user-images.githubusercontent.com/83515/220201113-b6ee1a88-95e6-4d23-8a1d-292afea9f862.png">

**Comment by ryands17** [comment]
@fwang The outputs section is empty. Is it happening because we have another team still on SST v1 and the bootstrap stack is overriden by that?

**Comment by jolajolajola** [comment]
Facing the same issue with different versions of SST 2.

@fwang Would it be possible to be more transparent with bootstrap version changes?

The most recent bump in version was done here https://github.com/serverless-stack/sst/commit/36e22c43649105bd355e551433d65c8b510fecad and released in https://github.com/serverless-stack/sst/releases/tag/v2.0.17 but its not really clear from the release notes.

**Comment by jayair** [comment]
@ryands17 yeah the v1 to v2 bootstrap change is a big one, they aren't compatible.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
