### ISSUE TITLE
Aurora Serverless v2

### ISSUE THREAD

**Issue by lefnire** [sst/sst#2506]
I've seen some convos, and think it unlikely SST will support this. But maybe we can start a thread at least discussing how to use it with SST which can help users who definitely want it (myself), and SST may or may not consider integrating it as an option (defaulting still to v1 for simplicity). 

# Why

### Cold starts
v1 goes to sleep, which is awesome. What's not awesome is the time to warm-start the DB. 30sec+ isn't rare, and the problem there is if the first DB hit is an API call (sst.Api / sst.WebsocketApi), then the max allowable timeout is 30sec. I hit this issue VERY frequently in my project, it's not an edge-case. So it goes like this: user comes to website, pokes around, sure -> sign up. Pre/post hooks triggered to save user to DB, thinking... thinking... fail. The Lambda timed out while waiting for the DB. If the user hits submit again, extra-fail because Cognito succeeded in user-creation, but there's no user in DB; so they need to be re-consolidated with crazy logic. Similar situations happen when they're using the website without interacting for a while, DB goes to sleep. Now they create something, but it doesn't get saved. 

There's some `continueAfterTimeout` flag I can't find now, but it didn't help all the way. There's strategies for predictive warm-starting the DB, but thinking through those scenarios is imperfect (eg, the latter part of my scenario). The only true solution is to never sleep the DB. However, that costs $86 minimum / month, because the minimum ACUs is 2 ($0.06 / h * 2). 

Aurora v2's solution is simply the last option: never sleep (it can't sleep). However, it's half the price at $0.12 / h, but with a min ACU of 0.5 = $43.2. So that's still min $40/m even if you're not using it - so if you CAN, definitely stick to DynamoDB. But I can't safely recommend sleepable v1 to anyone, it will cause too many problems. And non-sleepable is double the cost.

### Library support
rds-data-api's is atypical. Pro: is it handles everything, like data types and sqli in the request; con is it's unusual, so low library compatibility (node-postgres, prisma, etc). I know Prisma is controversial due to its Lambda overhead; but I've hit a LOT of snags with kysley-data-api, which I tried to fix and submit as PRs to the project. But I couldn't fix, due to the order of obfuscation from kysley -> ksyley-data-api sort of locking me out. Hard to explain, and I didn't take notes, but I can revisit if it's valuable. 

### data-api is half-baked
It doesn't support arrays. In any way, shape, or form (`WHERE  x IN :arr`, `UPDATE x SET myarr=:arr`, etc). That's MAJOR. I've found "patches" (gists) to get around this. This wasn't the only time I hit a snag like this. In the end I have this nasty big file called `aurorav1patches.ts`. I know you know what I mean, kysley-data-api's transformations to/from the DB. Even that file lacks certain requirements, like UUID, so I find myself patching the patcher. Further, Aurora v1 is being sunset for MySQL - who knows when Postgres's time comes. And they're clearly moving on; v1's Postgres version is far behind; I fear we're going to lose support.

### Other considerations
V2 scales faster. V2 supports multi-AZ. **It is worth noting cons**, so I don't do SST a disservice! V2 requires a VPC. That changes everything. Now your Lambdas must be in said VPC to access the DB, which causes complexity and performance issues. If you want access to your DB (via the VPC), you'll need a ClientVPN - which aint easy. And that VPC needs a NAT Gateway to access the internet, +$30/m. So you're at $30(NAT) + $40(RDS) = $70 for something that may not even be touched. Also, that VPC code is CDK-proper, not SST, so you're sort of left to your own devices - which isn't a bad thing, I see SST as great training wheels into CDK, 80/20 style. You'll also need to come up with your own db-init, db-migration system; and combine that with the VPC/VPN considerations. 

All in all, if someone's reading this trying to decide v1 or v2, I recommend first taking a long hard look at DynamoDB. Literally try to make it work against all odds, before you know for a fact you need SQL. Because the journey is not fun.

# Code samples
* **UPDATE** use this one: https://github.com/serverless-stack/sst/issues/2506#issuecomment-1631711256
* All-in-one. https://github.com/jetbridge/sst-prisma is the full setup, a-z with VPC and all. Ironically they use Aurora v1, so all the cons and none of the pros. Just swap out the stacks/database.ts code with v2 code and bam. 
* Aurora v2 CDK: https://github.com/aws/aws-cdk/issues/20197#issuecomment-1360639346

**Comment by lefnire** [comment]
Frankly this'd all be moot if Aurora v2 supported data-api, and continued building it out (array operations, etc). But we're at AWS's mercy, and all indications from my research say they're not revisiting data-api. Seems like they considered it a failed experiment somehow.

**Comment by jayair** [comment]
Thanks for starting this thread. Needless to say we aren't super happy about the state of RDS either.

**Comment by Newbie012** [comment]
AWS has introduced a new feature called [EC2 Instance Connect](https://aws.amazon.com/blogs/compute/secure-connectivity-from-public-to-private-introducing-ec2-instance-connect-endpoint-june-13-2023/) which appears to make life a bit easier to connect to an EC2 inside a VPC.

Doesn't it solve the problem which Data API tried to?

**Comment by berenddeboer** [comment]
Note that Serverless v1 now supports postgres 13, so that alleviates the pressure from our point of view. Obviously the autoscaling in v1 isn't great, but can be managed quite well.

**Comment by OSonntag** [comment]
@lefnire hey man i got a tip for you regarding cognito and user creation. I dismissed the use of lambda post triggers as they are not save and can fail leaving you with a broken data state. 
I solved user creation in the preAuthentification method, yep thats right on every signin. I first check if the user exists and if not create it. If this fails for whatever reason, the sign in fails as well - so the user can retry.

Hope that helps

**Comment by tyrauber** [comment]
Thank you for this thread, @lefnire. It was a huge help. I’ve been struggling to use node-postgres with SST / RDS, and this thread helped me through it.

Two other points to make about the necessity of upgrading the V2 Aurora:

- V2 Aurora supports publicly accessible instances, V1 does not
- V2 Aurora supports IAM authentication, v1 does not

These two issues are important because:

A) [VPC’s do not work in dev mode](https://github.com/serverless-stack/sst/issues/487), so if you create a V1 Aurora instance you cannot access it locally (without using BastionHostLinux, which is overkill for development). I lost half a day debugging this issue. By using V2, we can just create a public instance for dev, and a private instance with a vpc for all other environments.

B) Right now, we need to expose the master RDS password to the lambda in order to use postgres, node-postgres, or other libraries that don’t use the data-api and require postgres connection parameters.  With V2, we can enable IAM authentication and generate auth tokens to use as passwords, using AWS.RDS.Signer. Which is far more secure than exposing the master password.

I would absolutely love to see the SST RDS construct support Aurora V2 directly.

**Comment by disbelief** [comment]
A quick chime in after I also lost about a day trying to get postgres+aurora-serverless-v2 working on SST.

It seems that serverless V2 is the way forward for Aurora at AWS so it would make sense for SST to support it and eventually make it the default (in my opinion).

**Comment by berenddeboer** [comment]
@disbelief the problem with v2 is that you cannot autoPause it. That's quite a money saver in dev. So supporting v1 in addition to v2 makes sense. But v2 is much harder to support for SST's dev model. And a public VPC even in dev won't work, that will be ringing too many alarm bells in enterprise environments, where we don't even tend to have public subnets.

**Comment by disbelief** [comment]
@berenddeboer that's all quite understandable, but I wonder about the long term strategy for SST if we assume that AWS will eventually deprecate serverless v1?

**Comment by tyrauber** [comment]
@berenddeboer,  why won't a public VPC work in dev mode? 

From a technical perspective or a policy perspective? From a technical perspective, you can make the Aurora v2 DB and VPC public.  If you need to lock it down, grant isolated IP access via the Security Group.  Or you can set up BastionHostLinux or Amazon VPN to access the VPC, just as you would with Aurora V1.  Price is a factor, but V2 is cheaper than V1, and always-on prevents cold starts, which is worth the extra cost in IMO. 

I am not necessarily advocating replacing v1 with v2 - I think that migration would be tough for people relying on the Data API - I am just trying to understand the motivations for staying with v1.

**Comment by lefnire** [comment]
For my projects, I have local Postgres instance (Docker) for `IS_LOCAL` (`app.mode === "dev"`); and the v2 cluster otherwise. This gets around the VPC issues, you can test your DB stuff locally while maintaining private subnets for staging/prod. I know it breaks the SST paradigms, but it's really a small if/else for the connection part, and that's the only bit that cares. BastionHost for staging/prod connection. ClientVPN is expensive, $5/d without even connecting.

**Comment by lefnire** [comment]
Here's an updated repo with V2 sample: https://github.com/lefnire/sst-aurorav2 (sorry took so long to respond @disbelief). Note: untested!

See the README and sst.config.ts. It allows for $0 (local only), $40 (common stack for all envs), or $80 (prod, and common for everyone else).

As you see, the code is pretty minimal. And while it's $80 min for a prod/stage/dev setup, that's still likely less than you'll pay with real consistent users in the same setup for Aurora v1. It's not too much effort (though it did take me trial & error to get there), by which I mean: it's not really a shortcoming of SST. You can just bolt this on yourself if you want it. Though I do think SST could provide some pointers / documentation, or a sample repo (feel free to take & gut mine). Point is: the longer I've sat with this, the less certain I am it's SST's "responsibility". But they would benefit from giving users a nudge in this direction.

**Comment by berenddeboer** [comment]
@disbelief SST doesn't depend on RDS. That's just one use case. Given AuroraServerless v1 just supported Postgresql 13 I think there's some life left in it.

@tyrauber: policy.

@lefnire: yep, that's a great solution.

**Comment by disbelief** [comment]
> SST doesn't depend on RDS. That's just one use case. Given AuroraServerless v1 just supported Postgresql 13 I think there's some life left in it.

True and knowing AWS it'll take years to deprecate V1, if ever.

An anecdote that may be of interest: my reason for using Aurora v2 is that it supports Postgres 15.2, which in turn supports the `pgvector` extension for Postgres (at least I thought it did), which enables vector DB functionality that many AI apps require.

It turns out that [only vanilla RDS Postgres clusters support `pgvector` at this time](https://github.com/pgvector/pgvector/issues/54#issuecomment-1568321080), though I expect they'll add it to Aurora soon (they just added it to RDS in May).

The point of this story is that a major use case of many AI apps will likely not be possible with v1.

Many thanks to @lefnire for again sharing the code to get v2 working on SST with minimal costs. I will happily use this approach once Aurora supports `pgvector`.

**Comment by tyrauber** [comment]
Here is an example stack, [sst-aurora-v2](https://github.com/tyrauber/sst-aurora-v2), with Postgres 15.2, and Postgres.js.  I am seeing about 150ms response times for `select postgres();` from an ec2 instance within the same region, which isn't terrible.  I'm guessing that extra ~100ms is the lambda initializing and network latency.

**Comment by TriTranSendpayments** [comment]
Is it even worth it implementing this Serverless Aurora V2 using SST stack ? I feel like this is so complicated. Feels like a black box and will bite us back in the future ( for me at least ) to manage the resources and make sure other devs understand this as well

**Comment by tyrauber** [comment]
@TriTranSendpayments, for us, yes. We wanted to be able to access the Postgres RDS with pg or postgres libraries, not the data api.  Otherwise, you need to not use aurora and use the original ec2 variant postgres rds instances.

**Comment by TriTranSendpayments** [comment]
@tyrauber yea my company is fixed on Serverless Aurora V2 and we are using SST as well, what a "great" combination

**Comment by nirweiner2** [comment]
Aurora Serverless V2 is now supporting data-api
I think it make sense now to migrate
https://aws.amazon.com/pt/about-aws/whats-new/2023/12/amazon-aurora-postgresql-rds-data-api/

**Comment by jayair** [comment]
Yeah we have some plans!

**Comment by nacho-vazquez** [comment]
Alright, AWS just announced they are deprecating Aurora Serverless V1.

**Comment by zammitjames** [comment]
@jayair  any plans to support aurora v2 here in sst v2?

**Comment by jayair** [comment]
Yeah we do, it'll most likely land in Ion first.

**Comment by lefnire** [comment]
What's.. Ion... precious

**Comment by disbelief** [comment]
I had the same question. Looks like Ion will eventually become SST v3 with some major breaking changes (eg. no more CDK) https://sst.dev/blog/moving-away-from-cdk.html

**Comment by lefnire** [comment]
@disbelief holy shit.. from CDK/CFN to Terraform/Pulumi. Here I thought I was Belieber enough to catch wind of something like that. That's like Epic switching to Unity. Welp, I'm hook-line-sinker SST diehard thus far - if they say so!

**Comment by allen-n** [comment]
Late to the thread, I'm looking at migrating to Ion once its stable and there is a solid roadmap for SST v2 -> Ion, but in the meantime, has anyone tried this option (`autoPause: false`) to reduce the cold start times @lefnire mentioned in the original post?

```ts
  const appointmentTable = new RDS(stack, 'AppointmentsDb', {
    engine: 'postgresql13.9',
    defaultDatabaseName: 'main_db',
    // NOTE: If we need to reduce cold-start delays, we can turn off auto-pause in production
    // scaling: {
    //   autoPause: !isDev,
    // },
    cdk: {
      cluster: {
        deletionProtection: !isDev, // only protect in prod
        removalPolicy: isDev ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN, // only destroy in PR stages to complete cleanup
        backupRetention: Duration.days(7),
      },
    },
    migrations: 'migrations',
    types: 'packages/core/src/types/generated-sql.ts',
  });
  ```
  
They are killing me too, I saw this option it the CDK to keep the v1 serverless instance warm at all times, but am a little concerned about the potential cost implications since we have a burst-heavy but generally low-usage internal use case - I wanted to see if anyone had any experience with it for solving cold start latency. Thanks!

**Comment by zacronos** [comment]
@allen-n Yes, my startup is using it, and it makes a big difference on that first invocation.  We're setting it to false for prod, leaving it on for dev, demo, test, etc environments, so I'm very aware of how much faster prod responds.

Of course, we're also using some provisioned lambda concurrency on prod, so I don't quite recall how much delay is due to which cause, but IIRC the `autoPause` delay is larger than the lambda delay, but some whole-number multiplier.

**Comment by allen-n** [comment]
@zacronos got it, thanks! I think I'll give it a try on my end though, will update the thread with % increase in cost so others with more intermittent / low volume use cases can get a sense of that too.

**Comment by allen-n** [comment]
Quick update, as of turning this on I'm seeing pretty massive latency reduction, red line indicates when I turned off the auto-pause. In terms of costs, in the last 24h there hasn't been a noticeable increase. 

![latency](https://github.com/user-attachments/assets/90138668-b390-41ca-b6ba-424d03e41e2b)

**Comment by allen-n** [comment]
One last checkin - steady state of our db cluster cost has gone from $2.41/day to $4.15/day, but at least for us, it's worth the massive latency reduction we saw, hopefully this is useful to others' considering disabling auto-pause for production:
<img width="1496" alt="image" src="https://github.com/user-attachments/assets/08cd798b-c2fd-455e-ae07-7c80691c43bc">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by allen-n** [comment]
If helpful, me and some others worked through how to do this via PNPM patches with SST v2, full details in the SST discord thread, putting it here in case it helps someone out: https://discord.com/channels/983865673656705025/1204830115532640289
