### ISSUE TITLE
Environment variables don't override values in .env

### ISSUE THREAD

**Issue by RoryStokes** [sst/sst#2523]
According to the documentation (https://docs.sst.dev/config#other-environment-variables), dotenv shouldn't override any existing environment variables. The current implementation has all four invocations of dotenv configured to override (https://github.com/motdotla/dotenv#override).

In `packages/sst/src/cli/sst.ts`:
```
import dotenv from "dotenv";
dotenv.config({
  override: false,
});
dotenv.config({
  path: ".env.local",
  override: false,
});
```

And in `packages/sst/src/project.ts`:
```
  dotenv.config({
    path: path.join(project.paths.root, `.env.${project.config.stage}`),
    override: false,
  });
  dotenv.config({
    path: path.join(project.paths.root, `.env.${project.config.stage}.local`),
    override: false,
  });
```

I'm not sure if this is an mistake in documentation or implementation, but I'm happy to raise a pull request if helpful.

**Comment by jayair** [comment]
Let me ask Dax about it.

**Comment by ddouglascarr** [comment]
I can confirm this is happening. 

To reproduce:
- add `FOO='bar'` to `.env`
- put a `console.log('FOO: ' + process.env.FOO)` in a stack somewhere
- run `$ FOO='baz' npx sst build`

You can observe a `FOO: bar` line in the logs.

I've seen it running bash v5 on macos.

**Comment by ddouglascarr** [comment]
A clarification on @RoryStokes comment above: the code they've posted is what it should be to comply with the documentation. Currently, `dotenv` is being configured with `override: true`. 

I'm also happy to raise a PR which fixes the calls to `dotenv.config`, or the documentation. Please advise which one is currently wrong.

**Comment by jayair** [comment]
I'm pretty sure we'd want to fix the behaviour. Would appreciate a PR @ddouglascarr! Thank you!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
