### ISSUE TITLE
Unable to deploy SST project v2 to unsupported IoT region

### ISSUE THREAD

**Issue by aguglie** [sst/sst#2527]
Hello,
I recently upgraded my SST project from v1.18 to v2, but I have been unable to deploy it successfully. 
It appears that the V2 Live Lambda is using AWS IoT, which is not supported on every region. 

Specifically, I am trying to deploy to `eu-south-1`, which is not supported. As a result, I am unable to deploy my project in this region. Is there a workaround for this issue? 

Thank you.

**Comment by fwang** [comment]
Hi @aguglie, I was able to verify this. I just enabled `eu-south-1` in my account, and it seems the `IoT` service is grayed out.

Does only `sst dev` fail for you? Or is `sst deploy` also failing?

**Comment by fwang** [comment]
cc @thdxr For regions that don't support IoT, is it possible to piggy bag on IoT in a nearby region?

**Comment by aguglie** [comment]
Hi @fwang,

> Does only `sst dev` fail for you? Or is `sst deploy` also failing?

I only tried `sst dev` and it was failing because of `iot.eu-south-1.amazonsws.com` missing :)

Thank you 😊

**Comment by aguglie** [comment]
I can confirm that `deploy` works correctly in `eu-south-1` 😄

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
