### ISSUE TITLE
Support for `--path` in `sst env`

### ISSUE THREAD

**Issue by dtsn-vmles** [sst/sst#2536]
Just upgraded to v2 and i'm having problems with the frontend application when it isn't placed within the sst directory. In the previous version I used `--path` to specify the relative path.

When using the following command

`sst env --path=../app \"react-scripts start\"`

SST seems to ignore the path variable. Logging the output of `findRoot` in `project.js` you can see that it doesn't start in the correct directory.

```
/Users/dtsn/repositories/fe-dashboard/app
/Users/dtsn/repositories/fe-dashboard/app/sst.config.ts
/Users/dtsn/repositories/fe-dashboard/app/sst.config.mts
/Users/dtsn/repositories/fe-dashboard/app/sst.config.cts
/Users/dtsn/repositories/fe-dashboard/app/sst.config.cjs
/Users/dtsn/repositories/fe-dashboard/app/sst.config.mjs
/Users/dtsn/repositories/fe-dashboard/app/sst.config.js
/Users/dtsn/repositories/fe-dashboard
/Users/dtsn/repositories/fe-dashboard/sst.config.ts
/Users/dtsn/repositories/fe-dashboard/sst.config.mts
/Users/dtsn/repositories/fe-dashboard/sst.config.cts
/Users/dtsn/repositories/fe-dashboard/sst.config.cjs
/Users/dtsn/repositories/fe-dashboard/sst.config.mjs
```

My directory structure is very similar to that of the documentation (https://docs.sst.dev/packages/sst#sst-env).

```
\
  - api
    - sst.config.ts
  - app
    - package.json 
```

Everything else seems to be working fine after following the upgrade guide.

**Comment by jayair** [comment]
I'll check on the `--path` option but we don't recommend this setup. The config needs to be at the root, is there a reason why it's in a sub directory?

**Comment by dtsn-wtc** [comment]
@jayair Personal preference, I would like my FE code separated so it can be easily worked on by a different team.

Why is it not recommended?

**Comment by jayair** [comment]
The way to think about this is that SST is packaging and deploying both the frontend and the API. So it'll be odd if they are sitting side by side. You'd want to run SST at the root so it can work with both of them. You can place your stacks code elsewhere but the config needs to sit at the root.

**Comment by dtsn-wtc** [comment]
@jayair That makes sense, but why is `--path` an option at all? Especially a fully documented option.

**Comment by jayair** [comment]
Yeah we used to have it in SST v1 when things were structured a little differently. We need to remove it from the docs.

**Comment by dtsn-wtc** [comment]
@jayair Should also add it in the release notes that the option was removed in version 2.0

**Comment by jayair** [comment]
Good point! @fwang can we add this to the Migration guide?

**Comment by jayair** [comment]
Usually it's just moving the `sst.config.ts` to the root. What does your project structure look like?

**Comment by arnaldocrescente** [comment]
I'm using nx to manage my monorepo. My project's folders looks like this:
```
Apps/
   Serverless/
       Sst.config.ts
   Frontend/
   MobileApp/
Libs/
   Mobile/
   Backend/
   Web/
   shared/
Package.json
```
Tomorrow I'll try to move my sst config file to root folder but it seems a temporary fix, because in my monorepo I can't have more then 1 serverless app.

**Comment by chayakumart** [comment]
It looks like the --path option is not working as expected in SST v2 when
starting the frontend application. Instead, you can specify the working
directory for the react-scripts start command by using the --cwd option.
Try the following command instead:
sst env --cwd=../app \"react-scripts start\"

This should set the working directory for the react-scripts start command
to the app directory, which is one level above the SST directory.

**Comment by nurulhudaapon** [comment]
> I'm using nx to manage my monorepo. My project's folders looks like this:
> 
> ```
> Apps/
>    Serverless/
>        Sst.config.ts
>    Frontend/
>    MobileApp/
> Libs/
>    Mobile/
>    Backend/
>    Web/
>    shared/
> Package.json
> ```
> 
> Tomorrow I'll try to move my sst config file to root folder but it seems a temporary fix, because in my monorepo I can't have more then 1 serverless app.

Having the same issue with `nx` project structure.

**Comment by jayair** [comment]
What's the issue? We don't have the env command anymore.

**Comment by arnaldocrescente** [comment]
Hi @jayair if I have to formulate an issue, there is no support for monorepo project that need more then one serverless stack pipeline.

**Comment by jayair** [comment]
I'm kinda confused by what you are saying? Can you post your project structure in #help on Discord? We'll take a look.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
