### ISSUE TITLE
Typos in examples docs affecting yarn create.

### ISSUE THREAD

**Issue by Wkasel** [sst/sst#2539]
There are a series of typos in the docs for example projects that affect the ability of a user to copy & paste the commands in the readme. For example: `yarn create sst --template=examples/rest-api` inside the `rest-services` returns an error because the proper should be `yarn create sst --template=examples/rest-services` (to match the folder names). 

I don't see another ticket noting this, so opening and planning on submitting a PR.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
