### ISSUE TITLE
Delayed Job & API question

### ISSUE THREAD

**Issue by nbabaka** [sst/sst#2543]
Hello! Thank you so much for framework!

I have a question!  I have API and need to run the job after the API call, but with a delay and API should return a response before the job started. How to do it?

Thank you!

**Comment by jayair** [comment]
What kind of a job are you trying to run? Will it run inside a Lambda function?

**Comment by nbabaka** [comment]
Yes. I that's inside Lambda

**Comment by jayair** [comment]
Then run it async, publish it to a Topic and handle those events. Here's a simple example: https://sst.dev/examples/how-to-use-pub-sub-in-your-serverless-app.html

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
