### ISSUE TITLE
`FunctionProps.layers` doesn't actually attach a layer to the function, as opposed to `function.addLayers`

### ISSUE THREAD

**Issue by dankochetov** [sst/sst#2546]
The layer isn't being attached to the function with a construct defined like this:

```ts
const migratorFunction = new Function(stack, 'MigratorFunction', {
	handler: 'src/handlers/custom-resources/migrator/handler.migrate',
	timeout: 60,
	layers: [
		new lambda.LayerVersion(stack, 'MigrationsLayer', {
			code: lambda.Code.fromAsset('layers/migrations'),
		}),
	],
});
```

 However, it works like this:

```ts
const migratorFunction = new Function(stack, 'MigratorFunction', {
	handler: 'src/handlers/custom-resources/migrator/handler.migrate',
	timeout: 60,
});

migratorFunction.addLayers(
	new lambda.LayerVersion(stack, 'MigrationsLayer', {
		code: lambda.Code.fromAsset('layers/migrations'),
	}),
);
```

**Comment by thdxr** [comment]
Layers are not added in dev mode because there's not a good way to support them locally

**Comment by MichaelMjc** [comment]
> Layers are not added in dev mode because there's not a good way to support them locally

Assuming the layer resources exist within the repo, is it feasible to create a local env variable that points to the layer?

I created a utility function within my repo to point to the layer resource when the IS_LOCAL env variable is set to true.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
