### ISSUE TITLE
Issue in RDS cdk vpc subnets

### ISSUE THREAD

**Issue by sebscholl** [sst/sst#2550]
I think I spotted a bug here.

https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/RDS.ts#L444

This code isn't allowing the vpcSubnet configuration with having set a vpc. 

This disables the developer from setting the subnetType.

Should the code not be 

`if (props.vpcSubnets)...`?

**Comment by sebscholl** [comment]
Sorry, missed this! It's hard for me to recall back on where I was, but I believe the answer is yes, I was attempting to use the default VPC settings while providing a Subnet config.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
