### ISSUE TITLE
Unable to build SolidStartSite

### ISSUE THREAD

**Issue by eekrain** [sst/sst#2551]
Hi. I am trying to deploy the SolidStartSite construct, following closely on the docs in https://docs.sst.dev/constructs/SolidStartSite. When it's building, it throws an error caused by generated .solid/server/index.mjs needing to import solid-start/node/globals.

> [Error: Could not load /home/eekrain/Documents/CODE/CV-RESTU-SEMARA-BUMI/personal-branding/node_modules/solid-start/node/globals (imported by .solid/server/index.mjs): ENOENT: no such file or directory, open '/home/eekrain/Documents/CODE/CV-RESTU-SEMARA-BUMI/personal-branding/node_modules/solid-start/node/globals']

Here's the repro https://github.com/eekrain/solid-start-sst-repro

**Comment by fwang** [comment]
Hey @eekrain, the repo seems to create an Astro site.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
