### ISSUE TITLE
Extracting Pothos schema results in not defined errors

### ISSUE THREAD

**Issue by lukeshay** [sst/sst#2553]
I am creating a GraphQL API using the recommended setup by SST. When `sst dev` tries to write the schema to `schema.graphql` it gets the following error:

```
Pothos: Failed to extract schema:
Tracer is not defined
```

I am using `@aws-lambda-powertools/tracer` which has the export `Tracer`. The import for it is being removed from the transpiled file.

What seems to be happening is `resolve` functions inside of `t.field` are not being removed. Even after those resolve functions are removed, it will still fail if you have global variables that the resolve functions use.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
