### ISSUE TITLE
Enhancement: Find sst.config.ts in rootDir

### ISSUE THREAD

**Issue by kernwig** [sst/sst#2572]
Simply look for `sst.config.ts` relative to the `rootDir` as configured in `tsconfig.json`. `rootDir` is defined as "the root folder within your source files."  _No .ts files may exist above this directory._

This should be non-breaking for most users, since `rootDir` is `"."` by default.

Other options:

- Specify path to `sst.config.ts` configurable in `package.json` (`main` property?)
- Check current directory, and if not found check `rootDir` directory.

**Comment by kernwig** [comment]
I can take a try and this change, if you give the 👍 on what would be acceptable to you.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
