### ISSUE TITLE
Enhancement: Relative path to Function handler

### ISSUE THREAD

**Issue by kernwig** [sst/sst#2573]
If a `sst.Function` handler value starts with `"./"`, treat it as relative to the stack file referencing it.

I like to treat my handler as part of infrastructure (they are just small adapters from Lambda to my domain), and place them in the same directory as the stack defining them.

**Comment by spacerumsfeld-code** [comment]
Would love this.

**Comment by rossibelcasanova** [comment]
Thanks You

**Comment by cmjacques** [comment]
Not exactly the same use-case, but I'd love to see the option to set the path function handlers are under (especially for .NET functions). Moving SST to the root of my solution is not an option.

Right now I have to hack the dotnet.js handler to get the functionality I need:

```
build: async (input) => {
    const project = useProject();
    const name = input.props.handler.split(":")[0];
    //const srcPath = await findBelow(project.paths.root, `${name}.csproj`);            
    const srcPath = await findBelow('../', `${name}.csproj`);
    sources.set(input.functionID, srcPath);
    ...
```

**Comment by jayair** [comment]
Not familiar with .NET but how come moving the sst.config.ts to the root isn't an option?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
