### ISSUE TITLE
[SST-135] Unable to Import faunadb Package Post SST 2.0.35

### ISSUE THREAD

**Issue by nicholas-gates** [sst/sst#2585]
# Unable to Import faunadb Package Post SST 2.0.35

I created [this repo](https://github.com/nicholas-gates/sst-faunadb-rest-services) demo'ing that sst.dev releases *after* 2.0.35 produce an error when importing [the faunadb package](https://github.com/fauna/faunadb-js).

`Error: URL is not a constructor`

Steps to reproduce

1. Clone [this repo](https://github.com/nicholas-gates/sst-faunadb-rest-services) which is based on the basic sst.dev `rest-services` example. The modification is that it attempts to load the `faunadb` package in the `GET` endpoint for `notes`
1. Run the usual `npm install` for a sst.dev project
1. Run `npm run dev`
1. Access `https://[aws_domain]/notes
1. Observe this error in the console: `Error: URL is not a constructor`

Current Workaround:
1. Downgrade from SST 2.0.36 to 2.0.35 and re-run the above
2. Observe that the faunadb package can be imported without errors and the REST endpoint works as expected.

Blockers:
1. No SST2 package beyond 2.0.35 works with faunadb

<sub>[SST-135](https://linear.app/sst-dev/issue/SST-135/unable-to-import-faunadb-package-post-sst-2035)</sub>

**Comment by jayair** [comment]
Thanks for the repo. We'll take a look.

**Comment by Brian-Azizi** [comment]
We're getting the same errors on SST 2.1.24 with the [graphql-requests package](https://www.npmjs.com/package/graphql-request)

**Comment by jayair** [comment]
Oh sorry we might've missed this.
