### ISSUE TITLE
Rust runtime: missing field `identityId`

### ISSUE THREAD

**Issue by tdwells90** [sst/sst#2595]
I've run into the same issue that @thdxr ran into on his stream where invoking a rust lambda function returns the error `missing field "identityId"`.

## The fix

Reverting back to version `2.0.36` fixed the issue, so I suspect this is an issue with commit [2c33291](https://github.com/serverless-stack/sst/commit/2c332911ffa2ee6d6d459ab2464dc21cd04c9405) that was introduced in `2.0.37`. Either changing this or reverting it should fix the problem.

Thanks!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
