### ISSUE TITLE
Replace deprecated querystring@0.2.0 with URLSearchParams in Examples

### ISSUE THREAD

**Issue by EddyDavies** [sst/sst#2620]
ran `npx create-sst@latest --template=examples/api-sst-auth-google`

Got this error
```
 WARN  deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

**Comment by jayair** [comment]
Hmm we'll update all the auth examples in the near future. So this should get fixed then.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
