### ISSUE TITLE
Example project readme has npm run start

### ISSUE THREAD

**Issue by henrypenny** [sst/sst#2624]
The documentation for several example projects suggest using `npm run start`, however packages.json doesn't contain this script:

E.g `sst-cognito-example` has:
```
    "dev": "sst dev",
    "build": "sst build",
    "deploy": "sst deploy",
    "remove": "sst remove",
    "console": "sst console",
    "typecheck": "tsc --noEmit"
```

**Comment by jayair** [comment]
Would you mind submitting a PR for the docs? I'll merge it.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
