### ISSUE TITLE
[SST-121] NX Workspace SST plugin: Would be absolutely amazing to tie sst into NX

### ISSUE THREAD

**Issue by algoflows** [sst/sst#2625]
NX Workspace SST plugin, it would be absolutely amazing to add SST into NX

https://nx.dev/

<sub>[SST-121](https://linear.app/sst-dev/issue/SST-121/nx-workspace-sst-plugin-would-be-absolutely-amazing-to-tie-sst-into-nx)</sub>

**Comment by jayair** [comment]
@thdxr how would this work?

**Comment by algoflows** [comment]
NX has a vscode plugin that make it super easy for integrated projects to run commands, would also work well to integrate so that we can use SST with multiple frontend projects etc...

**Comment by vespertilian** [comment]
NX x SST would be awesome. @codetelo how did you go with the integration? Did you get it running?

**Comment by chihabhajji** [comment]
FIRESHIP BROUGHT ME HERE 🚀🚀🚀🚀🚀🚀🚀🚀
