### ISSUE TITLE
[SST-89] local env variables not populating

### ISSUE THREAD

**Issue by z0d14c** [sst/sst#2627]
My environment variable `REACT_APP_API_URL` is not populating in my frontend when I develop locally. I have tested on Windows and Linux. It does not appear to affect deployment to my staging environment.

I recently changed my StaticSite path to `frontend/build` which I suspect causes this issue now.

Specifically, because `cwd` which is how `env.js` keys into the `sites` is equal to the `path + /frontend/build` instead of just the path.

see:

https://github.com/serverless-stack/sst/blob/master/packages/sst/src/cli/commands/env.ts#L42-L43

example `site-environment-values.json` to illustrate my point. `process.cwd()` is equal to `<PROJECT_PATH>` (or `<PROJECT_PATH>/frontend` if I run an `sst env` command from the `frontend/` dir) but the site variables are keyed by `<PROJECT_PATH>/frontend/build`:

```json
{
    "<PROJECT_PATH>\\frontend\\build": { << wrong key here
        "REACT_APP_API_URL": "<REDACTED_URL>"
    }
}
```

[also discussing here in discord](https://discord.com/channels/983865673656705025/1082812936491380787)

Please let me know if I am missing something. I don't see any recent changes that would've caused this so I don't know if there's a workaround I should be utilizing.

<sub>[SST-89](https://linear.app/sst-dev/issue/SST-89/local-env-variables-not-populating)</sub>

**Comment by thdxr** [comment]
test

**Comment by thdxr** [comment]
can you keep the path at `frontend` and then set the `buildOutput` field to `build`?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
