### ISSUE TITLE
[SST-118] Async stacks not deploying as expected in SST2

### ISSUE THREAD

**Issue by paymonsattar** [sst/sst#2634]
We have been using SST V1 for a while now. We recently decided to upgrade to V2. However, we have come across an issue with Async stacks not deploying as expected. We get no errors or warnings - but we notice that no ApiGateways are created. Also cloudformation stacks seem empty...

These same stacks were working perfectly fine in V1 (even with the async/await on the stack)

Removing the await call on the stack does fix the issue with ApiGateways not being created.

This is our index.ts file in the stack dir
```
export default async function main(app: App) {
  app.setDefaultFunctionProps({
    runtime: "nodejs16.x",
    architecture: "arm_64",
    environment: {
      STAGE: app.stage,
      REGION: app.region,
    },
  });

  const stackTags = process.env.GITHUB_AUTHOR
    ? { GITHUB_AUTHOR: process.env.GITHUB_AUTHOR }
    : undefined;

  app
    .stack(DatabaseStack, {
      stackName: `database--${app.stage}`,
      tags: stackTags,
    })
    .stack(EncryptionStack, {
      stackName: `encryption--${app.stage}`,
      tags: stackTags,
    })
    .stack(FileSystemStack, {
      stackName: `file-system--${app.stage}`,
      tags: stackTags,
    })
    await app.stack(ApiStack, {
      stackName: `api--${app.stage}`,
      tags: stackTags,
    });
```

This is our sst.config.ts file. I am providing this as I have a feeling the issue is caused from the change from the sst.json file.
```
import type { SSTConfig } from "sst";
import main from "./stack/index";

export default {
  config() {
    return {
      name: "api-test",
      region: "eu-west-1",
    };
  },
  stacks(app) {
    main(app);
  },
} satisfies SSTConfig;
```

<sub>[SST-118](https://linear.app/sst-dev/issue/SST-118/async-stacks-not-deploying-as-expected-in-sst2)</sub>

**Comment by thdxr** [comment]
You need to make sure you await `main` in your sst.config.ts file
