### ISSUE TITLE
Error: Unknown file extension ".ts" for /lib/events/src/index.ts

### ISSUE THREAD

**Issue by paymonsattar** [sst/sst#2635]
Upon upgrading to SST2 we get this error when trying to deploy:

`Error: Unknown file extension ".ts" for /lib/events/src/index.ts`

We originally came across this error late last month when we upgraded one of our projects to SST2. We managed to fix it for the project by changing the package.json of the external lib from `"main": "src/index.ts",` to
  ```
"main": "dist/index.js",
  "types": "dist/index.d.ts",
```

This was a temporary fix. However, as we are now moving some of our other projects from SSTv1 to SST2 we are getting similar issues with other shared external libs. We don't want to continue making the same temp fix as these external common libraries are used by multiple non-SST projects as well.

This error only occurs in SSTv2. 

Here is how the external lib is used in the sst projects package.json:

`"@companyx/events": "workspace:*",`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
