### ISSUE TITLE
Can I import an Api construct to use for CDK triggers?

### ISSUE THREAD

**Issue by paambaati** [sst/sst#2636]
I'm trying to set up a database initialisation script, and I'm using a [CDK Trigger](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.triggers-readme.html) for it.

For now, it is built using a Docker image. But I'd like to use the build + tooling of SST as much as possible. Is it possible to use a `Function` construct as a `TriggerFunction`?

```typescript
const dbInit = new TriggerFunction(stack, 'ProjectsDbInitHandler', {
        functionName: 'fold-backend-db-init-lambda-trigger',
        description: 'Lambda function that is triggered when the database is initialized',
        timeout: Duration.seconds(30),
        runtime: Runtime.FROM_IMAGE,
        architecture: Architecture.ARM_64,
        code: Code.fromAssetImage('stacks/triggers/db-init', {}),
        handler: Handler.FROM_IMAGE,
        environment: {
            DB_HOST: db.dbInstanceEndpointAddress,
            DB_PORT: db.dbInstanceEndpointPort,
            DB_NAME: dbName,
            DB_SECRET_ID: dbMasterSecret.secretName,
        },
        executeAfter: [
            db,
        ],
        executeBefore: [
            dmsReplicationTask,
        ],
        vpc: db.vpc,
});
```

**Comment by jayair** [comment]
Hmm I might need to check with the team on this. Can you post this over on #help on https://discord.gg/sst?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
