### ISSUE TITLE
Auth Future private key breaking the console

### ISSUE THREAD

**Issue by justindra** [sst/sst#2660]
When using the new Auth, if I call `sst secrets list`, the `PrivateKey` ends up messing up the table in the console. See image below.

![image](https://user-images.githubusercontent.com/4289486/225169137-f74162f7-3227-42bf-b678-21b0f9f6237e.png)

P.S. scribbles to stop anyone finding out what is in the key.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
