### ISSUE TITLE
Compliance: Underlaying construct default settings

### ISSUE THREAD

**Issue by HenrikStanley** [sst/sst#2686]
I am currently working on a project for a very large enterprise where we are building up a library of CDK level "2.5" constructs. Aka extended versions of the base constructs compliant with all the corporate security and governence rules.

We are also eyeing SST for a good way for developers to do serverless applications.

I am trying to wrap my head around what the best approach would be to customize the underlying resources deployed by SST so they are compliant with our internal compliance and can be validated through our internal NagPacks.

Any input on this would be greatly appreciated.

**Comment by jayair** [comment]
Hmm that's interesting. Can you give me an example of some the changes you are making to these base constructs?

**Comment by HenrikStanley** [comment]
Sure!

The main idea is that, like many large enterprise organizations, we have central security governance which evaluates each AWS service from a security and compliance point of view. Then we create a set of Security Rules which needs to be followed by our Line of Business projects when they spin up services on AWS.

The way we are working towards accomplishing this currently is a whole lifecycle of things.

Step 1:
For each service we allow in the organization, that is evaluated and have security rules, we create an "L 2.5" construct.  
We basically take the AWS default construct and extend it to have default settings that complies with our security rules, and then allow the rest to be set through regular props. This here would be an example of a construct to do an S3 bucket:

```Typescript
export class SecureBucket extends Bucket {
  constructor(scope: Construct, id: string, props?: BucketProps) {

    super(scope, id, {
      ...props,
      encryption: BucketEncryption.S3_MANAGED, 
      enforceSSL: true,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      versioned: true, 
      accessControl: BucketAccessControl.LOG_DELIVERY_WRITE,
      serverAccessLogsPrefix: 'access-logs',
    });
  }
}
```

Step 2:
Write an assertion / unit test to validate when code changes are made, we have no regressions of these settings.

Step 3: 
Make a custom CDK Nag ruleset that complies with the same security settings.

Step 4: 
Setup custom rules through security hub / config that validates the deployed resources.

For each base construct, the changes will depend upon the security rules decided by a central security team, but it is mainly setting some more default that are not taken into consideration from the normal L2 constructs "Sane Defaults".

**Comment by jayair** [comment]
Thanks for sharing. I'm not sure how we could go about supporting that right now. Let me ask @fwang.

**Comment by berenddeboer** [comment]
I have to agree with @HenrikStanley here: SST out of the box is not suitable for an enterprise environment. It just triggers all kinds of alarms. Better defaults, which don't cost anything, would be good. I'm working on submitting patches.

**Comment by fwang** [comment]
You can extend the SST constructs in a similar manner. For example:
```ts
export class SecureBucket extends sst.Bucket {
  constructor(scope: Construct, id: string, props?: sst.BucketProps) {

    super(scope, id, {
      ...props,
      cdk: {
        bucket: {
          encryption: BucketEncryption.S3_MANAGED, 
          enforceSSL: true,
          blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
          versioned: true, 
          accessControl: BucketAccessControl.LOG_DELIVERY_WRITE,
          serverAccessLogsPrefix: 'access-logs',
        }
      }
    });
  }
}
```

Does this work? /cc @HenrikStanley

**Comment by fwang** [comment]
> I have to agree with @HenrikStanley here: SST out of the box is not suitable for an enterprise environment. It just triggers all kinds of alarms. Better defaults, which don't cost anything, would be good. I'm working on submitting patches.

🙏 @berenddeboer!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
