### ISSUE TITLE
Add support for Function handler prefix

### ISSUE THREAD

**Issue by fire015** [sst/sst#269]
Using Typescript within my `src` folder I have created a `lambda` folder where all of the lambda code lives rather than have them in `src`. The `start` command works fine and I can debug as usual, however the `deploy` command fails:

```
Type checking Lambda function source

Error: Cannot find a "tsconfig.json" in the function's srcPath: /opt/code/ts-app/src/lambda
```

Should it not inherit this file from the root?

**Comment by fire015** [comment]
This is my stack code:

```
    const api = new sst.Api(this, "Api", {
      defaultFunctionProps: {
        srcPath: "src/lambda",
      },
      routes: {
        "GET /": "index.handler",
      },
    });
```

**Comment by fwang** [comment]
Hey @fire015, can you give this a try?
```
    const api = new sst.Api(this, "Api", {
      routes: {
        "GET /": "src/lambda/index.handler",
      },
    });
```
For most cases, you shouldn't need to define a `srcPath`.

**Comment by fire015** [comment]
That works, it would be nice for it to work with `srcPath` as just duplicating code for every route. Maybe something to add to the backlog?

**Comment by fwang** [comment]
We aren't doing a good job of describing it in the docs - https://docs.serverless-stack.com/constructs/Function#srcpath

`srcPath` is meant to be used to specify the location of the tsconfig.

But I hear you, I think having a way to specify ie. `handler` prefix would help.

**Comment by fwang** [comment]
Opened a discussion for this https://github.com/serverless-stack/serverless-stack/discussions/271

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
