### ISSUE TITLE
[SST-141] [feature request] auto-invoke `aws sso login` when the session is expired

### ISSUE THREAD

**Issue by ari-becker** [sst/sst#2690]
Sometimes I'll run an `sst` command and I'll get an error like the following:

```
Error: The SSO session token associated with profile=x was not found or is invalid. To refresh this SSO session run 'aws sso login' with the corresponding profile.
```

And then I need to invoke `aws --profile=x sso login` by myself.

It would be no small quality of life / DX improvement if either by default or by a config option, `sst` could just run that for me, so that instead of seeing an error message, I just see a browser tab open that starts the AWS SSO login flow.

<sub>[SST-141](https://linear.app/sst-dev/issue/SST-141/[feature-request]-auto-invoke-aws-sso-login-when-the-session-is)</sub>

**Comment by jayair** [comment]
Yeah we should improve this. I know @thdxr uses SSO too.

**Comment by DemonFemaleAlpha1** [comment]
hi

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
