### ISSUE TITLE
Custom tags for CDKToolkit

### ISSUE THREAD

**Issue by corvettii** [sst/sst#2694]
SSTBootstrap appears to incorporate tags from the project config, but CDKToolkit does not. CDK supports this as command line option. It would be ideal if these same tags were incorporated when the CDK bootstrap process is spawned.

**Comment by jayair** [comment]
Can you post this over on #help on Discord, so we can take a look?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
