### ISSUE TITLE
Question: how to pass props to stack in `sst.config.ts`

### ISSUE THREAD

**Issue by seanWLawrence** [sst/sst#2708]
Hi team! I searched the docs and couldn't find a pattern for passing in props to stacks that go in `sst.config.ts`. I came with this solution, but it feels a bit odd and like there either should be a more elegant way to handle this.

`sst.config.ts`

```ts
import { SSTConfig } from "sst";
import invariant from "tiny-invariant";
import { WebStack } from "./stacks/WebStack";

export default {
  config(_input) {
    return {
      name: process.env.NAME || "cobra-events",
      region: process.env.AWS_REGION || "us-east-1",
    };
  },
  stacks(app) {
    const domainName = process.env.DOMAIN_NAME || "cobra.events";
    const certificateArn = process.env.CERTIFICATE_ARN;
    invariant(domainName);
    invariant(certificateArn);

    app.stack(WebStack({ domainName, certificateArn }));
  },
} satisfies SSTConfig;
```

And then in my stack:

```ts
export function WebStack(props: WebStackProps) {
  return ({ stack }: StackContext): void => {
    const site = new RemixSite(stack, "Site", {
      path: "web/",
      customDomain: {
        isExternalDomain: true,
        domainName: props.domainName,
        domainAlias: `www.${props.domainName}`,
        cdk: {
          certificate: Certificate.fromCertificateArn(
            stack,
            "Certificate",
            props.certificateArn
          ),
        },
      },
    });

    stack.addOutputs({
      URL: site.url || "localhost",
    });
  };
}
```

Also tried:
- `Config.Parameter` and `Config.Secret` seem like they're just for Lambda functions
- Context is not ideal for this since the values aren't going to be checked into the repo

Thanks for your help!

**Comment by fwang** [comment]
Hey @seanWLawrence, just to clarify, are you looking for a way pass in the domain and certificate ARN (other than setting them as `DOMAIN_NAME` environment variable)?

**Comment by seanWLawrence** [comment]
@fwang Sorry for the confusion! I'm asking if there’s a way to pass props to a stack from the SST Config file without having to make a higher order function. 

For example, in the native CDK how we have the ability to pass it when we instantiate the new instance in the bin script. Since SST uses an un-invoked function instead, and the function signature for the ‘stack’ method doesn’t have a parameter for passing in props, it seems like you have to do something like my higher order function example. 

I don’t see anything wrong with the higher order function approach if that’s the only way to do it. I just figured it would be documented somewhere as a configuration pattern and was wondering if there's a different way to achieve this using something built-in to SST or an already established SST pattern that I can refactor this to instead. 

I’d be happy to create a PR to add an example in the docs with whichever approach you recommend.

**Comment by stephen-wigginton** [comment]
+1 this. I've been trying to cleanly pass config values to an `AstroSite` and while i can pull from env vars if they exist, they won't on a fresh pull locally and wanted to store those values somewhere else

**Comment by jayair** [comment]
Hi all, would appreciate you opening a thread in #help on Discord for this? It'll help us track it better. Feel free to link back here.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
