### ISSUE TITLE
No loader is configured for ".node" files

### ISSUE THREAD

**Issue by nbabaka** [sst/sst#2712]
Hello,
I am using axios and JSDOM 

I just got error - No loader is configured for ".node" files: node_modules/canvas/build/Release/canvas.node when tried to use jsdom

Could you help me please? Thank you!

**Comment by webdevcody** [comment]
I'm getting a similar error when trying to import pdfjs-lib.  It depends on "canvas" which causes my bundle to fail with "no loader is configured for ".node" file: ../node_modules/canvas/build/Release/canvas.node"

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
