### ISSUE TITLE
[NextJsSite] v2.3.1 :: Cannot Deploy => site/ServerFunction lacks permissions

### ISSUE THREAD

**Issue by NicholasFields** [sst/sst#2714]
Originally posted in SST Discord #help channel [link](https://discord.com/channels/983865673656705025/1090021281870655568)

-------------

command:
`pnpm run dev --stage=dev`

==>

Eventual console response:
```
Errors
NextApp ROLLBACK_COMPLETE
site/ServerFunction: Resource handler returned message: "The provided execution role does not have permissions to call CreateNetworkInterface on EC2 (Service: Lambda, Status Code: 400, Request ID: <requestId>)" (RequestToken: <requestToken>, HandlerErrorCode: InvalidRequest)
```

-------------

On rollback to v2.2.6, 
error is inhibited (after full deletion of NextJsSite construct in CloudFormation console // via `remove`).

**Comment by jayair** [comment]
Sorry for the run around. We'll follow up on Discord.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
