### ISSUE TITLE
AWS SSO Refresh Tokens

### ISSUE THREAD

**Issue by blytheaw** [sst/sst#2716]
We have been having issues where SST and/or CDK are not triggering token refresh for AWS SSO credentials using the [refresh-able token model](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html#sso-configure-profile-token-manual).

The result is that we are having to run `aws sso login` every hour when working with SST in order to have valid credentials while using AWS SSO. The SSO sessions are good for 12 hours in our configuration, but this assumes the token is refreshed. The AWS CLI is doing this when running commands, but either SST or CDK (or both?) are not doing this.

Related CDK issue: https://github.com/aws/aws-cdk/issues/24782

**Comment by tobz1000** [comment]
What was the outcome of this?

**Comment by michaelgmcd** [comment]
I don't think there's been any movement, but worth noting that running another aws cli command will refresh your session instead of having to re-run `aws sso login`. Here's the command I use:

`aws ec2 describe-instances --region us-east-1`

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
