### ISSUE TITLE
Automatic Stage Expiration

### ISSUE THREAD

**Issue by CervarlCG** [sst/sst#2727]
Is there any way to set an automatic expiration time for the state resources? i mean for example delete all functions and tables after 1 week or the especified expiration time

**Comment by jayair** [comment]
Can you post this on #help on Discord?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
