### ISSUE TITLE
Warn when `aws-cdk-lib` and `constructs` are not in sync

### ISSUE THREAD

**Issue by ryands17** [sst/sst#2746]
In SST v1, there was a nice warning during the build process when dependencies like `aws-cdk-lib` were out of sync. Is it possible to have the same for SST v2?

**Comment by jayair** [comment]
That's a good idea. Can you post this on #help on Discord?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
