### ISSUE TITLE
future/auth: "No auth provider" error swallowed in Session.verify

### ISSUE THREAD

**Issue by estyrke** [sst/sst#2770]
When calling `useSession`, `Session.verify()` -> `getPublicKey()` may throw if no auth provider is bound to the function. This error is silently swallowed in Session.verify.

**Comment by jayair** [comment]
Hey Emil, can you post this on #help on Discord? I'll have the team look at it.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
