### ISSUE TITLE
sst CLI hangs when function runtime is set to 'python3.9'

### ISSUE THREAD

**Issue by jimboboliver** [sst/sst#2779]
I'm trying to deploy a lambda function with the python3.9 runtime as part of a very basic stack. It hangs indefinitely. If I delete runtime and let it default, SST CLI doesn't hang. 

SST: 2.5.2
CDK: 2.72.1

**Comment by james1050** [comment]
Maybe related to #2334 but I don't get any error.

**Comment by jayair** [comment]
Can you post this in #help on Discord?

**Comment by goxvaetva101** [comment]
Any updates on this, can't deploy any python functions after upgrading to sst v2, it hangs for me in indefinitely too.

**Comment by jayair** [comment]
We opened a new channel to track these, can you post this on #python?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
