### ISSUE TITLE
Bug: Runtime.ImportModuleError when using dot in s3 notification function handler name

### ISSUE THREAD

**Issue by m4tty-d** [sst/sst#2783]
Using a dot in an s3 notification function handler name is causing a Runtime.ImportModuleError on a production deployment. (it doesn't happen locally.)

```
bucket.addNotifications(stack, {
  onObjectCreated: {
    function: {
      handler: "packages/functions/src/events/csv.created.handler",
    },
    events: ["object_created"],
  },
});
```

Error from CloudWatch:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/6316925/232233748-35893d9b-9a9f-4e6b-a9e6-4741640f6a05.png">

**Comment by brubraz** [comment]
I am experiencing the same issue. I am using lambdas for the API.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
