### ISSUE TITLE
rest-api example error

### ISSUE THREAD

**Issue by jamienz** [sst/sst#2798]
SST v2.5.7, Windows 11, GitBash, VS Code, node v16.19.1

I followed this guide: https://sst.dev/examples/how-to-create-a-rest-api-with-serverless.html

When I go to the API Explorer and click the Send button for GET /notes my terminal shows

> Invoked packages/functions/list.handler
>
>✖  Build failed packages/functions/list.handler
>   Could not find file for handler "packages/functions/list.handler"

The routes for the api are: 
```
const api = new Api(stack, "Api", {
    routes: {
        "GET /notes": "packages/functions/list.handler",
         "GET /notes/{id}": "packages/functions/get.handler",
        "PUT /notes/{id}": "packages/functions/update.handler",
    },
  });
```

and the instructions say: 

> Getting a list of notes
> Add a packages/functions/src/list.ts.

Changing the routes by adding `src` fixes it:
```
const api = new Api(stack, "Api", {
    routes: {
        "GET /notes": "packages/functions/src/list.handler",
         "GET /notes/{id}": "packages/functions/src/get.handler",
        "PUT /notes/{id}": "packages/functions/src/update.handler",
    },
  });
```

Is that `src` change necessary, or have I gone wrong somewhere?

**Comment by jayair** [comment]
Oh no the steps are wrong. There should be a `src.

Can I bother you to edit it and submit a PR: https://github.com/AnomalyInnovations/serverless-stack-com/edit/master/_examples/how-to-create-a-rest-api-with-serverless.md

**Comment by jamienz** [comment]
done https://github.com/AnomalyInnovations/serverless-stack-com/pull/711

**Comment by jamienz** [comment]
The fix is merged and live already.  Thanks @jayair

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
