### ISSUE TITLE
Get built static site after environment variables are replaced

### ISSUE THREAD

**Issue by bblanke** [sst/sst#2809]
We use a mono repo to deploy an Angular application, which is then packaged into a native app with electron.

The StaticSite construct makes it really easy to deploy our site while filling in necessary environment variables (user pool id, api endpoint, etc.), but there's no way (as far as I know) to access the built site with its environment variables already replaced.

SST fills in environment variables with placeholders at build-time. So after my site is built, I will end up with files that contain, for example, `{{ USER_POOL_ID }}`, instead of the actual user pool id, in my `dist` folder. At some point, I believe while uploading those `dist` files to S3, those placeholders are filled in with their actual values.

I would like to access those files after they've had their values swapped in so that I can re-package the configured application into an electron app.

Is there a good way to do this? Has anyone else had experience deploying both a site and a native app with SST?

**Comment by jayair** [comment]
Hmm that's interesting. We didn't really plan for this use case because we can only get those values after they are deployed. So those tokens get replaced later. Can you open a thread in #help on Discord and we can figure out how to do this?

**Comment by AMar4enko** [comment]
@jayair excuse me good sir, could you please elaborate on `We didn't really plan for this use case` part?
If that's the case, SST documentation is completely misleading, since documentation example is exactly the use case in the question.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
