### ISSUE TITLE
createClient should be new Client in create-sst@latest

### ISSUE THREAD

**Issue by kewp** [sst/sst#2819]
Busy going through the starter tutorial https://docs.sst.dev/learn/create-a-new-project and there's a bug in `packages/web/src/main.tsx` - on line 14 it uses `createClient` when it should be `new Client`.

> i know i should open a pull request ... to be honest never done that before

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
