### ISSUE TITLE
StaticSite with Lambda@Edge on VIEWER_REQUEST event not deployable

### ISSUE THREAD

**Issue by PedroHase** [sst/sst#2822]
_(Follow-up from my post on https://discord.com/channels/983865673656705025/1101619447858470914)_

## Description
I tried to add a Lambda@Edge function to a `StaticSite` construct using the `VIEWER_REQUEST` event trigger to intercept requests to the Cloudfront Distribution:

```ts
const frontend = new StaticSite(stack, 'frontend', {
    path: 'frontend',
    cdk: {
      distribution: {
        defaultBehavior: {
          edgeLambdas: [
            {
              functionVersion: edgeFn.currentVersion,
              eventType: LambdaEdgeEventType.VIEWER_REQUEST,
            },
          ],
        },
      },
    },
  });
```

Unfortunately, I am getting following error when trying to deploy my frontend stack with this construct setup:

```
The event type of a function association must be unique in the cache behavior. Event type viewer-request cannot be associated with two functions
```

<details>

<summary>Error Details</summary>

```text
CREATE_FAILED Resource handler returned message: "Invalid request provided: AWS::CloudFront::Distribution: The event type of a function association must be unique in the cache behavior. Event type viewer-request cannot be associated with two functions: null and amazon.edge.datastore.entity.HookFunctionAssociation@3be8dab7[cacheBehaviorId=<null>,hookType=viewer-request,functionArn=<null>,bufferingFunctionArn=<null>,goalFunctionArn=arn:aws:lambda:us-east-1:378132197614:function:dev-functionname-edgegoogleauth7F68702C-hZxjlyepHu2g:2,includeBody=false,bufferingIncludeBody=false,goalIncludeBody=false,changeNumber=<null>]. (Service: CloudFront, Status Code: 400, Request ID: 30c39fb0-551e-435f-b644-dde2194c896d)" (RequestToken: bfd9c33e-2ffd-5d00-984f-88d0c0612272, HandlerErrorCode: InvalidRequest)
```

</details>

The issue is likely caused by the fact that in `StaticSite` a CloudFront function is being added internally for the `VIEWER_REQUEST` event as well:

https://github.com/serverless-stack/sst/blob/2877fd13c4ccf2840ed7758c29ab32ac6ea9102b/packages/sst/src/constructs/StaticSite.ts#L870-L890

Removing above lines allowed me to deploy the app. I suspect that the Cloudfront function and Lambda@Edge function are in conflict/cannot run at the same time? (That would at least explain the `Event type viewer-request cannot be associated with two functions` error)

## How to Reproduce

1. Create a clean sst app
2. Create a frontend stack and add following code:
<details>

<summary>Code Example</summary>

The code was taken from https://docs.sst.dev/constructs/StaticSite#using-lambdaedge

```ts
const edgeFn = new experimental.EdgeFunction(stack, 'edge-fn', {
    runtime: Runtime.NODEJS_16_X,
    handler: 'index.handler',
    code: Code.fromInline(`
      exports.handler = function() {
        return {
          status: "200",
          body: "Hello, World!"
        }
      }
`),
    stackId: `${app.logicalPrefixedName('edge-fn')}`,
  });

const frontend = new StaticSite(stack, 'frontend', {
    path: 'frontend',
    buildOutput: 'dist',
    buildCommand: `npm build`,
    cdk: {
      distribution: {
        defaultBehavior: {
          edgeLambdas: [
            {
              functionVersion: edgeFn.currentVersion,
              eventType: LambdaEdgeEventType.VIEWER_REQUEST,
            },
          ],
        },
      },
    },
  });
```

</details>

3. Deploy the app (e.g. `pnpm run deploy`)
4. See that the above error occurs

## How to Verify the Issue

1. Remove the `functionAssociations` prop from `StaticSite` in `node_modules/sst/constructs/StaticSite.js` (inside the `buildDistributionBehavior` method)
2. Redeploy the app
3. The deployment should work now

##  Expected Behavior

I would expect that I can use the `VIEWER_REQUEST` event with Lambda@Edge and the `StaticSite` construct.

**Comment by jayair** [comment]
We'll follow up on Discord!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
