### ISSUE TITLE
Unable to use NextAuth with Next.js middleware

### ISSUE THREAD

**Issue by pablote** [sst/sst#2828]
I just created a vanilla Next.js site, added SST and NextAuth to it, and tested several NextAuth use cases to see if/how it worked. Pretty much everything works as expected except middleware enforcing authentication.

This is the middleware code:
```js
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import nextAuthFn from "next-auth/middleware";

export default async function middleware(request: NextRequest) {
  if (request.nextUrl.pathname === "/restricted") {
    const resp = await nextAuthFn(request);
    if (resp) {
      return resp;
    }
  }

  const resp = NextResponse.next();

  return resp;
}
```

And the application breaks returning a 500 error with no response:

<img width="824" alt="A" src="https://user-images.githubusercontent.com/2463995/235807904-6c5b7c4d-2228-43f9-952e-14017a9e6d6e.png">
<img width="1443" alt="B" src="https://user-images.githubusercontent.com/2463995/235807929-354d5ec5-6c64-468a-a59d-e4db2934a3da.png">

Is not just the protected paths under `/restricted` that fail because of this, but the root and any other path. If I remove the middleware file everything else works fine. If I keep the middleware file but I comment out anything related with NextAuth it also works. There seems to be something going on about using NextAuth from within a middleware that makes SST fail.

Thanks.

**Comment by jayair** [comment]
Can you post this in #open-next on Discord?

**Comment by pablote** [comment]
Ok, I will. Adding another bit of information I just found. This gets logged when the application fails:

<img width="1188" alt="Screenshot 2023-05-02 at 9 07 45 PM" src="https://user-images.githubusercontent.com/2463995/235811550-7bddb4df-00c5-4465-9339-f7c7bc42295b.png">

**Comment by jayair** [comment]
Also post on there? We don't use GitHub issues for support.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
