### ISSUE TITLE
NextJS Site not serving from cache because cookie is being included.

### ISSUE THREAD

**Issue by nathabit** [sst/sst#2830]
Cloud front is not serving images from cache because cookie being accounted for considering request as unique.

`curl 'https://d1amksygxpvlmf.cloudfront.net/_next/image?url=https%3A%2F%2Fnh-media.s3.ap-south-1.amazonaws.com%2Fwinter_essentials_web_2275f950a9.jpg&w=828&q=50' \
  -H 'authority: d1amksygxpvlmf.cloudfront.net' \
  -H 'accept: image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'accept-language: en-IN,en-GB;q=0.9,en;q=0.8,en-US;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'cookie: cart=eyQBdSbeHK9Q2tV5ZTDw; _ga=GA1.1.1389810058.1683098351; _ga_EMTPKPT3P9=GS1.1.1683098351.1.1.1683099122.0.0.0' \
  -H 'pragma: no-cache' \
  -H 'referer: https://d1amksygxpvlmf.cloudfront.net/' \
  -H 'sec-fetch-dest: image' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 Edg/112.0.0.0' \
  --compressed`
  
  `curl 'https://d1amksygxpvlmf.cloudfront.net/_next/image?url=https%3A%2F%2Fnh-media.s3.ap-south-1.amazonaws.com%2Fwinter_essentials_web_2275f950a9.jpg&w=828&q=50' \
  -H 'authority: d1amksygxpvlmf.cloudfront.net' \
  -H 'accept: image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'accept-language: en-IN,en-GB;q=0.9,en;q=0.8,en-US;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'cookie: cart=eyQBdSbeHK9Q2tV5ZTDw; _ga=GA1.1.1389810058.1683098351; _ga_EMTPKPT3P9=GS1.1.1683098351.1.1.1683099146.0.0.0' \
  -H 'pragma: no-cache' \
  -H 'referer: https://d1amksygxpvlmf.cloudfront.net/' \
  -H 'sec-fetch-dest: image' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 Edg/112.0.0.0' \
  --compressed`
  
  
 Request for same image results in **Miss From Cloudfront** because cookie value of **_ga** (Google analytics) changes on every request.

**Comment by jayair** [comment]
I thought WebDevCody worked on this too? https://www.youtube.com/watch?v=BjjnDu0KRfE

**Comment by jayair** [comment]
If you don't figure it out, post this on #help on Discord.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
