### ISSUE TITLE
Nextjs 13 app directory: Can't render page when using dynamic routes

### ISSUE THREAD

**Issue by Donngi** [sst/sst#2834]
I'm beginner of Nextjs and SST, so I apologize if I am asking the wrong questions.

### Overview
When I use NextjsSite constructs with Nextjs 13 app directory, pages using dynamic routes returns 500 error.

### Question
Does NextjsSite constructs support Nextjs 13 app dir? 
Do I need to do any additional configuration to use app dir?
(I couldn't find documents about supporting status of app dir.)

### To Reproduce
Use this repo.
https://github.com/Jimon-s/sst-app-dir-dynamic-routes-issue

```shell
npx sst deploy 
```

Then, open `https://xxxx.cloudfront.net/test`.
(test is [slug])

When I provision nextjs site locally (with `npx next dev`), there are no errors.

### Error log
ServerFunction lambda records a following error.

```
ERROR	TypeError: Cannot set properties of undefined (setting 'current')
    at ue (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:113:42)
    at /var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:151:127
    at new Promise (<anonymous>)
    at exports.renderToReadableStream (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:151:53)
    at /var/task/node_modules/next/dist/server/node-web-streams-helper.js:195:117
    at NextTracerImpl.trace (/var/task/node_modules/next/dist/server/lib/trace/tracer.js:86:20)
    at renderToInitialStream (/var/task/node_modules/next/dist/server/node-web-streams-helper.js:195:37)
    at /var/task/node_modules/next/dist/server/app-render/app-render.js:937:92
```

**Comment by jayair** [comment]
Can you post this on #help and we'll take a look!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
