### ISSUE TITLE
dotnet 6 bootstrap selection and special caractes input.out

### ISSUE THREAD

**Issue by deb-oliveira** [sst/sst#2836]
There's currently an issue with the way the bootstrap selection works for .NET 6 and the handling of quotes in input.out, which results in failures when trying to run .NET 6 applications or build in directories with special characters. 

Example 1: Unable to run .NET 6 due to incorrect bootstrap

In this example, the user could not run a .NET 6 application because the bootstrap selected was for .NET Core 3.1:

The application failed to launch with the following error:

```
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '3.1.0' (arm64)
.NET location: /usr/local/share/dotnet/

The following frameworks were found:
  6.0.16 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  7.0.5 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=arm64&rid=osx.13-arm64
```

Example 2: Build error due to special characters in the path

The user encountered a build error when working in a directory with special characters, such as an ampersand (&) in the path:

```
/Users/.../OneDrive-Company&Company/...
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
