### ISSUE TITLE
Extending `Table` breaks generated types for `sst/node/table`

### ISSUE THREAD

**Issue by mikestopcontinues** [sst/sst#2841]
To add some consistency to the naming of keys and indexes in Dynamo, I ported over an old CDK construct to SST.

```ts
class CleanTable extends Table {}
```

However, doing so breaks the generated types for `sst/node`:

```ts
import "sst/node/table";
declare module "sst/node/table" {
  export interface CleanTableResources { // should be `TableResources`
    "SessionsTable": {
      tableName: string;
    }
  }
}
```

For the time being, I'll clean this up using composition:

```ts
class CleanTable {
  table: Table;
}
```

However, I think this gotcha would be better if remedied. It's definitely not what you'd expect.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
