### ISSUE TITLE
Multiple cloudformation and cloudfront getting created.

### ISSUE THREAD

**Issue by anil1712** [sst/sst#2842]
Hi,

I am using SST with NextJS projects, its working like a charm but somehow it is creating the another cloudfront distributions when I am running the build command from multiple machines. Like for example we do have 4 developers working on single project and if each of running the deploy command then its is generating 4 URLs for each of us. 

Let me know if anyone experiencing the same issue. 

Thanks,
Anil

**Comment by jayair** [comment]
Yeah it creates a new environment or stage per developer; it'll ask you this when you first run sst and store it in `.sst`. This is recommended. When you deploy to prod though pick a stage name that you'll all use and it'll deploy it together: https://docs.sst.dev/what-is-sst#environments

**Comment by anil1712** [comment]
ok got it @jayair
Thanks for the quick reply

**Comment by anil1712** [comment]
@jayair It worked! 
So it means I need to push the `.sst` into the git repo? Right now its around 90MB for me.

**Comment by jayair** [comment]
No no that's just for your local environment. Everybody on your team will get their own.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
