### ISSUE TITLE
Support Java 17 runtime

### ISSUE THREAD

**Issue by julbrs** [sst/sst#2855]
Hi!

CDK is supporting Java 17 since [2.77](https://github.com/aws/aws-cdk/releases/tag/v2.77.0). I would love to see this in SST now 🤟 

I can work on a PR if needed ;) 

Thanks !

**Comment by jayair** [comment]
Ah would appreciate it!

**Comment by julbrs** [comment]
It's here @jayair 🤓 #2870 
(require CDK version bump 🙈)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
