### ISSUE TITLE
Python 3.10 runtime support 

### ISSUE THREAD

**Issue by hookercookerman** [sst/sst#2884]
supporting this would be great

**Comment by jayair** [comment]
Join the #python channel on Discord!

**Comment by hookercookerman** [comment]
seems to be with the recent cdk updates this is a 2 line change. whilst one could submit a PR it seems easier to leave the changes to you, but I can if you feel it necessary

**Comment by jayair** [comment]
Which version of CDK is this? Since my last comment we did a CDK update. Is it in there by any chance?

**Comment by hookercookerman** [comment]
v2.84.0

https://github.com/aws/aws-cdk/blob/v2.85.0/packages/aws-cdk-lib/aws-lambda/lib/runtime.ts#L139

**Comment by jayair** [comment]
https://github.com/serverless-stack/sst/releases/tag/v2.16.0

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
