### ISSUE TITLE
Module '"sst/node/api"' has no exported member 'WebSocketApi'.ts(2305)

### ISSUE THREAD

**Issue by twiddler** [sst/sst#2893]
```ts
import { WebSocketApi } from "sst/node/api";
```

as per [the docs](https://docs.sst.dev/clients/api#websocketapi) results in

>Module '"sst/node/api"' has no exported member 'WebSocketApi'.ts(2305)

It looks like this export was moved to `sst/node/websocket-api` in #2817 but without appropriate exports. I used to be able to access `WebSocketApi.url`, but now that causes

>Property url does not exist on type WebSocketApiResources.

**Comment by jayair** [comment]
Oh weird. Let me ask the team to take a look.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
