### ISSUE TITLE
[astro-sst] Unable to get client IP address

### ISSUE THREAD

**Issue by ffxsam** [sst/sst#2918]
In our Astro SST app, we're using `Astro.clientAddress` and passing that to MaxMind's API to fetch geo info. However:
```json
{
    "errorType": "ClientAddressNotAvailable",
    "errorMessage": "`Astro.clientAddress` is not available in the `astro-sst/lambda` adapter. File an issue with the adapter to add support.",
    "type": "AstroError",
    "errorCode": 3002,
    "name": "ClientAddressNotAvailable",
    "title": "`Astro.clientAddress` is not available in current adapter.",
    "message": "`Astro.clientAddress` is not available in the `astro-sst/lambda` adapter. File an issue with the adapter to add support.",
    "loc": {
        "file": "src/pages/[...slug].astro"
    },
    "stack": [
        "ClientAddressNotAvailable: `Astro.clientAddress` is not available in the `astro-sst/lambda` adapter. File an issue with the adapter to add support.",
        "    at get clientAddress [as clientAddress] (file:///var/task/dist/server/entry.mjs:2459:21)",
        "    at file:///var/task/dist/server/entry.mjs:138348:47",
        "    at AstroComponentInstance.PrivateReel [as factory] (file:///var/task/dist/server/entry.mjs:111:12)",
        "    at AstroComponentInstance.init (file:///var/task/dist/server/entry.mjs:3470:33)",
        "    at AstroComponentInstance.render (file:///var/task/dist/server/entry.mjs:3475:22)",
        "    at render.next (<anonymous>)",
        "    at renderChild (file:///var/task/dist/server/entry.mjs:522:18)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async EagerAsyncIterableIterator.next (file:///var/task/dist/server/entry.mjs:3363:18)",
        "    at async [Symbol.asyncIterator] (file:///var/task/dist/server/entry.mjs:3445:11)"
    ]
}
```
And since SST's `AstroSite` generates the Lambda function, there's (apparently) no way to access the raw `event` object to grab the client's IP.

**Comment by ffxsam** [comment]
Temporary workaround: using `Astro.request.headers.get('x-forwarded-for')`.

**Comment by lostra01** [comment]
That's not a temporary solution, that's basically what every adapter in Astro does. For instance, here's the relevant parts from the Vercel adapter:

`
const clientAddressSymbol = Symbol.for('astro.clientAddress');
...
...

Reflect.set(request, clientAddressSymbol, headers['x-forwarded-for']);
`

See whole code here: [https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/serverless/request-transform.ts](url)

**Comment by ffxsam** [comment]
@lostra01 IMO this is a workaround, not the solution.

https://docs.astro.build/en/reference/api-reference/#astroclientaddress

People using Astro and referencing the official docs will expect `Astro.clientAddress` to work, which it doesn't currently (with this adapter).

**Comment by lostra01** [comment]
@ffxsam We had a misunderstanding, what I mean is that we need the `x-forwarded-for` pull in the adapter itself. That's what the rest of the SSR adapters do. They just get that header and provide it via `Astro.clientAddress`

**Comment by ffxsam** [comment]
Ah, gotcha! We're on the same page.

**Comment by bayssmekanique** [comment]
This is an annoying feature gap. I'll take a swing at addressing it soon.
