### ISSUE TITLE
Using a KMS key to generate data encryption keys for a Next.js Site

### ISSUE THREAD

**Issue by wpoynter** [sst/sst#2923]
I think I have stumbled upon a potential use case where SST does not produce the most secure outcome. In my case, I have a Next.js site in which I would like each user to be issued a data encryption key. Therefore, I would like the server function have the required permissions (e.g. "kms:GenerateDataKey") to the key. I can use CDK to create the Key and then pass the ARN as an environment variable to the site, but I cannot pass the key to `.attachPermissions` as augmenting the IAM role permissions cannot give access to a KMS key (the permissions must be defined on the resource). If I try to use the role ARN generated by the Next.js site as the principal of the key resource policy, then I have a circular dependency.

At first, I thought I could create a separate IAM role, give it access to the key and then pass it to Next.js site, but I cannot find an opportunity to pass an existing role to `NextjsSite`.

As a result, I have generated the key using principal conditions in an attempt to limit the scope of access to just the server function, but this is a lot less robust than ensuring the key can only be used by the required role. 

I can put an example together of this if it would be helpful.

**Comment by jayair** [comment]
Hmm I'll need to ask the team to take a look. Can you post this on #help on Discord?

**Comment by wpoynter** [comment]
I will join Discord and get on it.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
