### ISSUE TITLE
Reference Imagelambda function in the cloudformation output

### ISSUE THREAD

**Issue by abhishek-chandrasekar** [sst/sst#2933]
Some of the components created (Image Function) cannot be referenced in the outputs section of the code and therefore we are unable to obtain them as cloudformation outputs.
We do not want the lambda's to be deployed as they do not serve any purpose to our usecase.

```
 stack.addOutputs({
      WebURL: site.customDomainUrl || site.url || "unknown",
      CloudfrontDistId: site.cdk?.distribution.distributionId ?? "unknown",
      ImageLambdaId: site.cdk.function,
      Foo: 'bar'
    });
```
    
 The outputs for all the above parameters appear in cloudformation except for the ImageLambdaId
 
we have also tried the below
```
    /*site.cdk?.CfnOutput(this, 'ImageFunctionArn', {
      value: site.cdk?.ImageFunction.functionArn,
      description: 'The ARN of the Image function'
    });*/
```

Is there a way to reference them? Thanks

**Comment by jayair** [comment]
Can you post this on #help on Discord?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
