### ISSUE TITLE
app.setDefaultFunctionProps overrides local DockerImageFunction settings

### ISSUE THREAD

**Issue by mixman** [sst/sst#2935]
Hi,

Global settings like `app.setDefaultFunctionProps({memorySize: 1024})` override `DockerImageFunction(stack, 'MyFun', { memorySize: 2048 })` settings. Also, when no memorySize is specified the globals are not applied for DockerImageFunction resulting in default CDK memorySize of 128.

This can be worked around via use of `stack.setDefaultFunctionProps({memorySize: 2048})`.

**Comment by jayair** [comment]
Oh let me ask the team to take a look.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
