### ISSUE TITLE
[NextjsSite] Replace/Specify execution role of ServerSide function

### ISSUE THREAD

**Issue by mtkcs** [sst/sst#2952]
Hello,

We have policies/roles left from an older projet and want to use those for the lambda. currently SST manages the creation of the role/policies of the ServerSide function:

- Is there a way to change or specify the **execution role** to reference an existing one?
- Is there a way to attach existing **policies** to the ServerSide function?

Thank you,

**Comment by jayair** [comment]
Can you post this in #help on Discord? I'll get the team to take a look.

**Comment by mtkcs** [comment]
@jayair done:

https://discord.com/channels/983865673656705025/1083422760111439973/threads/1115536332362633346

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
