### ISSUE TITLE
Make Bucket construct support unauthenticed access to files

### ISSUE THREAD

**Issue by inorganik** [sst/sst#2955]
When I create a Bucket like so, and try to use `Storage.put()` method to create a publicly accessible file, I keep getting "Access denied". Amplify docs explain how to set up a bucket to make uploaded files publicly accessible, but I don't think the construct support this.

```ts
// Create an S3 bucket
  const bucket = new Bucket(stack, "Uploads", {
    cors: [
      {
        maxAge: "1 day",
        allowedOrigins: ["*"],
        allowedHeaders: ["*"],
        allowedMethods: ["GET", "PUT", "POST", "DELETE", "HEAD"],
      },
    ],
  });
```

```ts
import { Storage } from "aws-amplify";

export async function s3Upload(file) {
  const filename = `${Date.now()}-${file.name}`;

  const stored = await Storage.put(filename, file, {
    contentType: file.type,
  });

  return stored.key;
}
```

This call always results in 403 Access denied.

According to Amplify docs, you should be able to configure a bucket for publicly accessible files: https://docs.amplify.aws/lib/storage/getting-started/q/platform/js/#using-amazon-s3

**Comment by jayair** [comment]
Replied on Discord

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
