### ISSUE TITLE
SSR Site construct support for base path option

### ISSUE THREAD

**Issue by Ankcorn** [sst/sst#2964]
All the SSR frameworks support rendering on a base path like 

example.com/docs

* svelte - https://kit.svelte.dev/docs/configuration#paths
* astro - https://docs.astro.build/en/reference/configuration-reference/#base
* next - https://nextjs.org/docs/pages/api-reference/next-config-js/basePath

I can't get this working with sst  :(

**Comment by jayair** [comment]
Hey Thomas, can you post this on #help and we'll take a look at supporting it.

**Comment by jplwood** [comment]
@jayair Any updates on this? Searching discord just turns up workarounds and callouts that `basePath` isn't currently supported. We use `basePath` extensively  with multiple apps behind a reverse proxy, so not having having `basePath` is certainly a hindrance!

**Comment by jayair** [comment]
I think this is supported for Astro and maybe Next.js. Which one are you looking for?

**Comment by jplwood** [comment]
Next.js, yeah, we use it in our app's Next config, but when deployed with SST, that basePath isn't used as a prefix in cloudfront (specifically the app looks for static bundles at `<basePath>/.next/*`, but the cloudfront route has it as `.next/`. That was at least the obvious one, not sure if there are other places it should apply. 

I've got a workaround for now, but certainly would be nice if the next construct used it when defining the CF routing rules!

**Comment by jayair** [comment]
Let me check on the Next.js one with the team.

**Comment by jplwood** [comment]
I derped/lied. My workaround doesn't actually solve the issue. Regarding what I said before: 
> We use basePath extensively with multiple apps behind a reverse proxy

Without base path support, my next app will request all static bundles and such from the root path `/`. When behind a reverse proxy, the routing rules will have no idea that the `/` root requests should be routed to my app without putting all requests behind a `basePath`. Those requests will be sent to the default routing rule.

So this remains a big hindrance.

**Comment by jplwood** [comment]
@jayair since I saw how it was previously done, went ahead and opened a suggested PR ☝️ to address at least the Next.js part of this issue.

**Comment by eschaefer** [comment]
Just wanted to bump this, since using `basePath` seems to result in `403` forbidden errors for static assets for me. Just curious if anyone else using `basePath` experiences this?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
