### ISSUE TITLE
adding `#fallback` breaks importing secrets

### ISSUE THREAD

**Issue by henrycrib** [sst/sst#2977]
adding `#fallback` breaks importing secrets

https://github.com/serverless-stack/sst/blame/7afe93fde25ae03277d1f60381ec3e99d3243d73/packages/sst/src/cli/commands/secrets/list.ts#L46

Filtering by fallback values should not be done this way.

**Comment by jayair** [comment]
Can you post this in #help and we'll take a look? Or submit a PR?

**Comment by henrycrib** [comment]
newb question? what is #help?

**Comment by jayair** [comment]
Sorry #help on Discord.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
