### ISSUE TITLE
future/auth: handle trailing slash

### ISSUE THREAD

**Issue by devlsh** [sst/sst#2985]
Posted on Discord already, but thought it be better to post here as well;

Some OAuth systems that don't follow the OAuth spec (Or do, but in my experience, I've only had this issue with one that doesn't follow the spec) will forcibly append a trailing slash to the callback URL regardless of input.

Currently, future/auth doesn't handle this, and it just 404s - would be awesome if it could handle both with/without trailing slash on the callback path.

**Comment by caesarisme** [comment]
Same problem Ive had experienced with amplify, the [issue](https://github.com/aws-amplify/amplify-cli/issues/7359) still open for 2 years. Probably it worth to make this thing configurable

**Comment by jayair** [comment]
Can we post this in #auth on Discord so we work on it? Maybe tag @thdxr as well.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
