### ISSUE TITLE
[NextjsSite] Using custom L2 constructs in NextjsSite

### ISSUE THREAD

**Issue by guillaumeduboc** [sst/sst#3019]
First of all thanks a lot for all the impressive work on SST! 

In my current project I have a library of L2 constructs enforcing some configuration for Lambda functions, buckets, distributions, etc. 
I'd like to use them as building blocks inside the NextjsSite.

Have you thought about how the construct can build on top of such custom constructs? 

From what I read, a first possibility would be to extend the NextjsSite and overwrite methods creating resources. This would require to change private methods to protected. It's not great in the long run as the extension would copy some of the logic that you guys have created.

To go a step further, I thought we could use create functions such as https://github.com/serverless-stack/sst/blob/d615080013d8fc09d1bfc93bfe53284866d71c5f/packages/sst/src/constructs/SsrSite.ts#L711-L727 for basic resources (distribution, lambdas, queue). A user that want to use its custom L2 constructs would simply override these protected create methods.

What do you think ?

**Comment by jayair** [comment]
Do you mind sharing what the process is for your team? So you want to use existing buckets and distributions? Or is it that you want to enforce some config for creating new ones?

Also if you wouldn't mind sharing what some of these constraints are?

**Comment by guillaumeduboc** [comment]
We would like to enforce configuration for new ones

for example we have a class

```ts
import {
  BlockPublicAccess,
  Bucket,
  BucketAccessControl,
  BucketEncryption,
  BucketProps,
} from "aws-cdk-lib/aws-s3";
import { Construct } from "constructs";
import { CustomBucketSecurityError } from "../../errors";

export interface CustomBucketProps extends BucketProps {
  publicReadAccess?: false;
  accessControl?: BucketAccessControl.PRIVATE;
  encryption?: BucketEncryption.S3_MANAGED;
  enforceSSL?: true;
}

export class CustomBucket extends Bucket {
  constructor(scope: Construct, id: string, props?: CustomBucketProps) {
    if (
      props?.blockPublicAccess != null &&
      props?.blockPublicAccess !== BlockPublicAccess.BLOCK_ALL
    )
      throw new CustomBucketSecurityError(
        "All public access must be blocked. Please set blockPublicAccess to BLOCK_ALL."
      );
    if (props?.publicReadAccess != null && props?.publicReadAccess !== false)
      throw new CustomBucketSecurityError(
        "publicReadAccess must be set to false."
      );
    if (
      props?.accessControl != null &&
      props?.accessControl !== BucketAccessControl.PRIVATE
    )
      throw new CustomBucketSecurityError(
        "accessControl must be set to Private."
      );
    if (
      props?.encryption != null &&
      props?.encryption !== BucketEncryption.S3_MANAGED
    )
      throw new CustomBucketSecurityError(
        "encryption must be set to S3_MANAGED."
      );
    if (props?.enforceSSL != null && props?.enforceSSL !== true)
      throw new CustomBucketSecurityError(
        "enforceSSL must be set to true, so that encryption is enforced in transit with SSL."
      );


    super(scope, id, {
      ...props,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      publicReadAccess: false,
      accessControl: BucketAccessControl.PRIVATE,
      encryption: BucketEncryption.S3_MANAGED,
      enforceSSL: true,
    });
  }
}
```

it is used by multiple teams and it is our way to have some configuration enforced to all.

in this specific case, we could give the bucket through the cdk props. But for functions, the queue or the distribution, this wouldn't work.

I was thinking that having factory methods to create resources would give that possibility. Kind of like the abstract factory design pattern, with a default implementation

I can open a draft PR to show what I was thinking about

**Comment by guillaumeduboc** [comment]
Here would be a simple diff https://github.com/serverless-stack/sst/compare/master...guillaumeduboc:feat%2Ffactory-methods-for-nextjssite

Let me know if you have some feedback

**Comment by jayair** [comment]
Yeah this is interesting. I'll need to talk to the team about this. It'll be nice to figure out a good pattern that we can use across the board for this.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
