### ISSUE TITLE
NextJsSite - Unable to replace CloudFront Distribution

### ISSUE THREAD

**Issue by liam-reilly** [sst/sst#3022]
I've found that when using the NextJsSite construct you can only override the values of the CloudFront distribution that the construct creates for you. 

This behaviour does not match the StaticSite construt which allows you to decide if you want to ovrride the values or replace the CloudFront distribution entirely.

I have a requirement to spin up CloudFront distributions separately and attach sites to them afterwards. Can this construct be updated to bring consistency between the two constructs? 

Thanks

**Comment by jayair** [comment]
Replied in Discord I think

**Comment by khuezy** [comment]
I can take a stab at this tomorrow.

**Comment by zhavir** [comment]
Any update on this?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
