### ISSUE TITLE
[BREAKING] Deploying AstroSite creates invalid CloudFront origins

### ISSUE THREAD

**Issue by ffxsam** [sst/sst#3063]
Reproduction: https://github.com/ffxsam/repro-sst-cloudfront

Result in CloudFront:

<img width="1114" alt="CleanShot 2023-07-01 at 15 01 51" src="https://github.com/serverless-stack/sst/assets/12532733/cc7ec559-bac2-4e53-ad1b-8129fec6c0e4">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
