### ISSUE TITLE
500 Internal Server Error when using i18n & rewrites

### ISSUE THREAD

**Issue by ignaciolarranaga** [sst/sst#3064]
Hi guys, there seems to be an error when using pages router together with rewrites and i18n (not sure if all the components are really needed).

I created this repo for reproduction: https://github.com/ignaciolarranaga/sst-issue, the steps are in the main page, but basically is to click any of the links which I think are preloaded in the backend then causing the error.

This is what you will see:
<img width="1032" alt="Screenshot 2023-07-01 at 18 35 45" src="https://github.com/serverless-stack/sst/assets/15932965/f184dc74-ee34-45e9-9d44-b20741888175">

**Comment by jayair** [comment]
Can you post this over on #help on Discord? Or maybe you might've already.

**Comment by ignaciolarranaga** [comment]
Already did it 😎

**Comment by 516310460** [comment]
I have also encountered it. Do you currently have a solution

**Comment by 516310460** [comment]
AWS console output:

**Comment by ignaciolarranaga** [comment]
I'm afraid not @516310460 , I actually reverted the code I migrated to the app router back to the pages router (very frustrating experience let me tell you 😞 ). In retrospective I think it might be too early to move to the app directory.

The other thing I realize during the migration is that to debug the server components might be a real pain.
Everything run smoothly on local, even in production mode, but the execution in the edge is kind of a blackbox that is hard to handle.

**Comment by 516310460** [comment]
I'm not sure if I can support output: 'hybrid'

> I'm afraid not @516310460 , I actually reverted the code I migrated to the app router back to the pages router (very frustrating experience let me tell you 😞 ). In retrospective I think it might be too early to move to the app directory.
> 
> The other thing I realize during the migration is that to debug the server components might be a real pain. Everything run smoothly on local, even in production mode, but the execution in the edge is kind of a blackbox that is hard to handle.

I'm not sure if I can support output: 'hybrid'

**Comment by 516310460** [comment]
> 

In astro

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
