### ISSUE TITLE
SnapStart support

### ISSUE THREAD

**Issue by dundalek** [sst/sst#3066]
[SnapStart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html) is a game changer for Java runtime which suffers long start times (even more for Clojure which starts even slower). For example in my demo Clojure lambda cold start initialization time 1.7s went down to 220 ms restore time.

It probably makes sense to wait if SnapStart gets support for other runtimes other than Java before exposing the option. I am opening an issue to track it and share a workaround to enable SnapStart for Java lambdas that may be useful to other people. 

I came up with a following helper function:
```ts
function snappyFunction(stack, id, props) {
  const fn = new Function(stack, id, props);

  // SST does not expose option to enable SnapStart, but we can reach in the inner construct.
  const cfnFunction = fn.node.defaultChild as CfnFunction;
  cfnFunction.snapStart = {
    applyOn: 'PublishedVersions',
  };

  // Accessing currentVersion property enables publishing versions which is needed for SnapStart.
  const version = fn.currentVersion;

  // It would work to just pass the version to ApiGateway,
  // but permissions would need to be re-created on every deployment.
  // Using alias creates stable ARN, so that permissions get updated only when routes change,
  // but deployment of code just needs to bump the version of the alias.
  const alias = new Alias(stack, id + "Alias", {
    aliasName: "current",
    version,
  });

  return alias;
}
```

Then instead of basic:
```ts
const api = new Api(stack, "api", {
  routes: {
    "GET /": "api.Handler::handleRequest",
  },
});
```

Using the helper enables SnapStart for the lambda:
```ts
const api = new Api(stack, "api", {
  routes: {
    "GET /": { cdk: { function: snappyFunction(stack, "MyFn", { handler: "api.Handler::handleRequest" }) } },
  },
});
```

**Comment by jayair** [comment]
Hmm we should look into supporting it. Want to take a stab at a PR?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
