### ISSUE TITLE
Feature: SsrSite Basic Auth

### ISSUE THREAD

**Issue by khuezy** [sst/sst#3067]
There have been some more requests on basic auth support for SsrSites.

Currently, SsrSites configures a VIEWER_REQUEST CloudFront function to set the `x-forwarded-host` headers: https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/SsrSite.ts#L899

But when a user configures their own VIEWER_REQUEST, it will be ignored since CF uses the first one

```typescript
      functionAssociations: [
        ...this.buildBehaviorFunctionAssociations(),
        ...(cfDistributionProps.defaultBehavior?.functionAssociations || []), // VIEWER_REQUESTS here are ignored
      ],
```

Proposal:
Add `basicAuth` config prop to the site config property, eg:
```typescript
basicAuth?: {
   username: string,
   password: string
}
```

Update:

```typescript
  private createCloudFrontFunction() {
    const {username, password} = this.cdk...basicAuth;
    const basicAuth = `
      var authHeaders = event.request.headers.authorization;
      if (authHeaders && authHeaders.value === "Basic ${Buffer.from(${username}:${password}).toString('base64')
}"}) {
        ${this.buildConfig.serverCFFunctionInjection || ""}
        return event.request;
      }
     return {
        statusCode: 401,
        statusDescription: "Unauthorized",
        headers: {
          "www-authenticate": { value: 'Basic realm="Secure Area"' },
        },
      };
    `;
    const normal = `
      ${this.buildConfig.serverCFFunctionInjection || ""}
      return request;
    `

    return new CfFunction(this, "CloudFrontFunction", {
      code: CfFunctionCode.fromInline(`
function handler(event) {
  var request = event.request;
  request.headers["x-forwarded-host"] = request.headers.host;

  ${this.cdk.basicAuth ? basicAuth : normal}
    });
  }

```

**Comment by bayssmekanique** [comment]
I suspect the best way to handle this that doesn't force a specific auth implementation is to fix the `injections` prop for `AstroSite` construct.

The `this.props` from Line 80 needs to also extract the `injections` prop, and then place that prop in end of each of the `injections` arrays here: https://github.com/sst/sst/blob/2bba12c7b031f13f70bcbb03499f434db3cc554e/packages/sst/src/constructs/AstroSite.ts#L96-L108

**Comment by khuezy** [comment]
Should be done at the `SsrSite` level right?

**Comment by bayssmekanique** [comment]
It's already supported on the `SsrSite` level through the `plan` hook with the `cloudFrontFunctions` property. It just needs to be added to the dependent Constructs (like `AstroSite`).

https://github.com/sst/sst/blob/2bba12c7b031f13f70bcbb03499f434db3cc554e/packages/sst/src/constructs/SsrSite.ts#L923-L944

If you wanted to use `SsrSite` directly you could achieve this by extending the `SsrSite` construct before you instantiate it. (I haven't tested this, just an idea).

```ts
const {username, password} = this.cdk...basicAuth;
const basicAuth = `
  var authHeaders = event.request.headers.authorization;
  if (authHeaders && authHeaders.value === "Basic ${Buffer.from(${username}:${password}).toString('base64')
}"}) {
    ${this.buildConfig.serverCFFunctionInjection || ""}
    return event.request;
  }
 return {
    statusCode: 401,
    statusDescription: "Unauthorized",
    headers: {
      "www-authenticate": { value: 'Basic realm="Secure Area"' },
    },
  };
`;
    
class MySsrSite extends SsrSite {
  protected plan() {
    const plan: Plan = {
      cloudFrontFunctions: {
        serverCfFunction: {
          constructId: "CloudFrontFunction",
          injections: [
            this.useCloudFrontFunctionHostHeaderInjection(),
            basicAuth
          ]
        }
      }
    }
    return this.validatePlan(plan);
  }
}
```

**Comment by khuezy** [comment]
Cool, then I can probably close this feature ticket. @jayair can you add some documentation around basic auth (see code above)

**Comment by jayair** [comment]
Oh interesting.

**Comment by fwang** [comment]
Yeah we've been getting requests for all sorts of customization. Most requests are quite niche/advanced. For example, we added the `enableServerUrlIamAuth` for enabling IAM auth for the server function URL a while back, which I sense very few people need.

I [added a `cdk.transform` prop](https://github.com/sst/sst/commit/b29ce15fa94305cc50e4a40b95476cf8bd316bca), which takes a callback that lets your customize the site.

Quick refresher, each site has this concept of a `plan` that defines the origins, edge function, CF functions, etc that are going to be created. [See `NextjsSite`'s plan here](https://github.com/sst/sst/blob/b29ce15fa94305cc50e4a40b95476cf8bd316bca/packages/sst/src/constructs/NextjsSite.ts#L248). With this callback, you can customize the plan like this:
```ts
new NextjsSite(stack, "Web", {
  cdk: {
    transform: (plan) => {
      const basicAuth = `...`;
      plan.cloudFrontFunctions.serverCfFunction.injections.push(basicAuth);
    },
  },
});
```

Over time I can see `plan` support more customization options. You run the risk of breaking/maintaining the `transform`.

This will be in the next release. Let me know if it makes sense.

**Comment by fwang** [comment]
Added an example here https://docs.sst.dev/constructs/NextjsSite#advanced-examples

**Comment by bayssmekanique** [comment]
@fwang, that's a much better approach than extending the construct class.  Is the `plan` parameter typed or does it come through untyped?

**Comment by fwang** [comment]
Yup should be typed
<img width="499" alt="Screen Shot 2024-01-24 at 3 16 45 PM" src="https://github.com/sst/sst/assets/83515/e36c159a-2855-45d6-a353-70505ecafee1">

**Comment by eduardokanema** [comment]
I believe I may have caught this a bit late, but it appears there might be some discrepancies in the documentation. It's possible that the code examples provided by @fwang were directly inspired by the initial pseudocode from @bayssmekanique.

To make it work you must return the value like:
````js
const basicAuthInjection = `
if (request?.headers?.authorization?.value !== '${Buffer.from(${username}:${password}).toString('base64')}') {
  return {
    statusCode: 401,
    statusDescription: "Unauthorized",
    headers: {
      "www-authenticate": { value: 'Basic realm="Secure Area"' },
    },
  };
}`;

**Comment by Roman86** [comment]
@eduardokanema the syntax doesn't seem to be correct for me in this part
<img width="519" alt="image" src="https://github.com/sst/sst/assets/6422343/30d2f022-2271-4d47-8007-54ea18698cf1">

And when I fix it like this (I call this function to get the injection) - credentials are requested, but never accepted.

```typescript
const basicAuthInjection = (username: string, password: string) => {
  const userPwdPair = `${username}:${password}`;
  const encodedPair = Buffer.from(userPwdPair).toString('base64');

  return `
if (request?.headers?.authorization?.value !== '${encodedPair}') {
  return {
    statusCode: 401,
    statusDescription: "Unauthorized",
    headers: {
      "www-authenticate": { value: 'Basic realm="Secure Area"' },
    },
  };
}`;
};
```

What am I doing wrong?

**Comment by bayssmekanique** [comment]
@Roman86, that's better asked in the [sst-astro Discord](https://discord.com/channels/983865673656705025/1068236979659092038).

Running the function from the console might be easiest way to debug this.

**Comment by Roman86** [comment]
thanks @bayssmekanique ! The code was invalid for sure. I've managed to make it work. Thanks for the discord link btw. Many people may come here while searching the topic, so I've updated my question by turning it into the working solution

**Comment by eduardokanema** [comment]
I had just updated the docs with the basic fix: https://github.com/sst/sst/pull/3716
