### ISSUE TITLE
rest-api example creates an HTTP api gateway

### ISSUE THREAD

**Issue by tchcxp** [sst/sst#3080]
I tried to run `npm run dev` in the `rest-api` example and expected a restful API gateway to be deployed; however, it created an HTTP API gateway.

It looks like [the API construct](https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/Api.ts#L733) creates HTTP APIs, and [the ApiGatewayV1Api construct](https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/ApiGatewayV1Api.ts#L213) creates Restful APIs.

Maybe rename the example to `http-api` to avoid misleading.

**Comment by jayair** [comment]
Isn't that just odd AWS naming? https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html

**Comment by tchcxp** [comment]
@jayair There's nothing wrong with [this API example](https://github.com/serverless-stack/sst/tree/master/examples/rest-api), I suggest renaming the folder `rest-api` to `http-api` as this example builds an HTTP API, not a REST API.

**Comment by jayair** [comment]
But from that link I shared, aren't they both REST APIs? I might be missing the distinction here.

**Comment by SinBirb** [comment]
The distinction is pretty huge. AWS HTTP APIs do not support private APIs, resource policies, WAF, Caching and other features. 

As far as I can see, HTTP APIs can not be restricted to a specific VPC or a specific IP addresses, with the exceptions of using an authorization lambda. Correct? 

Will you support REST APIs in the future or do I need to use ApiGatewayV1Api for this?

**Comment by jayair** [comment]
ApiGatewayV1Api is REST API though.

**Comment by tchcxp** [comment]
@jayair @SinBirb Yeah, I use `ApiGatewayV1Api` for the REST API at the moment.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
