### ISSUE TITLE
The "standalone mode" of the NextjsSite Quick Start is broken

### ISSUE THREAD

**Issue by dan-turner** [sst/sst#3081]
Hello,

In attampting to [follow the instructions](https://docs.sst.dev/constructs/NextjsSite) of the `monorepo starter in standalone mode`, the NextJS site never starts.

```
npx create-sst@latest --template standard/nextjs
cd my-sst-app
yarn install
yarn dev
```

Results in the following output:

```
› yarn dev
yarn run v1.22.19
$ sst dev
Please enter a name you’d like to use for your personal stage. Or hit enter to use dan-turner: dan
SST v2.18.3  ready!

➜  App:     my-sst-app
   Stage:   dan
   Console: https://console.sst.dev/my-sst-app/dan

|  Default site/ServerFunction/AssetReplacer Custom::AssetReplacer UPDATE_COMPLETE
|  Default site/ServerFunction/ServerFunction AWS::Lambda::Function UPDATE_COMPLETE
|  Default AWS::CloudFormation::Stack UPDATE_COMPLETE
⠋  Deploying...

✔  Deployed:
   Default

➜  Start Next.js: cd packages/web && npm run dev
```

The following line of output never occurs and the app does not spin up listening on port 3000:

`- ready started server on 0.0.0.0:3000, url: http://localhost:3000`

Doing an `sst deploy --stage dev` does indeed work though.  Likewise running `yarn dev` from `packages/web` correctly spins up the app listening on port 3000.

In following the `drop-in mode` instructions, the app does indeed start up and is available on port 3000.

```
› yarn dev
yarn run v1.22.19
$ sst bind next dev
Please enter a name you’d like to use for your personal stage. Or hit enter to use dan-turner: dan
Warning: The site has not been deployed. Some resources might not be available.

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 181 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 156 ms (20 modules)
```

I have tried following the instructions using Node 16, 18 and 20 and seeing the same broken behaviour in each.

**Comment by jayair** [comment]
Sorry when you say it never spins up, what do you mean? From the terminal output it looks like it started fine?

**Comment by dan-turner** [comment]
The key missing line of output is:

`- ready started server on 0.0.0.0:3000, url: http://localhost:3000`

With the standalone example this line is never output, and nothing is listening on port 3000

**Comment by dan-turner** [comment]
@jayair were you able to reproduce the issue?

Do these commands in fact work for you?

```
npx create-sst@latest --template standard/nextjs
cd my-sst-app
yarn install
yarn dev
```

**Comment by jayair** [comment]
@dan-turner Are you missing a `sst dev` in between?

**Comment by dan-turner** [comment]
Hi @jayair, no:

![image](https://github.com/serverless-stack/sst/assets/814113/02d5e712-c735-4a91-9b8d-2a63a94461d2)

Have you tried the above and did it work for you?

**Comment by jayair** [comment]
Yeah it should. I was commenting on the steps you shared above. Can you open a thread in #help on Discord and we'll take a look.

**Comment by cwfuller** [comment]
@dan-turner did you ever find a solution to this?

**Comment by krydos** [comment]
I've faced similar issue. Apparently that `➜  Start Next.js: cd packages/web && npm run dev` line is an invitation for user to execute the command. It's **NOT** an indication of what has been executed. 
You can see it in [cli/commands/dev.js](https://github.com/sst/sst/blob/master/packages/sst/src/cli/commands/dev.tsx#L341)

Does anyone know if it is planned like this or something is broken?

**Comment by danielivanovz** [comment]
I am bringing this back since I am experiencing the same problem:

Once run the `sst dev` from the root of the monorepo, and then in a second terminal tab I run `sst bind next dev`, it hangs and nothing happens.

My sst stack is deployed and linked to a `eu-central-1` region.

Does anybody has any clue?

**Comment by dan-turner** [comment]
My issue was assuming that running the `dev` target also spun up the next app.  I hadn't realised I also needed to spin up next too.
