### ISSUE TITLE
Bug: first build requiring cdk.context.json fails

### ISSUE THREAD

**Issue by eliasbrange** [sst/sst#3107]
Version 2.19.1 introduced a bug where the first build (when no `cdk.context.json` exist) in stacks that requires context (such as a Hosted Zone) fails.

Running `sst build` correctly generates the `cdk.context.json`, but subsequently fails with an error message like:

```
Error: It seems you are configuring custom domains for you URL. And SST is not able to find the hosted zone "xyz.domain.com" in your AWS Route 53 account. Please double check and make sure the zone exists, or pass in a different zone.
```

Since it did generate a `cdk.context.json`, subsequent `sst build`s works fine.

My guess is that it was introduced in the https://github.com/serverless-stack/sst/commit/42671324332dfa114bfefd4a6f7daba374b0ef23# commit.

**Comment by lostra01** [comment]
To add to the issue:

You actually have to manually do the sst build or push to a prod for the context file to appear.

Eg.: If you are using Github Actions or similar CI/CD, the context file is never present.

**Comment by jayair** [comment]
Yup taking a look.

**Comment by kevin-brashears-fhr** [comment]
seeing the same. My error is around VPC:
Error: Could not resolve context values for vpc-provider:account=xxxxxxxxxxx....

**Comment by jayair** [comment]
Rolled out a fix here: https://github.com/serverless-stack/sst/releases/tag/v2.21.5
