### ISSUE TITLE
DynamoDB table addConsumers bug

### ISSUE THREAD

**Issue by jonnedeprez** [sst/sst#3115]
I have a single Lambda function that serves as the stream handler for two different DynamoDB tables. When I configure custom filter criteria with `addConsumers` the criteria are getting mixed up. 

Say I have `tableA`, `tableB` and a lambda function `lambdaFunction`:

```
tableA.addConsumers(stack, {
    handlerA: {
      function: lambdaFunction,
      filters: [
        {
          dynamodb: {
            NewImage: {
              __edb_e__: {
                S:  'SomeEntityInTableA',
              },
            },
          },
        },
      ],
    },
  });

tableB.addConsumers(stack, {
    handlerB: {
      function: lambdaFunction,
      filters: [
        {
          dynamodb: {
            NewImage: {
              __edb_e__: {
                S:  'SomeEntityInTableB',
              },
            },
          },
        },
      ],
    },
  });
```

After deployment I get the filter criteria of table B applied to the event source mapping of table A, and no filter criteria for table B.

using SST v2.21.0
the issue is probably caused by: https://github.com/serverless-stack/sst/blob/c98db9a6683fd293bdfcf014fda7e79b44378690/packages/sst/src/constructs/Table.ts#L751

**Comment by jayair** [comment]
Ooh would appreciate a PR. Also if you could post this on #help on Discord, that'd help!

**Comment by Rohanr14** [comment]
is anyone working on this? I can get started on it and have PR up if not!

**Comment by jonnedeprez** [comment]
Hi @Rohanr14 , there's my own PR already. But feel free to comment

**Comment by brubraz** [comment]
I'm experiencing the same issue.

**Comment by jayair** [comment]
I'll check on the PR again. Sorry about that.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
