### ISSUE TITLE
RDS.Cluster bind bug when using CRON

### ISSUE THREAD

**Issue by vasco-santos** [sst/sst#3119]
I am currently getting error in lambda `Cannot use RDS.Cluster. Please make sure it is bound to this function.`

This function is inside a CRON and therefore might be related to it

However, lambda function construct where this error comes from has DB bound. I have 2 lambdas that interact with RDS cluster and only in one of them this issue happens (a lambda function that is triggered as a Queue consumer).

See

```javascript
const db = new RDS(stack, dbName, {
    engine: 'postgresql13.9',
    defaultDatabaseName: dbName,
    migrations: 'packages/core/migrations',
    types: 'packages/core/src/schema.ts',
    // https://docs.sst.dev/constructs/RDS#auto-scaling
    scaling: stack.stage !== 'production' ?
      {
        autoPause: true,
        minCapacity: 'ACU_2',
        maxCapacity: 'ACU_2',
      }
      :
      {
        autoPause: false,
        minCapacity: 'ACU_4',
        maxCapacity: 'ACU_64',
      }
  })
```

```javascript
  const { db } = use(DbStack)

  new Cron(
    stack,
    'piece-maker-consumer',
    {
      schedule: 'rate(15 minutes)',
      job: {
        function: {
          handler: 'packages/functions/src/workflow/piece-maker.consume',
          environment: {
            QUEUE_URL: pieceMakerItems.queueUrl,
            QUEUE_REGION: stack.region
          },
          bind: [db],
        },
      }
    }
  )
```

unless this issue is a consequence of the `autoPause` being true for dev.

**Comment by jayair** [comment]
Hmm I'm guessing sst dev is running? Can you post this in #help on Discord? Let's take a look.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
