### ISSUE TITLE
SsrSite: Allow override of serverCFFunctionInjection without having to extend the class 

### ISSUE THREAD

**Issue by luc-ferron** [sst/sst#3120]
At the moment, anyone who wants to have Basic Auth on any SSR Site will not be able to do it because the CFFunction for distribution is hard coded inside SsrSite: 
https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/SsrSite.ts#L907

There is a way to inject some additional code in there to be able to implement basic auth, however the property serverCFFunctionInjection  in the buildConfigs is not exposed.

Currently, the only way to override this is to extend the site you want to (for instance NextJSSite), and override the buildInitConfig function, call super, and add the serverCFFunctionInjection to it.

It would be easier and cleaner to be able to just pass in the serverCFFunctionInjection in the props and let the SsrSite merge this in its build configs.

Food for thoughts: should we be able to override any build config instead of focusing only on serverCFFunctionInjection or that would expose too many internal implementation details and potential edge cases? 

The context is all in this discussion on discord: 
https://discord.com/channels/983865673656705025/1123310249508601917

**Comment by luc-ferron** [comment]
Another thing I'd like to do once that is done, is to simply add inside SsrSite what's needed to handle basic auth, and add a few new props in SsrSite : 

enableBasicAuth: bool
basicAuthUser: string
basicAuthPassword: string

if those are passed, we automatically inject the following code in the VIEWER_REQUEST function as such: 

function decodeBase64(base64) {
        var alphabet =
          "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
        var str = "";
        var bytes = [];

        for (var i = 0; i < base64.length; i += 4) {
          var enc1 = alphabet.indexOf(base64[i]);
          var enc2 = alphabet.indexOf(base64[i + 1]);
          var enc3 = alphabet.indexOf(base64[i + 2]);
          var enc4 = alphabet.indexOf(base64[i + 3]);

          var chr1 = (enc1 << 2) | (enc2 >> 4);
          var chr2 = ((enc2 & 15) << 4) | (enc3 >> 2);
          var chr3 = ((enc3 & 3) << 6) | enc4;

          bytes.push(chr1);
          if (enc3 !== 64) bytes.push(chr2);
          if (enc4 !== 64) bytes.push(chr3);
        }

        for (var i = 0; i < bytes.length; i++) {
          str += String.fromCharCode(bytes[i]);
        }

        return str;
      }

      var auth = request.headers.authorization;
      if (auth) {
        console.log(decodeBase64(auth.value.split(" ")[1]));
        var parts = decodeBase64(auth.value.split(" ")[1]).split(":");
        if (parts[0] === "${this.basicAuthUser}" && parts[1] === "${this.basicAuthPassword}") {
          return request;
        }
      }

      return {
        statusCode: 401,
        statusDescription: "Unauthorized",
        headers: {
          "www-authenticate": { value: 'Basic realm="Secure Area"' },
        },
      };

This would be done here: 
https://github.com/serverless-stack/sst/blob/5122913c003ef7195fac5492417c39ad20df9beb/packages/sst/src/constructs/SsrSite.ts#L912 (and in the edge counterpart as needed)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
