### ISSUE TITLE
Astro integration is missing basic functionality

### ISSUE THREAD

**Issue by bayssmekanique** [sst/sst#3139]
The Astro implementation seems to be missing a few key features to make it usable without significant class overrides. By default, Astro's static file generation assumes the server will auto-append `index.html` to directory requests (`/`, `/blog`, `/blog/how-to-foo`).

For reference, I'll use the following distribution behaviors mapping as the example:
![image](https://github.com/serverless-stack/sst/assets/2280384/292e7196-10b2-4a14-a0e8-59bc605c1a31)

It's possible to re-introduce some portion of this functionality by utilizing the `defaultRootObject` property on the `cdk` configuration, but this only solves the issues for the root directory (`/`) and leaves the remaining directories unresolvable (`/blog`, `/blog/how-to-foo`).

It's also possible to add a CloudFront Function to the stack as part of the `defaultBehavior`, but this has 2 issues at the moment:
1) The function will be created, but the function built into the Astro integration will be the default behavior so the function added in the config is ignored and requires going into the console and selecting the function to assign to the default behavior. (See https://github.com/serverless-stack/sst/issues/3120)

![image](https://github.com/serverless-stack/sst/assets/2280384/8705eec4-5e73-426d-b5a2-37b935e764c1)

2) The function will only apply to the `Default(*)` behavior so any routes which match other behaviors will not run this function unless they are manually assigned in the console as well. So the root directory (`/`) and the direct children (`/blog`) are supported, but anything further descending will not be resolvable (`/blog/how-to-foo`).

<hr>

I would assume the proper way to resolve this would be to update the integration to include a default function which supports the `index.html` appending similar to how the `SvelteKitSite` constructor includes a query modification.

https://github.com/serverless-stack/sst/blob/9398de7fc9576f5a46372ce1d65756d0c3d5c990/packages/sst/src/constructs/SvelteKitSite.ts#L19-L39

It would also be necessary to update the wildcard behaviors (`/blog/*`, `/about/*`) to also have the function attached.

**Comment by bayssmekanique** [comment]
For further reference, here's the `sst.config.ts` and `cfFunction.js` files that I'm currently using but which still leave a bit to be desired.

### `sst.config.ts`
```ts
import {
  Function as CfFunction,
  FunctionCode as CfFunctionCode,
  FunctionEventType as CfFunctionEventType
} from 'aws-cdk-lib/aws-cloudfront'
import { HostedZone } from 'aws-cdk-lib/aws-route53'
import { AstroSite } from 'sst/constructs'
import type { SSTConfig } from 'sst'
import { Tags } from 'aws-cdk-lib'

export default {
  config(_input) {
    return {
      name: 'personal-website',
      region: 'us-west-2',
      profile: 'sst',
      bootstrap: {
        tags: {
          'Cost Center': 'Shared',
          Environment: 'Production',
          IaC: 'SST',
          Stack: 'IaC SST'
        }
      }
    }
  },
  stacks(app) {
    const isProd = app.stage === 'prod'

    Tags.of(app).add('Cost Center', 'Personal')
    Tags.of(app).add('Environment', isProd ? 'Production' : 'Development')
    Tags.of(app).add('IaC', 'SST')
    Tags.of(app).add('Stack', 'Personal Site')

    app.stack(function Site({ stack }) {
      const site = new AstroSite(stack, 'astro-site', {
        customDomain: {
          domainName: isProd
            ? 'astro.XXXXXXXXX.com'
            : `${app.stage}.XXXXXXXXX.com`,
          cdk: {
            hostedZone: HostedZone.fromHostedZoneAttributes(
              stack,
              'HostedZone',
              {
                hostedZoneId: 'XXXXXXXXX',
                zoneName: 'XXXXXXXXX.com.'
              }
            )
          }
        },
        path: './',
        runtime: 'nodejs18.x',
        cdk: {
          distribution: {
            defaultRootObject: 'index.html',
            defaultBehavior: {
              functionAssociations: [
                {
                  function: new CfFunction(stack, 'RouterFunctionV1', {
                    comment: 'Router Function (v1)',
                    code: CfFunctionCode.fromFile({
                      filePath: './cfFunction.js'
                    })
                  }),
                  eventType: CfFunctionEventType.VIEWER_REQUEST
                }
              ]
            }
          }
        }
      })
      stack.addOutputs({
        url: site.customDomainUrl
      })
    })
  }
} satisfies SSTConfig
```

### `cfFunction.js`
```js
/* eslint-disable no-var */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function handler(event) {
  var request = event.request
  var uri = request.uri

  // Check whether the URI is missing a file name.
  if (uri.endsWith('/')) {
    request.uri += 'index.html'
  }
  // Check whether the URI is missing a file extension.
  else if (!uri.includes('.')) {
    request.uri += '/index.html'
  }

  return request
}
```

**Comment by jayair** [comment]
Oh this is useful. Thanks for sharing. I haven't gotten to it yet but is there a related Discord conversation about this?

**Comment by bayssmekanique** [comment]
There were a few threads started but nothing that got any further than recommending a CF Function to resolve the issue.

**Comment by jayair** [comment]
Let's start a new thread for this then? I need the team to take a look at it. Feel free to tag me in it or leave a link here.

**Comment by bayssmekanique** [comment]
My first attempt at resolving this functionality, but I immediately hit the [cache-behavior limit](https://docs.sst.dev/known-issues#cloudfront-cachebehaviors-limit-exceeded) for CloudFront. Here's the diff for posterities' sake: https://github.com/serverless-stack/sst/compare/master...bayssmekanique:sst:feat/astro-hybrid-support-v1

The fact that AWS puts a limit on behaviors leads me to believe they are expensive and likely not intended to be used in the way that they are currently used by this tool, so I'm going to take another stab at implementing using Origin Group fail-overs.

**Comment by bayssmekanique** [comment]
My second attempt was a little more successful.
https://github.com/serverless-stack/sst/compare/master...bayssmekanique:sst:feat/astro-hybrid-support-v2

The origin-failover behavior works surprisingly well, but it only supports `GET`, `HEAD`, and `OPTION` methods so it would not support `PUT`, `POST`, `DELETE` methods in the failover behavior.This could be worked around using custom behaviors for the paths which require those methods.

There was also a lot of heavy lifting being performed by the CF Function to predict path resolution which is hard to do without knowledge of the Origin's content.

For attempt 3 I'm considering using the S3 web-server endpoint as the primary origin for the failover, with the lambda function as secondary. This worked REALLY well when tested in the console, but with the same limitation on supported methods. It might be worth considering the failover strategy to be the default strategy for `hybrid` mode and using a more cache reliant strategy for `server` mode.

**Comment by bayssmekanique** [comment]
In an attempt to better handle Astro Hybrid builds, I've authored a [PR](https://github.com/serverless-stack/sst/pull/3170) to pull the Astor build properties into the SST deployment constructs. This should allow for a more optimized CF Function to be written to route origins by route pattern.

**Comment by bayssmekanique** [comment]
Third attempt was a success and utilizes portions of all the approaches above. There are a few small portions left to implement in the PR before it's ready for merging but the hardest problems are now solved.

https://github.com/serverless-stack/sst/pull/3176
