### ISSUE TITLE
Large POST bodies seem to break live lambda mode

### ISSUE THREAD

**Issue by kamsar** [sst/sst#3147]
Reproduction repository, with instructions:

https://github.com/kamsar/sst-bug-lambda-dev/blob/main/README.md

**Comment by jayair** [comment]
Oh thanks for putting it together. @thdxr let's take a look.

**Comment by ekrata-main** [comment]
Any resolutions for this.. believe this might be related to https://discord.com/channels/983865673656705025/1177772648986595369 . going to have to do a workaround to avoid sending large POST bodies

**Comment by paul-dao-FHR** [comment]
We look to be running into this issue as well, with a payload size of 130KB

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
