### ISSUE TITLE
sst.Config + NextJsSite + getStaticProps fails on all builds until initial deploy

### ISSUE THREAD

**Issue by iDVB** [sst/sst#3149]
## Reproduction Repo:
https://github.com/iDVB/serverless-stack/blob/274c465f2720aa31539774c55f4db8aaf1028779/examples/nextjs-config-issue/stacks/Default.ts#L4-L11

Slack Thread here:
https://discord.com/channels/983865673656705025/1131695331206250616/1131695331206250616

## Repro Steps:
```bash
git clone git@github.com:iDVB/serverless-stack.git
cd examples/nextjs-config-issue
pnpm install
pnpm run build
```

## This will fail with:
`Error: Cannot use Config.TEST_PARAM. Please make sure it is bound to this function.`

![CleanShot 2023-07-21 at 09 55 12](https://github.com/serverless-stack/sst/assets/189506/32e81f50-d4ac-4f3f-bb1d-18d80fb8fd29)

## Expected:
Its my understanding that Config is simply trying to help with what can be done manually but passing the SSM param name as a Lambda env var (and permissions) and then in the Lambda calling out to get the value of that param. This can be done today **without** deploying first. It feels like there is something missing with Config if it requires a deploy first when using something like NextJsSite.

We require to `sst build --to ...` and `sst deploy --from ...` separately in our monorepo so we can cache the build and NOT the deploy. We also have a completely automated pipe that is deploying ephemeral environments, so the option to manually deploy first is not an option.

**Comment by jayair** [comment]
Yeah let me ask Frank to take a look.

**Comment by fwang** [comment]
Followed up in the thread — https://discord.com/channels/983865673656705025/1131695331206250616/1135940545106165880

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
