### ISSUE TITLE
How to add vm options when using java runtime?

### ISSUE THREAD

**Issue by ljd1991** [sst/sst#3156]
By refering to guides [Configuring Java runtime](https://docs.sst.dev/constructs/Function#configuring-java-runtime), I create a project using runtime of Java11, my stacks like 
```typescript
export default {
  config(_input) {
    return {
      name: 'my-sst-test2',
      region: 'cn-northwest-1'
    };
  },
  stacks(app) {
    app.setDefaultFunctionProps({
      runtime: "java11",
    });
    app.stack(function Stack({ stack }) {
      const api = new Api(stack, "api-java-test", {
        routes: {
          "GET /": "api.Handler::handleRequest",
        },
      });
      stack.addOutputs({
        ApiEndpoint: api.url,
      });
    });
  },
} satisfies SSTConfig;
```
And my handler implement in Java is like 
```java
public class Handler implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent>{
  @Override
  public APIGatewayProxyResponseEvent handleRequest(APIGatewayProxyRequestEvent event, Context context)
  {
    APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
    response.setStatusCode(200);
    response.setBody("Hello, World! Received a request with id " + event.getRequestContext().getRequestId());
    return response;
  }
}
```
when I try to invoke lambda by requesting "https://xxxxxxxxx.execute-api.cn-northwest-1.amazonaws.com.cn/", I got InaccessibleObjectException, error logs like
```
|  Invoked api.Handler::handleRequest
colors.js:6|  +4848ms Exception in thread "main"
colors.js:6|  +4850ms java.lang.Error: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @433c675d
colors.js:6|  +4850ms 	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:195)
colors.js:6|  +4851ms 	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:188)
colors.js:6|  +4851ms Caused by: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @433c675d
colors.js:6|  +4852ms 	at com.amazonaws.services.lambda.runtime.api.client.util.EnvWriter.<init>(EnvWriter.java:26)
colors.js:6|  +4852ms 	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:210)
colors.js:6|  +4853ms 	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:193)
colors.js:6|  +4853ms 	... 1 more
colors.js:6|  +4854ms Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @433c675d
colors.js:6|  +4854ms 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
colors.js:6|  +4854ms 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
colors.js:6|  +4855ms 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
colors.js:6|  +4855ms 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
colors.js:6|  +4855ms 	at com.amazonaws.services.lambda.runtime.api.client.util.EnvWriter.<init>(EnvWriter.java:21)
colors.js:6|  +4855ms 	... 3 more
```

after searching google, I got solutions like described in "https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m"
It request to add vm optins "java --add-opens java.base/java.lang=ALL-UNNAMED" when running java application to allow all reflect operations, but I cannot find where to add vm options when running sst.

In "sst/runtime/handlers/java.js/useJavaHandler", it seems sst accept extra options when running java application, but I cannot find where to configure it.
```typescript
const proc = spawn(`java`, [
    `-cp`,
    [
        url.fileURLToPath(new URL("../../support/java-runtime/release/*", import.meta.url)),
    ].join(os.platform() === "win32" ? ";" : ":"),
    "com.amazonaws.services.lambda.runtime.api.client.AWSLambda",
    input.handler,
], {
    env: {
        ...process.env,
        ...input.environment,
        IS_LOCAL: "true",
        AWS_LAMBDA_RUNTIME_API: `localhost:${server.port}/${input.workerID}`,
    },
    cwd: input.out,
});
```

**Comment by jayair** [comment]
I think this is emulating what's in Lambda. How would this work if you are going to deploy it to AWS?

**Comment by ljd1991** [comment]
> I think this is emulating what's in Lambda. How would this work if you are going to deploy it to AWS?

Sorry I cannot quiet follows you..... I am trying to invoke lambdas locally right now, and the Java runtime seems to have some constraint when using reflection, what is the influence running on AWS?

**Comment by ljd1991** [comment]
I think I have a clue here. Refer to [aws-lambda-java-libs issue](https://github.com/aws/aws-lambda-java-libs/issues/261),  **InaccessibleObjectException** occurs because aws-lambda-java-runtime-interface-client tried to use reflection, which is not allowed any more.
One of the simple way is to add vm option "--add-opens java.base/java.util=ALL-UNNAMED"
Also aws had fix this problem by removing "EnvWriter", and it is released. But I can see that sst still use aws-lambda-java-runtime-interface-client-1.1.0.jar, which is an old version

**Comment by danielbedo** [comment]
> I think I have a clue here. Refer to [aws-lambda-java-libs issue](https://github.com/aws/aws-lambda-java-libs/issues/261), **InaccessibleObjectException** occurs because aws-lambda-java-runtime-interface-client tried to use reflection, which is not allowed any more. One of the simple way is to add vm option "--add-opens java.base/java.util=ALL-UNNAMED" Also aws had fix this problem by removing "EnvWriter", and it is released. But I can see that sst still use aws-lambda-java-runtime-interface-client-1.1.0.jar, which is an old version

How can we pass a vm option? Or is it not possible with sst?

**Comment by jayair** [comment]
I replied here https://discord.com/channels/983865673656705025/1148314284510691429

We could use some help.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
