### ISSUE TITLE
When a Lambda with Runtime=Rust fails to build, the error is suppressed

### ISSUE THREAD

**Issue by Dzhuneyt** [sst/sst#3157]
If you try to compile a Lambda with the experimental "rust" runtime:

```
new Function(this, 'Function', {
			handler: 'crates/cedar',
			runtime: 'rust'
		})
```

There are many possible scenarios where this can fail. For example, if you haven't installed the cargo CLI locally (e.g. `cargo --help` returns an exit code 1 "Command not found").

However, the error is always captured and suppressed and converted to the pretty cryptic: `Error: Failed to build`.

<img width="933" alt="image" src="https://github.com/serverless-stack/sst/assets/1754428/f8927ff6-59d9-48b0-9dde-51fde56fb2f4">

Based on a quick research, I think we need to explicitly log the error that is captured in catch clause of the try/catch inside node_modules/sst/runtime/handlers/rust.js line 78. I managed to "surface" the actual captured error locally by adding this console.log() to our local node_modules, but obviously this fix can benefit others who have hard time debugging and was thinking it can be applied at the SST framework itself. I might be able to implement this change, if you want.

<img width="1591" alt="image" src="https://github.com/serverless-stack/sst/assets/1754428/b219a3e4-eca5-48dd-8abe-543194882501">

This issue is similar to https://github.com/serverless-stack/sst/issues/3021, but that one is for the Nodejs runtime, but this one is for the Rust runtime.

**Comment by ipatka** [comment]
nice catch, let's try to patch the same way as #3021

**Comment by Dzhuneyt** [comment]
Just started investigating this and realized it was fixed 3 weeks ago [here](https://github.com/serverless-stack/sst/pull/3101). So we probably just need to bump up our local SST to the latest version.
