### ISSUE TITLE
There is no straightforward way to bake-in or bind sst.Config.Secret to front-end JS of StaticSite.

### ISSUE THREAD

**Issue by ivanakcheurov** [sst/sst#3159]
Please simplify the following use case.

### Context:
I have StaticSite and I want to bake-in Stripe's publishable key into my frontend's JS (test would have `pk_test_xxxx` while prod would have `pk_live_xxxx`).
I tried to use npx sst secrets and  environment prop on StaticSite construct but ts shows an error (screenshots).
`const STRIPE_PUB_KEY = new Config.Secret(stack, "STRIPE_PUB_KEY")`
![image](https://github.com/serverless-stack/sst/assets/5347026/ce274b2f-4631-44cd-886d-e65cdefa3cb5)
![image](https://github.com/serverless-stack/sst/assets/5347026/d82d1738-8524-447f-9c31-824ff0196e56)

What is the correct way to specify an environment-specific key inside StaticSite's JS? 

### I got a workaround on Discord 
(_thank you Arpad_):
Arpad — 25/07/2023 13:18
the Config.Secret is a construct that abstracts a secret stored inside aws (sst does some magic behind the scenes), and you can only use bind with it. But you are using a static site, so you'll need to workaround that and use envs. I think the easiest way is to do something like process.env.STRIPE_PUB_KEY and then for the build command you need pnpm sst bind --stage {stage} "pnpm run build"
https://docs.sst.dev/packages/sst#sst-bind

### My final working solution:
1) `npx sst secrets set STRIPE_PUB_KEY pk_test_xxtyda7tdysa7y --fallback`
`npx sst secrets set STRIPE_PUB_KEY pk_live_j6d78sadsadsa6 --stage prod`
2) Stack.ts:
```ts
const web = new StaticSite(stack, "web", {
    path: "packages/web",
    buildOutput: "dist",
    buildCommand: "pnpm run build",

    environment: {
      VITE_APP_API_URL: api.url,
      VITE_APP_STRIPE_PUB_KEY: process.env.SST_Secret_value_STRIPE_PUB_KEY!,
    },
  });
```
3)  `npx sst bind --stage test "npx sst deploy --stage test"` because it also always builds frontend JS on deploy.
`npx sst bind --stage prod "npx sst deploy --stage prod"` 

### Conclusion
I made `package.json` script: `"dp": "npx sst bind --stage prod \"npx sst deploy --stage prod\"",` but it's a workaround.
So ideally I would like to keep deploying with `npx sst deploy --stage prod`.
This is a kind feature request to enable this :)

**Comment by cdimitroulas** [comment]
Why not use a Parameter instead of a Secret? If you are passing a value to a static site, then it's not really a secret anymore since it's clearly visible in the JS code that is ran on the client-side. Seems like you are trying to add security to something that is inherently insecure, which is why there's no good way to achieve it.

**Comment by ivanakcheurov** [comment]
Hi @cdimitroulas,
I don't use `sst.Config.Parameter` because parameters are **not** environment specific.
So a workaround could be this:
```ts
const SOME_PARAM = new Config.Parameter(stack, "SOME_PARAM", {
    value: 
        app.stage === "test"
        ? "TTT" 
        : app.stage === "prod" 
            ? "PPP" 
            : "PERSONAL_VALUE" /*personal env */
    });
```
but if I introduce `staging` or will have 5 different devs on the team with their personal values, the code becomes unmanageable. Would need to resort to `.env` files.

So you are right, maybe a good solution is to allow `sst.Config.Parameter` **be environment specific** in a convenient way.

**Comment by cdimitroulas** [comment]
I wouldn't say it becomes unmanageable, we have many functions that deal with environment-specific values like that.

We usually call it `getStagedSomething`. In this case it could be called `getStagedSomeParam` and look something like this:
```ts
const getStagedSomeParam = (stage: string): string => {
  switch (stage) {
    case 'test':
      return "TTT";
    case 'prod':
      return "PPP";
    default:
      return "PERSONAL_VALUE";
  }
} 
```

When you need to handle another stage name, you can just add a new case to this function.

**Comment by ivanakcheurov** [comment]
> I wouldn't say it becomes unmanageable, we have many functions that deal with environment-specific values like that.
> 
> We usually call it `getStagedSomething`. In this case it could be called `getStagedSomeParam` and look something like this:
> 
> ```ts
> const getStagedSomeParam = (stage: string): string => {
>   switch (stage) {
>     case 'test':
>       return "TTT";
>     case 'prod':
>       return "PPP";
>     default:
>       return "PERSONAL_VALUE";
>   }
> } 
> ```
> 
> When you need to handle another stage name, you can just add a new case to this function.

Let's say we have 5 devs: Sally, Bob, Peter, Mark and John. We also have test and prod envs.
How can I specify 7 values in the code?
```js
const getStagedSomeParam = (stage: string): string => {
  switch (stage) {
    case 'test':
      return "TTT_value";
    case 'prod':
      return "PPP_value";
    case "sally":
      return "Sally's_value";
    case "bob":
      return "Bob's_value";
    case "mark":
      return "Mark's_value";
    case "john":
      return "John's_value";
    case "peter":
      return "Peter's_value";
    default:
      return throw "I don't know who you are and therefore which value you need";
  }
} 
```
and that's for every parameter that needs to change depending on stage or person.

Perhaps a workaround would be putting the personal values in a separate `getSomeParamForPersonalStage.ts`, _gitignore_ it and [try to import dynamically](https://stackoverflow.com/questions/75295514/how-to-catch-dynamic-import-error-in-javascript).
If succeeds, try to take the personal value from that function (switch statement against the personal name of the stage), if the module doesn't exist or doesn't have a personal stage value, then just take _test_.

Crude, can be improved with storing values in a json file that is gitignored, but doable and somewhat resembles .env approach already.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
