### ISSUE TITLE
Feature request: Allow overwriting config file path

### ISSUE THREAD

**Issue by gqgs** [sst/sst#3160]
https://docs.sst.dev/configuring-sst#file-structure

According to this doc it seem it always assumed the configuration will be `sst.config.ts`.
This makes it inconvenient for use cases where there are multiple configuration files.

An option `--config` allowing to specify different configuration files would be useful for those use cases.

**Comment by jayair** [comment]
How come you have multiple config files?

**Comment by gqgs** [comment]
@jayair I have services that need to be deployed to multiple accounts and it's necessary for them to have different behavior and infrastructure depending on the account.
Using multiple configuration files has been so far the cleanest way to keep those concerns separated and clearly defined.
Migrating from `serverless` that does have a [--config](https://www.serverless.com/framework/docs/providers/aws/cli-reference/deploy#options) option for use this case I was expecting something similar to be available here.
Also, I know keeping a single `sst.config.ts` and just handling this use case programmatically in function of the accounts is probably an alternative but I'd rather have the option to specify the different config file directly instead.

**Comment by jayair** [comment]
Yeah your last point is kinda why we are going this route. Ideally most of things should be handled in code for SST. I can bring this up with the team but I don't recall this being requested before.

**Comment by gnllucena** [comment]
I have a monorepo with two different apps of the same ecosystem. 

One is a Next.js website, and the other is a WebSocket API that is deployed once for each new group created on the Next.js website. 

It would be much cleaner to have two different `sst.config.ts` files and have my CD pipeline trigger each one accordingly to the situation.

please add `--config` option.

**Comment by jayair** [comment]
>  WebSocket API that is deployed once for each new group created on the Next.js website

What does this mean?

**Comment by ayvazj** [comment]
I am using the following to deploy different apps from a mono repo

sst.config.ts
```
export default {
  config(input) {
    return {
      name: `${process.env.SST_APP}`,
      region: input.region || "us-east-1",
    };
  },
  stacks(app) {
    switch (app.name) {
      case "first-app":
        app.stack(function Site({ stack }) {
          const site = new NextjsSite(stack, "FirstSite", {
            path: "apps/first-app",
          });

          stack.addOutputs({
            SiteUrl: site.url,
          });
        });
        break;
      case "second-app":
        app.stack(function Site({ stack }) {
          const site = new StaticSite(stack, "SecondSite", {
            path: "apps/second-app",
          });

          stack.addOutputs({
            SiteUrl: site.url,
          });
        });
        break;
    }
  },
} satisfies SSTConfig;
```

Then I provide the environment variable whenever I run sst commands

```
# deploy first app
SST_APP=first-app npx sst deploy --production

# deploy second app
SST_APP=second-app npx sst deploy --production


```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
