### ISSUE TITLE
Make Table support AWS::DynamoDB::GlobalTable for replication

### ISSUE THREAD

**Issue by closesimple-wl** [sst/sst#3161]
It looks like Table generates a custom resource for replication, when replication is indicated via the `Table.cdk.table` API.  Why isn't it possible to use a GlobalTable resource to accomplish the same thing?

**Comment by closesimple-wl** [comment]
Never mind, looks like the CDK itself doesn't have the construct yet:

https://github.com/aws/aws-cdk/issues/24332
https://github.com/aws/aws-cdk/issues/16118

**Comment by closesimple-wl** [comment]
@jayair , I'm requesting a new version of SST supporting the latest CDK, for structural typing compatibility, so we can use the CDK's new `TableV2` construct, which creates a `AWS::DynamoDB::GlobalTable`.  Please.

https://docs.sst.dev/faq#how-often-is-ssts-version-of-cdk-updated
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.TableV2.html

**Comment by jayair** [comment]
Which version of CDK is this?

**Comment by closesimple-wl** [comment]
Latest.  :O  At the time of writing, that's `2.99.0`.  There have been bug fixes to it since initial release.

**Comment by jayair** [comment]
Oh okay. Let me tell the team.

**Comment by closesimple-wl** [comment]
Thank you for the CDK update.  Technically this issue should still be open, though, because it's about adding `GlobalTable` options to SST's `Table` Construct.

**Comment by closesimple-wl** [comment]
@jayair @fwang

**Comment by jayair** [comment]
Feel free to submit a PR for this!
