### ISSUE TITLE
Add Python 3.11 runtime

### ISSUE THREAD

**Issue by adolfogc** [sst/sst#3189]
Hi, AWS Lambda now supports Python 3.11 (https://aws.amazon.com/blogs/compute/python-3-11-runtime-now-available-in-aws-lambda/).

**Comment by jayair** [comment]
Do you have the CDK version that has this?

**Comment by adolfogc** [comment]
Hi, based on this commit:

https://github.com/aws/aws-cdk/commit/e2b7791072e187f441eb72a5f6d0462748ec5112

I think it is available starting from version v2.88.0

**Comment by adolfogc** [comment]
This PR would allow adding the Python 3.11 runtime: https://github.com/sst/sst/pull/3209

**Comment by jayair** [comment]
Yup taking a look

**Comment by adolfogc** [comment]
Hi @jayair, with https://github.com/sst/sst/pull/3217 now merged, I have created a PR to add the Python 3.11 runtime.
