### ISSUE TITLE
403 response for some  page resources when using Remix

### ISSUE THREAD

**Issue by barakcodes** [sst/sst#3206]
### Problem
I run into an issue where some of my js bundle for a specific page returns `403` upon request, I deployed the same app on vercel but doesn't seem like it's an issue on there. I'm using the [remix-flat-routes ](https://github.com/kiliman/remix-flat-routes/issues) package and using the [nested folders](https://github.com/kiliman/remix-flat-routes#nested-folders-with-flat-files-convention--new-in-v051) which let's you define a folder as a flat route by utilizing `folder_name+/routes.ts` upon inspecting the network calls
it seems only resources with the `+` fail with a `403` the file does exist on s3, but I suspect because `+` is a special character in terms of URL it is being parsed to a space which then fails to find the file.
 Response
<img width="835" alt="CleanShot 2023-08-08 at 10 31 32@2x" src="https://github.com/sst/sst/assets/35469348/32a2c3a9-7235-45e7-a6b7-84081bb1f7ea">

### Reproduction
Create a remix app, and set up the remix-flat-routes package. Add a nested folder route or two and deploy

**Comment by jayair** [comment]
Interesting, can you post this in #help on Discord. I'll get the team to take a look.
