### ISSUE TITLE
Feature request: Image Optimization Construct

### ISSUE THREAD

**Issue by jamesopstad** [sst/sst#3212]
Serving optimised images is a very common requirement and companies often end up paying for an image CDN (Imgix, Contentful etc.) so that they don't have to implement their own solution. SST could provide a construct that makes it much easier to implement this feature using AWS. This repo contains a good approach using CloudFront, S3 and Lambda - https://github.com/aws-samples/image-optimization. There is also an article about it here - https://aws.amazon.com/blogs/networking-and-content-delivery/image-optimization-using-amazon-cloudfront-and-aws-lambda/. I imagine some code could also be shared with the OpenNext image implementation.

**Comment by jayair** [comment]
That's interesting. So this would deploy an endpoint that would take images and return optimized versions of them?

I haven't read through that repo yet but how do you provide the source images? Are they uploaded to a given bucket?

**Comment by jamesopstad** [comment]
That's right. The original images are uploaded to a given bucket. A second bucket is used to store the generated images so that they are only generated once. You would request an image with a URL such as `https://YOURDISTRIBUTION.cloudfront.net/SRC?format=auto&width=200` (this URL format is really common for requesting optimised images and works with libraries such as [Unpic](https://unpic.pics/)). If the transformed image is already in the CloudFront cache then it is served from there. Otherwise it falls back to the S3 bucket that stores the generated images. If that fails then it falls back to invoking the Lambda, which generates the optimised image and stores it in the second bucket. This diagram shows the request flow:

![image](https://github.com/sst/sst/assets/13586373/37328957-816c-4f8a-822c-43ba0b0d9cc6)

**Comment by adamelmore** [comment]
hey, just saw this issue and have had the same thought (that this should be an sst construct). i've implemented that same solution in the statmuse.com repo if anyone wanted to use that example when implementing something more general purpose: https://github.com/statmuse/statmuse.com/blob/main/stacks/img-stack.ts

**Comment by sladg** [comment]
I implemented something like for previously, it's compatible with NextJS's api.
Code here: https://github.com/sladg/imaginex-lambda/tree/master
Cdk here: https://github.com/sladg/nextjs-lambda/blob/master/lib/cdk/utils/imageLambda.ts

Hope it helps

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by isaac-scarrott** [comment]
Hey, I've implemented the image optimisation as detailed in the [AWS blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/image-optimization-using-amazon-cloudfront-and-aws-lambda/) in an SST v3 stack if anyone is interested:

https://github.com/todoengineering/sst-cloudfront-image-optimizer

SST doesn't have all the constructs to make this happen with live development so not sure this would be a great example?
