### ISSUE TITLE
[Feature Request] Add support to Remix manual mode

### ISSUE THREAD

**Issue by jvzaniolo** [sst/sst#3214]
# Remix manual mode

With Remix, it's possible to run it manually by spinning a custom server instead of running the default one with `remix-serve`.
But the start command changes from `remix-serve build` to `node ./server.js`.

When deploying to AWS, _I think_ that CloudFront serves the `/build/index.js` generated in the `build` command.
Is there a way to instead, make it run my custom server `./server.js`?

Additionally, could you make the `RemixSite` construct ESM compatible?

## Related documentation

- [Manual mode | Remix](https://remix.run/docs/en/main/guides/manual-mode)

## Discord questions

- [Error when deploying Remix in manual mode.
](https://discord.com/channels/983865673656705025/1139189073014169641)

**Comment by jayair** [comment]
Yup I replied on Discord

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
