### ISSUE TITLE
Invoking Job during local dev in SST Console fails after not running for a few mins

### ISSUE THREAD

**Issue by relsunkaev** [sst/sst#3215]
I'm getting the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1097:7)
    at Object.pathToFileURL (node:internal/url:1463:25)
    at file:///.../node_modules/sst/support/nodejs-runtime/index.mjs:45:24
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Rerunning `sst dev` solves the issue

## Environment
| Dependency | Version |
| - | - |
| sst | 2.23.14 |
| node | 18.17.0 |
| esbuild | 0.18.20 |

**Comment by jayair** [comment]
That's weird. Does it happen every time when you start it?

**Comment by jayair** [comment]
Also are you on the latest? Something similar was reported a week ago that was fixed.

**Comment by Brian-Azizi** [comment]
I also started experiencing this. Same symptoms as OP

**Comment by jayair** [comment]
Can you all try this one https://github.com/sst/sst/releases/tag/v2.24.3

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
