### ISSUE TITLE
🐛 SST Documentation is wrong and outdated

### ISSUE THREAD

**Issue by AdrKacz** [sst/sst#3225]
[This official article](https://sst.dev/chapters/dynamically-generate-social-share-images-with-serverless.html) needs to be updated, and no newer article tackles this issue.

Can someone with domain expertise please upgrade the article so it is helpful to the community or mark it as **OUTDATED**. Indeed, I don't expect the official documentation to have broken instructions.

Link to the article: https://sst.dev/chapters/dynamically-generate-social-share-images-with-serverless.html

**Comment by jayair** [comment]
Do you mind sharing what was the issue you ran into so we can go fix it?

**Comment by AdrKacz** [comment]
That part from the article is not up to date:
```ts
const api = new Api(stack, "Api", {
  routes: {
    "GET /{template}/{file}": {
      function: {
        handler: "functions/lambda.handler",
        // Increase the timeout for generating screenshots
        timeout: 15,
        // Load Chrome in a Layer
        layers: [layer],
        bundle: {
          // Copy over templates
          copyFiles: [
            {
              from: "templates",
              to: "templates",
            },
          ],
          // Exclude bundling it in the Lambda function
          externalModules: ["chrome-aws-lambda"],
        },
      },
    },
  },
});
```
*`bundle` doesn't exist anymore in Function*

The import are a bit misleading and don't work out of the work (they probably use to work), I cross different articles from SST (this is not the only article talking about Puppeteer) and eventually got a working configuration 👍

For reference in case it helps future user (*well, it will probably be outdated in a few weeks but anyway*):

```ts
{
    handler: YOUR HANDLER,
    timeout: "2 minute",
    // Use 18.x here because in 14, 16 layers have some issue with using NODE_PATH
    runtime: "nodejs18.x",
    // Load Chrome in a Layer
    layers: [layerChromium],
    // Exclude bundling it in the Lambda function
    nodejs: {
        esbuild: {
          external: ["chrome-aws-lambda"],
        },
        install: ['@sparticuz/chromium']
      },
  }
```

With
```ts
const layerArn = `arn:aws:lambda:${stack.region}:764866452798:layer:chrome-aws-lambda:33`;
layerChromium = lambda.LayerVersion.fromLayerVersionArn(stack, "ChromeLayer", layerArn)
```

Making sure to install in `package` the correct version of `puppeteer-core` and `@sparticuz/chromium`

You will find on  AWS Lambda Layer for Chromium `README` ([`chrome-aws-lambda-layer`](https://github.com/shelfio/chrome-aws-lambda-layer)) the chromium version supported by the layer, you will then find on [Puppeteer's Chromium Support page](https://pptr.dev/chromium-support) the version of `puppeteer-core` that goes with it.

For example, with layer version `33` (the one above), you need to install:

```sh
cd packages/functions
yarn add puppeteer-core@19.4.0
yarn add @sparticuz/chromium@109
```


*Well overall, that probably didn't worth an "Issue", all the context was available in different articles, I struggled to find out hox to mix the different solutions, my bad* ☺️

**Comment by jayair** [comment]
Appreciate this! It'll help me update the doc.

**Comment by KryptonTh** [comment]
Are there plans to update the SST Guide to incorporate aws & aws-amplify gen2 updates?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
