### ISSUE TITLE
🐛 Unknown application error occurred Runtime.Unknown

### ISSUE THREAD

**Issue by AdrKacz** [sst/sst#3226]
I created a stack with only one `Functions`. I deployed the stack with Live Lambda Development, the function run as expected (`yarn dev`).

However, when deploying the stack without Live Lambda Development (`yarn deploy`) and then executing the function from the SST Console (`sst console`), I receive a very obscure message:

```
Unknown application error occurred Runtime.Unknown
```

There is nothing else to investigate.

Here is the definition of my stack:
```ts
    const layerArn = `arn:aws:lambda:${stack.region}:764866452798:layer:chrome-aws-lambda:22`;
    const layerChromium = lambda.LayerVersion.fromLayerVersionArn(stack, "ChromeLayer", layerArn)
      
    const function = new Function(stack, "function", {
        handler: "packages/functions/src/function.handler",
        timeout: "1 minute",
        // Use 18.x here because in 14, 16 layers have some issue with using NODE_PATH
        runtime: "nodejs18.x",
        // Load Chrome in a Layer
        layers: [layerChromium],
        // Exclude bundling it in the Lambda function
        nodejs: {
            esbuild: {
              external: ["@sparticuz/chromium", "chrome-aws-lambda"],
            },
          },
    })
```

**Comment by jayair** [comment]
Just to double-check, I replied this to on Discord right?

**Comment by AdrKacz** [comment]
Yes, thank you 😁 I replied there 👍 It's a bit misleading to have Discord and Github (well, if the community prefers Discord I don't mind, just that request posted on Discord are not indexed by Google search engine, which makes it harder to reach information)

**Comment by jayair** [comment]
No worries! Yeah our community is on Discord and that's the best place to get help.

**Comment by floriangosse** [comment]
Could you link the answer form Discord in here? Would be quite helpful wo everyone who has the same problem.

**Comment by floriangosse** [comment]
I found the topic on Discord: https://discord.com/channels/983865673656705025/1140970984816517150.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
