### ISSUE TITLE
[Feature Request] Make sst reuse parts of the deployment that haven't changed

### ISSUE THREAD

**Issue by BLucky-gh** [sst/sst#3235]
Right now every time I do `sst deploy` it builds the whole stack from scratch, even if I only changed one file in one of the 7 packages I'm deploying.

It would be nice if sst kept track of whether a given package changed (for example by just storing a checksum of the package folder in `.sst` or even in cloudformation metadata, since sst already has to check what the package root is for a given file, and only redeploying that part if the checksum changed. To make it work faster a method similar to `zsync` could be used where 2 checksums are stored, a simple crc checksum and a more collision resistant cheksum are stored at the same time, and the other checksum only gets checked if there's a match on the crc checksum)

This would greatly reduce deployment times, especially in cases like mine where one of the apis I'm using has to rebuild numpy from scratch instead of pulling from pypi so that it fits within lambda's limits, which takes 10 minutes by itself. It's not as big of a problem during manual deploys since it gets cached by docker, but it really slows down our ci whenever we clear the cache to get a newer version of deps

**Comment by BLucky-gh** [comment]
Another option I just thought of:
`sst build` could take another opt-in argument that specifies what package to build and only build that (for example in a stack with `Api("foo")` and `NextjsSite("bar")` let the user just build `bar`) and then just let the user manage that with for example turborepo.

**Comment by jayair** [comment]
Yeah we actually have some ideas around this. It's based around Turborepo. But it's a little further away on our roadmap.

**Comment by BLucky-gh** [comment]
Great, how far down the roadmap is it, is it gonna be done in the near future?

And in the meantime, where can I get any info on how to build most if not all of it myself instead of relying on `sst build --to`? I wanna try make a bandaid fix for it to at least reduce *some* of the duplication of effort, at least for things that don't require anything to be known at build time like backend APIs (cause it's gonna be hard to assign env vars that are derived from other constructs at build time outside of sst)

I took a look into the folder that's generated by `sst build --to` but there are a bunch of `asset.*` archives and folders with a naming scheme I don't understand just by looking at it so I don't know how to replicate that manually

**Comment by BLucky-gh** [comment]
> But it's a little further away on our roadmap.
@jayair by the way is there a tracking issue for this? I'd like to subscribe to it to keep up with any changes

**Comment by mpurdon** [comment]
Bumping this

**Comment by jayair** [comment]
Yeah we have some ideas on this, caching the assets that get built. But we haven't gotten to it yet.

**Comment by romulovalez** [comment]
+1, deployment time increases a lot more when deploying a NextjsSite resource, even if there have been no changes to this resource

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
