### ISSUE TITLE
Error: Unexpected token '{' when I use export class with sst dev 

### ISSUE THREAD

**Issue by montoyan877** [sst/sst#3239]
When I run the project with `npm sst dev` and call a lambda that calls a class exported with `export class`, I get the following error:

```
   Error: Unexpected token '{'
         at Loader.moduleStrategy(node:internal/modules/esm/translators:146:18)
         on the asynchronous link (node: internal/modules/esm/module_job:67:21)
```

This doesn't happen when running `npm sst deploy`, so I guess it could be a node version problem, I currently have 16.9.1, do you know what it could be?

Update: The problem is the version of node, I change to the node 18 that is the same of lambda Runtime and now work well.

**Comment by jayair** [comment]
I wonder if that's an issue with that specific version.
