### ISSUE TITLE
Quickstart issue

### ISSUE THREAD

**Issue by msimonc** [sst/sst#3240]
I had to run: "npm run dev" twice.

The first time I got "Internal Server Error" when I Postman'd the endpoint.

https://docs.sst.dev/live-lambda-development#quick-start

**Comment by montoyan877** [comment]
I have the same problem https://github.com/sst/sst/issues/3239

**Comment by jayair** [comment]
Which version of Node were you using @msimonc @montoyan877?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
