### ISSUE TITLE
[Feature request] Include source in published package and set declarationMap to true

### ISSUE THREAD

**Issue by steve-taylor** [sst/sst#3261]
When command/CTRL-clicking something imported from SST in Visual Studio code, I always end up at the type definition file, which isn't very useful. I can right-click the editor tab and then select _Reveal in Explorer View_, which takes me to the compiled JavaScript, but I have to flick back and forth to see the types associated with the implementation. What I ideally want is to navigate to the source and, fortunately, TypeScript has a nice feature to enable it.

Simply add `"declarationMap": true` to `tsconfig.json`'s `compilerOptions` and include SST's source in the published package. We'll now be able to navigate directly to the implementation source in Visual Studio Code. This will greatly improve the developer experience by easily being able to see what SST is doing under the hood.

**Comment by jayair** [comment]
Oh interesting. Let me share this internally.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
