### ISSUE TITLE
Support bun (an all-in-one JavaScript runtime)

### ISSUE THREAD

**Issue by dror-weiss** [sst/sst#3264]
Bun is growing and its official 1.0 launch is near (09-2023).

**I would love to see sst supporting bun as an AWS `provided` runtime.** 

The gist of my bun lambda setup:

1. Added a bun layer containing a bootstrap script and a binary (based on arm arch).
[see official docs](https://github.com/oven-sh/bun/tree/main/packages/bun-lambda#bun-lambda)

2. Wrote a lambda:
`lambda.ts`
```ts
export default { 
  async fetch(request: Request): Promise<Response> { 
    console.log(request.headers.get("x-amzn-function-arn")); 
    // ... 
    return new Response("Hello from Lambda!", { status: 200, headers: { "Content-Type": "text/plain", }, }); 
  }, 
}
```

3. Wrote an index file with the expected format by AWS:
`index.ts`
```ts
import lambda from "./lambda";

export default {
  js: lambda.fetch
};
```

4. Build the lambda using bun for the `bun` target:
```sh
bun build --target=bun --minify --outfile=index.js index.ts
```

5. Deploy `index.js` with matching runtime and arch.

**Comment by jayair** [comment]
We've definitely looked at this. Thoughts @thdxr?

**Comment by dror-weiss** [comment]
I've started working on a PR for this but it will take me some time to understand the code enough to complete it.

Right now I have encountered a few difficulties in implementing the build/cache process, despite `Bun.build` being heavily inspired by esbuild (what's used in node).

**Comment by jayair** [comment]
Do you think we need to switch the esbuild part of it though?

**Comment by dror-weiss** [comment]
I think the `bun` handler that needs to be added in `packages/sst/src/runtime/handlers` should use [`Bun.build`](https://bun.sh/docs/bundler).

I also think that someone with an intimate understanding of the codebase would be a better fit than me, as it's taking me more time than expected to issue a PR with this support. If there are guidelines for the codebase itself (more detailed than the one for contributors) I can try it.

**Comment by 5o50** [comment]
https://github.com/oven-sh/bun/issues/5549

**Comment by ivawzh** [comment]
Any updates on supporting bun in general?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
