### ISSUE TITLE
Constructs for SsrSite use AWS deprecated Python version 3.7

### ISSUE THREAD

**Issue by sadin999** [sst/sst#3289]
The constructs for SsrSite use a deprecated Python version - is there any harm in a straight upgrade for this to 3.11?

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy

One of the affected lines: 
https://github.com/sst/sst/blob/b483e6ad987ebf9ef1940daa058950909950a240/packages/sst/src/constructs/SsrSite.ts#L798C1-L799C1

**Comment by jayair** [comment]
Wait is it deprecated? That link shows that it's still supported?

**Comment by jayair** [comment]
Oh I see a PR for it https://github.com/sst/sst/pull/3285

**Comment by fwang** [comment]
Fixed in v2.25.0
