### ISSUE TITLE
experimentalUseProvidedRuntime not effected when running "npm run deploy"

### ISSUE THREAD

**Issue by ljd1991** [sst/sst#3298]
Recently I've been using SST to develop an serverless application, using Quarkus, which is a Java Framework, to develop lambda function code.

In order to provide a better performance, Quarkus provides an ability to build function to native image, which can be used with provided/ provided.al2 runtime in lambda instead of java runtime. 

Following [experimentalUseProvidedRuntime](https://docs.sst.dev/constructs/Function#experimentaluseprovidedruntime) docs, I tried to config with provided/provided.al2 runtime,  here is the configuration of a function in an API

```typescript
const api = new Api(context.stack, "api", {
    routes: {
        "POST /app": {
            function: {
                runtime: "java11",
                java: {
                    experimentalUseProvidedRuntime: "provided.al2"
                },
                handler: "io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest",
                environment: {
                    "QUARKUS_PACKAGE_TYPE": `native`
                }
            }
        }
    }
}
```

but it seems not working. When run `npm run deploy`, lambda function still configured with Java11 runtime

After reading some source code of SST, it seems that provided runtime is not supported any more?

- sst/constructs/Function.js

```typescript
/*
if (isJavaRuntime) {
  const providedRuntime = (bundle as FunctionBundleJavaProps)
    .experimentalUseProvidedRuntime;
  if (providedRuntime) {
    cfnFunction.runtime = providedRuntime;
  }
}
*/
```

If so, how can I use provided runtime or is it impossible? Please let me know.

**Comment by jayair** [comment]
Hmm that's weird.

**Comment by fwang** [comment]
@ljd1991 I brought the code back in #3314.

The ability to use user provided runtime for Java was contributed by the community. I don't have a setup at hand to test it.

Can you give v2.25.3 a try, and see if it works.

**Comment by ljd1991** [comment]
> @ljd1991 I brought the code back in #3314.
> 
> The ability to use user provided runtime for Java was contributed by the community. I don't have a setup at hand to test it.
> 
> Can you give v2.25.3 a try, and see if it works.

hello @fwang, I tried with v2.25.3 and provided runtime is configured properly. Thanks for the work~ 
I still wonder why are these codes excluded in the first place, were there any bugs related to these codes?

**Comment by fwang** [comment]
Awesome.

Looks like the code was commented out when SST went from v1 to v2. No it wasnt intentional.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
