### ISSUE TITLE
Detect app failed to build in `sst start` and auto rebuild every few seconds.

### ISSUE THREAD

**Issue by fwang** [sst/sst#33]
### How to reproduce
1. In a lambda handler file, add a new import at the top (at this point the imported files does not exist yet)
2. `sst start` console shows the build failed
3. Now add the import file, the watcher does not trigger a rebuild

### How to fix
- [ ] Flag the entry points failed to build
- [ ] Rebuild the entry points when a request comes in for the Lambda
- [ ] Rebuild the failed entry points every second of every X seconds

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
