### ISSUE TITLE
Add option for docker-less python lambda bundling for CI environments

### ISSUE THREAD

**Issue by BLucky-gh** [sst/sst#3312]
Some CI environments (for example gitlab ci or self-hosted gh actions runners on fargate/lambda containers, etc) do not allow running a docker containers due to the fact that the runner itself is in an unprivileged docker container.

Since CI environments can be controlled, and are usually linux anyways, there's not as much of a need to bundle the function with docker, so an option to bundle with system python/pip would be nice

**Comment by jayair** [comment]
Would accept a PR for this!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
