### ISSUE TITLE
Optimized images are not being cached efficiently on Cloudfront

### ISSUE THREAD

**Issue by gkaskonas** [sst/sst#3317]
I've been having some mixed results with it. Sometimes it take over over 2s to generate an image and it doesn't get cached on the CDN.
Once everything is cached on the client its fast but those first loads are pretty bad

```
  images: {
    minimumCacheTTL: 86400,
    deviceSizes: [320, 640, 768, 1024, 1280, 1536, 1820, 2000],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    formats: ["image/webp", "image/avif"],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "media.graphassets.com",
      },
    ],
  },

```

```
This is my images config. Nothing to crazy, right? 
                        <Image
                          src={bradley_testimonial}
                          alt="Bradley Testimonial"
                          placeholder={"blur"}
                          width={1024}
                          quality={60}
                          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                          onLoadingComplete={image => image.classList.remove("opacity-0")}
                          className="w-full rounded-t-lg lg:rounded-tr-none lg:rounded-bl-lg transition-opacity opacity-0 duration-[0.5s]"
                        />
```

cloudfront says that /_next/image hit ratio is just ~51%

I think the issue is in sst here, we should probably not use the same cache policy as the server. We don't need to add rsc, next-router-prefetch, next-url, next-router-state-tree to the cache key. https://github.com/sst/sst/blob/7e6e68d03696b27a5d5a566e4168a7b2bdb52178/packages/sst/src/constructs/NextjsSite.ts#L383

**Comment by khuezy** [comment]
We'd only need to cache the query string. We could do `all`, but maybe we can just cache the ones specific to next image optimization, eg: url=<url>&w=<width>&q=<quality>

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
