### ISSUE TITLE
Does not work 'pnpm sst dev' on the clean project 

### ISSUE THREAD

**Issue by ugreek85** [sst/sst#3330]
pnpm sst dev                                                
✖ Deploying bootstrap stack, this only needs to happen once

Error: Failed to load bootstrap stack status

Need help with this error? Post it in #help on the SST Discord https://sst.dev/discord

SST: v2.25.6
CDK: v2.95.1
Constructs: v10.2.69

npm: 9.8.1
node: v16.14.0

**Comment by jayair** [comment]
Like the error message says, post this in #help on Discord?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
