### ISSUE TITLE
It does not work when I try the "eu-central-1" region, but for "us-east-1" everything works perfectly. 

### ISSUE THREAD

**Issue by ugreek85** [sst/sst#3342]
I tried multiple times but nothing changed
How can I fix this?

Failed resources:
CDKToolkit | 12:28:27 AM | CREATE_FAILED        | AWS::S3::Bucket         | StagingBucket cdk-hnb659fds-assets-{accountId}-eu-central-1 already exists
 ❌  Environment aws://{accountId}/eu-central-1 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-hnb659fds-assets-{accountId}-eu-central-1 already exists
    at FullCloudFormationDeployment.monitorDeployment (/project_path/node_modules/sst-aws-cdk/lib/index.js:426:10236)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /project_path/node_modules/sst-aws-cdk/lib/index.js:431:2104
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (/project_path/node_modules/sst-aws-cdk/lib/index.js:431:1949)
    at async exec4 (/node_modules/sst-aws-cdk/lib/index.js:504:52797)

The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-hnb659fds-assets-{accountId}-eu-central-1 already exists

//sst.config.ts

import { SSTConfig } from "sst";
import { API } from "./stacks/MyStack";

export default {
  config(_input) {
    return {
      name: "{project_name}",
      region: 'eu-central-1',
    };
  },
  stacks(app) {
    app.stack(API);
  }
} satisfies SSTConfig;

**Comment by jayair** [comment]
Can you follow the steps the error message is saying?

**Comment by gregosgr** [comment]
(Im a noob, just started to use SST) it has nothing to do with regions. As the error message states, you already have a bucket with this name deployed... Most probably from an earlier SST run. You need to manually delete the bucket in your AWS console. Removing CloudFormation stack manually could help you guide through what are dangling pieces that SST automatically created. Also you may try to tweak the default removal policy https://docs.sst.dev/advanced/removal-policy

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
