### ISSUE TITLE
The `StaticSite` construct fails if the path contains a space

### ISSUE THREAD

**Issue by morficus** [sst/sst#3344]
https://discord.com/channels/983865673656705025/1152257795559784478
---
link to discuss ☝️ 

As the title states, if the path to the project contains a space, then the build process for the `StaticSite` construct will fail. This also seems to apply to the `SsrSite` and `NextJsSite` (well, the deprecated one) constructs as well.

For example:
If the project path is `/home/morficus/my cool project/app` then things will fail. But if the path is `/home/morficus/my-cool-project/app` then everything is fine.

**Comment by morficus** [comment]
After doing quite a bit of digging, I was able to determine that the root cause is because `child_process.exec()` (and by extension, `execSync()` do not support spaces in the command path. You can read all about it on this NodeJS issue from 2016: https://github.com/nodejs/node/issues/6803

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
