### ISSUE TITLE
Cron timeout not applied

### ISSUE THREAD

**Issue by bauer01** [sst/sst#3352]
---

Hi guys,
we've just discovered that when we create cron

```typescript
new Cron(this, 'CleanerFunction', {
	'rate(5 minutes)',
	job: {
		function: 'packages/constructs/cf-toolkit/cleaner/src/function.handler',
		timeout: Duration.minutes(15)
	}
})
```

it does not reflect timeout and in AWS console I can see it's still default 10s

But it works with this:

```typescript
new Cron(this, 'CleanerFunction', {
	"rate(5 minutes)",
	job: {
		function: {
			handler: 'packages/constructs/cf-toolkit/cleaner/src/function.handler',
			timeout: '15 minutes'
		}
	}
})
```

**Comment by jayair** [comment]
https://docs.sst.dev/constructs/Function#timeout

That's what it takes. Btw are you using TS? That config looks weird.

**Comment by oscarhermoso** [comment]
FYI @jayair  - I ran into the same issue as @bauer01, but worked around by setting the default function props

As per docs & types, the Cron Construct doesn't seem to support support `timeout` - https://docs.sst.dev/constructs/Cron

Workaround: https://docs.sst.dev/constructs/Function#setting-default-props

```ts
import { StackContext, Config, Cron } from 'sst/constructs';

export function API({ app, stack }: StackContext) {
	stack.setDefaultFunctionProps({
		timeout: '15 minutes',
		memorySize: 512,
	});

	const file_cleanup_cron = new Cron(stack, 'cron', {
		schedule: 'rate(1 hour)',
		job: {
			function: 'services/file-cleanup/src/main.handler',
		},
		enabled: !app.local,
	});
}
```

**Comment by jayair** [comment]
No no, any construct that takes a function is customizable. This takes a full function object https://docs.sst.dev/constructs/Cron#job

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
