### ISSUE TITLE
Select Python interpreter with Live Lambda + Install commands

### ISSUE THREAD

**Issue by JeffreyWardman** [sst/sst#3362]
Live Lambda uses the default Python environment and doesn't run the install command.

**Comment by jayair** [comment]
I'm not well versed in Python, but what are you looking to do?

**Comment by JeffreyWardman** [comment]
Hi @jayair, I'm looking to run a Python-based API locally. For reference, my OS is Ubuntu-based. I am using a different Python version to the default. So when I run Live Lambda, it tries to call the default, rather than trying to find the version specified (3.10 in the below example). My default is Python 3.8.12 and this Python version is called when running Live Lambda. I believe it's calling `python` rather than `python3.10`, although this change still wouldn't simulate a clean environment as `python3.10` might have additional packages installed locally.

It also doesn't run install commands. It would be good to be able to either a) allow for pointing to a Python venv when using Live Lambda, or b) to create its own. Afterwards, the install commands running is a necessity to replicate the API running on AWS.

```
  const api = new Api(stack, "Api", {
    defaults: {
      function: {
        timeout: 120,
        runtime: "python3.10",
        python: {
          installCommands: ["pip install -r requirements.txt"]
        }
      }
    }, ...
```

Hope that's clear and helpful.

**Comment by jayair** [comment]
Yeah so with Live Lambda we use what's available locally as opposed to the one defined in your config. This is true for the Node case as well. For some Python help I recommend posting on #python in our Discord. They know more about this than I do.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
