### ISSUE TITLE
SsrFunction overrides some props

### ISSUE THREAD

**Issue by dani-mp** [sst/sst#3366]
`SsrFunction` is overriding some props (e.g. timeout), hence not respecting what's defined in userland.

I noticed this when I upgraded sst to v2.26.9 and my RemixSite logs showed that all the invocations durations were max 10k ms.

See https://github.com/sst/sst/blob/347666100a43047512b614fb785bedd61e4a911f/packages/sst/src/constructs/SsrFunction.ts#L86-L96

**Comment by bayssmekanique** [comment]
Resolved in #3370
