### ISSUE TITLE
"sst bind" crashes if there are parameters in Parameter Store with an "SST-looking" name

### ISSUE THREAD

**Issue by dankochetov** [sst/sst#3367]
I have a parameter with a name like this: `/sst/sc/dev-stable/mobile-env` (for context, it was manually created by another developer, not used in SST, they just tried to follow a naming pattern)
When I tried to run something via `sst bind`, it crashed with an error: `TypeError: Cannot read properties of undefined (reading 'replace')`
I traced the error down to this line - https://github.com/sst/sst/blob/master/packages/sst/src/config.ts#L99
Apparently, SST detects that the parameter name starts with `/sst/`, assumes it was created by SST, tries to extract parts from the name but does it incorrectly, because, obviously, the parameter wasn't supposed to be used with SST. It would be good to have an additional check that the parameter name actually matches the expected pattern and skip the parameter otherwise.

**Comment by jayair** [comment]
Oh that's interesting. Would appreciate a PR for this if possible. If not then I'll ask the team to take a look.

**Comment by yugandhara-adi** [comment]
Any updates on this one?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
