### ISSUE TITLE
Check Node version when running

### ISSUE THREAD

**Issue by bt** [sst/sst#3372]
I recently just came across an issue which took me an hour to solve -- I was getting the following error when a Lambda was executed:

```
Error: invocations.findLastIndex is not a function
```

It took me long enough to realise that the issue was that I was running Node 16, and `findLastIndex` was not available until Node 18. While I know that it's technically my fault for running an EOL version of Node, it would be good for good developer experience to give a warning upon running SST CLI on versions that were not tested to be compatible, to save future developers from issues like these.

Happy to produce a PR if required!

**Comment by jayair** [comment]
Yeah this would be useful. Let me get the team to give some pointers before you start on the PR.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
