### ISSUE TITLE
Wrong version of cdk-assets resolved for 2.25.0 SST project when in a pnpm monorepo with a 2.24.28 SST project

### ISSUE THREAD

**Issue by chestercharles** [sst/sst#3375]
I'm running into an issue in a monorepo using pnpm. The wrong version of `cdk-assets` is resolved for >= 2.25.0 SST project when running in a pnpm monorepo with a 2.24.28 SST project.

I `console.log`'ed the version of `cdk-assets` resolved at runtime for my >= 2.25.0 SST project and observed that it is 2.91.0, but that is the version used by SST 2.24.x. 

It manifests as the following error after running `sst dev`

```bash
⠼  Bus PUBLISH_ASSETS_IN_PROGRESS
⠼  ShopsTable PUBLISH_ASSETS_IN_PROGRESS
|  ShopsTable PUBLISH_ASSETS_COMPLETE 
⠼  Bus PUBLISH_ASSETS_IN_PROGRESS
[50%] fail: Unrecognized asset type: '[object Object]'
|  Bus PUBLISH_ASSETS_COMPLETE 
⠋  Deploying...

✖  Errors
   ShopsTable UPDATE_FAILED
   stack: Failed to publish one or more assets. See the error messages above for more information.
   ShopTableSeed DEPENDENCY_FAILED
   ShopsEventHandlers DEPENDENCY_FAILED
   ShopsSubgraph DEPENDENCY_FAILED
   Bus UPDATE_FAILED
   stack: Failed to publish one or more assets. See the error messages above for more information.
```

**More Details:**

- When I run the project outside of a monorepo (still using pnpm) it works fine.

- When I remove the 2.24.28 SST project from the monorepo it works fine.

- When I add `"cdk-assets": "2.95.1"` to my package json it works fine. 

**Possible root cause**

SST depends on a package called `sst-aws-cdk` which appears to be a fork of `aws-cdk`. SST uses the `publishAssets` function from this library, which is where the error described above originates. 

[The version of `sst-aws-cdk` that the latest version of SST depends on is `2.91.0`](https://github.com/sst/sst/blob/bcf82650fef1161178426881e8b8b86ebb81461a/packages/sst/package.json#L100). It seems like this should be `2.95.1`, in order to match the version of `aws-cdk-lib` that SST depends on. However, I'm not sure why this would cause issue in a monorepo, but not in a single repo. 

Should the `sst-aws-cdk` package that the latest version of sst is using be updated to 2.95.1?

---

Discord Thread:

https://discord.com/channels/983865673656705025/1153846634271215676

**Comment by jayair** [comment]
I followed up on that thread.

**Comment by Dzhuneyt** [comment]
I had the same issue yesterday. We have a monorepo that uses PNPM. There are two SST applications/packages inside that monorepo.

I am assuming the issue came from some mixed versions of SST or CDK being installed and hoisted to the root node_modules.

The way I solved it (a workaround) is to run an `npm install` inside the specific SST package that was throwing this error. Not saying you should ditch PNPM and go back to NPM commands, but in this case - it seems a combination of factors is throwing off the PNPM hoisting behavior.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
