### ISSUE TITLE
invocations.findLastIndex is not a function

### ISSUE THREAD

**Issue by alli-MBI** [sst/sst#3380]
I am able to deploy the stack fine, but once I try to make any invocations I get the following error, and the session force quits. 

I was running v2.25 and this happened, upgraded to 2.27 in hopes that it would fix the error, but it is still persistent.

> Invoked backend/functions/list.getProjects
> 
> Error: invocations.findLastIndex is not a function
> 
> Trace: TypeError: invocations.findLastIndex is not a function
>     at publish (file:///C:/Projects/BITS/node_modules/sst/cli/local/server.js:108:35)
>     at Object.cb (file:///C:/Projects/BITS/node_modules/sst/cli/local/server.js:218:9)
>     at Object.publish (file:///C:/Projects/BITS/node_modules/sst/bus.js:28:21)
>     at DeviceClient.<anonymous> (file:///C:/Projects/BITS/node_modules/sst/iot.js:140:17)
>     at DeviceClient.emit (node:events:527:28)
>     at DeviceClient.emit (node:domain:475:12)
>     at MqttClient.<anonymous> (C:\Projects\BITS\node_modules\aws-iot-device-sdk\device\index.js:826:12)
>     at MqttClient.emit (node:events:527:28)
>     at MqttClient.emit (node:domain:475:12)
>     at Arguments.<anonymous> (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\mqtt\lib\client.js:1265:27)
>     at Object.MqttClient.options.customHandleAcks (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\mqtt\lib\client.js:183:150)
>     at MqttClient._handlePublish (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\mqtt\lib\client.js:1258:15)
>     at MqttClient._handlePacket (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\mqtt\lib\client.js:410:12)
>     at work (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\mqtt\lib\client.js:321:12)
>     at Writable.writable._write (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\mqtt\lib\client.js:335:5)
>     at doWrite (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\readable-stream\lib\_stream_writable.js:390:139)
>     at writeOrBuffer (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\readable-stream\lib\_stream_writable.js:381:5)        
>     at Writable.write (C:\Projects\BITS\node_modules\aws-iot-device-sdk\node_modules\readable-stream\lib\_stream_writable.js:302:11)      
>     at Duplexify.ondata (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:619:20)
>     at Duplexify.emit (node:events:527:28)
>     at Duplexify.emit (node:domain:475:12)
>     at addChunk (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:291:12)
>     at readableAddChunk (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:278:11)
>     at Duplexify.Readable.push (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:245:10)
>     at Duplexify._forward (C:\Projects\BITS\node_modules\duplexify\index.js:170:26)
>     at Transform.onreadable (C:\Projects\BITS\node_modules\duplexify\index.js:134:10)
>     at Transform.emit (node:events:527:28)
>     at Transform.emit (node:domain:475:12)
>     at emitReadable_ (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:504:10)
>     at emitReadable (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:498:62)
>     at addChunk (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:298:29)
>     at readableAddChunk (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:278:11)
>     at Transform.Readable.push (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_readable.js:245:10)
>     at Transform.push (C:\Projects\BITS\node_modules\readable-stream\lib\_stream_transform.js:148:32)
>     at WebSocket.onmessage (C:\Projects\BITS\node_modules\websocket-stream\stream.js:167:11)
>     at WebSocket.onMessage (C:\Projects\BITS\node_modules\websocket-stream\node_modules\ws\lib\EventTarget.js:99:16)
>     at WebSocket.emit (node:events:527:28)
>     at WebSocket.emit (node:domain:475:12)
>     at Receiver._receiver.onmessage (C:\Projects\BITS\node_modules\websocket-stream\node_modules\ws\lib\WebSocket.js:141:47)
>     at Receiver.dataMessage (C:\Projects\BITS\node_modules\websocket-stream\node_modules\ws\lib\Receiver.js:380:14)
>     at Receiver.getData (C:\Projects\BITS\node_modules\websocket-stream\node_modules\ws\lib\Receiver.js:330:12)
>     at Receiver.startLoop (C:\Projects\BITS\node_modules\websocket-stream\node_modules\ws\lib\Receiver.js:165:16)
>     at Receiver.add (C:\Projects\BITS\node_modules\websocket-stream\node_modules\ws\lib\Receiver.js:139:10)
>     at TLSSocket.<anonymous> (C:\Projects\BITS\node_modules\websocket-stream\node_modules\ws\lib\WebSocket.js:138:22)
>     at TLSSocket.emit (node:events:527:28)
>     at TLSSocket.emit (node:domain:475:12)
>     at addChunk (node:internal/streams/readable:315:12)
>     at readableAddChunk (node:internal/streams/readable:289:9)
>     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
>     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
>     at process.<anonymous> (file:///C:/Projects/BITS/node_modules/sst/cli/sst.js:62:21)
>     at process.emit (node:events:539:35)
>     at processEmit [as emit] (C:\Projects\BITS\node_modules\signal-exit\index.js:199:34)
>     at process._fatalException (node:internal/process/execution:167:25)
>     at processPromiseRejections (node:internal/process/promises:279:13)
>     at processTicksAndRejections (node:internal/process/task_queues:97:32)

---

If you've already posted your issue on Discord, make sure to leave a link to it here.

**Comment by fabiaraujo** [comment]
thanks

Em sex., 6 de out. de 2023 às 12:16, Alli ***@***.***>
escreveu:

**Comment by jayair** [comment]
I think you need a Node 18 update. Node 16 is EOL.

**Comment by alli-MBI** [comment]
> I think you need a Node 18 update. Node 16 is EOL.

Fairly certain we upgraded to Node 18.

**Comment by jayair** [comment]
If you are on Node 18, then open a new thread in #help on Discord with some details about your project.

**Comment by dev2xl** [comment]
I can confirm that your local node should be at least 18. I had 16 and updated to 20 and the error was fixed

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
