### ISSUE TITLE
Please migrate your code to use AWS SDK for JavaScript (v3) - After lambda was invoked

### ISSUE THREAD

**Issue by dev2xl** [sst/sst#3385]
Invoked packages/functions/src/connect.main
|  Built packages/functions/src/connect.main
|  +832ms  (node:12424) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
|  +832ms  
|  +832ms  Please migrate your code to use AWS SDK for JavaScript (v3).
|  +832ms  For more information, check the migration guide at https://a.co/7PzMCcy
|  +832ms  (Use `node --trace-warnings ...` to show where the warning was created)
|  Done in 1070ms

Node local: v20.8.0
sst: 2.28.0

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
