### ISSUE TITLE
[Nextjs] Custom tags are not applied to all resources

### ISSUE THREAD

**Issue by JanStevens** [sst/sst#3412]
Hi,
We deploy our NextjsSite to lambda@edge using open-next, we noticed that the edge lambda's don't receive the tags we set. All other lambdas do get tagged. We are using the following way to tag the app

```typescript
stacks(app) {
    Tags.of(app).add('LUMIGO_TAG', `${process.env.LUMIGO_ENVIRONMENT} - SST`);
    // ... more setup
}
```

Regards

---

https://discord.com/channels/983865673656705025/1161984882390597652

**Comment by jayair** [comment]
Replied in Discord

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
