### ISSUE TITLE
Upgrade zod to v3.22.3 or higher

### ISSUE THREAD

**Issue by cdimitroulas** [sst/sst#3413]
sst currently has zod v3.21.4 as a dependency and dependabot has identified a vulnerability with this.

If sst could be updated to increase that dependency version, that would be great as it's currently the only thing preventing us from fixing this vulnerability (we can use yarn resolutions to solve it as a workaround for now).

**Comment by jayair** [comment]
Happy to accept a PR for this!

**Comment by sumit-kumar-bhowmick** [comment]
raised the PR.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
