### ISSUE TITLE
Allow for conflict resolution in AppSync's cdk: graphqlApi

### ISSUE THREAD

**Issue by JeffreyWardman** [sst/sst#3415]
From the documentation and props, it doesn't look like this is enabled as an option. Adding this feature would allow for better usage with AWS Datastore. Maybe it requires using the CDK construct as per https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/.

https://github.com/aws-amplify/amplify-category-api/issues/1952#issuecomment-1761996214

```
conflictResolution: {
  project: {
    handlerType: 'AUTOMERGE',
    detectionType: 'VERSION'
  }
}
```

**Comment by jayair** [comment]
Hmm can we open a #help thread on Discord for this? Alternatively a PR would help!

**Comment by JeffreyWardman** [comment]
@jayair I've opened up a thread but without any luck.

**Comment by fwang** [comment]
Hey @JeffreyWardman, I just followed up on Discord — https://discord.com/channels/983865673656705025/1163999915228270683/1166435230744322139

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
