### ISSUE TITLE
Failing Dotnet build does not log to stderr and thus does not get logged to the set build output

### ISSUE THREAD

**Issue by JNK** [sst/sst#3418]
In my project, I encountered a problem, where the dotnet publish command fails to build due to a missing package. Obviously something that I need to fix. The issue I encountered with set though is, that I did not get a meaningful error message from the build output.

The expected behavior is that during sst deploy, the error gets published to the console. Instead of this, all that is displayed (even in verbose mode) is `Error: Failed to build function "Project.Name.Here"`.

As it seems, dotnet does not write to stderr, but to stdout. I get the expected result, when I return `ex.stdout` instead of `ex.stderr` (affecting line linked below).

https://github.com/sst/sst/blob/3ccea2158acc84666d0f1c2e340929eba084a4cb/packages/sst/src/runtime/handlers/dotnet.ts#L129

**Comment by jayair** [comment]
Would appreciate a PR!

**Comment by chrisdlangham** [comment]
I believe this can be closed

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by chrisdlangham** [comment]
> We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

Great! Because it has already been completed
