### ISSUE TITLE
Can't add iam policies directly within route definition

### ISSUE THREAD

**Issue by aeftimia** [sst/sst#3421]
It seems we can have
```
    routes: {
      "GET /handle": {
          function: "packages/functions/src/file.somefunction",
        permissions: [bucket]
    },...
```

and 
```
    routes: {
      "GET /handle": {
          function: "packages/functions/src/file.somefunction",
        permissions: ["s3"]
    },...
```

But not 
```
    routes: {
      "GET /handle": {
          function: "packages/functions/src/file.somefunction",
          permissions: [new iam.PolicyStatement({...})]
          },...
```

For this, we seem to need 

```
  api.attachPermissionsToRoute("GET /handle", [new iam.PolicyStatement({...}])
```

Which is nice, but still requires a lot more repetition than the inline definitions available for other ways of defining permissions. I'd love to be able to define iam policies inline!

**Comment by jayair** [comment]
Hmm I'm pretty sure you can configure the whole function https://docs.sst.dev/constructs/Function#permissions

**Comment by aeftimia** [comment]
I think you can configure the whole function too. That said, I would like to be able to assign policies to routes for more granularity. The type signatures in the code seem to imply you can do this like you would assign any other permission to the route, but there might be a bug in the code that prevents those permissions from taking effect without using `attachPermissionsToRoute`. I tried it both ways and examined the lambda function's policies to confirm.

**Comment by jayair** [comment]
No I meant for permissions per route. You can set it for the specific function. https://docs.sst.dev/constructs/Api#configuring-an-individual-route

**Comment by aeftimia** [comment]
OK, it's possible that sst/aws cdk just doesn't always do updates consistently... I tried a few variations including your suggestion, and my original attempts and now I'm seeing the policies updated. I'm getting similarly inconsistent updates on environment variables. I'll close this out since it now seems more likely an inconsistency in updates than something specific to policies.

Thanks!
