### ISSUE TITLE
A few hiccups when trying to use SST for the first time.

### ISSUE THREAD

**Issue by gamliela** [sst/sst#3429]
Hello,

I recently had the opportunity to explore SST and wanted to share some observations and suggestions to enhance the platform. I'm experienced in web development, AWS, and CDK. I started with a fresh NextJS app and followed the guide [here](https://docs.sst.dev/migrating/vercel).

**Observations:**

1. **AWS Setup Guide:** The [AWS setup guide](https://docs.sst.dev/setting-up-aws) is excellent. It's well-detailed and helped me get started smoothly. Kudos for that!

2. **`npx sst dev` Role Clarification:** I found the role of `npx sst dev` a bit unclear. While the guide [mentions](https://docs.sst.dev/migrating/vercel#start-the-local-environment) it's for starting the local environment, it also requires AWS credentials. Clarifying its purpose, especially in relation to local Lambda debugging, would be helpful.

3. **`npx sst dev` Deployment:** After running `npx sst dev`, CDK finished successfully, but I couldn't find any endpoint to actually launch the app. So I then ran `npm run dev` and opened the app from localhost. This didn't seem to trigger the website Lambda on AWS (if that was ever supposed to happen). Overall, it wasn't clear what the stack was doing, and what is the relation between `npx sst dev` and `npm run dev`. Clarifying how these steps are connected could improve the experience.

4. **Deployment Error:** When attempting to deploy using `npx sst deploy --stage dev`, I encountered the following error message:

```
Site site/Distribution AWS::CloudFront::Distribution CREATE_FAILED Resource handler returned message: "Access denied for operation 'AWS::CloudFront::Distribution: Your account must be verified before you can add new CloudFront resources. To verify your account, please contact AWS Support."
```

Since this happened in a new AWS account, including a note in the guide about this potential issue and how to resolve it would be beneficial.

5. **Two Stacks:** I noticed two separate stacks generated by `npx sst dev` and `npx sst deploy --stage dev.` The latter stack was significantly larger. If one is meant for development aid and the other for the final site, making the first stack optional or excluding it from the Vercel migration guide could streamline the process.

6. **Resource Concerns:** The size of the stack was a bit overwhelming, especially for independent developers concerned about AWS expenses and enterprise workers dealing with IAM roles. Providing more guidance on optimizing resource usage or offering a leaner default setup could be helpful.

These observations are intended to contribute to the improvement of SST for all users. Thank you for your hard work on this project!

**Comment by jayair** [comment]
Thanks for this! Just curious if you checked out our quick start before trying the migration doc? https://docs.sst.dev/start/nextjs

For 2, we have this breakdown of what `sst dev` is https://docs.sst.dev/live-lambda-development

For 4, I did not know they do that for new accounts now. We'll add a note.

For 5, yeah with `--stage` you are basically doing a full deployment to a new stage. This is what powers preview environments etc.

For 6, we have this https://docs.sst.dev/advanced/bootstrapping

I think the migration doc needs an update on our side.

**Comment by gamliela** [comment]
Hi Jay,

Thank you for your response. I was curious to see what it would take to integrate SST into an existing NextJS project, so I decided to follow the migration guide. I also had a look at the quick-start guide. Thanks for providing the additional reference on bootstrapping; it appears to be quite detailed.

In general, it would be beneficial to have a more streamlined version of the project that doesn't necessitate live-lambda and potentially requires fewer resources.

Thanks again!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
