### ISSUE TITLE
crypto-js < 4.2.0 critical vulnerability

### ISSUE THREAD

**Issue by berenddeboer** [sst/sst#3447]
Using `pnpm audit --audit-level critical` we get a critical vulnerability. This seems to require an sst/sdk update to fix. The issue seems to be that sst uses an old (?) library: aws-iot-device-sdk

![image](https://github.com/sst/sst/assets/1514612/e1208ea0-743a-4af1-9caf-462b249cef2a)

---

If you've already posted your issue on Discord, make sure to leave a link to it here.

**Comment by ShyamMoorthy** [comment]
Any Suggestion on how this can be fixed?
