### ISSUE TITLE
Logical Id's always generating a string at the end of json template

### ISSUE THREAD

**Issue by lukiwlosek** [sst/sst#3462]
Hello, 
I am trying to migrate from serverless framework to sst, in order to do so I need exact logical Id's in both stacks (for a dynamo table migration), but the cfn template generated from sst always has some additional text at the end even when I try to overwrite with the cdk prop e.g:
```
 const table = new Table(stack, 'blah', {
    cdk: {
      id: 'lukaszTable',
      table: {
        tableName: 'lukaszTable',
        timeToLiveAttribute: 'ttl',
        removalPolicy: RemovalPolicy.RETAIN,
      },
    },
...
```

in the cfn json output I have `lukaszTableD7B5F0C3`, when the expected should be lukaszTable, can this be done in full to generate the logical id's myself, as I need to match it with the serverless framework dynamoDb table id.

Cheers.

**Comment by jayair** [comment]
Hmm I think there might be a workaround here. Can you start a new thread in #help on Discord. I think there might be some other migration related questions as well.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
