### ISSUE TITLE
CDK update forgot to update the "constructs" package

### ISSUE THREAD

**Issue by closesimple-wl** [sst/sst#3483]
Structural typing compatibility is broken.

PR that lacked the lockstep update: https://github.com/sst/sst/pull/3426

https://github.com/sst/sst/blame/fc3dd92a6f116b42f60196fd8a3ce8a2d04a9c85/packages/sst/package.json#L78

**Comment by closesimple-wl** [comment]
Here's the dependency graph:

```
devDependencies:
aws-cdk-lib 2.101.1
└── constructs 10.3.0 peer
sst 2.34.3
├─┬ @aws-cdk/aws-apigatewayv2-alpha 2.101.1-alpha.0
│ ├─┬ aws-cdk-lib 2.101.1 peer
│ │ └── constructs 10.3.0 peer
│ └── constructs 10.3.0 peer
├─┬ @aws-cdk/aws-apigatewayv2-authorizers-alpha 2.101.1-alpha.0
│ ├─┬ @aws-cdk/aws-apigatewayv2-alpha 2.101.1-alpha.0 peer
│ │ ├─┬ aws-cdk-lib 2.101.1 peer
│ │ │ └── constructs 10.3.0 peer
│ │ └── constructs 10.3.0 peer
│ ├─┬ aws-cdk-lib 2.101.1 peer
│ │ └── constructs 10.2.69 peer
│ └── constructs 10.2.69 peer
├─┬ @aws-cdk/aws-apigatewayv2-integrations-alpha 2.101.1-alpha.0
│ ├─┬ @aws-cdk/aws-apigatewayv2-alpha 2.101.1-alpha.0 peer
│ │ ├─┬ aws-cdk-lib 2.101.1 peer
│ │ │ └── constructs 10.3.0 peer
│ │ └── constructs 10.3.0 peer
│ ├─┬ aws-cdk-lib 2.101.1 peer
│ │ └── constructs 10.2.69 peer
│ └── constructs 10.2.69 peer
├─┬ aws-cdk-lib 2.101.1
│ └── constructs 10.2.69 peer
└── constructs 10.2.69
```

Error occurs using `Alarm.addAlarmAction(SnsAction)`:
```
Argument of type 'SnsAction' is not assignable to parameter of type 'IAlarmAction'.
  Types of property 'bind' are incompatible.
    Type '(_scope: Construct, _alarm: IAlarm) => AlarmActionConfig' is not assignable to type '(scope: Construct, alarm: IAlarm) => AlarmActionConfig'.
      Types of parameters '_scope' and 'scope' are incompatible.
```

**Comment by jayair** [comment]
Was this was fixed in the latest releases?

**Comment by fwang** [comment]
hmm @thdxr knows this better.. afaik CDK doesn't pin `constructs` to a specific version — https://github.com/aws/aws-cdk/blob/v2.101.1/packages/aws-cdk-lib/package.json#L175

@closesimple-wl Can you try removing the `node_modules` and the lock file and install the deps again?

**Comment by closesimple-wl** [comment]
Thanks guys for looking into this.  Upon further inspection, this appears to only be an issue in VS Code's TypeScript compiler...?

The local and CI build works before and after deleting the old "node_modules".  I wonder what could be wrong with VS Code...  Not even the magical `TypeScript: Restart TS Server` command makes a difference (as it shouldn't).  Anyway, seems to not be an issue with SST.

I guess the good news, to your point, is, at least at the moment, the CDK doesn't have a semantic versioning bug.

**Comment by closesimple-wl** [comment]
I spoke too soon.  Remembered we're not verifying types on build.  This is an issue when running the `tsc` compiler, so I'm going to reopen this issue.

It's possible the bug is upstream.  Or not.

**Comment by closesimple-wl** [comment]
So I think the problem is the CDK isn't paying enough attention to/testing thoroughly for semantic versioning bugs across its wonderful `constructs` dependency.  And/or they don't really understand how structural typing (yay TypeScript...) is vastly different than nominal typing.

It's clear that CDK's https://github.com/aws/aws-cdk/blob/v2.101.1/packages/aws-cdk-lib/package.json#L175 isn't actually semantic, otherwise this error wouldn't be occurring.  AWS needs to figure out how all versions of major version 10 `constructs` should interoperate, at compile-time at least.

Yes the CDK is a huge conglomeration of projects.  But that's not my problem; they need to figure this out.

But the problem remains: The user can pin an arbitrary 10-ish version via `overrides` to workaround this problem to the extent that their combination of used CDK features and arbitrary choice happen to work, as I have.

However, since SST is a conceptual layer on top of the CDK mess, shouldn't SST _not_ pin its `constructs` version, and instead do a `^10.2.69` thing, specifying the minimal version you need, for whatever reason that need is.  It might not functionally affect this, but semantically SST is not an application; SST is a library.  Libraries need to accept more version combinations, and therefore libraries should only rarely ever be "pinning" any dependency.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
