### ISSUE TITLE
Is it possible to set specific cloudfront distribution id in nextjssite?

### ISSUE THREAD

**Issue by trustyoo86** [sst/sst#3492]
Currently, cloudfront and s3 are already set up.
When setting up nextjsSite, can I use the previously created distribution ID of Cloudfront?
I can't confirm how to set the existing distribution ID because it isn't listed in the documentation.

**Comment by jayair** [comment]
Can you post this in #help on Discord?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
