### ISSUE TITLE
RemixSite + Vite: Error: Site, could not find "remix.config.js"

### ISSUE THREAD

**Issue by mauscoelho** [sst/sst#3494]
Remix with Vite does not require the file `remix.config.js` but SST throws the error that the file is missing.

> I just added the file again and SST works as expected

**Comment by jayair** [comment]
Hmm can you start a thread on #help on Discord?

**Comment by mauscoelho** [comment]
It's not a bug given that SST builds with esbuild and requires the `remix.config.js` file.
Idk what is the status of supporting Vite + Remix for SST as well, but keeping the `remix.config.js` file makes it work.

I could not find any topic about supporting Vite for RemixSite it still a unstable feature but it's going to be the default for Remix

**Comment by mattf96s** [comment]
SST + remix  with Vite is working for me (haven't tested a deployed version though).

**Comment by zelkibuilds** [comment]
@mauscoelho Does the content of `remix.config.js` matter or are they only checking for the existence of the file? Since remix's build with vite won't depend on it I'm confused. Is the output of vite's build process deployed or are you essentially using vite for dev while the build output that's deployed is done some other way by SST?

**Comment by mauscoelho** [comment]
> @mauscoelho Does the content of `remix.config.js` matter or are they only checking for the existence of the file? Since remix's build with vite won't depend on it I'm confused. Is the output of vite's build process deployed or are you essentially using vite for dev while the build output that's deployed is done some other way by SST?

SST RemixSite is on charge of your build using esbuild, so it requires the file to be able to build. 
You are only able to use Vite on development mode. 

There were some attempts of creating a new construct for Vite and Remix the  last time I checked the Discord group, but I think it still not available.

**Comment by SpencerDuball** [comment]
Dang crazy timing, was looking at this yesterday and just finished a PR for it, can you reopen the issue for visibility? I have reference this issue here too: https://github.com/sst/sst/pull/3650

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
