### ISSUE TITLE
SST console not loading

### ISSUE THREAD

**Issue by yashwanth2804** [sst/sst#3508]
![image](https://github.com/sst/sst/assets/8038593/db569740-296e-42cd-bc12-eb993e23961d)

**Comment by yashwanth2804** [comment]
SST v2.36.1  ready!

```
➜  App:     api-sst-auth-google
   Stage:   sst-auth-stage
   Console: https://console.sst.dev/local/<app>/sst-auth-stage

⠴  Checking for changessite url undefined
|  ExampleStack PUBLISH_ASSETS_COMPLETE

✔  Deployed:
   ExampleStack
   ApiEndpoint: https://cr8zuxem4m.execute-api.us-east-1.amazonaws.com
```

**Comment by jayair** [comment]
Can you post this on #help on Discord? I might need some more info from you.

**Comment by ascheucher-shopify-partner** [comment]
Have the same here ...

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
