### ISSUE TITLE
SvelteKit env vars - doc update

### ISSUE THREAD

**Issue by ctdh** [sst/sst#3510]
---
Docs suggest you should be able to create PUBLIC envars in a SvelteKit stack
```
new SvelteKitSite(stack, "Site", {
  path: "path/to/site",
  environment: {
    PUBLIC_API_URL: api.url,
  },
});
```
and then use them in the server side:
```const data = await db(import.meta.env.API_URL);```

but would be helpful to add
Then you can access the API's URL in your client code:

```
import { env } from '$env/dynamic/public';
{env.PUBLIC_API_URL}
```

https://discord.com/channels/983865673656705025/1100464735180308621/threads/1174299213769744386

**Comment by jayair** [comment]
Oh interesting. Which page in the docs is this?

**Comment by ctdh** [comment]
https://docs.sst.dev/constructs/SvelteKitSite#environment-variables

**Comment by jayair** [comment]
Thanks! I'll update it.
