### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/var/task/.next/server/edge-chunks/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm'

### ISSUE THREAD

**Issue by Antonytm** [sst/sst#3511]
I have Next.js website.
Locally it works fine (`npm run dev` or `npm run build / npm run start`).
Deployed to Vercel or Netlify it works fine.

I try to deploy it to AWS using `npx sst deploy --stage prod`. Deployment is successful.
But I am not able to open the pages at all.  Even the pages that I assume should be static.
I get this error message.

```
[Error: ENOENT: no such file or directory, open '/var/task/.next/server/edge-chunks/wasm_a7e702bc5ba9227243abda7977c8096f59478d3f.wasm'
]
```

**Comment by simonhoye** [comment]
I am experiencing a similar issue, I believe it started when I upgraded AWS Amplify from a pre release of v6 to the stable v6, do you manage to resolve the issue?

**Comment by olivergrimes** [comment]
Same issue here - was there a resolution to this?

**Comment by socalledvicky** [comment]
Same issue here

**Comment by jayair** [comment]
Can you post this on https://github.com/sst/open-next or #open-next in our Discord instead?

**Comment by olivergrimes** [comment]
It's worth adding that my issues seem to be due to running the build/deploy locally from a windows machine.  Not sure if that's the case for anyone else here.

https://github.com/sst/open-next/issues/241

**Comment by jayair** [comment]
Oh is this with WSL?

**Comment by itzcull** [comment]
I had the same issue, I solved it by removing a dependency from the `middleware.ts` file that used `wasm` for edge environments

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
