### ISSUE TITLE
SvelteKit adapter: Incorrect Content-Type header for __data.json

### ISSUE THREAD

**Issue by thobson** [sst/sst#3514]
`__data.json` returns data from the server to the client and is fetched during a preload event. `__data.json` should have a content type of `application/json` but instead it's being returned as`text/html`. This wasn't an issue in earlier SvelteKit releases however the 1.27.6 release includes this check in `client.js`:

```javascript
// if `__data.json` doesn't exist or the server has an internal error,
// fallback to native navigation so we avoid parsing the HTML error page as a JSON
if (res.headers.get('content-type')?.includes('text/html')) {
    await native_navigation(url);
}
```

(Please see https://github.com/sveltejs/kit/pull/11025)

The result of which is that hovering over a link will not just preload the page, it will actually navigate to it.

To see the issue in action please see https://d3hhyleu7n6eqh.cloudfront.net and hover over the about link. If you check the network requests you'll see that the about/__data.json resource has content type of text/html

Here's a [link](https://discord.com/channels/983865673656705025/1105534387598131270/1175078461052825710) to the issue mentioned on Discord

**Comment by thobson** [comment]
BTW, I originally filed an issue with the SvelteKit project https://github.com/sveltejs/kit/issues/11055

**Comment by jayair** [comment]
Hmm I wonder why it's setting the wrong content type. We'll take a look.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
