### ISSUE TITLE
ApiLambdaAuthorizer fails if not an async function

### ISSUE THREAD

**Issue by volfpe** [sst/sst#3541]
Hello. I encountered a problem with lambda authorizer and discovered that in the production environment, the function handler must be defined as async for the authorizer to work. Interestingly, it operates fine in the development environment (live lambda development).

Reproduction:

- Clone this example: [examples/api-auth-lambda-authorizer-iam-response](https://github.com/sst/sst/tree/master/examples/api-auth-lambda-authorizer-iam-response)
- Remove the async keyword in the [authorizer function](https://github.com/sst/sst/blob/master/examples/api-auth-lambda-authorizer-iam-response/packages/functions/src/authorizer.ts#L1).
- Execute `pnpm run deploy` (it needs to be deployed, as it works with `pnpm run dev`).
- Test the authorizer with `curl -u admin:password https://xxxxxxxxxx.execute-api.region.amazonaws.com/private` (it fails with an internal server error).
- Direct invocation of the authorizer lambda function returns no value (returns `null`), which is why the authorization fails.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
