### ISSUE TITLE
Cannot deploy Python container using Service construct

### ISSUE THREAD

**Issue by jansdhillon** [sst/sst#3546]
I have been trying to troubleshoot this for days. I've already asked in the Discord but I figured I'd ask here as well.

Following the docs for Service, I have the following sst.config.ts:

```
import { SSTConfig } from "sst";
import SiteStack from "./stacks/SiteStack";

export default {
  config(_input) {
    return {
      name: "obscurus",
      region: "ca-central-1",
    };
  },
  stacks(app) {
    app.stack(SiteStack);
  },
} satisfies SSTConfig;
```

And SiteStack.ts:

```
import {
  StackContext,
  NextjsSite,
  Bucket,
  Table,
  Service,
} from "sst/constructs";
import { Duration } from "aws-cdk-lib/core";

export default function SiteStack({ stack }: StackContext) {
  const bucket = new Bucket(stack, "public");
  const table = new Table(stack, "counter", {
    fields: { counter: "string" },
    primaryIndex: { partitionKey: "counter" },
  });

  new Service(stack, "MyService", {
    path: "./service",
    cdk: {
      container: {
        healthCheck: {
          command: ["CMD-SHELL", "curl -f <http://localhost:3000/> || exit 1"],
          interval: Duration.minutes(1),
          retries: 1,
          startPeriod: Duration.minutes(2),
          timeout: Duration.seconds(60),
        },
      },
    },
  });

  const site = new NextjsSite(stack, "site", {
    bind: [bucket, table],
    environment: { TABLE_NAME: table.tableName },
  });

  stack.addOutputs({
    SiteUrl: site.url,
  });
}
```

In /service I have:
 - Dockerfile:
 - app.py
 - requirements.txt:

app.py:

```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def home():
    return "Hello world"

if __name__ == '__main__':
    app.run(port=3000)
 ```
 
 Dockerfile:
 ```
 FROM public.ecr.aws/docker/library/python:3.9-slim

COPY . /app
WORKDIR /app/

RUN pip install -r requirements.txt

EXPOSE 3000

ENTRYPOINT ["python", "app.py"]
```

requirements.txt:
`Flask`

And everytime I deploy it with this Service, it will always get stuck here and eventually time out (from Seed):
```

02:46:46 | CREATE_IN_PROGRESS | AWS::IAM::Policy                                | MyServiceCDNCloudFrontInvalidatorPolicyD14D75DC
02:46:46 | CREATE_IN_PROGRESS | AWS::SSM::Parameter                             | MyServiceParameterurl88AA47F5
02:46:47 | CREATE_IN_PROGRESS | AWS::IAM::Policy                                | MyServiceCDNCloudFrontInvalidatorPolicyD14D75DC
02:46:47 | CREATE_IN_PROGRESS | AWS::SSM::Parameter                             | MyServiceParameterurl88AA47F5
02:46:48 | CREATE_COMPLETE    | AWS::SSM::Parameter                             | MyServiceParameterurl88AA47F5
02:47:02 | CREATE_COMPLETE    | AWS::IAM::Policy                                | MyServiceCDNCloudFrontInvalidatorPolicyD14D75DC
02:47:03 | CREATE_IN_PROGRESS | Custom::CloudFrontInvalidator                   | MyServiceCDNCloudFrontInvalidatorBAFA485E
02:47:05 | CREATE_IN_PROGRESS | Custom::CloudFrontInvalidator                   | MyServiceCDNCloudFrontInvalidatorBAFA485E
02:47:05 | CREATE_COMPLETE    | Custom::CloudFrontInvalidator                   | MyServiceCDNCloudFrontInvalidatorBAFA485E
```

Going to ECS through the AWS console, I can see that the Flask server task does run, and I see the output in the logs. However, it seems to somehow halt the deployment. 

Note that the health check was only added to try and resolve it. The health check appears to fail for some reason, but even without specifying the health check or setting it to undefined, I get the same result.

I have tried deploying the stack without the Service and it works. I have also tried deploying with the [quickstart example from the docs](https://docs.sst.dev/constructs/Service), which uses a nodejs image. And that works.

I am just confused about what's going wrong here. I feel like I've tried many different configurations at this point but it seems like whenever I use a Python image the deployment just gets stuck.

Any help at all is appreciated. I obviously intend to do more with the Service than just a simple Flask server, but I wanted to do this as a test to confirm that it is possible to create Python environment containers in this way. And so far, I have yet to confirm that it actually works at all.

Has anyone been able to deploy and use a Python container using Service?

---

If you've already posted your issue on Discord, make sure to leave a link to it here.

https://discord.com/channels/983865673656705025/1179541314279321711

**Comment by jansdhillon** [comment]
I've created a min repro here: https://github.com/jansdhillon/my-app.git

It's just the starter Next.js and SST app with the same Service I was trying to use before, and it gives the same result.

**Comment by jayair** [comment]
We'll reply on Discord.

**Comment by jansdhillon** [comment]
Specifying the port for the container in the Service construct seems to fix things!

```
  const service = new Service(stack, "processVideo", {
    path: "./service",
    port: 8080,
    bind: [bucket],
  });
  ```
