### ISSUE TITLE
PFR: automatically add `awsApplication` tag to all resources created by SST to enable new "myApplications" AWS feature

### ISSUE THREAD

**Issue by DanielTatarkin** [sst/sst#3549]
AWS announced [**myApplications**](https://aws.amazon.com/blogs/aws/new-myapplications-in-the-aws-management-console-simplifies-managing-your-application-resources/) at re:Invent 2023 which lets you view dashboards specific to your app's resources in a single place.

The requirement is all relevant resources must be tagged with key-value pair: `{awsApplication: <MY_APP_NAME>}`

Would it be possible to add this tag by default to all resources created by SST similar to existing `sst:app` and `sst:stage` tags? Example `{awsApplication: ${sst:app}-${sst:stage}}`

**Comment by jayair** [comment]
Does this help? https://docs.sst.dev/advanced/tagging-resources

If not post this in #help on Discord.

**Comment by DanielTatarkin** [comment]
@jayair thank you, this looks like exactly what I need. I'll test it and update the issue if anything.

**Comment by DanielTatarkin** [comment]
Ok, to register resources in [**AWS myApplications**](https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/aws-myApplications.html) I needed to:

1. [Create an Application](https://us-east-1.console.aws.amazon.com/console/applications) - creates a new Resource Group ARN which you use as a tag value to register your resources like so: `{"awsApplication": <RESOURCE_GROUP_ARN>}`
2. Tag your resources with that key-value tag, they will then show up in your application in myApplications

Example:
```typescript

export default {
  config() {
    // Config
  },
  stacks(app) {
    if (app.stage === "dev") {
      Tags.of(app).add(
        "awsApplication",
        `arn:aws:resource-groups:<AWS_REGION>:<AWS_ACCOUNT_ID>:group/<SST_APP_NAME>-<SST_APP_STAGE>/<AWS_RESOURCE_GROUP_ID>`,
      )
    } else if (app.stage === "prod") {
      Tags.of(app).add(
        "awsApplication",
        `arn:aws:resource-groups:<AWS_REGION>:<AWS_ACCOUNT_ID>:group/<SST_APP_NAME>-<SST_APP_STAGE>/<AWS_RESOURCE_GROUP_ID>`,
      )
    }
    app.stack(Secrets).stack(API)
  },
} satisfies SSTConfig;
```
