### ISSUE TITLE
Cloudformation Termination Protection and Confusion with setDefaultRemovalPolicy

### ISSUE THREAD

**Issue by imaginaryCorn** [sst/sst#3551]
We are looking to add more protection from unintended stack deletions on our SST applications. There is some confusion about how `setDefaultRemovalPolicy` works.

- The docs for [Removal Policy](https://docs.sst.dev/advanced/removal-policy#changing-the-removal-policy) say to conditionally set `destroy` for any stage that isn't `prod`. This is the example our developers have followed. But the Cloudformation docs say that the default action of not setting a deletion policy is to delete everything (with exceptions): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html#aws-attribute-deletionpolicy-options.
- Does setting no `setDefaultRemovalPolicy` do the same in SST and can the result of not setting it be made clearer if so?
- Can there also be the option for SST to turn on Cloudformation Termination Protection as a clearer alternative to protect whole stacks of resources with a flag that requires changing first before it can be deleted? https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateTerminationProtection.html

Many thanks!

**Comment by jayair** [comment]
Hmm let me check with the team.

What's the core issue here? Somebody accidentally runs `sst remove` on a prod stage? And you want that command to fail?

**Comment by imaginaryCorn** [comment]
Many thanks! Its more the interraction with Cloudformation that feels at issue here, a key Lambda was deleted from a stack during a Rollback and subsequent Rollback Failure. We followed this [SST docs example](https://docs.sst.dev/advanced/removal-policy#changing-the-removal-policy) until this incident, but this example does not explicately set any removal policy on production, where Cloudformation's default behaviour for having no removal policy is to follow the destroy policy.

Termination protection appears possible to set with CDK so we should be fine there, but we want to know what happens in SST when `setDefaultRemovalPolicy` is not set at all. If there is undocumented issues with unset being the same as `destroy` we should clear this up, or `setDefaultRemovalPolicy` should be required in some way so that there is no implicate behaviour for not setting this.

**Comment by jayair** [comment]
So this is the policy on remove if nothing is set: https://docs.sst.dev/advanced/removal-policy#retained-resources

Does that make sense?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
