### ISSUE TITLE
How to get node-canvas layer working with live lambda

### ISSUE THREAD

**Issue by Edwin-Luijten** [sst/sst#3573]
Perhaps it's more of how to get layers working with live lambda.
I don't wan't it to look into my local node_modules.

Also, how to add an extra folder in the package.

**Comment by jayair** [comment]
For Live Lambda your functions get run locally, so there are no layers involved. You can point to a binary on your local and use a layer when deployed. https://docs.sst.dev/advanced/lambda-layers

Feel free to post in #help on Discord for more.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
