### ISSUE TITLE
SST prisma example is broken

### ISSUE THREAD

**Issue by renanpupin** [sst/sst#3581]
Prisma example is broken and doesn't work locally and neither on cloud environment.
# Steps to reproduce:

- init your project using prisma example
```npx create-sst@latest --template=examples/prisma```

- run install
```pnpm install```

- run deploy and you will be able to see the following errors
```pnpm run deploy```

<img width="734" alt="Captura de Tela 2023-12-12 às 21 31 52" src="https://github.com/sst/sst/assets/8743530/af877a75-8696-4931-bc95-4823b85a917d">

<img width="885" alt="Captura de Tela 2023-12-12 às 21 33 20" src="https://github.com/sst/sst/assets/8743530/da662117-1cc2-4879-9b6f-6847504875d4">

- it seems that libraries got updated and it doesn't have old functions yet

- also esbuild 'externalModules' doesn't work anymore, I replaced it to just 'external'

<img width="725" alt="Captura de Tela 2023-12-12 às 21 33 47" src="https://github.com/sst/sst/assets/8743530/2c42a855-25a9-4a20-8252-0d9867ed6226">

- after fixing these errors and running deploy again, I got the following errors

<img width="769" alt="Captura de Tela 2023-12-12 às 21 38 28" src="https://github.com/sst/sst/assets/8743530/2203645c-3e51-474d-8f08-8f3552e3264b">

<img width="764" alt="Captura de Tela 2023-12-12 às 21 50 28" src="https://github.com/sst/sst/assets/8743530/1266708f-413e-4304-80de-b36b6b24ed42">

# Example repo

https://github.com/renanpupin/prisma-sst

**Comment by jayair** [comment]
Yeah sadly this is community maintained. I think there have been some newer versions of a Prisma SST template. You can give it a search on our Discord.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
