### ISSUE TITLE
FeatureRequest: Provide a way to use TypeBox as scheme provider for EventBus

### ISSUE THREAD

**Issue by KONFeature** [sst/sst#3594]
It would be awesome to have another type of `EventBuilder` using typebox instead of zod schema. 

TypeBox provide better runtime performance, and is now more used than Zod (https://npmtrends.com/@sinclair/typebox-vs-yup-vs-zod)

On our side, we are already using TypeBox for schema validation on the api side & for validation of the response on the frontend, so all of our api dto types are built using TypeBox. Having another dependency on the backend for od seems redundant for us, and so having the option to build events with typebox would be awesome. 

Something like `createTypeboxEventBuilder(...)` with same logic would be greatly appreciated, and permit to gain a bit of perf for projects already using typebox and needing to use event bus.

**Comment by jayair** [comment]
Hmm interesting let me share internally.

**Comment by KONFeature** [comment]
Here is a very simply gist of a custom implementation we use at Frak: https://gist.github.com/KONFeature/ade9d1dc1b3b323f5f3f8b6b8316ece8

We don't have a lot of time right now so no time to make a PR, but you got the idea. This gist is missing metadata support & using a replica of the `useLoader` function (since not exposed by SST)

**Comment by thdxr** [comment]
I personally have this same issue because I want to use valibot - I would suggest copying the `createEventBuilder` code and the `EventHandler` code and modifying

I need to figure out how nicely to make this pluggable - have seen other libraries do it

**Comment by decs** [comment]
hey, folks! I'm the maintainer of [TypeSchema](https://github.com/decs/typeschema), which lets libraries like sst support any validation library. I made a quick prototype and the integration seems straightforward: https://github.com/decs/sst/commit/ded29788b2e3bb40d8ba55ff506ce77801e9dd2d.

with this, people can call `createEventBuilder` without needing to set a validator, just like before. then they'd just need to install `@typeschema/typebox` as a dependency on their end, and the event builder would automatically accept TypeBox schemas. and sst could still offer zod support by default by coming with `@typeschema/zod` pre-installed.

how does that approach sound?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
