### ISSUE TITLE
XML Sitemap getServerSideProps: 404 in production

### ISSUE THREAD

**Issue by nuhardlopen** [sst/sst#3596]
Almost everything in my NextJS is getStaticProps. 
I only generate the dynamic XML Sitemaps with getServerSideProps. If I check it localhost it is working, in production the URL it is giving a 404. Any ideas to fix this?

SST: 2.38.7
OpenNext v2.3.1
Next.js v14.0.2
https://discord.com/channels/983865673656705025/1027265626085019769/threads/1170375439664025773

**Comment by jayair** [comment]
I think this was meant for https://github.com/sst/open-next?

**Comment by nuhardlopen** [comment]
Thanks, moved it.
