### ISSUE TITLE
SolidStartSite is broken with the new version of SolidStart 0.4.0

### ISSUE THREAD

**Issue by binajmen** [sst/sst#3604]
There is a new version of SolidStart (https://github.com/solidjs/solid-start/releases/tag/v0.4.0) that is not compatible anymore with SST.
```
Error: ENOENT: no such file or directory, scandir 'packages/web/dist/client'

Trace: Error: ENOENT: no such file or directory, scandir 'packages/web/dist/client'
    at Object.readdirSync (node:fs:1451:3)
    at SolidStartSite.plan (file:///Users/binajmen/Projects/fbnb/node_modules/.pnpm/sst@2.39.2/node_modules/sst/constructs/SolidStartSite.js:80:23)
```

**Comment by jayair** [comment]
Would appreciate somebody taking a stab at this with a PR!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
