### ISSUE TITLE
EdgeLambda construct environment variables

### ISSUE THREAD

**Issue by kslbdev** [sst/sst#3610]
When using the EdgeFunction construct, there are some issues regarding the environment variables: they get inlined into the function handler only on stack create. Which means:

1. The function is not re-deployed if the env variables change. I'm not sure if this is what this code comment is referring to _"A downside of this approach is that environment variables cannot be toggled after deployment, each change to one requires a redeployment."_, but it would be nice if the lambda can be updated on stack updates if there is an env variable change. Would including the environment in the calculateHash payload do the trick?

2. If there is a redeployment of the lambda, due to an explicit code change, even the initial env variables are lost and not available to the script.

**Comment by kslbdev** [comment]
A workaround to using 'environment' on EdgeFunction is is to use customHeaders.

**Comment by jayair** [comment]
Which EdgeFunction construct are you talking about?

**Comment by kslbdev** [comment]
[https://github.com/sst/sst/blob/master/packages/sst/src/constructs/EdgeFunction.ts](This one). I realized later this is not part of official public API and it's intended for internal use only? It would be a helpful construct though since deploying to us-east-1 is complicated.

I actually started using it, but I got into some weird interactions with the NextjsSite. One of the edge functions associated with the site went missing; although i can't say for sure it wasn't something else in my stack, I do think the EdgeFunction construct was the culprit. If it would be useful I can try to re-repro and get some logs, but if this is really just for internal use I guess there's no need?

**Comment by jayair** [comment]
Ah yeah currently it's internal use only. We might release something but it's a bit further on the roadmap.

**Comment by mdnorman** [comment]
It would be really great if we could have access to this.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
