### ISSUE TITLE
mTLS support in API construct

### ISSUE THREAD

**Issue by morcs** [sst/sst#3616]
I'd like to add the mTLS config to the `Api` construct. It's possible through the older `ApiGatewayV1Api` construct and is implemented on the underlying CDK v2 API gateway/custom domain constructs, so I think it should be relatively straightforward.

I'm happy to work on this myself and PR if it's not something that's already been ruled out?

**Comment by Samantaaparajita** [comment]
Ok

**Comment by jayair** [comment]
Oh interesting. Can you point me to the CDK doc on the props you use to set this in `ApiGatewayV1Api`? I can figure out how we want to do it for the `Api` construct.

**Comment by morcs** [comment]
Awesome, thanks Jay!

There's an optional `mtls` property on `aws-cdk-lib/aws_apigatewayv2/DomainName`:

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2.DomainName.html

This allows us to provide an S3 bucket reference and key (plus optional S3 version) to the pem encoded public key file used to validate client certificates.

N.b. This is already available in SST, via the legacy `ApiGatewayV1Api` construct https://docs.sst.dev/constructs/ApiGatewayV1Api#mtls, it's just not exposed on the newer `Api` (HTTP API) construct, if that makes sense.

**Comment by jayair** [comment]
Ah I see. Let me check with the team.

**Comment by fwang** [comment]
> I'm happy to work on this myself and PR if it's not something that's already been ruled out?
@morcs that would be great!

**Comment by danielsharvey** [comment]
Any progress on this?

**Comment by jayair** [comment]
@danielsharvey did you mean for v2 or v3?

**Comment by danielsharvey** [comment]
@jayair Yes, sorry - I can see the confusion.

I was looking at SST Ion - and hoping for MTLS in [ApiGatewayV2 | SST](https://sst.dev/docs/component/aws/apigatewayv2).

**Comment by jayair** [comment]
Yeah no worries. We haven't reorganized our repos yet. Can you open an issue here? https://github.com/sst/ion/issues

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
