### ISSUE TITLE
createEventBuilder input parameter `bus` has type `never`

### ISSUE THREAD

**Issue by gramliu** [sst/sst#3621]
I'm following the [guide](https://docs.sst.dev/events#the-event-bus) for setting up an EventBus, but I'm encountering some typing issues with the `createEventBuilder` function.
```ts
import { createEventBuilder, ZodValidator } from "sst/node/event-bus";

export const event = createEventBuilder({
  bus: "bus",
  validator: ZodValidator
});
```

 In the guide, you specify the required parameter, `bus`. However, I'm getting an error saying its type is `never`.

<img width="1100" alt="image" src="https://github.com/sst/sst/assets/24856195/071acf03-b4e3-4500-8e0f-38bb2b3d8b17">

I looked at the [source](https://github.com/sst/sst/blob/master/packages/sst/src/node/event-bus/index.ts#L3-L6) and it seems like its type is indeed being assigned to the [keys of an empty interface](https://github.com/sst/sst/blob/master/packages/sst/src/node/event-bus/index.ts#L29). Is this intentional behavior? I'm also getting the same error with a fresh template created from `pnpm create sst test-app`

**Comment by jayair** [comment]
Might've replied to this on Discord. But would appreciate a PR!

**Comment by AdditionAddict** [comment]
Temp workaround:
```ts
export const event = createEventBuilder({
  bus: 'bus' as never,
  validator: ZodValidator,
});
```

Also getting error from default setup `pnpm create sst`
```ts
export const Events = {
  Created: event(
    'todo.created',
    // ⛔️⛔️⛔️ should be the object zod schema
    {   
      id: z.string(),
    }
  ),
};
```

@jayair To double check, I presume 'bus' must match the 2nd arg of `new EventBus(...)`?

Given the runtime nature of EventBus, are we happy to type as `Bus extends string` instead of `Bus extends keyof typeof EventBus`? Happy to create PR (likely on weekend)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
