### ISSUE TITLE
API retainDeployments param does not work

### ISSUE THREAD

**Issue by tchcxp** [sst/sst#3648]
Hi there,

I just found that the `retainDeployments` in the API CDK construct doesn't work.

The stack for a demo is below:

```
import { ApiGatewayV1Api } from 'sst/constructs'

 const api = new ApiGatewayV1Api(stack, 'Api', {
    cdk: {
      restApi: {
        restApiName: 'demo-api',
        description: 'Demo API',
        retainDeployments: true,
      },
    },
  })

api.addRoutes(stack, {
    ... 
})
```

Then jump to the AWS console, I can see only one deployment is there, no matter how many new deployments/changes have been made.

<img width="721" alt="image" src="https://github.com/sst/sst/assets/5209926/b7e7538e-6feb-47f3-8868-bc377656e104">

Can someone please look into it?  Keeping the old deployment resources is extremely important for the production environment.

Thanks,

**Comment by jayair** [comment]
Where did you find the `retainDeployments` prop btw? Can I see a link to it?

**Comment by tchcxp** [comment]
> Where did you find the `retainDeployments` prop btw? Can I see a link to it?

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.RestApiProps.html#retaindeployments

**Comment by jayair** [comment]
Ah I see. Let me ask the team to take a look.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
