### ISSUE TITLE
(docs) typos in frontend construct examples

### ISSUE THREAD

**Issue by andrewantolino** [sst/sst#3652]
Hello,

I've noticed some typos in the import statements of some frontend construct examples. They are as follows:

- Named import statement error on [NextjsSite quickstart](https://docs.sst.dev/constructs/NextjsSite#quick-start) step 2
- Named import statement error on [RemixSite quickstart](https://docs.sst.dev/constructs/NextjsSite#quick-start) step 4
- Named import statement error on [SolidStartSite quickstart](https://docs.sst.dev/constructs/NextjsSite#quick-start) step 5

An example:
```ts
import { NextjsSite, StackContext } as sst from "sst/constructs";
```
where `as sst` is incorrect.

All good for me to go ahead and create a PR for this?

Thanks

**Comment by jayair** [comment]
Oh that's weird. Yeah would appreciate a PR. Here's where they come from. https://github.com/sst/sst/blob/master/www/docs/constructs/NextjsSite.about.md

**Comment by andrewantolino** [comment]
I've created a PR here: #3657 

Please note I wasn't able to get the docs running locally, I'll create an issue or two for that as well.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
