### ISSUE TITLE
set deploy will fail on sst create example app

### ISSUE THREAD

**Issue by franz101** [sst/sst#3653]
using version:
```
  "sst": "2.40.1",
    "aws-cdk-lib": "2.124.0",
```
I get the following error:
```
stack: Role
arn:aws:iam::112323:role/cdk-hnb659fds-cfn-exec-role-112323-us-east-1
is invalid or cannot be assumed
```
The account has admin access and I also added the IAM policies from the docs to make sure

https://discord.com/channels/983865673656705025/1203025313693696060

**Comment by franz101** [comment]
Or maybe related to:
https://github.com/serverless/serverless/discussions/10412

**Comment by jayair** [comment]
Replied on Discord!

**Comment by franz101** [comment]
Ok the execution role was deleted, so I had to recreate it and remove the stack and run sst bootstrap
