### ISSUE TITLE
Headers function works differently in dev and production environments

### ISSUE THREAD

**Issue by Jack-Dane** [sst/sst#3661]
I ran into this problem when deploying my app to production, the `headers()` function wasn't picking up a header that was added by middleware, but could get the value when running the application locally. 

I was adding the header to the response headers: 
```
export async function middleware(request: NextRequest) {
  let headers = new Headers(request.headers);
  headers.set("test-header", "abc");

  return NextResponse.next({
    headers: headers
  });
}
```
And is being read with: 
```
headers().get("test-header") || "could not find header 'test-header'"
```

The documentation mentions the function picks up request headers: 
> The headers function allows you to read the HTTP incoming request headers from a [Server Component](https://nextjs.org/docs/app/building-your-application/rendering/server-components).

https://nextjs.org/docs/app/api-reference/functions/headers

So I updated my middleware to add the header to request headers, which worked. But I would expect both environments to behave in the same way. It is not the case the middleware isn't working, based on the devtools network panel the response header is there, it just isn't being picked up the same way when developing. 

[Here is a reproducible example. ](https://github.com/Jack-Dane/headers-test-nextjs-sst)

Running in production. Deployed with `npx sst deploy --stage prod`. 
![Screenshot from 2024-02-07 20-38-12](https://github.com/sst/sst/assets/17383921/cea30698-c7ac-4f3f-9141-60f9376a9bf0)

Running on my machine as `npx sst dev` followed by `npm run dev`. 
![Screenshot from 2024-02-07 20-30-12](https://github.com/sst/sst/assets/17383921/e227d31a-9c44-4aa0-8930-acfeb5404484)

Package versions: 
```
jack@jackd:~/Documents/nextjs/headers-test$ npm list
headers-test@0.1.0 /home/jack/Documents/nextjs/headers-test
├── @types/node@20.11.16
├── @types/react-dom@18.2.18
├── @types/react@18.2.55
├── autoprefixer@10.4.17
├── aws-cdk-lib@2.124.0
├── constructs@10.3.0
├── eslint-config-next@14.1.0
├── eslint@8.56.0
├── next@14.1.0
├── postcss@8.4.34
├── react-dom@18.2.0
├── react@18.2.0
├── sst@2.40.1
├── tailwindcss@3.4.1
└── typescript@5.3.3
```

**Comment by jayair** [comment]
Do you mind posting this over on https://github.com/sst/open-next?

Thanks!

**Comment by Jack-Dane** [comment]
Opened bug ticket https://github.com/sst/open-next/issues/360
