### ISSUE TITLE
Allow use of LLRT runtime

### ISSUE THREAD

**Issue by nerdoza** [sst/sst#3669]
AWS released an _experimental_ runtime called **LLRT** (Low Latency Runtime) which promises to be faster at cold boots than even some of the compiled runtimes containers like Go. The full details are here: https://github.com/awslabs/llrt

As an experiment, sst should support using the LLRT runtimes. The best place to start would likely be with the `Function` construct, and then if it's stable and workable apply the changes to `SsrFunction` construct as well.

The runtime should be an opt-in only runtime for the foreseeable future, and I expect there will be annoying bugs and limited support until the runtime hits `v1`, so this should be considered an extremely dumb thing to do in a production environment.

**Comment by jayair** [comment]
Thanks for taking a crack at it!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
