### ISSUE TITLE
Feature Request: Pass TokenError's to onError() of LinkAdapter

### ISSUE THREAD

**Issue by jsadoski-rockhall** [sst/sst#3690]
`fast-jwt` has a Token Error object with discreet error codes: [fast-jwt/src
/error.js](https://github.com/nearform/fast-jwt/blob/master/src/error.js)

It would be great if Token Errors were passed to `onError()`, along with the `TOKEN_ERROR_CODES`, so we can respond differently when the token is expired:

```javascript
const adapter = LinkAdapter({
  onLink: ...;
  onSuccess: ...;
  onError: async (error) => {
    if (error.code === LinkAdapter.TOKEN_ERROR_CODES.expired) {
      return {
        // Invalid Token
        statusCode: 498,
      }
    }

    return {
      statusCode: 400,
    }
  }
})
```

This would allow devs to handle different scenarios in the client. It should be easy to implement and shouldn't break current developer code, since the argument could be ignored.

I would be happy to open a pull request, when I have time in a few weeks from now 🙂.

**Comment by jayair** [comment]
Would appreciate a PR!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
