### ISSUE TITLE
Resource Binding for multiple Lambda Functions

### ISSUE THREAD

**Issue by MartinLoeper** [sst/sst#3695]
I just noticed that lambda types are generated only once in the .sst folder for all lambda functions in our project.

I would expect to see separate types for each lambda because we bind different resources to the respective functions. 

Is this intended our is something misconfigured in our project?

**Comment by jayair** [comment]
Hmm is there an issue you are running into?

**Comment by MartinLoeper** [comment]
No, its just a conceptional question as while I'm coding one particular lambda function, the typescript type definitions suggest an environment variable is available whereas it is not available because it was bound to another function. This gives a false sense of security when one of our devs forgets to check the actual bindings in the infrastructure part. So its more like a maintenance issue than a functional one.

Thus I am asking whether I set it up wrong or this case was not taken into consideration yet. 
If it is intended, I think a quick note in the Resource Binding docs would be nice to raise awareness.
Anyway, thanks for your quick response Jay! Love your work here!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
