### ISSUE TITLE
Function code deployment and local are different.

### ISSUE THREAD

**Issue by VanThanh12195** [sst/sst#3702]
I have a question about deployment. The code I write in local is different in deployment. Although they have the same functionlity. Images are attached for clarify:

In local (VS code):
![image](https://github.com/sst/sst/assets/14349308/add3e1ca-de98-4a5a-b267-4114a09cdc5a)

In AWS Lambda after run "npx sst deploy"
![image](https://github.com/sst/sst/assets/14349308/c0e2ea78-617b-4c21-a808-10a72fcf85eb)

How can I keep the code for both local and deployment stay the same?

**Comment by jayair** [comment]
This is adding top level await to support https://docs.sst.dev/resource-binding

Was there an issue you ran into?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
