### ISSUE TITLE
Deployment error (next.js) for a new AWS account (free)

### ISSUE THREAD

**Issue by 12evgen** [sst/sst#3704]
Following the instructions (https://docs.sst.dev/start/nextjs), I'm trying to set up the SST for the next.js application
I created a new AWS account (free), set up an AIM account according to the instructions (https://docs.sst.dev/advanced/iam-credentials#loading-from-a-file).

After the npx create-sst@latest command, I see the changes in my repository. And after that I run npx sst dev. My application is starting.
![image](https://github.com/sst/sst/assets/25562185/3da773a6-0f70-4a7f-bf3c-fa5327f843ed)

Now I am trying to deploy my application and I get an error: "Access denied for operation 'AWS::CloudFront::Distribution: Your account must be verified before you can add new CloudFront resources. To verify your account, please contact AWS Support"
![image](https://github.com/sst/sst/assets/25562185/0825defa-55bd-46ac-9067-e315c1fad7b0)

How can this problem be solved?

**Comment by 12evgen** [comment]
Yes, I contacted support but I haven't received a response yet.
However, such a bug was noticed in this issue - https://github.com/sst/sst/issues/3429

**Comment by yarabramasta** [comment]
Welp, can confirm this also. I am trying to delete my dev stage resources and deploy the prod one. I think it has something to do with resources, sst creating many resources for NextjsSite stack.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
