### ISSUE TITLE
Status 500 Error for Images in public Folder Following Update to v2.4.6

### ISSUE THREAD

**Issue by vitharanagedonjani-i2e** [sst/sst#3706]
After updating to version 2.4.6, I've encountered a status 500 error when trying to access images stored in the Next.js `public` folder. These images were accessible and displayed correctly in the previous version.

## Steps to Reproduce
1. Update to version 2.4.6 from version (specify your previous version)
2. Access any static image stored in the `public` folder via a URL or within the application
3. Observe that the server returns a status 500 error instead of displaying the image

## Expected Behavior
Images stored in the Next.js `public` folder should load and display correctly without any server errors.

Thank you for looking into this issue. Your assistance is greatly appreciated.

**Comment by jayair** [comment]
Does this fix it for you? https://discord.com/channels/983865673656705025/1214865068550918215/1214865068550918215

**Comment by vitharanagedonjani-i2e** [comment]
@jayair Thanks! it worked!
