### ISSUE TITLE
Please expose Distribution in sst/constructs

### ISSUE THREAD

**Issue by iliazlobin** [sst/sst#3723]
When trying to import and use Distribution constructs:
```
import { Bucket, Distribution, StackContext, Table } from 'sst/constructs'
```

It's complaining that Distribution isn't available, despite having this construct exported in source code...

Problem is index.d.ts, index.js do not include Distribution module and as such, a consumer code can't use it

Workaround, use pnpm patch or patch-package to slightly modify the sts package. Eg:
```
diff --git a/constructs/index.d.ts b/constructs/index.d.ts
index fc4a47f61b678e41885284164be183fc6271bb90..190a543219b23c6bd3e14255ed685d5ebe58a6a5 100644
--- a/constructs/index.d.ts
+++ b/constructs/index.d.ts
@@ -11,6 +11,7 @@ export * from "./Stack.js";
 export * from "./Table.js";
 export * from "./Topic.js";
 export * from "./Bucket.js";
+export * from "./Distribution.js";
 export * from "./Script.js";
 export * from "./Service.js";
 export * from "./EventBus.js";
diff --git a/constructs/index.js b/constructs/index.js
index c25058cf32bad913e241f502f7fd4782ad1018d5..2b2fe2763d3537cfcdeba882c6ed3cf21e108939 100644
--- a/constructs/index.js
+++ b/constructs/index.js
@@ -11,6 +11,7 @@ export * from "./Stack.js";
 export * from "./Table.js";
 export * from "./Topic.js";
 export * from "./Bucket.js";
+export * from "./Distribution.js";
 export * from "./Script.js";
 export * from "./Service.js";
 export * from "./EventBus.js";
```

Author, please export/expose this object for usage out of 'sst/constructs', find it necessary.

Thank you so much!

**Comment by jayair** [comment]
Hmm it's an internal construct. Is there a reason you want to use it?

**Comment by zammitjames** [comment]
Yes +1 I would use this.

**Comment by srodriki** [comment]
This can potentially help suffice other problems, such as being able to host multiple static sites under the same distribution (which can be done right now but it's super painful).

+1 would use this

**Comment by 3stacks** [comment]
I have a similar use case. I have a S3 Bucket for images with a Lambda function to do processing on those images, but I'd like to have a Cloudfront distribution in front of it to cache requests. 

It's working well using SST except for the caching, so unless someone could propose an alternative caching setup that will play nicely with the Lambda, I'll need to use a different tool.

**Comment by BrunnerLivio** [comment]
Same here. We're processing a high volume of data and putting the processed JSON files into an S3 bucket that should be served via Cloudfront. 

It would be nice to use the internal Distribution construct!

**Comment by ravibanks54** [comment]
I also needed this as I wanted SST to handle the cert provisioning on my behalf. I copied the source code into my stacks code and it worked perfectly. I don't think they'll get to this since they're likely focusing on SST Ion development.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
