### ISSUE TITLE
[Function]: Update python runtime

### ISSUE THREAD

**Issue by pholik** [sst/sst#3730]
Executing lambdacontext method **get_remaining_time_in_millis()** is raising an error:

`TypeError: unsupported operand type(s) for -: 'str' and 'int'`

for python runtime. Wrong casting is performed at sst/support/python-runtime/runtime.py.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
