### ISSUE TITLE
require() of ES Module right after init

### ISSUE THREAD

**Issue by garrettlove8** [sst/sst#3738]
```
|  Error        Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/username/Development/website/.sst/platform/node_modules/string-width/index.js from /Users/username/Development/website/.sst/platform/node_modules/wide-align/align.js not supported.
|  Instead change the require of index.js in /Users/username/Development/website/.sst/platform/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
```

I encountered this error trying to run `npm run dev --verbose` immediately after running `sst init`. I realize this is a common error to encounter, but my expectation would be that `sst init` will configure what needs to be configured such that this doesn't happen, or that the docs call it out and direct me to how to fix it.

**Comment by ryanleecode** [comment]
Add `NO_BUN=true` to your env

![image](https://github.com/sst/sst/assets/21375952/75744812-0c8e-48c0-91d1-0de84a7f86c6)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
