### ISSUE TITLE
Display build process messages to console

### ISSUE THREAD

**Issue by ZakkProjects** [sst/sst#3739]
Hi,

Lately i've been working with rust a lot and one thing is driving me crazy a little during production deploy.

I dont know it it properly works for other (outside compiled) runtimes like c# and Java, but SST hides all output from async executions of cargo-lmabda.

It could be easilly solved by using callback from execAsync and piping it to console. Just how it works with workers just few lines above [workers.stdout(input.workerID, data.toString()); ](https://github.com/sst/sst/blob/d67d9c99b1882dddb1219a482d4956d66a47c4db/packages/sst/src/runtime/handlers/rust.ts#L45)
Or i guess even directly calling console.log() since thats how internally works eslint implementation in node runtime (i guess).

I could try to implement it later this month if this makes sense.

**Comment by ZakkProjects** [comment]
Anyways just from curiosity, is there a reason execAsync is used ? Using spawn just like in worker process would eliminate problem caused by combination of promisify and callbacks.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
