### ISSUE TITLE
sst deploy set CloudFormation Parameter 

### ISSUE THREAD

**Issue by ziggy6792** [sst/sst#3752]
When using cdk cli to deploy a stack I can set a CloudFormation Parameter like [this](https://stackoverflow.com/questions/58138536/how-to-specify-parameter-definition-in-cdk-stack)
`cdk deploy MyStack --parameters uploadBucketName=UpBucket --parameters downloadBucketName=DownBucket`

Is it possible to do this with the sst cli?

I tried this but it did not work 
`sst deploy MyStack --parameters uploadBucketName=UpBucket --parameters downloadBucketName=DownBucket`

Thanks a lot

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
