### ISSUE TITLE
Add a [filter] option to sst dev

### ISSUE THREAD

**Issue by leo-petrucci** [sst/sst#3753]
Hello,

We currently use Serverless Framework in a Monorepo to develop and deploy our APIs. Serverless Framework isn't great, but it allows us to start as many or as few APIs as we want depending on the situation.

This has worked quite well because some of our Apps only use some of the APIs that we have. For example:
```
Store Frontend depends on:
> Auth API
> Products API

Dashboard Frontend depends on:
> Auth API
> Sales API
```

I've been trialing out SST as a replacement and I've loved everything about it so far, however I am confused by the `sst dev` command.

When running `sst dev` every single API in the Monorepo is automatically deployed and started. This works great when you only have a couple, but in my case I might end up having a dozen or more which would really slow down the process. I've read the docs and asked on Discord, but there doesn't seem to be a way to change this behavior.

I've been told to use `enableLiveDev`, however this option only stops re-builds. It will still initially deploy the app for development.

What's even more confusing is that [`sst deploy` has a `[filter]` option](https://docs.sst.dev/packages/sst#sst-deploy) which allows to deploy just one of the APIs.

Are there any plans the filter option could be ported to `sst dev`? It seems like it would be extremely useful in bigger projects! 

Let me know if I've missed something in the docs. If this seems like a good feature I'm willing to open a PR.

**Comment by jayair** [comment]
Let me clarify, is your issue that the initial deploy is taking long and that's why `enableLiveDev` doesn't work for you?

**Comment by jayair** [comment]
Hmm 20 is a pretty small number tbh. But if there haven't been any changes it shouldn't redeploy them right? In this case are there changes to redeploy?

**Comment by hugo082** [comment]
It would be useful for us to be able to select the part of the stack we are working on and limit the AWS costs related to the development environment.
We would love to have this feature.

**Comment by mzhubail** [comment]
@jayair If there's interest I can submit a PR to add this option to `dev` command.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Comment by hugo082** [comment]
@thdxr IMO It would still make sense to add a `[filter]` option to sst dev in the v3.

Having the ability to selectively deploy and develop only the parts of the stack you're working on can help reduce AWS costs in the development environment, especially for larger projects with many APIs.

This feature would be very useful and I encourage the team to consider implementing it.

**Comment by jayair** [comment]
@hugo082 just curious, how does it help reduce costs?

**Comment by hugo082** [comment]
@jayair by filtering it limits the deployed resources and the related cost. + it reduce the overhead. We are using it in a big a monorepo, deploying every part of the stack is not an option for us

**Comment by leo-petrucci** [comment]
> [@hugo082](https://github.com/hugo082) just curious, how does it help reduce costs?

Not only costs, but having all frontends start by default is a killer unless you have 32GB of ram. Our stack has like 6 different Next.js apps and they're never developed together.

I mean yeah I could have some complex setup where each command sets a specific environment variable and then each OpenNext stack checks for them and decides whether to start or not... Or I could decide which one to start in the first place.

I don't know, it just seems like a much more sensible way of doing things?

**Comment by jayair** [comment]
@leo-petrucci does setting autostart to false work for you? https://sst.dev/docs/component/aws/nextjs#dev-autostart
