### ISSUE TITLE
SST dev to use custom toolkitStack(CDKtoolkit stack) and Not update it

### ISSUE THREAD

**Issue by karankapur999** [sst/sst#3757]
I have to customize the customToolKit so i created a customized version using 

cdk bootstrap aws://<MY_AWS_ACCOUNT>/us-east-2 --template template.yaml

the issue i am facing is whenever i try to run sst dev 

it tries to update the customToolKit i created above. I do not need the updates to ben done

**Comment by jayair** [comment]
There are some config options for these that we expose: https://docs.sst.dev/configuring-sst#config-options

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
