### ISSUE TITLE
You installed esbuild for another platform than the one you're currently using

### ISSUE THREAD

**Issue by ccfai8** [sst/sst#3760]
You installed esbuild for another platform than the one you're currently using. This won't work because esbuild is written with native code and needs to install a platform-specific binary executable. Specifically the "@esbuild/darwin-arm64" package is present but this platform needs the "@esbuild/linux-arm64" package instead. People often get into this situation by installing esbuild on Windows or macOS and copying "node_modules" into a Docker image that runs Linux, or by copying "node_modules" between Windows and WSL environments. If you are installing with npm, you can try not copying the "node_modules" directory when you copy the files over, and running "npm ci" or "npm install" on the destination platform after the copy. Or you could consider using yarn instead of npm which has built-in support for installing a package on multiple platforms simultaneously. If you are installing with yarn, you can try listing both this platform and the other platform in your ".yarnrc.yml" file using the "supportedArchitectures" feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures Keep in mind that this means multiple copies of esbuild will be present. Another alternative is to use the "esbuild-wasm" package instead, which works the same way on all platforms. But it comes with a heavy performance cost and can sometimes be 10x slower than the "esbuild" package, so you may also not want to do that.

Received an error after successfully deployed. The error occurs when I visit my outstatic posts. Hopefully someone can help me please.. thanks!

**Comment by berenddeboer** [comment]
No one copies node_modules, that's such bad practice I can't even imaging someone doing this.

**Comment by ccfai8** [comment]
> No one copies node_modules, that's such bad practice I can't even imaging someone doing this.

No I didn't do anything to copy it. I use the default sst config for deployment. I did not do anything else.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
