### ISSUE TITLE
im not able to upgrade to nodejs 18 for AWS stack

### ISSUE THREAD

**Issue by baraadeek** [sst/sst#3763]
im tried to upgrade the nodejs version from 16 to 18 but there was no choice to use node 18 even when I used the latest version of the package I still couldn't find nodejs 18 

app.setDefaultFunctionProps({
        runtime: 'nodejs16.x'
    })
    
 only I found these runtimes 
 export declare type Runtime = "nodejs" | "nodejs4.3" | "nodejs6.10" | "nodejs8.10" | "nodejs10.x" | "nodejs12.x" | "nodejs14.x" | "nodejs16.x" | "python2.7" | "python3.6" | "python3.7" | "python3.8" | "python3.9" | "dotnetcore1.0" | "dotnetcore2.0" | "dotnetcore2.1" | "dotnetcore3.1" | "go1.x";

so how I can upgrade the node version any options?

**Comment by Jaafar-abusair** [comment]
I have the same issue

**Comment by jaferi512** [comment]
I'm also trying to upgrade and having same issue.

**Comment by baraadeek** [comment]
@nick

**Comment by jayair** [comment]
That's strange because it's right there: https://github.com/sst/sst/blob/master/packages/sst/src/constructs/Function.ts#L72

**Comment by baraadeek** [comment]
@jayair  what is the package version you get this link from, I tried multiple times with no luck only can see nodejs16_x and I tried to create new project getting the same issue

**Comment by jayair** [comment]
@baraadeek Hmm that one was from master, but if I take the tag for the latest release: https://github.com/sst/sst/blob/v2.41.5/packages/sst/src/constructs/Function.ts#L72

**Comment by baraadeek** [comment]
@jayair ok what do you think i miss when I do this

`mkdir my-sst-app
cd my-sst-app
npx create-serverless-stack@latest my-sst-app
cd my-sst-app
`
but also I have node 14 only for newly created project

**Comment by baraadeek** [comment]
@jayair  is this package belongs to sst 

@serverless-stack/resources

https://www.npmjs.com/package/@serverless-stack/resources

**Comment by jayair** [comment]
These are from SST v1 which is a couple of years old. We don't update them anymore.

```
npx create-sst@latest my-sst-app
npx sst dev
```

Is what you are looking for.

**Comment by baraadeek** [comment]
@jayair  thanks a lot for your response

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
