### ISSUE TITLE
astro-sst depends on deprecated astrojs/webapi

### ISSUE THREAD

**Issue by lschierer** [sst/sst#3766]
when I run a number of pnpm commands, I get a warning
```
 WARN  5 deprecated subdependencies found: @astrojs/webapi@3.0.0, @aws-sdk/config-resolver@3.374.0, @aws-sdk/middleware-retry@3.374.0, @aws-sdk/smithy-client@3.374.0, querystring@0.2.0
```

The one I'm concerned about in this ticket is ```@astrojs/webapi@3.0.0``` though all of these are included in the project because of sst (as best I can tell).  

If you go to <https://www.npmjs.com/package/@astrojs/webapi> you will see the prominent notice "This package is not used by Astro any more and is no longer maintained. In Astro 3.0 polyfills are part of a core module."  

Please update this adapter 1) so that it does not break when Astro does release 3.0 (no clue when that will be) 2) so that I can stop using unmaintained packages 3) to clean up my terminal and remove a warning I can't control (directly). 

Thanks!!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
