### ISSUE TITLE
Invalid srcPath error message format

### ISSUE THREAD

**Issue by jayair** [sst/sst#377]
When the `srcPath` is set to the project root, the error message is greyed out for some reason.

<img width="569" alt="Screen Shot 2021-05-20 at 9 22 42 PM" src="https://user-images.githubusercontent.com/53023/119068198-af84d480-b9b1-11eb-9460-81577aaa3a2d.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
