### ISSUE TITLE
Migration path to SST v3 for stacks using CDK constructs

### ISSUE THREAD

**Issue by adolfogc** [sst/sst#3771]
Hi,

We currently use SST v2 in combination with some CDK constructs to deploy various lambda functions developed in C++.

For example:

```typescript
// ...

const myApiKeySecret = new Config.Secret(stack, "MY_API_KEY");

const myApiKeyParameterName = `/sst/${app.name}/${app.stage}/Secret/${myApiKeySecret.name}/value`;

const myApiKeyParameter =
  StringParameter.fromSecureStringParameterAttributes(
    stack,
    "MY_API_KEY_PARAMETER",
    { parameterName: myApiKeyParameterName, version: 1 }
  );

const myLambdaFunction = new Function(stack, "FoobarLambda", {
  runtime: Runtime.PROVIDED_AL2023,
  architecture: Architecture.ARM_64,
  memorySize: 512,
  timeout: Duration.seconds(10),
  handler: "foobar", // not actually used
  code: Code.fromBucket(myLambdaCodeZip.bucket, myLambdaCodeZip.s3ObjectKey),
  layers: [myLambdaLayer],
  environment: {
    LD_PRELOAD: "libmimalloc.so",
    API_KEY_PARAMETER_NAME: myApiKeyParameterName,
  },
});

myApiKeyParameter.grantRead(myLambdaFunction);
```

We understand that Ion/SST v3 (https://ion.sst.dev/docs/) will drop CDK support, so we were wondering if this setup will be possible with the newer SST.

**Comment by jayair** [comment]
It supports https://ion.sst.dev/docs/component/aws/function/#runtime `provided.al2023`.

Is that what you are looking for?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
