### ISSUE TITLE
Next.js 15 does not work.

### ISSUE THREAD

**Issue by noahgsolomon** [sst/sst#3774]
Next.js 15 introduced in next.js the ability to use the react compiler with babel. When deploying with sst deploy, it builds successfully, and when running next dev it works locally, however, when running ```sst dev next dev``` as the dev script, it runs next in version 14.2.3. 

So this makes it not feasible to use Next.js 15 with react compiler with SST :(

**Comment by jayair** [comment]
`sst dev next dev` runs the version of Next.js you have in your package.json.

**Comment by noahgsolomon** [comment]
must be a fault of my own then. Maybe I didn't update my lockfile.
