### ISSUE TITLE
No vitest in current create-sst as referenced in docs

### ISSUE THREAD

**Issue by timkinnane** [sst/sst#3781]
The below seems incorrect for the current state of `create-sst`. There's no vitest config created and no test script in `package.json`.

https://github.com/sst/sst/blob/5caf568587c62c0928e55e5577becc09e701edf6/www/docs/testing.md?plain=1#L39-L51

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
