### ISSUE TITLE
Deployed Prod API returning null instead of expected output

### ISSUE THREAD

**Issue by MarkMatute** [sst/sst#3783]
[Example code](https://github.com/MarkMatute/sstv2-prod-error-sample)

---
[If you've already posted your issue on Discord, make sure to leave a link to it here.
](https://discord.com/channels/983865673656705025/1248374264009199627)

**Comment by MarkusWendorf** [comment]
Hi @MarkMatute your example link returns a 404.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
