### ISSUE TITLE
[Next.js] Separate cache policies

### ISSUE THREAD

**Issue by marwendecade** [sst/sst#3786]
Hello, 

Is there a way to have two cache policies:
- One for images (_next/image) that DOES NOT include cookies
- Another one for server functions that DOES include cookies

Looking at the documentation, it seems that there is only one cache policy that is shared between all lambdas

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
