### ISSUE TITLE
`sst start` keeps asking to redeploy infrastructure

### ISSUE THREAD

**Issue by jayair** [sst/sst#380]
I might've done something weird to get into this state but I'm now stuck in a loop.

``` bash
Deploying stacks
Failed to parse generated manifest.json [Error: ENOENT: no such file or directory, open '.build/cdk.out/manifest.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.build/cdk.out/manifest.json'
}

Redeploying infrastructure failed
Press ENTER to redeploy infrastructure again
```

If I hit ENTER, I get the same error and it prints this same message.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
