### ISSUE TITLE
Dependabot reports high security vulnerability due to ws package

### ISSUE THREAD

**Issue by richardcho-sr** [sst/sst#3800]
Advisory: https://github.com/advisories/GHSA-3h5v-q93c-6h6q

Latest version of sst still has this vulnerable package.

Currently unable to resolve the vulnerability due to transitive dependencies relying on a vulnearbale version of the `ws` package:

```bash
yarn why v1.22.22
[1/4] Why do we have the module "ws"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "ws@8.14.2"
info Has been hoisted to "ws"
info Reasons this module exists
   - Hoisted from "sst#ws"
   - Hoisted from "jsdom#ws"
   - Hoisted from "sst#ink#ws"
   - Hoisted from "sst#@aws-sdk#signature-v4-crt#aws-crt#@httptoolkit#websocket-stream#ws"
info Disk size without dependencies: "180KB"
info Disk size with unique dependencies: "180KB"
info Disk size with transitive dependencies: "180KB"
info Number of shared dependencies: 0
=> Found "websocket-stream#ws@3.3.3"
info This module exists because "sst#aws-iot-device-sdk#websocket-stream" depends on it.
info Disk size without dependencies: "196KB"
info Disk size with unique dependencies: "284KB"
info Disk size with transitive dependencies: "284KB"
info Number of shared dependencies: 3
=> Found "mqtt#ws@7.5.9"
info This module exists because "sst#aws-iot-device-sdk#mqtt" depends on it.
info Disk size without dependencies: "168KB"
info Disk size with unique dependencies: "168KB"
info Disk size with transitive dependencies: "168KB"
info Number of shared dependencies: 0
=> Found "aws-crt#ws@7.5.9"
info Reasons this module exists
   - "sst#@aws-sdk#signature-v4-crt#aws-crt#mqtt" depends on it
   - Hoisted from "sst#@aws-sdk#signature-v4-crt#aws-crt#mqtt#ws"
info Disk size without dependencies: "168KB"
info Disk size with unique dependencies: "168KB"
info Disk size with transitive dependencies: "168KB"
info Number of shared dependencies: 0
```

---

[Link to Discord post](https://discord.com/channels/983865673656705025/1252516046447841380/1252516046447841380)

**Comment by jgangelBLNG** [comment]
Seconding, this is a real pain for all our sst projects since dependabot has opened PRs that are trying to update us to v3 which breaks our builds.

![image](https://github.com/sst/sst/assets/135644891/9e6f4f27-d5c2-4da4-aa54-7d684605d568)

And from what I've found there's no way to disable specific dependency upgrades in dependabot security PRs so I'm not sure there's a fix outside of fixing this vulnerability in sst v2's dependency tree

**Comment by jayair** [comment]
Hmm is there a PR related to this. Happy to review it.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
