### ISSUE TITLE
Experimental settings for NextjsSite are in docs but seem to be removed.

### ISSUE THREAD

**Issue by MisterJimson** [sst/sst#3809]
It seems like the experimental settings for NextjsSite were removed, but are still present in the docs: https://docs.sst.dev/constructs/NextjsSite#experimental

SSTv 2.43.3

https://discord.com/channels/983865673656705025/1027265626085019769/1260667419764985897

**Comment by jayair** [comment]
Oh I think the docs are failing to generate. We'll take a look.

**Comment by mbaquerizo** [comment]
@jayair per-route logging seems to have been removed, but its still in the docs as well. Not sure if that is related
- https://github.com/sst/sst/pull/3567/commits/b841ef563dd7e09d2d0fdfa1a979a93edd380e2f
- https://discord.com/channels/983865673656705025/1245500552998289458/1245623347690082315

**Comment by jayair** [comment]
I think the docs generating issue has been fixed. We need to remove the per route logging from the description section at the top. I'll do that.
