### ISSUE TITLE
Allow specifying multiple folders in RDS migrations

### ISSUE THREAD

**Issue by gqgs** [sst/sst#3812]
Currently the [migrations](https://github.com/sst/sst/blob/b22831495b889c9af125a79344c6d030f3997e1f/packages/sst/src/constructs/RDS.ts#L100) field in the `RDSProps` only accepts the definition of a single folder.

>Path to the directory that contains the migration scripts. The `RDS` construct uses [Kysely](https://kysely.dev/) to run and manage schema migrations. The `migrations` prop should point to the folder where your migration files are.

This is inconvenient because there are migrations that I might want to run into some environments but not others (e.g., seeding the database in development environments but not in staging / production).

Seems like the ideal behavior here would be allowing multiple folders and then the internal logic would merge them and execute them sequentially in Kysely. Then it becomes trivial to control which folders are included in the migration in function 
of the stage environment during the resource definition.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
