### ISSUE TITLE
[Astro] Support astro:env in astro-sst adapter

### ISSUE THREAD

**Issue by janus-reith** [sst/sst#3814]
The build succeeds but throws an error if Astro `experimental.env` is used:

```
20:54:36 [ERROR] [config] The feature "astro:env getSecret" is not supported (used by astro-sst).
20:54:36 [ERROR] The adapter astro-sst doesn't support the feature envGetSecret. Your project won't be built. You should not use it.
```

Despite the error, the build creates some output.

I would assume the astro-sst adapter to use the node adapter internally and expect adding astro:env support to be rather simple. I wonder if additional steps are even required or the error just stems from the key `supportedAstroFeatures.envGetSecret = 'experimental'` not being present on the adapter.

**Comment by janus-reith** [comment]
Closing this and Reopening in Ion

**Comment by janus-reith** [comment]
Reopening. Despite the error, env seems to work, except for middleware.

**Comment by jayair** [comment]
Would appreciate a PR!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
