### ISSUE TITLE
Service (ECS) construct forces default autoscaling settings and there is no way to prevent that

### ISSUE THREAD

**Issue by zxan1285** [sst/sst#3894]
Hi!
When creating `new Service()` it will automatically create scaling based on CPU/Memory/Requests metrics. 
It also makes it impossible to add custom autoscaling settings, as `autoScaleTaskCount` is already created by default.
I'd like to have an option to disable default autoscaling. It then gives me possibility to use `service.cdk.fargateService.autoScaleTaskCount()` to setup custom autoscaling.
I created PR sst/sst#3840 to address this.
Thank you!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
