### ISSUE TITLE
Clarification needed: Using sst dev vs sst deploy after adding secrets (Not really a bug)

### ISSUE THREAD

**Issue by ironbyte** [sst/sst#3934]
When adding secrets to an SST project using AWS as a provider for a Remix app, the docs instruct to run sst deploy after using the sst secret set command. However, `sst dev` also appears to work and is pretty faster. I've verifed that the secret's properly added on my AWS account.

Steps to reproduce:

1. Run `sst secret set StripeKey st_1234`
2. Instead of `sst deploy`, run `sst dev`

Observed behavior:

1. `sst dev` works and is much faster (in seconds)
2. Changes take effect without running sst deploy

Question:

Are there any repercussions or potential issues when using `sst dev` instead of `sst deploy` after adding secrets? Maybe SST docs are a bit outdated regarding this?

**Comment by jayair** [comment]
No they both work, `sst dev` is doing the deploy for you. It's just the docs doesn't assume that you are running `sst dev` all the time, so it's asking you to explicitly do a deploy.

**Comment by jayair** [comment]
The other aspect to this is you might be setting the secret for a stage that you don't usually run `sst dev` on.

**Comment by ironheart122** [comment]
> No they both work, `sst dev` is doing the deploy for you. It's just the docs doesn't assume that you are running `sst dev` all the time, so it's asking you to explicitly do a deploy.

[Clarity obtained] Makes sense thank you!


> The other aspect to this is you might be setting the secret for a stage that you don't 
> usually run sst dev on.

Gotcha. My main issue with using sst deploy is that it takes so long to deploy my Remix apps (Setting up a cloudfront distribution and all). Just gotta be a bit patient.
