### ISSUE TITLE
Misleading advertising: how to run self-hosted docker containers?

### ISSUE THREAD

**Issue by vemonet** [sst/sst#3942]
Reading the official docs at https://sst.dev/docs/ the following tag line is overused:

> Build full-stack apps on your own infrastructure.

But then all examples are just using `aws` (Amazon infrastructure), and when going down the left sidebar we can find some instructions for `cloudflare`. Nothing to actually self-host...

Where are the instructions to run my own docker container with `docker compose` or `podman compose` on my **own infrastructure**?

When I search for deploying container in the search bar I get this: https://sst.dev/docs/component/aws/service/#containers AWS again

Would it be possible to fix the many usages of the phrasing "on your own infrastructure" that is so prominent on your website and semantically wrong regarding the proposed offering, so that it is not misleading? It should be "on cloud infrastructure"

Or fix the docs to give some instructions to run SST on actual physical server infrastructure using [OCI container images](https://opencontainers.org/) using `compose.yml` file or Kubernetes?

Thanks a lot!

**Comment by vemonet** [comment]
Ok it seems like it could be possible through nomad from hashicorp, just that the current docs are really focused on cloud deployment

Usually we deploy on-premise with docker/podman compose through SSH or kubernetes

**Comment by MentalGear** [comment]
Not on-premise, but docker based HowTo:
https://www.prudkohliad.com/articles/deploy-next-js-to-vps-using-sst-2024-08-11
