### ISSUE TITLE
Docs: Example for additional cache behaviours

### ISSUE THREAD

**Issue by devmarwen** [sst/sst#3944]
On SST v2 we had this `additionalBehaviors`

```
const site = new NextjsSite(stack, "site", {
  // ... 
  cdk: {
    distribution: {
      // ...
      additionalBehaviors: {
        "/a/*": {
          origin: aOrigin,
        },
        "/b/*": {
          origin: bOrigin,
        },
        "/c/*": {
          origin: cOrigin,
        },
      },
    },
  },
});

```

How to migrate this to SST v3. Using `transform.cdn` did not help because it overridden `orderedCacheBehaviors`/`origins` SST had generated

    const site = new sst.aws.Nextjs("ffd-nextfront-ion", {
      transform: {
        cdn: {
          orderedCacheBehaviors: [newCacheBehavior],
          origins: [googleOrigin],
        },
      },
    });

If it's not supported at the moment, can we combine SST v3 (Pulumi) with CDK ? An example would be much appreciated.

**Comment by jayair** [comment]
Added https://sst.dev/docs/examples/#aws-nextjs-add-behavior
