### ISSUE TITLE
[ION-1278] Docs: global AWS helper function

### ISSUE THREAD

**Issue by fwang** [sst/sst#3957]
https://sst.dev/docs/reference/global#aws
- does the section need some description?
- does the doc/example for `iamEdit` make sense?

<sub>[ION-1278](https://linear.app/sst-dev/issue/ION-1278/docs-global-aws-helper-function)</sub>

**Comment by jayair** [comment]
I edited it but a couple of issues. The link to the [PolicyDocument](https://www.pulumi.com/registry/packages/aws/api-docs/iam/documents/) for the Pulumi type is broken.

And the source file for this is not the `global.d.ts` so the "Edit this page" button doesn't work for this.
