### ISSUE TITLE
Docs: review VPC NAT

### ISSUE THREAD

**Issue by fwang** [sst/sst#3967]
NAT used to take `"ec2" | "managed"`, now we also allow ppl to customize the ec2 instance type: 
```ts
new sst.aws.Vpc("Vpc", {
  nat: {
    ec2: { instance: "t4g.micro" }
  }
});
```

See if the doc is clear - https://sst.dev/docs/component/aws/vpc#nat

**Comment by jayair** [comment]
Yeah looks good
