### ISSUE TITLE
Feat: Golang Support?

### ISSUE THREAD

**Issue by markoj3s** [sst/sst#4138]
Hello 😊

Any plan to support Golang with SST v3?

CC @thdxr

**Comment by markoj3s** [comment]
@thdxr Any update on this matter?

**Comment by pjvds** [comment]
Till we got support for this, I'm using the following to have our Go functions on v3. Caveat is that it doesn't support live dev.

``` typescript
async function GoFunction(
  name: string,
  args: FnArgs
): Promise<sst.aws.Function> {
  const binaryName = `${name}-${(args.bundle.split("/").splice(-1)[0] || ""
  ).replace(/\./g, "_")}`;

  const dir = ".build/lambda";
  const handler = join(resolve(args.bundle), dir);
  const build = `GOOS=linux GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-linux-musl-gcc CXX=x86_64-linux-musl-g++  go build -o ${dir}/${binaryName} main.go`;

  execSync(build, { cwd: args.bundle, stdio: "inherit" });

  return new sst.aws.Function(name, {
    runtime: "provided.al2023",
    bundle: handler,
    handler: binaryName,
    ...args,
  });
}
```

**Comment by brianfeister** [comment]
@pjvds that lack of support for live dev is a definitely bummer 😞

**Comment by pjvds** [comment]
> @pjvds that lack of support for live dev is a definitely bummer 😞

Totally agree. Also the lack of rebuild on change during dev mode is something I miss. But this was the only thing holding us back for upgrading to v3. Not perfect, but at least it works.

**Comment by pjvds** [comment]
This one can be closed! 🥳 
https://sst.dev/blog/go-runtime-support
