### ISSUE TITLE
Add docs on unit testing SST stacks

### ISSUE THREAD

**Issue by fwang** [sst/sst#415]
### Show how to unit test CDK code: create a stack instance, and use CDK's jest helper to check CF template output
  ```
  import {
    expect as expectCdk,
    haveResource,
    haveOutput,
  } from "@aws-cdk/assert";

  const stack = new MyStack(new App(), "stack");

  expectCdk(stack).to(haveResource("AWS::Lambda::Function", {
    Handler: "lambda.handler",
    Timeout: 20,
    MemorySize: 512,
  }));

  expectCdk(stack).to(haveOutput({
    outputName: "keyA",
    outputValue: "valueA",
  }));
  ```
### Show examples of how to use each of the helper method
https://www.npmjs.com/package/@aws-cdk/assert?activeTab=readme
- haveResource
- haveResourceLike
- countResources
- countResourcesLike
- haveOutput
- etc

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
