### ISSUE TITLE
CloudFlare DNS provider does not enable proxying

### ISSUE THREAD

**Issue by Badbird5907** [sst/sst#4261]
The CloudFlare dns provider does not enable proxying, and there is no way to enable proxying programmatically via the config.

What I've tried:
```ts
export const next = new sst.aws.Nextjs("Next", {
  domain: {
    name: "connectalum.com",
    dns: sst.cloudflare.dns({
      transform: {
        record: {
          proxied: true,
          ttl: 1,
        }
      }
    })
  },
  path: "apps/nextjs",
  environment: { ... }
});
```
This fails with: `failed to create DNS record: Target _39b918f2edf59bc2ff944ca1a053462c.djqtsrsxkq.acm-validations.aws. is not allowed for a proxied record. (9003))`

[Discord conversation link](https://discord.com/channels/983865673656705025/983865673656705028/1275158435566063786)

**Comment by vimtor** [comment]
@Badbird5907 did you find any solution?

**Comment by Badbird5907** [comment]
> @Badbird5907 did you find any solution?

Somewhat of a workaround, you can manually enable proxying on cloudflare, and it will stay proxied. However it may get overwritten in the future should any settings change.

Here is a screenshot of the discord conversation:
<img src="https://github.com/user-attachments/assets/362eec9c-2687-4a70-bc9f-3b37d31eda80" width="124" />

**Comment by leo-the-nardo** [comment]
the issue persists, any plans to merge the PR above?
