### ISSUE TITLE
ability to copy output from console in dev mode

### ISSUE THREAD

**Issue by mbhoward73** [sst/sst#4300]
it would be nice if we could copy output from the console in dev mode.  I'm running in linux and I've tried all the usual copy commands but I can't seem to get selected output into the clipboard.  one use case for this is when I'm looking at a long unformatted json string and I want to copy to another window and format it so it's more human readable

**Comment by kslbdev** [comment]
i can't shift+copy, so can't really copy with scrolling. Is this known? should i create a separate issue?
