### ISSUE TITLE
Bug: `Expired Token` encountered when trying to `PUT` on lambda-generated S3 Presigned URL

### ISSUE THREAD

**Issue by ian-pascoe** [sst/sst#4301]
During local dev I am experiencing "Expired Token" when generating a presigned url for a linked S3 bucket.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message>
```

When trying to execute the POST request to the generated presigned url
In reading here it looks like it is an issue with the token in the live dev? 
https://stackoverflow.com/questions/42951040/s3-expiredtoken-error-for-s3-pre-signed-url-within-expiry-period.

I have a NextJS trpc endpoint that I am creating a presigned url and when I call the PUT to that URL it gives me the expired token error 
Essentially I have 
```
Client requests presigned URL from TRPC -> TRPC returns presigned URL -> Client calls PUT on presigned URL -> Client receives error
``` 

I've also noticed that it doesn't happen the first couple minutes after a fresh deploy. It's if I let the `sst dev` sit for a little while then try to do the procedure

**Comment by wrobbinz** [comment]
I'm seeing this behavior with same steps as above on `v3.2.60`. Flagging in case this is a regression with all the changes to dev process handling I've seen in the latest releases.
