### ISSUE TITLE
Resources are not linked in next.js middleware

### ISSUE THREAD

**Issue by brapifra** [sst/sst#4326]
When setting up a really simple next.js middleware:

```typescript
import { NextRequest, NextResponse } from "next/server";
import { Resource } from "sst";

export async function middleware(request: NextRequest) {
  console.log(Resource.MySecret.value);

  return NextResponse.next();
}
```

I get the following error when running `sst dev`:

```
Error: "MySecret" is not linked
```

And if I log `Resource`, it prints an empty object. So it looks like resources are not linked at all.
However, it works if I print the same on a next.js page or API route.

sst cli version: 0.1.76
sst package version: 3.0.33 (Although I also tried with 3.0.37)

**Comment by axyl** [comment]
This is working correctly for me in SST@3.2.61 .  The resources object has all of the links that it should.  (Astro 5 Beta .5)

**Comment by brapifra** [comment]
I can confirm this seems to be working now! (Tested with SST@3.3.30)
