### ISSUE TITLE
Updating bundle config needs to restart `sst start`

### ISSUE THREAD

**Issue by fwang** [sst/sst#436]
I updated the `loader` for one of my functions:
```
        function: {
          handler: "services/api/stageBuildBadge.main",
          loader: {
            ".svg": "text",
          },
        },
```

I need to restart `sst start` for esbuild to use the loader.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
