### ISSUE TITLE
 SST 0.1.42: sst dev errors after updating

### ISSUE THREAD

**Issue by South-Paw** [sst/sst#4375]
Updating installed version of SST to 0.1.42 and now running the following command that used to work

```bash
sst dev "npm run dev:web"
```

just returns the following error

```
Ensure `sst dev` session is running where you sst.config.ts is. If you do not want to use the multiplexer you can start `sst dev --mode=basic` instead.
```

- Project is a npm workspaces monorepo
- The `sst.config.ts` is at the root of the project where the command is being run
- `npm run dev:web` runs `vite` within the `packages/web` folder
- Adding `--mode=basic` returns the same error

According to all the docs, this command should still work as expected - right?

**Comment by anil-kashipaka** [comment]
sst dev is not running , can anybody help ?
