### ISSUE TITLE
Create a SST starter with Lerna and Yarn Workspaces

### ISSUE THREAD

**Issue by jayair** [sst/sst#446]
### Repo: https://github.com/serverless-stack/sst-lerna-yarn-starter

Use a setup similar to https://github.com/AnomalyInnovations/serverless-lerna-yarn-starter

Requested by Adrián Mouly on Slack (https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1623723326141600).

Things the starter needs to address:
- [ ] Explain the folder structure of 1 SST app with multiple stacks, as opposed to multiple SST apps (the setup people are more used to with SLS)
- [x] Setting up yarn + lerna
- [x] How to structure the frontend code?
  1. Is SST at the root, and the frontend sits in a sub-directory?
  2. Are both the SST and the frontend sub-directories?
- [x] Can we/How to get around the Jest version mismatch issue with React?
  React error:
  ```
  The react-scripts package provided by Create React App requires a dependency:
    "jest": "26.6.0"
  ```
  #### Solution 1: Currently solution is adding a `.env` file with `SKIP_PREFLIGHT_CHECK=true`
  #### Solution 2: Alternatively, you can add dependency resolution to your `package.json`:
  ```json
   "resolutions": {                                                                                   
     "**/jest": "26.6.0"                                                                              
   }
  ```
- [ ] Check why enabling linting is causing this error in the setup:
  ```
  /Users/.../tasksApi/lib/TasksApiStack.ts
    0:0  error  Parsing error: Cannot read file '/users/.../node_modules/@serverless-stack/cli/tsconfig.json'
  /Users/.../tasksApi/lib/index.ts
    0:0  error  Parsing error: Cannot read file '/users/.../node_modules/@serverless-stack/cli/tsconfig.json'
  ```
- [ ] Show a comparison of the folder structure of an SST Lerna+Yarn project vs an SLS Lerna+Yarn project.
- [ ] Setup tests for services
- [x] Add README

**Comment by jayair** [comment]
Added a README and updated the chapter on it https://serverless-stack.com/chapters/using-lerna-and-yarn-workspaces-with-serverless.html

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
