### ISSUE TITLE
Discussion: How to use Ion in CI/CD 

### ISSUE THREAD

**Issue by kxseilerjo** [sst/sst#4595]
So, I don't know whether this is known or even intentional, but with an Ion version of SST you can't do
> npx sst deploy
in CI/CD environments anymore, or rather you can't use SST over Npx anywhere at all anymore.

So are you supposed to just install the new SST CLI in CI/CD environments as well?

**Comment by imdkbj** [comment]
Dear @thdxr, Any update on the same.
