### ISSUE TITLE
EC2 Instance support?

### ISSUE THREAD

**Issue by dev2xl** [sst/sst#4603]
I don't see it on the docs. It would be great to be able to easily setup an EC2 instance and install, and upload some scripts, assigning dedicated IP using ion. Idk if this is out of the scope of the project. Thanks

**Comment by greglearns** [comment]
+1

**Comment by agamm** [comment]
I added docs for it:
https://sst.dev/docs/examples/#ec2-with-pulumi

**Comment by greglearns** [comment]
I had actually already seen that example before I asked for help (I should
have clarified that), so I can see how to create an EC2 instance; but it's
not clear how to use that EC2 instance with everything else that sst.dev
offers. I read through all of the documentation but I couldn't figure it
out (I'm new to sst). For example, I'm not sure how I would launch a
SolidStart app that would run on the EC2 instance, and then update the app
(just as an example), while using S3 buckets with links, etc.

**Comment by agamm** [comment]
> I had actually already seen that example before I asked for help (I should have clarified that), so I can see how to create an EC2 instance; but it's not clear how to use that EC2 instance with everything else that sst.dev offers. I read through all of the documentation but I couldn't figure it out (I'm new to sst). For example, I'm not sure how I would launch a SolidStart app that would run on the EC2 instance, and then update the app (just as an example), while using S3 buckets with links, etc.


Did you try the [SDK ](https://sst.dev/docs/reference/sdk) and [linking](https://sst.dev/docs/component/linkable)?

**Comment by jayair** [comment]
@greglearns  Out of curiosity, why EC2 and not Fargate for SolidStart?
