### ISSUE TITLE
Support for lambda JWT authorizer

### ISSUE THREAD

**Issue by geauser** [sst/sst#4606]
Hello 👋 

In the previous version of SST we could use [lambda authorizers](https://docs.sst.dev/constructs/Api#apilambdaauthorizer), does such a feature exists in SST ion?

**Comment by geauser** [comment]
@jayair @fwang Any news on that?

**Comment by jayair** [comment]
We have this https://sst.dev/docs/component/aws/apigatewayv2/#auth-lambda

**Comment by geauser** [comment]
Awesome @jayair closing this then!
