### ISSUE TITLE
Support CDK context

### ISSUE THREAD

**Issue by fwang** [sst/sst#461]
### Research
- [ ] is cdk.json auto generated? (how to handle CDK feature flags in SST)
- [ ] App loads context.json so can be used in tests

Slack thread: https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1622737782063000

**Comment by riccardogiorato** [comment]
Would need this feature to use "CDK feature flags"!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
