### ISSUE TITLE
sst.aws.ApiGatewayWebSocket seems to be missing a way to inject the managementEndpoint into the handlers, and also lacks AWS permissions to invoke it

### ISSUE THREAD

**Issue by XaeroDegreaz** [sst/sst#4633]
sst: ion (3.0.15)

I have an `ApiGatewayWebSocket` component defined:

```ts
const api = new sst.aws.ApiGatewayWebSocket( "MyApi")
api.route( "$connect", "lambda/handler.connect" );
api.route( "$disconnect", "lambda/handler.disconnect" );
api.route( "$default", "lambda/handler.defaultHandler" );
```

And a default handler:
```ts
export const defaultHandler: APIGatewayProxyHandler = async ( event ) => {
  const id = event.requestContext.connectionId;
  console.log( `Default: id:${id}` )

  //# I had to capture the management endpoint in the console output in order to statically place it here
  const api = new ApiGatewayManagementApi( {endpoint: "https://****.execute-api.us-east-1.amazonaws.com/$default"} )

  //# This fails because the ApiGatewayWebSocket is missing AWS permissions for 'execute-api:ManageConnections'
  await api.postToConnection( {ConnectionId: id, Data: JSON.stringify( {text: "received", timestamp: Date.now()} )} )
  return {
    statusCode: 200,
    body: "OK!"
  }
}
```

1. There should be a way for the Lambda handlers to get access to their `managementEndpoint`. Simply using `Resource.MyApi.managementResource` inside the handler doesn't work because the componenent isn't 'linked' with itself.
2. When creating the API gateway resources, the lambda should have the `execute-api:ManageConnections` permission so that it can send messages to clients.

I had to manually define the `$default` handler to include the permission, as well as an environment variable pointing to the `managementEndpoint`:
```ts
const api = new sst.aws.ApiGatewayWebSocket( "MyApi");
api.route( "$connect", "lambda/handler.connect" );
api.route( "$disconnect", "lambda/handler.disconnect" );
api.route( "$default", {
  handler: "lambda/handler.defaultHandler",
  permissions: [
    {
      actions: ['execute-api:ManageConnections'],
      //# It would be nice to be able to lock this down better...
      resources: ['arn:aws:execute-api:us-east-1:*']
    }
  ],
  environment: {
    MANAGEMENT_ENDPOINT: api.managementEndpoint
  }
} );
```
Documentation for the `managementEndpoint` does not seem to be correct:
<img width="712" alt="image" src="https://github.com/sst/ion/assets/312459/d62a3d8a-7c56-4b59-9b84-061aa5612a7e">

I always get the error:
```
|  Error       
|  "MyApi" is not linked
```
in my terminal when running `npm run dev`

**Comment by antonigiske** [comment]
> you can specify the lambda handlers like this
> 
> ```
> api.route( "$connect", { handler: "lambda/handler.connect", link: [api] } );
> ```

This works, but remember to remove any existing route transform handlers on the ApiGatewayWebSocket that will override.
