### ISSUE TITLE
Run & deploy application programmatically

### ISSUE THREAD

**Issue by kedrzu** [sst/sst#469]
For some more complicated development & deployment setups, it would be super nice to be able to run serverless-stack from my own `.js` script, instead of running it from the command line. 

SST has nice support for typescript and has bundling included, but it can't match with full-blown bundler, like rollup. I would like to create a pipeline, where I have rollup to build & bundle my big project and then SST to work on rollup output files. I did this using command line for both tools, but it's not very convenient, because I need to wait for rollup build to start SST. With ability to run SST from script, I could do that easily. Also, it would allow for more customized development flows.

Currently, as far as I see, main problem is, that whole logic for `start` and `deploy` is tightly connected with CLI logic, like parsing arguments and so. I think it would suffice to move that logic ie. into `@serverless-stack/core` and have `cli` to be a pure wrapper with argument parsing, help and so.

**Comment by fwang** [comment]
Hey @kedrzu, thanks for bringing this up!

Currently, SST uses esbuild to bundle ur Lambda functions. So with your setup, are you bundling the Lambda code twice? ie. you manually bundle the code using rollup, and then SST runs esbuild against rollup's output again?

**Comment by kedrzu** [comment]
Yes, that's true. But my output is pure JS, so there is no need to transpile TS again.
There are many issues with bundler used in SST. For example, it does not work with ES modules, as far as I know.

I tried to setup some more complicated lambda, that would use VueJS to render emails and send through AWS SES. For this I need vue or JSX compiler, so I need some more sophisticated build pipeline.

Maybe it would be a good idea to use rollup JS inside of SST? This would make it super powerful and customizable. Esbuild could be used simply as rollup plugin. BTW, that's the approach Vite is using for it's blazing fast development server - it's build on the top of the RollupJS.

**Comment by fwang** [comment]
Yeah that makes sense. I think we should let ppl use whichever bundler they want, giving full flexibility over the build process.

Imagine you define the function like this:
```js
new sst.Function(this, "MyFunction", {
  handler: "bundle.handler",
  buildCommand: "rollup src/main.js --file output/bundle.js",
  buildOutput: "output",
});
```
SST would run the `buildCommand`, zip up and upload the `buildOutput`.

Would something like this work for you?

**Comment by kedrzu** [comment]
I'm not so fond of command line driven approach:
- It's problematic, when you want to use it with watcher. You would have to reinvent the wheel and make your own watcher for the whole dependency tree, which is super non-trivial. Or you would have to make different commands for build and watch.
- With more and more functions to compile, performance will quickly degrade. Having 20 concurrent rollup builds instead of 1 build with 20 inputs  & outputs is so much slower.

I think it would be better to stick to Rollup: it's super customizable, one can do almost anything, if he knows how to write plugins. It's super fast as well (compared to webpack for example). Then all the bundling logic that are internal to SST would be written as Rollup plugins. That's the approach ViteJS is using - nice case study to look at.

Maybe creating `sst.Function` would add another input to some single Rollup configuration. Also you would have a possibility to add your own rollup plugins maybe on `sst.App` level. Rollup is easy to run from pure JS, so this should be easy to do. And because rollup plugins can extend rollup in any way possible (even extending configuration), this I think would suffice to do anything with build pipeline.

The only problem I see with rollup builds, is that it cannot do full separate bundles without code splitting. Check this issue: https://github.com/rollup/rollup/issues/2756 
Every Lambda must be self-contained, and with rollup you would need to have separate rollup config per lambda function, which, as I said, quickly becomes super slow. 

Maybe there is some nice solution to think about, like two-staged builds. First stage will build all output JS files, and then pure ESBuild would bundle them into self-contained lambda files.

**Comment by fwang** [comment]
Yeah, you are right, running a rollup command per Function is definitely not feasible.

My angle on this is to make sure the build/rebuild speed is AS FAST AS POSSIBLE for the common use case (ie. without ES modules support). And esbuild seems to be the fastest available option at the moment.

But hey, maybe we can just support multiple bundlers natively! Something like:
```js
new sst.Function(this, "MyFunction", {
  handler: "bundle.handler",
  bundler: FunctionBundler.ROLLUP,
  rollupOptions: {
    ...
  }
});
```
And this will work exactly like how you described above. In `sst.App`, you can set the default bundler for all functions, and also add your own plugins:
```js
app.setDefaultFunctionProps({
  bundler: FunctionBundler.ROLLUP,
  rollupOptions: {
    plugins: [...],
  },
});
```
What do you think?

**Comment by o-alexandrov** [comment]
> running a rollup command per Function is definitely not feasible.

That's opposite.
Bundling functions individually should always be preferred due to otherwise functions' execution performance degradations and a lot more.

[This approach](https://github.com/theBenForce/cdk-rollup-code/blob/master/src/index.ts) works great with pure aws-cdk.

> And this will work exactly like how you described above. In sst.App, you can set the default bundler for all functions, and also add your own plugins:

This would be great

**Comment by o-alexandrov** [comment]
On a side note, it would have been great, if `sst` mimicked or directly used [vite.js](https://vitejs.dev/)' approach in bundling.

As of now, bundling without ability to add stable plugins probably turns many devs away from `sst`, me including.
- probably at least for the next couple of years, it's better to prefer esbuild within rollup, rather than running esbuild directly

**Comment by ivands** [comment]
There should just be a build function present on the Function resource that should return the bundled code & maybe the source map.
```js
new sst.Function(stack, "MyFunction", {
  handler: "functions/file.handler",
  build: async (file) => {
    const { code, sourcemap } = await useOwnBundler(file);
    return { code, sourcemap };
  }
});
```
This way you people can define there own bundling strategies.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
