### ISSUE TITLE
Cannot remove the app if the app is in a non-synth-able state on `sst remove`

### ISSUE THREAD

**Issue by fwang** [sst/sst#48]
### Two scenarios
1. User has deployed the app, then made some changes and the app can no long be synthed (ie. `sst build` fails). The user now wants to remove the app and start fresh but cannot because `sst remove` fails at the build step.
2. User has deployed the app, then the dependencies have changed (ie. a stack no longer uses the export from another stack). The user now wants to remove the app, and removal might fail because the removal order is now changed.

### Solution
Create a SST bucket in the user's S3 account that stores the app's latest deployed state. And `sst remove` does not rebuild the app, but rather remove using the state.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
