### ISSUE TITLE
Astro Server Route cannot receive POST, PUT, or DELETE requests, resulting in a 403 error

### ISSUE THREAD

**Issue by gel1123** [sst/sst#4812]
I am building a system using the `<form>` tag and Astro's server endpoints. I have defined a route in the Astro server endpoints to handle POST requests. However, after deploying with SST, POST requests to this route result in a 403 error in the AWS environment. I think this is because the SST Ion's Astro component, by default, only permits HTTP methods like GET, HEAD, and OPTIONS for server routes, and does not allow PUT, DELETE, or POST. Currently, it seems there are no options within the Astro component settings to change the permitted HTTP methods.

If I'm operating Astro in SSR (Server-Side Rendering), I would really like to be able to receive POST, PUT, and DELETE requests in Server Routes. I suspect the issue might be due to the CloudFront origin group, which, by specification, origin group only allows configurations for GET, HEAD, and OPTIONS...

I have created a repository that reproduces this issue: 

https://github.com/gel1123/astro-sandbox-001

**Comment by lukefernandez** [comment]
If anyone else is wondering where to set `serverRoutes`, the adapter's README covers it at https://www.npmjs.com/package/astro-sst. 

Copying here in case that link stops working:

> When utilizing regional deployment strategy, server routes should be defined for any routes utilizing non-GET methods:
> 
> ```js
> import { defineConfig } from "astro/config";
> import aws from "astro-sst";
> 
> export default defineConfig({
>   output: "server",
>   adapter: aws({
>     deploymentStrategy: "regional",
>     serverRoutes: [
>       "feedback", // Feedback page which requires POST method
>       "login", // Login page which requires POST method
>       "user/*", // Directory of user routes which are all SSR
>       "api/*", // Directory of API endpoints which require all methods
>     ],
>   }),
> });
> ```
