### ISSUE TITLE
Feat: Long Running Jobs

### ISSUE THREAD

**Issue by adileo** [sst/sst#4834]
Opening this issue since I can't find any option in Ion SST for Long Running Jobs or Container Constructs available in standard SST

https://docs.sst.dev/long-running-jobs
https://docs.sst.dev/containers

Those are essential components for developing data intensive applications.

**Comment by Cirelion** [comment]
Do we have a rough timeline for when this will be implemented? Long running jobs is a blocker for migration for me.

**Comment by jayair** [comment]
Coming in the next week or so.

**Comment by jayair** [comment]
https://sst.dev/blog/tasks-in-v3
