### ISSUE TITLE
Validate construct input

### ISSUE THREAD

**Issue by fwang** [sst/sst#486]
### Api Routes
[Garret Harp on Slack](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1628474739285100) ran into his issue while configuring Api routes:
```
"GET /": {
  handler: "src/index.handler",
  authorizer: MyAuthorizer
}
```

### Defining permissions
Instead of
```
transcodeFunction.attachPermissions([
  [props!.uploadBucket, 'grantRead'],
  [props!.storageBucket, 'grantWrite'],
]);
```
Should be
```
[props!.uploadBucket.s3Bucket, 'grantRead']
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
