### ISSUE TITLE
sst start does not work when Lambdas are deployed to an isolated VPC subnet

### ISSUE THREAD

**Issue by fwang** [sst/sst#487]
Here's the VPC configuration with the isolated subnet shared by Brett Gullan in Slack.
```js
    this.vpc = new Vpc(this, 'CustomVPC', {
      cidr: '10.0.0.0/16',
      natGateways: 0,
      maxAzs: 2,
      subnetConfiguration: [
        {
          name: 'publicSubnet',
          subnetType: SubnetType.PUBLIC,
          cidrMask: 24,
        },
        {
          name: 'isolatedSubnet',
          subnetType: SubnetType.ISOLATED,
          cidrMask: 24,
        },
      ],
    })
```

**Comment by zhex900** [comment]
The lambda timeout during local dev running sst. However the lambda runs after it is deployed.

```
const api = new Api(stack, "api", {
    routes: {
      "GET /notes": {
        function: {
          handler: "./stacks/lambda.handler",
          architecture: "arm_64",
          runtime: "nodejs18.x",
        },
      },
    },
    defaults: {
      function: {
        architecture: "arm_64",
        vpc,
        vpcSubnets: {
          subnetGroupName: "Postgres", //SubnetType.ISOLATED,
        },
        securityGroups: [securityGroup],
      },
    },
  });
```

**Comment by jayair** [comment]
@zhex900 Is it unable to connect to the VPC locally?

**Comment by zhex900** [comment]
Yes. I am referring local dev environment. For now, I have switched not to use VPC during local dev.

**Comment by jamiechong** [comment]
> Yes. I am referring local dev environment. For now, I have switched not to use VPC during local dev.

@zhex900  Could you show a code snippet for how you elegantly switch between `vpc` and no `vpc` when on localhost?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
