### ISSUE TITLE
Error: spawnSync node ENOENT

### ISSUE THREAD

**Issue by fwang** [sst/sst#514]
### Issue
A common cause for the error is when the SST app is not sitting at the root of a repo. And the `cli` package is in root's node_modules, while the `resources` package is in app's node_modules. ie.
```
/
  node_modules/
    @serverless-stack/
      cli/
  app/
    node_modules/
      @serverless-stack/
        resources/
```
And linting Lambda functions will failed with the error
```
Error: spawnSync node ENOENT
```

### Solution
The solution is to have both the `cli` and `resources` packages installed at the root, or both at the app level.

### Monorepo
If you have a monorepo setup, checkout this starter - https://github.com/serverless-stack/lerna-yarn-starter

### TODO for maintainer
- [ ] handle the `cli` and `resources` packages not installed at the same level. Currently, path to the `cli` package is guessed from the path to the `resources` package. https://github.com/serverless-stack/serverless-stack/blob/master/packages/resources/src/App.ts#L282-L296

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
