### ISSUE TITLE
Doc: people are confused if they only import resources created in CDK

### ISSUE THREAD

**Issue by fwang** [sst/sst#523]
### Problem
Many of the SST construct examples has an importing example. For example, for `AppSyncApi` there is an example `Importing an existing GraphQL Api` that says `Override the internally created CDK GraphqlApi instance.`

A user was confused if one can only import an Api created using CDK:
> Hey – is there a way to import an existing AppSync API to SST that was created via Cloudformation (by way of serverless framework)? I noticed the docs only show such for AppSync created by CDK.

### Solution 1
Mention in all example: `Instead of creating a new GraphQL Api, you can import one that's been previously created.`

### Solution 2
```js
new Api(this, "Api", {
  httpApi: Api.importHttpApiFromApiId(httpApiId),
  routes: {
    "GET /notes": "src/list.main",
  },
});
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
