### ISSUE TITLE
Post stack deployment hook

### ISSUE THREAD

**Issue by cmaycumber** [sst/sst#527]
Is it possible to determine when the stack has deployed and run a custom script after the fact? 

My use case is automatically generating code from the AppSync schema that was deployed to the cloud based on its introspection schema. If there's a better way, I'd love to explore that as well.

**Comment by fwang** [comment]
Hey @cmaycumber, are you looking to run the script on every deploy? Or only once on the first deploy?

**Comment by cmaycumber** [comment]
> Hey @cmaycumber, are you looking to run the script on every deploy? Or only once on the first deploy?

I'd need the script to run on every deploy.

 For some context, I'm trying to run a codegen for the graphql API. It would be super helpful that when after a successful deploy was made when using `sst start` or `sst deploy`, the codegen script would run for the valid graphql schema.

**Comment by fwang** [comment]
Thanks for the details! If you were to change the `start` and `deploy` scripts in your `package.json` like this:
```json
  "scripts": {
    "start": "sst start && ./codegen",
    "build": "sst build",
    "deploy": "sst deploy && ./codegen",
  },
```

Does this work for you?

**Comment by thdxr** [comment]
@cmaycumber did that work for you? Going to close this issue for now - feel free to comment if you'd like to reopen it

**Comment by cmaycumber** [comment]
Sorry, for not responding. It has worked in the meantime! We are revisiting our codegen as we speak with a new solution, I'll respond back here if I still think it would be helpful!

**Comment by cmaycumber** [comment]
@thdxr Would it be possible to re-open this? 

After re-evaluating some of our codegen logic it would still be super helpful to us to have a post-deploy hook that runs after the start command performs a successful deploy. I can somewhat get around the issue currently be running our codegen inside of of the stack code but it's less safe than checking that the deploy was actually successful before running the desired effect.

**Comment by thdxr** [comment]
> Thanks for the details! If you were to change the `start` and `deploy` scripts in your `package.json` like this:
> 
> ```json
>   "scripts": {
>     "start": "sst start && ./codegen",
>     "build": "sst build",
>     "deploy": "sst deploy && ./codegen",
>   },
> ```
> 
> Does this work for you?

Does this solution work for you? If not would like to understand more

**Comment by cmaycumber** [comment]
> > Thanks for the details! If you were to change the `start` and `deploy` scripts in your `package.json` like this:
> > ```json
> >   "scripts": {
> >     "start": "sst start && ./codegen",
> >     "build": "sst build",
> >     "deploy": "sst deploy && ./codegen",
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does this work for you?
> 
> Does this solution work for you? If not would like to understand more

This solution currently doesn't seem to work because when calling `sst start && ./codegen`, codegen runs after the start command has been completed. But since running `sst start` is an ongoing process it never finishes so the codegen command doesn't seem to run when pressing the `enter key` to redeploy the stack during the `sst start` process.

**Comment by thdxr** [comment]
Ah got it.  I have a similar setup where there's codegen that generates bindings for the frontend to use with an API.  I actually run those prior to even deploying (similar to running it in the stack).  Let me think a bit more about adding hooks and get back to you

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
