### ISSUE TITLE
Updating python lambda layer in sst.Api defaultFunctionProps does not update Lambda in deploy

### ISSUE THREAD

**Issue by shechter** [sst/sst#528]
I updated a lambda layer
```
 const myLambdaLayer = lambda.LayerVersion.fromLayerVersionArn(this, 'myLayer', <string>process.env.LAMBDA_LAYER)
```
which is used in my Api
```
const api = new sst.Api(this, "Api", {
            defaultFunctionProps: {
                srcPath: "src/lambda/",
                layers: [myLambdaLayer, scipyLambdaLayer],
 ```
 
On `deploy`, Lambda did not update the Layer version.

**Comment by shechter** [comment]
It seems to reliably update the layer version when I deploy through Seed whereI see it goes through build -> deploy actions; whereas on my local dev machine, when I just run deploy, it does not update the layer version.

**Comment by fwang** [comment]
Hi @shechter, taking a look.

**Comment by fwang** [comment]
Hey @shechter, I wanted to circle back to this issue. This is what I tried,
```js
    // Import the "numpy" layer from https://github.com/mthenw/awesome-layers
    const layer = lambda.LayerVersion.fromLayerVersionArn(this, "Layer", "arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-numpy:19")

    // Create the HTTP API
    const api = new sst.Api(this, "Api", {
      defaultFunctionProps: {
        runtime: "python3.8",
        srcPath: "src",
        layers: [layer],
      },
      routes: {
        "GET /notes": "list.main",
      },
    });
```
After I `sst deploy` the app, I then changed the layer version from `:19` to `:20`; ran `sst deploy` again, and I saw CloudFormation updated the Function.

Are you running into this issue consistently after you change the layer version?

**Comment by fwang** [comment]
Chatted with @shechter on Slack, and this is what we can do to triage this issue:
1. The next time the layer version is not being updated, open up the CloudFormation template inside `.build/cdk.out/`;
2. Find the `Layers` definition inside a `AWS::Lambda::Function` resource block that looks like this:
  ```
  "Layers": [
    "arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-numpy:20"
  ],
  ```
3. Check if the version number matches that that defined in SST code;
4. If the version mismatches, console.log the layer's ARN in SST and see what the value is at build time;
5. If the version matches, go to the Lambda console, and see if the version's ARN is updated.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
