### ISSUE TITLE
Api: support multi-level paths in BasePathMapping

### ISSUE THREAD

**Issue by fwang** [sst/sst#529]
Waiting for CDK to add support for it - https://github.com/aws/aws-cdk/issues/14822

### Workaround
Guy Shechter has a [workaround](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1625807944199600) by configuring the custom domain manually:
```js
import {CfnApiMapping, IStage} from "@aws-cdk/aws-apigatewayv2";
...
        const myApi = sst.Api(...)
        const customDomainMapping = new CfnApiMapping(this, "customDomainMapping", {
            apiId: myApi.httpApi.apiId,
            domainName: 'api.myapp.com',
            stage: (<IStage>myApi.httpApi.defaultStage).stageName,
            apiMappingKey: (scope.stage !== 'prod' ? {path: scope.stage + '/orders/returns'} : {path: 'orders/returns'})
        })
        this.addOutputs({
            "CustomEndpoint": 'https://' + customDomainMapping.domainName + '/' + customDomainMapping.apiMappingKey
        });
```

**Comment by shechter** [comment]
This worked until I went to deploy a new stage. In that case, I also needed to add a dependency to prevent customDomainMapping from being created before the Api was created:
```
        customDomainMapping.node.addDependency(api.httpApi);
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
