### ISSUE TITLE
Function: manage commonly used Lambda layers

### ISSUE THREAD

**Issue by fwang** [sst/sst#541]
### Goal
1. Be able to specify layers by name instead of their ARN
2. Simply configuring the bundle props ie. `externalModules` and `nodeModules`

### Commonly used layers
- AWS Chrome (reference an existing third-party layer)
- Prisma (set a package in `externalModules` and create a layer)
- discord.js (set `discord.js` in `nodeModules`)

#### Prisma example from [Josias in Slack](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1627508724073000)
```js
const dataGraphApi = new ApolloApi(this, "Api", {
  server: {
    handler: "apps/data-graph/src/lambda.handler",
    bundle: {
      nodeModules: [
        // node_modules/nexus-plugin-prisma/src/index.ts
        "graphql",
        "nexus",
        "@prisma/client",
        "prisma",
      ],
      commandHooks: {
        beforeBundling: () => [],
        beforeInstall: (inputDir, outputDir) => {
          console.log("beforeInstall: ", { inputDir, outputDir })
          return ["pwd", "cp -R apps/data-graph/src/prisma ${outputDir}/"]
        },
        afterBundling: (inputDir, outputDir) => {
          console.log("afterBundling: ", { inputDir, outputDir })
          return [
            "pwd",
            "ls -al",
            `cd ${outputDir}`,
            `yarn prisma generate`,
            `rm -rf node_modules/@prisma/engines`,
          ]
        },
      },
    },
  },
})
```
---
_Requested by [Justin in Slack](https://serverless-stack.slack.com/archives/C01J5QB8T6F/p1625115155031600?thread_ts=1624993998.026400&cid=C01J5QB8T6F)_

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
