### ISSUE TITLE
Dashboard: Queue DLQ funtionality

### ISSUE THREAD

**Issue by fwang** [sst/sst#572]
Mentioned by [Omi in Slack](https://serverless-stack.slack.com/archives/C01HYQRUGG6/p1626711246084100):
> Related note - what are people doing for handling DLQs? Ideal tool would act like sentry for SQS - alert me sanely, let me inspect failed messages, save them off the queue and let me resubmit pending messages back into the original queue - anything out there like that?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
