### ISSUE TITLE
Fail to deploy debug stack after updating SST

### ISSUE THREAD

**Issue by fwang** [sst/sst#585]
SST was updated from serverless-stack@0.29.2 to 0.34.0 and @aws-cdk/* from 1.105.0 to 1.111.0

The error was:
> failed bootstrapping: Error: Not downgrading existing bootstrap stack from version '5' to version '0'. Use --force to force.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
