### ISSUE TITLE
Example: Debugging in IntelliJ

### ISSUE THREAD

**Issue by XaeroDegreaz** [sst/sst#627]
Is there a way to debug from IntelliJ / Webstorm, etc? I can only find documentation for VSCode.

**Comment by fwang** [comment]
Hey @XaeroDegreaz, not yet. But lemme take a look and put something in!

**Comment by krivachy** [comment]
It "just works" for me in Webstorm if you create an NPM run configuration for the `start` command and launch it in debug mode:

![image](https://user-images.githubusercontent.com/5367669/127897528-7de1f954-ee1a-4de8-b947-4ef3c4b2181e.png)

**Comment by fwang** [comment]
Hmm.. let me give it a try. And also add some examples for setting up SST in Webstorm and IntelliJ.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
