### ISSUE TITLE
Support for S3 transfer acceleration

### ISSUE THREAD

**Issue by ffxsam** [sst/sst#631]
It would be great to not have to use this escape hatch:

```ts
(uploadBucket.s3Bucket.node.defaultChild as s3.CfnBucket).accelerateConfiguration = {
    accelerationStatus: 'true',
};
```

And instead do:

```ts
  const uploadBucket = new Bucket(scope, 'UploadBucket', {
    s3Bucket: {
      bucketName: `${process.env.APP_NAME}-uploads-${scope.stage}`,
      transferAcceleration: true,
    },
  });
```

**Comment by fwang** [comment]
Yup.

I also voted on the [CDK's issue](https://github.com/aws/aws-cdk/issues/9947) in case they get to this first.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
