### ISSUE TITLE
Should eslint config be part of the project code?

### ISSUE THREAD

**Issue by ColinCee** [sst/sst#653]
Because the CLI uses a linter not in my project directory, I can't

- Override rules specific to my project
- Have linting suggestions in VSCode as I develop

To overcome this, I would need to duplicate the lint config you guys use and then disable the `lint` option in `sst.json`

**Comment by franciscocpg** [comment]
Same issue here. Any thoughts here?

**Comment by fwang** [comment]
It's something we are working on. Allow users to provide their own eslint config. @thdxr is leading the initiative. I will let him chime in once he figures out a rough design.

**Comment by adambiggs** [comment]
Any updates on this? I want to enforce our organization's standardized eslint rules in SST services.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
