### ISSUE TITLE
Api: support Step Function integration

### ISSUE THREAD

**Issue by fwang** [sst/sst#666]
_Requested by [Sakar on Slack](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1628410878082900)_

**Comment by kotfilemon** [comment]
+1

**Comment by marconucara** [comment]
+1

**Comment by fwang** [comment]
@riccardogiorato are you looking for API invoking a Step Function directly, or being able to live debug a Step Function locally?

You can already do the latter by passing `sst.Function` to `tasks.LambdaInvoke`, for example:
```js
import * as tasks from "aws-cdk-lib/aws-stepfunctions-tasks";

const submitJob = new tasks.LambdaInvoke(this, 'Job', {
  lambdaFunction: new sst.Function(...),
});
```

Let me know, and we can create a friendlier wrapper around this.

**Comment by pharindoko** [comment]
Thanks for the explanation @fwang 
Would be great if you can mention this in the documentation. 
Step functions is great for long running tasks and this is the only real component I was missing when I read the sst documentation.

**Comment by LudoLab92** [comment]
We are wondering if we could use SST in my company but if we can't deploy Step Functions it won't be an option anymore :(
+1 to add it on a next release

**Comment by fwang** [comment]
@LudoLab92 You can deploy Step Functions (and any AWS resources) in SST today. We just haven't created a "beautiful" syntax for it yet.

You can use any AWS CDK constructs in SST. Here's an example of how to do it currently — https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions-readme.html#example

Use `sst.Function` instead of `lambda.Function`, and live dev will work.

Let me know if it makes sense.

**Comment by ifeltsweet** [comment]
> Let me know, and we can create a friendlier wrapper around this.

@fwang I would love to have this as well. We are building a step functions heavy application with SST and AWS CDK and this would come in so handy!

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
