### ISSUE TITLE
Strategy on splitting resources into multiple stacks

### ISSUE THREAD

**Issue by fwang** [sst/sst#677]
Things to cover:
- [ ] Show an example of how to split resources across multiple stacks. Especially useful for constructs that are likely to span multiple stacks like Api, AppSyncApi, etc
- [ ] How to move (ie. an Api route) from 1 stack to another without downtime?

Justin and Alex Price asked:
> I'd love to see some generic guidance to (if possible). We're not there yet (still in design phase), but it would be good to know how best to build the stacks and how to knit them together (if possible).
> We're using AppSync with unique lambdas for each resolver FYI.

---
_Requested by [Justin and Alex Price on Slack](https://serverless-stack.slack.com/archives/C01JVDJQU2C/p1628697687084300)_

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
