### ISSUE TITLE
Api: add an example on using path variables for HTTP proxy integration

### ISSUE THREAD

**Issue by fwang** [sst/sst#680]
For example:
```
/projects/{projectId} -> google.com/projects/{projectId}
```
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-http.html

---
_Requested by [Adrian on Slack](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1628725152175100)_

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
