### ISSUE TITLE
sst test: accept jest cli options and pass them to jest

### ISSUE THREAD

**Issue by fwang** [sst/sst#681]
For example, this should work for SST. Check how CRA passes options to jest.
```
--collectCoverageFrom='!**/node_modules'
```

---
_Requested by [Bhuvaneshwaran on Slack](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1628675333377700)_

**Comment by thdxr** [comment]
Running the cli with `sst test --collectCoverageFrom='!**/node_modules' --showConfig` shows the correct values and as far as I can tell in the code we are passing through all params

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
