### ISSUE TITLE
Fix npm vulnerabilities

### ISSUE THREAD

**Issue by fwang** [sst/sst#690]
npm audit reports some vulnerabilities
```
❯ npm audit                                                                                      
# npm audit report

jszip  <3.7.0
Severity: moderate
Prototype Pollution - https://npmjs.com/advisories/1774
fix available via `npm audit fix --force`
Will install @serverless-stack/resources@0.4.5, which is a breaking change
node_modules/jszip
  zip-local  *
  Depends on vulnerable versions of jszip
  node_modules/zip-local
    @serverless-stack/resources  >=0.5.0
    Depends on vulnerable versions of zip-local
    node_modules/@serverless-stack/resources
      @serverless-stack/cli  >=0.5.0
      Depends on vulnerable versions of @serverless-stack/resources
      node_modules/@serverless-stack/cli

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

---
Requests:
- Ashishkumar https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1628849395188800
- Ross https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1634107499395700
- Brian https://github.com/serverless-stack/serverless-stack/issues/1804
- Eric https://serverless-stack.slack.com/archives/C01JG3B20RY/p1655323561978139?thread_ts=1655319609.372779&cid=C01JG3B20RY

**Comment by thdxr** [comment]
Spent some time exploring our usage of `zip-local` which hasn't been updated in 5 years and only works with an outdated/vulnerable version of `jszip`

Seems like we use it primarily for synchronous zipping in constructors of resources.  I need to do some digging to see if there's another library that offers this same functionality, quick googling only turned up async options.

**Comment by thdxr** [comment]
We have a new set of them, most are coming from sls-next

**Comment by pitgrap** [comment]
any news on this? jszip is reported as "critical", not as "moderate" anymore and still used in SST v2

```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ critical            │ JSZip contains Path Traversal via loadAsync            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ jszip                                                  │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <3.8.0                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=3.8.0                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ . > sst@2.0.25 > zip-local@0.3.5 > jszip@2.7.0         │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-36fh-84j7-cv5h      │
└─────────────────────┴────────────────────────────────────────────────────────┘
```

Related to https://github.com/serverless-stack/sst/issues/1804 since jszib is coming from zip-local. (Maybe the other one can be closed as duplicate).

**Comment by ashleyfrieze** [comment]
@thdxr - can I add to the request here.

There are three dependencies that we've found CVEs with. I've been able to use `yarn` resolutions to tie to more recent versions. Things still seem to work with SST.

`zip-local` maybe the root cause culprit of some of this.

```
  "resolutions": {
    "jszip": "^3.10.1",
    "async": "^2.6.4",
    "y18n": "^5.0.5"
  }
```

**Comment by jayair** [comment]
Is it possible to get a PR with this?

**Comment by ashleyfrieze** [comment]
@jayair - it turns out that `jszip 3` breaks `zip-local` which seems, in turn, to break sst deployments. I think it makes more sense to eradicate `zip-local` from the project altogether. See my comment on #1804

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
