### ISSUE TITLE
Function: Allow more control over what gets uploaded to AWS Lambda

### ISSUE THREAD

**Issue by ffxsam** [sst/sst#694]
Currently, source maps are bundled into the ZIP that gets uploaded to AWS. For many, we upload source maps elsewhere (Sentry), and the source maps can double the size of the Lambda bundle file which can (in some cases) increase cold start times.

It would be important IMO to have an option to disable source map inclusion in the Lambda bundle files.

**Comment by jayair** [comment]
Just sharing a note, we wanted this on by default to make it easy to debug. So the Lambda errors in CloudWatch point to the right line numbers.

**Comment by ffxsam** [comment]
That makes total sense.. and I agree, it should be on by default, rather than assume someone is going to upload source maps elsewhere.

An option to disable it would be fantastic.

**Comment by thdxr** [comment]
Another request:
https://serverless-stack.slack.com/archives/C01JG3B20RY/p1636923310000500

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
