### ISSUE TITLE
CLI: Watcher not showing rebuild error messages

### ISSUE THREAD

**Issue by jayair** [sst/sst#728]
Steps to reproduce:

- I added a new stack `lib/AuthStack.js` to the `lib/index.js`.
- The new stack had an ESLint error in it, an unused variable.
- The watcher said that rebuilding failed but it didn't display an error message.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
