### ISSUE TITLE
sst cdk - CDK not found 

### ISSUE THREAD

**Issue by RyanHow** [sst/sst#73]
WIndows 10

```
npx sst cdk --app=.build/run.js diff
```

```
'C:\working\myapp\node_modules\@serverless-stack\cli\node_modules\.bin\cdk' is not recognized as an internal or external command,
operable program or batch file.
```

It looks like it's in the top level node modules instead?

**Comment by RyanHow** [comment]
Additionally... (And this may not be supported or even an SST issue, I just wanted to provide some extra information)

If I run cdk directly, I get an error that looks like it's trying to access program files and not handling the space.

```
npx cdk -a .\.build\run.js diff
```

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Subprocess exited with error 1
```

**Comment by jayair** [comment]
Hmm I lack Windows experience here. Any thoughts on why pointing to `cdk` in the `bin` dir doesn't work?

**Comment by RyanHow** [comment]
If I invoke the globally installed `cdk` it doesn't work either

It looks like at some point it's trying to spawn a separate nodejs process, which is in `C:\Program Files\nodejs` and it's not handling the space.

Not sure if it's a CDK bug, or if something in the run.js is telling CDK to spawn a command?

CDK projects work fine on their own, but I haven't used the `cdk -a` parameter before.

**Comment by jayair** [comment]
So there are two separate issues here right? One is that it's unable to run this 'C:\working\myapp\node_modules\@serverless-stack\cli\node_modules\.bin\cdk'? And CDK internally is not handling the space in the path?

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
