### ISSUE TITLE
Cannot run sst commands while `sst start` is running

### ISSUE THREAD

**Issue by fwang** [sst/sst#732]
All sst commands starts by wiping out `.build` folder and recreating it. The `sst start` is a long running command and relies on the build artifacts in the `.build` folder.

### Proposed Solution 1
Let start use a separate build folder, ie. `.build/start`. 

---
_Requested by [colin](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1629471002322700)_

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
