### ISSUE TITLE
__dirname in dependency code resolves to `.build/lib` when the dependency is not listed in package.json

### ISSUE THREAD

**Issue by fwang** [sst/sst#733]
When building CDK code, we set all packages in `package.json` as esbuild externals. By doing this, `__dirname` in dependencies' code will resolve to the correct path b/c they are not bundled.

But if a package is `package.json` of a parent directory, it will be bundled, and `__dirname` resolves to `.build/lib`.

In Kujtim's case, he was using `@aws-cdk/aws-certificatemanager`, but he did not have the package in his `package.json`. The package is still found b/c it is a dependency of `@serverless-stack/resources`. The package hence was not bundled, and b/c the plugin creates a custom resource referencing Lambda code relative to `__dirname`, the code cannot be found.

Solution 1: traverse up the directory and include all packages in all `package.json`. But what if the package is not explicitly included in `package.json`? ie. @aws-cdk packages

Solution 2: exclude all modules in `node_modules` and parent's `node_moduels`. Does this work? How does this affect local modules?

Solution 3: Dax mentioned we might be able to turn off the esbuild `bundle` option.

---
_Requested by [Kujtim in slack](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1629404824208900)_

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
