### ISSUE TITLE
Example: Debugging in Webstorm

### ISSUE THREAD

**Issue by fwang** [sst/sst#738]
---
_Requested by [gio in Slack](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1629497063331200?thread_ts=1629392361.311000&cid=C01HQQVC8TH)_

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
