### ISSUE TITLE
sst start: Support EFS

### ISSUE THREAD

**Issue by fwang** [sst/sst#739]
Trying to access files in EFS like this:
```
import {APIGatewayProxyEventV2, APIGatewayProxyHandlerV2} from "aws-lambda";
import * as fs from 'fs'

export const handler: APIGatewayProxyHandlerV2 = async (event: APIGatewayProxyEventV2) => {

    fs.readdirSync("/").forEach(file => {
        console.log(file);
    });

    return {
        statusCode: 200,
        headers: {"Content-Type": "text/plain"},
        body: `Response: ${JSON.stringify({})}`,
    };
};
```
---
Requested by [Slawomir Stec](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1629559207252600)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
