### ISSUE TITLE
Best practice on importing VPC in app.setDefaultFunctionProps

### ISSUE THREAD

**Issue by fwang** [sst/sst#741]
_Requested by [Ross](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1629143050235500)_

**Comment by pabacham** [comment]
This is my approach

`const vpc = ec2.Vpc.fromLookup(stack, "DefaultVpc", {
      vpcId: process.env.AWS_VPC_ID ?? '',
    });

    const allowedSubnets: string[] = process.env.AWS_VPC_SUBNETS
      ? JSON.parse(process.env.AWS_VPC_SUBNETS)
      : [];

    const vpcSubnets =
      allowedSubnets.length > 0
        ? vpc.selectSubnets({
            subnetFilters: [
              {
                selectSubnets: (subnets) => {
                  const filteredSubnets = subnets.filter((item) =>
                    allowedSubnets.includes(item.subnetId),
                  );
                  return filteredSubnets;
                },
              },
            ],
          })
        : undefined;

    // Setup Security Group for Lambda
    const securityGroup = ec2.SecurityGroup.fromLookup(
      stack,
      'SecurityGroup',
      process.env.AWS_SECURITY_GROUP_ID ?? '',
    );`

**Comment by aramix** [comment]
And this is my approach

```
app.setDefaultFunctionProps((stack) => {
    if (!appVpc) {
      appVpc = ec2.Vpc.fromLookup(stack, 'vpclookup', {
        tags: { [app.stage]: 'allow' },
      });
    }

    return {
      runtime: Runtime.NODEJS_14_X, // Set default runtime for all functions
      environment: {
        ...allEnv,
        SUBDOMAIN: app.stage,
        ROOT_DOMAIN: envMap[app.stage],
      },
      vpc: appVpc,
      vpcSubnets: {
        subnets: appVpc.privateSubnets,
      },
    };
  });
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
