### ISSUE TITLE
Deploying a large number of Lambda function with custom log retention causes Rate exceeded error

### ISSUE THREAD

**Issue by fwang** [sst/sst#749]
### Issue
Function's default retry option is:
```
{
  base: Duration.millis(100),
  maxRetries: 3,
}
```
When creating a large number of functions, the custom resource that's creating the log groups might fail with the error `Rate exceeded`.

### Solution
Slow down retry by default
```
{
  base: Duration.millis(500),
  maxRetries: 20,
}
```

---
_Requested by [Sam Hulick](https://serverless-stack.slack.com/archives/C01HYQRUGG6/p1629919707099200)_

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
