### ISSUE TITLE
Example: Epsagon integration (hold off)

### ISSUE THREAD

**Issue by fwang** [sst/sst#756]
### Update
Let's hold off on this example, as Epsagon is acquired, and not sure if the service will be maintained.

---
Ross mentioned
```
I know Epsagon have recently launched a frontend tracing option for React apps so you can tie a request all the way from UI through to the serverless backend which would be very cool, except we don't use React. I think Vue is in the works
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
