### ISSUE TITLE
sst start - non-interactive "Would you like to run the app on another port instead?"

### ISSUE THREAD

**Issue by electblake** [sst/sst#774]
Although there is the option to explicitly specify `--port` via `sst start --port 1337`

For my mono-repo use-cases and given I don't care which ports my debuggers are running through..

I'd actually prefer to just have `--auto-port` or `--yes` type of option to automatically pick whatever port `sst` wants to when running multiple stacks at same time - this would make it easier to script multiple stacks to start debugging at same time w/o interaction.

Also would remove the need for me to manage a set of ports in all of my services, and caring which port is next in line, etc. etc.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
