### ISSUE TITLE
Function: allow using a specific version

### ISSUE THREAD

**Issue by fwang** [sst/sst#777]
Aram had to work around the limitation by adding the SNS subscription manually.
> this is what worked for us
```js
// WebhookEventsProcessor
const webhookEventsProcessor = new Function(this, 'WebhookEventsProcessor', {
  handler: 'src/webhookEventsProcessor.handler',
  functionName: `${scope.stage}-webhook-events-processor`,
  memorySize: 256,
  timeout: 30,
  environment: {
    ...globalEnvironment,
    SEND_WEBHOOK_EVENTS_QUEUE: sendWebhookEventsQueue.sqsQueue.queueUrl,
  },
  permissions: ['sns', 'sqs'],
  currentVersionOptions: {
    provisionedConcurrentExecutions: 1,
  },
});
const webhookEventsProcessorLive = webhookEventsProcessor.currentVersion;

const messagingEventsTopic = new sns.Topic(this, 'MessagingEvents');
messagingEventsTopic.addSubscription(new subscriptions.LambdaSubscription(webhookEventsProcessorLive));
```

> it invokes the original function because trigger is added to it but that doesn't work for us because we try to keep lambdas hot. This is a messaging app and we need a few of our lambdas be up all the time to deliver the messages as soon as possible, so invoking the original function still requires that to start up and the process the event which takes a lot of time

---
Requests:
-  Aram https://serverless-stack.slack.com/archives/C01JG3B20RY/p1630484490164200
- Lukasz K https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1636734467073400

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
