### ISSUE TITLE
sst build: add option to skip building code

### ISSUE THREAD

**Issue by fwang** [sst/sst#781]
After we implement #779, we can add an option for `sst build` to skip building function code.

This is requested by [Aram](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1630666199240600?thread_ts=1630564083.210600&cid=C01HQQVC8TH)
> having that would be really awesome, in our case we are deploying the same production stack to multiple stages and it will decrease the deployment time dramatically

**Comment by aramix** [comment]
@Frank another nice thing here would be to avoid rebuilding before redeploy if there is no codebase change.
The use case for that is when there is an issue during redeployment that can be fixed manually from aws console and redeploy it will still build the same code before redeploying again

**Comment by fwang** [comment]
Hey @aramix, how would you suggest to detect if there were codebase changes?

**Comment by aramix** [comment]
@fwang not sure how it's done currently but maybe look for something like [v8-compile-cache](https://www.npmjs.com/package/v8-compile-cache)

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
