### ISSUE TITLE
Cleanup failed to created resources automatically when RemovalPolicy is retain

### ISSUE THREAD

**Issue by fwang** [sst/sst#784]
When 

---
Requested by:
- Sam Hulick
- Fazi: https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1630859566271300?thread_ts=1630851666.269200&cid=C01HQQVC8TH

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
