### ISSUE TITLE
sst start: silence logs for specific Functions

### ISSUE THREAD

**Issue by fwang** [sst/sst#785]
Requested by [Pavan](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1630896919267700)
> I still want live debug, but don't want to print anything in terminal.
> I have a lambda which listen to Topic. This SNS Topic is not part of our project. This topic gets lot of events. So we end up getting lots of logs from this particular lambda pollution our terminal.
> So we want to silence output from this lambda. May be as follows
> `sst start -silence Lambda1`

**Comment by riccardogiorato** [comment]
Hey @fwang is silence now supported? Is it possible to remove logs from the terminal?

Should this issue still be open?

**Comment by fwang** [comment]
Hey @riccardogiorato, I must have closed this by mistake. Re-opening this.

Yeah, this is definitely on our mind, and we are making some changes to the terminal to give ppl more control over the lambdas and logs.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
