### ISSUE TITLE
Need a better error message for invalid examples

### ISSUE THREAD

**Issue by jayair** [sst/sst#813]
If we try the new `--example` option for the `create-serverless-stack` CLI with an invalid example name, we get an ugly error. Let's show a more descriptive error.

<img width="572" alt="Screen Shot 2021-09-13 at 8 37 38 PM" src="https://user-images.githubusercontent.com/53023/133175098-1bc13682-23cf-42f7-938e-adb8af08e951.png">

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
