### ISSUE TITLE
How to give permissions in AWS Opensearch

### ISSUE THREAD

**Issue by fernandoralha** [sst/sst#834]
I tried to find some documents or forum with some example permission for AWS Opensearch (oldest Elasticsearch) and I didn't find it. I need this to implement in my project. How do I do that?

**Comment by thdxr** [comment]
Checkout this last section here: https://docs.serverless-stack.com/util/Permissions#permission

You can add any IAM policy to anything that accepts a permissions array (function permissions, api default function permissions, etc)

**Comment by fernandoralha** [comment]
I tried it but it didn't work:

`this.auth.attachPermissionsForAuthUsers([
      // Allow access to the API
      this.api,
      // Policy granting access to a specific folder in the bucket
      new iam.PolicyStatement({
        // principals: ['arn:aws:iam::238058608668:user/4bikers'],
        actions: ["s3:*", "es:*"],
        effect: iam.Effect.ALLOW,
        resources: ['*', 'arn:aws:es:us-east-1:238058608668:domain/bikersdev/*'],
      }),
    ]);
`

**Comment by fernandoralha** [comment]
Message error: 'User: anonymous is not authorized to perform: es:ESHttpPost'

**Comment by thdxr** [comment]
Is this coming through an sst.API endpoint? Looks like the authorizer isn't setup correctly and the user's credentials are not being passed through

**Comment by fernandoralha** [comment]
So I'm calling Elastic over HTTP from inside a lambda using Axios. Something like this: 

`const instance = axios.create({
          baseURL, timeout: 5000   });
      
        await instance.put('/xxxx/_doc/' + objMessage.newId,
        {
          title: objMessage.title,
          content: objMessage.content,
          type: "NEWS",
          datetime: Date.now()
      })`

**Comment by dkershner6** [comment]
This isn't so much a question to serverless stack, so much as the CDK itself for opensearch. You may have more luck over in the CDK slack or GitHub.

In addition, you would need to specify which method of authorization you are using on OpenSearch (fine-grained, Cognito, IAM, etc).  It will change the answer.

Off the cuff, it looks as though you are not establishing yourself as a User of OpenSearch (hence the anonymous), and you need to create a role for lambda to use that does this.

Something like:
```typescript
 const esAdminFnRole = new iam.Role(this, "ESAdminFnRole", {
            assumedBy: new iam.ServicePrincipal("lambda.amazonaws.com"),
        });
        esAdminFnRole.addManagedPolicy(
            iam.ManagedPolicy.fromAwsManagedPolicyName(
                "service-role/AWSLambdaBasicExecutionRole"
            )
        );
```

Again, though, better question for the CDK. Whatever answer they give should work with SST.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
