### ISSUE TITLE
sst info: display deployed stack outputs

### ISSUE THREAD

**Issue by fwang** [sst/sst#847]
Requests:
- https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1632260489054500
- Rudi https://serverless-stack.slack.com/archives/C01JG3B20RY/p1649783747780599

**Comment by KinnersleyM** [comment]
Spec:

- [ ]  Research: What CDK commands could give the desired output?
- [ ]  Research: What flags would be appropriate for this command?
- [ ]  Implement: New CLI command, either `sst info` or the name of the CDK command if there is one.
- [ ]  Test: Add a test to check the output of the command contains the expected information.
- [ ]  Doc: Document the new CLI command.

**Comment by KinnersleyM** [comment]
A couple implementations I have thought of are:
1.  Use the AWS CLI and run `aws cloudformation describe-stacks` to get the deployed outputs but that would require the AWS CLI to be installed.
2. On deploy, write the outputs in a file in `.build` and on `sst info` print the contents of that file.

**Comment by fwang** [comment]
Hey @KinnersleyM, approach #2 can return wrong info if u deployed somewhere else (ie. in a CI), and the outputs in `.build` can be outdated. Let's go with #1.

As for #1, we already do something like you suggested for the `sst deploy` command. This file is where all the AWS SDK calls are made https://github.com/serverless-stack/serverless-stack/blob/master/packages/core/src/index.js.

If you look at [this block](https://github.com/serverless-stack/serverless-stack/blob/master/packages/core/src/index.js#L671-L701), when deploying we check if the template has changed. If not, we short circuit it and mark the deployment completed with no changes. And we are still printing out the stack outputs to the terminal since we know all the outputs and exports, they are all in `stackRet`. So `sst info` will work very similarly to an `sst deploy` where all the deployments are skipped.

**Comment by KinnersleyM** [comment]
Oh cool yeah I'll use the SDK 👍

**Comment by fwang** [comment]
Yeah, we already have a function in there `describeStackWithRetry` that wraps around the `describeEvents` SDK call with auto-retry.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
