### ISSUE TITLE
NextjsSite: help triaging API errors

### ISSUE THREAD

**Issue by fwang** [sst/sst#851]
Currently, when the API routes fail, you get a 503 CloudFront error.
![image (8)](https://user-images.githubusercontent.com/83515/134587383-28d7b567-f6e6-49e1-a08e-07a5f7a88ea8.png)

### Solution 2: help with locating and debugging the CW log

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
