### ISSUE TITLE
NextjsSite: Pages that begin with "api" seem to be excluded from the default-lambda server bundle

### ISSUE THREAD

**Issue by rogerchi** [sst/sst#855]
If a page name begins with the string "api" and relies on server rendering, it seems to be excluded from the default/main lambda function that gets deployed, which results in a 404 error when trying to navigate to that path.

Reproduction steps:
- Create a page named for example `src/pages/apidocs.tsx`
- Run `sst build`
- Navigate to `.build/{site-bundle}/default-lambda/pages`
- See that `apidocs.js` does not exist in the directory
- Rename page to `src/pages/pidocs.tsx`
- Rerun build
- `pidocs.js` does exist in the `default-lambda/pages` directory

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
