### ISSUE TITLE
AppSyncApi: watch for `schema.graphql` while running `sst start` and auto-redeploy infrastructure

### ISSUE THREAD

**Issue by fwang** [sst/sst#902]
Requests:
- https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1633601492300800

**Comment by cmaycumber** [comment]
If it helps we implemented this in our codebase by running a script that calls `appsync.startSchemaCreation` method from the `aws-sdk`. This helps us update the AppSync schema on the fly without a full redeploy. This helped us develop our graphql resolvers a bit faster.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
