### ISSUE TITLE
StaticSite: fileOptions uploader does not mimic the S3 CLI and is limited

### ISSUE THREAD

**Issue by iDVB** [sst/sst#903]
## Issue 1
I think there is an issue with how the current fileOptions works in StaticSite  since exclude and include are setup as static properties (where includes always override excludes) there is no way to reproduce this command that the s3 sync CLI could…
```bash
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*" \
  --include "static/*" \
  --include "*.css" \
  --include "*.js" \
  --exclude "sw.js" \
  --cache-control 'public,max-age=31536000,immutable' --delete
```
Notice the second exclude comes after a bunch of includes and another exclude. Perhaps laying out these fileOptions would have been better this way…
```javascript
{
  fileOptions: [
    {
      matching: [
        { exclude: '*' },
        { include: 'static/*' },
        { include: '*.css' },
        { include: '*.js' },
        { exclude: 'sw.js' },
      ],
      cacheControl: 'public,max-age=31536000,immutable',
    },
  ],
}
```
or perhaps even shorter something like
```javascript
{
  fileOptions: [
    {
      matching: [ '!*', 'static/*', '*.css', '*.js', '!sw.js'],
      cacheControl: 'public,max-age=31536000,immutable',
    },
  ],
}
```
Need to check that it doesn’t conflict with other ! in [standard rules](https://docs.aws.amazon.com/cli/latest/reference/s3/index.html#use-of-exclude-and-include-filters)… but it appears you have to use [!thingy] if you want to use negate.

## Issue 2
It also seems like being able to use **ONLY** `exclude` is also missing and is a perfectly acceptable command with the CLI.
`Property 'include' is missing in type '{ exclude: string[]; cacheControl: string; }' but required in type 'StaticSiteFileOption'`
The following command would upload all files, except for the excluded, and **not** set any caching options on them.
```bash
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*.html" \
  --exclude "page-data/*.json" \
  --exclude "*.js" \
  --exclude "*.css" \
  --exclude "static/*" \
  --exclude "robot.txt" \
  --exclude "sitemap.xml" \
  --delete
```

## For reproduction steps
The following is a working list of CLI commands that sets up any GatsbyJS site will [officially recommended cache control options](https://www.gatsbyjs.com/docs/caching/).
Once the site is live, you can use the [check-gatsby-caching npx tool](https://www.npmjs.com/package/check-gatsby-caching?__cf_chl_jschl_tk__=pmd_8_qAwrGTIXgg6UefNMTmfUtMs2thXoZq2YdDcM0Ut2A-1633629780-0-gqNtZGzNAhCjcnBszQmR) to check that the cache settings are right.
`npx check-gatsby-caching https://domain/`
```bash
# https://www.gatsbyjs.com/docs/caching/
# Long Cache for static, css, js except for sw.js
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*" \
  --include "static/*" \
  --include "*.css" \
  --include "*.js" \
  --exclude "sw.js" \
  --cache-control 'public,max-age=31536000,immutable' --delete
# NO cache for html, page-data, and sw.js
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*" \
  --include "*.html" \
  --include "page-data/*.json" \
  --include "sw.js" \
  --include "robot.txt" \
  --include "sitemap.xml" \
  --cache-control 'public,max-age=0,must-revalidate' --delete
# Upload/Sync everything else, w/o cache-control
aws s3 sync ./public/ "s3://${BUCKET_NAME}/" \
  --exclude "*.html" \
  --exclude "page-data/*.json" \
  --exclude "*.js" \
  --exclude "*.css" \
  --exclude "static/*" \
  --exclude "robot.txt" \
  --exclude "sitemap.xml" \
  --delete
```

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
