### ISSUE TITLE
Permissions: Strongly typed / enums

### ISSUE THREAD

**Issue by joekendal** [sst/sst#913]
It would be better to have something like 

```ts
fun.attachPermissions([
 [topic, PermissionType.grantPublish],
 [table, PermissionType.grantReadData],
]);
```
or 
```ts
fun.attachPermissions([
 [topic, PermissionType.PUBLISH], // or PermissionType.GRANT_PUBLISH
 [table, PermissionType.READ], // or PermissionType.GRANT_READ
]);
```

instead of
```ts
fun.attachPermissions([
 [topic, "grantPublish"],
 [table, "grantReadData"],
]);
```

so as to avoid deploy-time issues and enhance developer experience in their IDE

**Comment by thdxr** [comment]
We can actually provide type safety with the strings by properly using a union type inferred from the functions we support. I agree these should be checked in your editor so you can see what the valid options are.

Will get it on our todo

**Comment by junaway** [comment]
- [x] Research: Union types vs Enums, for this issue specifically.
https://fettblog.eu/tidy-typescript-avoid-enums/
https://blog.bam.tech/developer-news/should-you-use-enums-or-union-types-in-typescript
==> Going with union types.
- [x] Research: All the relevant grants or shape `public grantSomeGrant>(grantee: iam.IGrantable): iam.Grant` in `@aws-cdk`.
- [x] Implement: Individual grant types per construct and a unified grant type for all constructs.
- [ ] Test: Ideally all grants for all constructs.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
