### ISSUE TITLE
sst test: building StaticSite when running tests is slow and not always required

### ISSUE THREAD

**Issue by fwang** [sst/sst#921]
Requests:
- Devin https://serverless-stack.slack.com/archives/C01JG3B20RY/p1634141279105100?thread_ts=1634136813.087200&cid=C01JG3B20RY

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
