### ISSUE TITLE
Support VSCode debugging for Go runtime

### ISSUE THREAD

**Issue by fwang** [sst/sst#932]
Michael Clifford mentioned that he got the following error:
```
Starting: /home/mclifford/go/bin/dlv-dap dap --check-go-version=false --listen=127.0.0.1:45873 --log-dest=3 from /home/mclifford/Development/github.com/cliffom/sst-bff-demo/src/handlers/api/users
DAP server listening at: 127.0.0.1:45873
2021/10/15 10:58:36 expected AWS Lambda environment variables [_LAMBDA_SERVER_PORT AWS_LAMBDA_RUNTIME_API] are not defined
Process 16573 has exited with status 1
Detaching
Process 16573 has exited with status 1
Detaching
dlv dap (16407) exited with code: 0
```

---
Requests:
- Michael https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1634320934435500
- Kevin Baker
- Miguel https://serverless-stack.slack.com/archives/C01JG3B20RY/p1653043045475819

**Comment by bluprince13** [comment]
So, this isn't supported then? From reading the docs I assumed debugging in VSCode is supported for any language. But, the example is only in JavaScript. And, the breakpoint didn't work when I tried it out.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
