### ISSUE TITLE
sst build: hangs when yarn 3 is used as packager

### ISSUE THREAD

**Issue by fwang** [sst/sst#952]
Reported by Carter Himmel:
> i'm currently running into an issue with one of our builds failing. it installed our dependencies with yarn@3 correctly then just hangs for ~20 minutes and cancels. i'm looking at our logs and there's nothing here

![image (10)](https://user-images.githubusercontent.com/83515/138368655-abe34524-07f2-4471-a368-ac8ff573856f.png)

---
Requests:
- https://serverless-stack.slack.com/archives/C01JG3B20RY/p1634595709346000

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
