### ISSUE TITLE
Function: setting log retention causes `rate exceeded` with a lot of Functions

### ISSUE THREAD

**Issue by fwang** [sst/sst#953]
## Problem
Log retentions are being configured via AWS SDK through custom resource. With a lot of Functions, AWS SDK calls are made concurrently and results in `rate exceeded` error.

Setting `logRetentionRetryOptions` to 100 retries will fix the `rate exceeded` error, but causes:
```
Received response status [FAILED] from custom resource. Message returned: A conflicting operation is currently in progress against this resource. Please try again. (RequestId: 27daaaf0-f4b5-472d-8cae-643d3664f740)
```

## Solution 1
Creating the log group manually for Functions:
```
this.getAllFunctions().forEach(func => {
	new logs.LogGroup(this, `${func.node.id}-LogGroup`, {
		logGroupName: `/aws/lambda/${func.functionName}`,
		retention: logs.RetentionDays.THREE_MONTHS,
		removalPolicy: scope.defaultRemovalPolicy
	})
})
```

The issue with this approach is that if the log group already exists, deployment will fail.

## Solution 2
Understand what is causing the `A conflicting operation` error, and either come up with a more sensible `LogRetentionRetryOptions` config; or rewrite the custom resource for setting log retention to gracefully handle the logic.

---
Requests:
https://serverless-stack.slack.com/archives/C01JG3B20RY/p1634839201037400
https://serverless-stack.slack.com/archives/C01JG3B20RY/p1635375910361800
Dan https://discord.com/channels/983865673656705025/996097936440180767

**Comment by pa-dentally** [comment]
Hi @garretcharp, I tried the suggestion of adding a dependency from the function to the log and hit a circular dependency issue if you have stacks adding routes to stacks.  Thought I'd just mention it in case it helped with what you were doing!

**Comment by pa-dentally** [comment]
Also, just doing solution 1 didn't work for me.  It got further on one deploy but sitll failed with the rate limit on one of the stacks.  A combination of setting the maxRetries on the defaultFunctionProps and solution 1 seemed to work though:

`logRetentionRetryOptions: {
        maxRetries: 100,
      },`

**Comment by pa-dentally** [comment]
Now I've started hitting the duplicate name issue so the workaround worked for a while but has now stopped...  I'm looking into ways to check for the log existing beforehand.  I thought log.logFromGroupName might work but that seems to been a bust.

**Comment by nnyegaard** [comment]
We are also running into this issue, sadly.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
