### ISSUE TITLE
Creating a lambda @ edge outside us-east-1 gives an error 

### ISSUE THREAD

**Issue by NickBlow** [sst/sst#967]
When creating a lambda @ edge outside US-East-1 region, AWS CDK by default creates a new substack with the lambda to deploy it to US-East-1, with a default name - see https://github.com/aws/aws-cdk/blob/fb43f89310c7aab6426cc436bbb128fbe0071e1a/packages/%40aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts#L221. 

This then errors out with the error : "Stack "edge-lambda-stack-..." is not parameterized with the stage name. The stack name needs to either start with "$stage-", end in "-$stage", or contain the stage name "-$stage-"

The workaround is to provide an explicit stack id to the construct.

**Comment by dev-samples** [comment]
Any update on this? I get :

`    'Error: Stack "edge-lambda-stack-c88e8caf16351c747b34b596859f9e6c145f78eb34" is not parameterized with the stage name. The stack name needs to either start with "$stage-", end in "-$stage", or contain the stage name "-$stage-".\n' +`

And it I try and add $stage in e.g. the sst.json file I then get:


`Error: Stack name must match the regular expression: /^[A-Za-z][A-Za-z0-9-]*$/, got 'sandbox-$stage-my-sst-app-MyStack'`

:-(

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
