### ISSUE TITLE
NextjsSite: deploy on normal lambda instead of Lambda @ edge

### ISSUE THREAD

**Issue by ixartz** [sst/sst#975]
Lambda@Edge has more limitation compare to classic AWS Lambda. AWS Lambda is more powerful, more tooling, etc.

Lambda@Edge limit our Next.js api's to accept only 1MB of data.

Normal lambda is cheaper and better for API purpose

It could be great if we can choose between classic AWS Lambda and Lambda@Edge at least for API routes and SSR.

**Comment by fwang** [comment]
Hi @ixartz, this is on our roadmap and we are experimenting with it. I don't have a firm date around when we can have a v1. But I will keep you posted when we have something.

**Comment by ixartz** [comment]
Hi @fwang, thank you for taking the time to respond.

With recent announcement of Next JS 12, _middleware run on edge. So perfect to run it on edge like Lambda@Edge.
But, for Api routes and serverless function on Vercel, there is a region and doesn't run on edge.

https://vercel.com/docs/concepts/functions/regions

I'm not an Vercel expert, I just read the official documentation. I might be wrong.

Thank you again for making an alternative.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
