### ISSUE TITLE
How to sign up when link is used instead of verification code ?

### ISSUE THREAD

**Issue by bedamatta05** [sst/sst#983]
Hey,
In the chapter [https://serverless-stack.com/chapters/signup-with-aws-cognito.html](url), instead of confirmation code I have used confirmation link for sign up.

What should be my flow of code instead of the following for the same?

```
async function handleConfirmationSubmit(event) {
  event.preventDefault();

  setIsLoading(true);

  try {
    await Auth.confirmSignUp(fields.email, fields.confirmationCode);
    await Auth.signIn(fields.email, fields.password);

    userHasAuthenticated(true);
    history.push("/");
  } catch (e) {
    onError(e);
    setIsLoading(false);
  }
}
```

(_for of confirmation code)_

**Comment by fwang** [comment]
Let me pull in @jayair as he's more familiar with the frontend.

**Comment by jayair** [comment]
Actually I'm not totally sure about this one. I haven't used the link yet. Maybe you can popover to our Slack and ask if somebody has used that flow? Or if somebody else that reads this can chime in.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
