### ISSUE TITLE
Enable sourcemaps by default

### ISSUE THREAD

**Issue by thdxr** [sst/sst#984]
Enable sourcemaps by adding `NODE_OPTIONS=--enable-source-maps`. We should try and detect if they're already passing in NODE_OPTIONS as an env variable and append to it rather than replace

**Comment by junaway** [comment]
- [x] Research: How NODE_OPTIONS is formatted and how it is supposed to be used.
- [x] Implement: Add NODE_OPTIONS if not exists.
- [x] Implement: Update NODE_OPTIONS is exists.
- [x] Test: existing tests with fixes.
- [x] Test: new tests with various ways to define environment variables (default props, function props, addEnvironment(), etc).

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
