### ISSUE TITLE
sst build: output color not consistent with the sst diff command

### ISSUE THREAD

**Issue by fwang** [sst/sst#985]
Here is the output from `sst build`
![Screen Shot 2021-11-01 at 22 22 12](https://user-images.githubusercontent.com/83515/139773109-026b88ef-0cf3-4377-a86b-47287a0dcd65.png)
![Screen Shot 2021-11-01 at 22 23 10](https://user-images.githubusercontent.com/83515/139773112-4aea542c-92c8-42b9-8c46-b089f92e281f.png)

Here is the output from `sst diff`
![Screen Shot 2021-11-01 at 22 24 14](https://user-images.githubusercontent.com/83515/139773127-d3b40f45-c9b7-4db9-b738-c130138eff6a.png)
![Screen Shot 2021-11-01 at 22 24 47](https://user-images.githubusercontent.com/83515/139773129-35784fe1-2d54-4908-a546-4cdf3e2acd0b.png)

Spotted two differences:
1. the word `verbose` is cyan in `sst diff`, but gray in `sst build`
2. all the white text in `sst diff` are gray in `sst build`

---
Requests:
- Adrian https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1635645783213800

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
