### ISSUE TITLE
TableProps should not allow setting stream

### ISSUE THREAD

**Issue by thdxr** [sst/sst#996]
### Requests
- https://serverless-stack.slack.com/archives/C01JG3B20RY/p1636068236228800

**Comment by junaway** [comment]
- [x] Implement: typecasting `dynamoTableProps` to `TableCdkProps` first and **then** to `dynamodb.TableProps`. This restricts the allowed fields for Typescript users while still protectively checking the restricted fields for non-Typescript users.
- [x] Test: using `stream` with Typescript should throw an error at compile time. ==> Must remove failing test from test suite.
- [ ] Test: using `stream` without Typescript should throw an error at run time.

**Comment by thdxr** [comment]
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble
